objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Account_Status__c</fullName>
        <description>Account Status</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Status-1</fullName>
                </value>
                <value>
                    <fullName>Status-2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Airline_Code__c</fullName>
        <description>3 digit Airline Code</description>
        <inlineHelpText>The 3-digit customer code is assigned by PAC and should be the ICAO code for airlines.</inlineHelpText>
        <label>Airline Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Customer_ID__c</fullName>
        <description>Customer Account ID. External ID of Account, not shown in UI; may be redundant with Party ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2I_Operator_Number__c</fullName>
        <description>Panasonic Operator Number 2 digit Airline Code; Not entered by sales</description>
        <inlineHelpText>The 2-digit customer code is assigned by PAC and should be the IATA code for airlines.</inlineHelpText>
        <label>Operator Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Party_Id__c</fullName>
        <description>Party Id</description>
        <externalId>true</externalId>
        <label>Party Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Payment_Term__c</fullName>
        <description>PAC Payment Terms</description>
        <inlineHelpText>Please select payment term</inlineHelpText>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NO TERMS</fullName>
                </value>
                <value>
                    <fullName>30 NET</fullName>
                </value>
                <value>
                    <fullName>Cash In Advance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Region_2</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IFE_Email_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be checked when the email for the contact has been verified, either automatically via lead-to-contact creation or manually.</description>
        <label>IFE Email Verified</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_Related_Account__c.object
<CustomObject>
    <description>Custom object to model the many-to-many relationships between PAC accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Account from which the relationship is being viewed</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related account</description>
        <label>Related To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Related To)</relationshipLabel>
        <relationshipName>Related_to_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Merger</fullName>
                </value>
                <value>
                    <fullName>Sister concern</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>MRO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Account</label>
    <nameField>
        <displayFormat>REL-{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/myIfeOrderHeaders__x.object
<CustomObject>
    <description>myIfeOrderHeaders</description>
    <externalDataSource>Order_Status</externalDataSource>
    <externalName>myIfeOrderHeaders</externalName>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>myIfeOrderHeaders</relationshipLabel>
        <relationshipName>myIfeOrderHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>myIfeOrderHeaders</label>
    <pluralLabel>myIfeOrderHeaders</pluralLabel>
</CustomObject>

globalValueSets/L2I_Region_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Americas</fullName>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>South Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Oceana</fullName>
        <isActive>false</isActive>
        <label>Oceana</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

classes/L2I_SalesOrderSearchControllerTest.cls
@isTest
private class L2I_SalesOrderSearchControllerTest {
    @isTest
    public static void downloadCSVTest(){
        Account testAccount = new Account(
            Name = 'BRITISH AIRWAYS CORP',
            L2I_Payment_Term__c = '30 NET -a',
            L2I_Customer_Group__c = 'External',
            L2I_Customer_ID__c = '1083',
            L2I_Party_Id__c = '1083',
            L2I_Region__c = 'Europe',
            L2I_Operator_Number__c = 'BA',
            L2I_Airline_Code__c = 'BAW',
            AccountNumber = '1058',
            L2I_Account_Status__c = 'Active'
        );
        insert testAccount;
        
        Test.startTest();
        //Updated by Jan for W-004376 - added testAccount.L2I_Customer_ID__c
        List<myIfeOrderHeaders__x> MYIFEorderHeaders = L2I_SalesOrderSearchController.downloadCSV('test','test','test','test','test','1083',testAccount.L2I_Customer_ID__c,'test','test',12,12);
        System.assertEquals(0, MYIFEorderHeaders.size());
        Test.stopTest(); 
    }
    
    @isTest
    public static void getSearchERPOrderStatusByCustomerPOTest(){
        L2I_SalesOrderSearchController salesOrderSearch = new L2I_SalesOrderSearchController();
        L2I_SalesOrderSearchController.getSearchERPOrderStatusByCustomerPO('123');
    }
    
    @isTest
    public static void getERPOrderStatusForAccountTest(){
         Test.startTest();
       List<myIfeOrderHeaders__x> MYIFEorderHeaders =  L2I_SalesOrderSearchController.getERPOrderStatusForAccount('12');
        System.assertEquals(0, MYIFEorderHeaders.size());
        Test.stopTest();
       
    }
    
    @isTest
    public static void getERPOrderStatusTest(){
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        system.debug('portalRole is ' + portalRole);
        
        User userObj = ife_TestDataUtil.CreateUser(true);
        userObj.UserRoleId =  portalRole.Id;
        update userObj;
        
        System.runAs (userObj) {
            
            Account acc = ife_TestDataUtil.createAccount(true);
            
            Contact con = ife_TestDataUtil.createContact(acc.Id, true);
             //Added by Jan for W-004376: Start
            con.IFE_Email_Verified__c = true;
            con.Email = 'test12345@test.com';
            update con;
            //Added by Jan for W-004376: Stop
            
            Profile portalProfile = [SELECT Id FROM Profile where name = 'PAC Customer' limit 1];
            User usr = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = con.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTesty',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US');
            
            insert usr;
            
            System.runAs(usr){
                Test.startTest();
            //    L2I_SalesOrderSearchController salesorder = new L2I_SalesOrderSearchController();
                L2I_SalesOrderSearchController.getERPOrderStatus();
            //    System.assertEquals(salesorder.shipToCustomerName, 'Ship to');
                Test.stopTest();
            }
        }
    }

    @isTest
    public static void getSearchERPOrderQueryTest(){
        Test.startTest();
       List<myIfeOrderHeaders__x> MYIFEorderHeaders = L2I_SalesOrderSearchController.getSearchERPOrderQuery('123');
        System.assertEquals(0, MYIFEorderHeaders.size());
        Test.stopTest();
    }
    
    @isTest
    public static void getSearchERPOrderStatusTest(){
        Account acc = ife_TestDataUtil.createAccount(true);
        acc.L2I_Customer_ID__c = '1083';
        update acc;
        
        L2I_Related_Account__c relatedacc = new L2I_Related_Account__c();
        relatedacc.Relationship_Type__c = 'Ship To';
        relatedacc.Account__c = acc.Id;
        relatedacc.Related_To__c = acc.Id;
        insert relatedacc;
        
        
        L2I_SalesOrderSearchController.getSearchERPOrderStatus('salesOrderNumber', 'eCommerceNumber', 'customerPo', 'programNumber', 'shipToCustomerName', 'tailNumber', acc.L2I_Customer_ID__c, 'orderStatusSerach', 'orderCustomerName', 123, 12);
    }
	
	@isTest
	public static void getRelatedAccountTest() {
		Map<String, String> accountIdWithRelationshipTypeMap = new Map<String, String>();
		accountIdWithRelationshipTypeMap = L2I_SalesOrderSearchController.getRelatedAccount('0018A00000LBYg0QAH',true);
		Test.startTest();
        //Added by Jan for W-004376: Start
        L2I_SalesOrderSearchController.getRelatedAccount_1('0018A00000LBYg0QAH',true);
        L2I_SalesOrderSearchController.getShipToCustomerNameByCountactAccountId('0018A00000LBYg0QAH');
        L2I_SalesOrderSearchController.getShipToCustomerList('0018A00000LBYg0QAH');
        L2I_SalesOrderSearchController.getUserInfo();
        //Added by Jan for W-004376: Stop
		System.assertEquals('{0018A00000LBYg0QAH=Ship To}', accountIdWithRelationshipTypeMap.toString());
		Test.StopTest();
	}
	
	@isTest
    public static void getSearchERPOrderStatusBoeingTest(){
		Account acc = ife_TestDataUtil.createAccount(true);
        acc.L2I_Customer_ID__c = '1516';
        update acc;
        
        L2I_Related_Account__c relatedacc = new L2I_Related_Account__c();
        relatedacc.Relationship_Type__c = 'Ship To';
        relatedacc.Account__c = acc.Id;
        relatedacc.Related_To__c = acc.Id;
        insert relatedacc;
		
        Test.startTest();
        L2I_SalesOrderSearchController.getSearchERPOrderStatus('salesOrderNumber', 'eCommerceNumber', 'customerPo', 'programNumber', 'shipToCustomerName', 'tailNumber', acc.L2I_Customer_ID__c, 'orderStatusSerach', 'orderCustomerName', 123, 12);
		Test.StopTest();
    }
}