objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Fit_Type__c</fullName>
        <label>Fit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>L2I_Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell/Follow-on</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval flow</description>
        <label>Program Mgr</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Fit_Type__c</fullName>
        <label>Fit Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_PMO_Groups__c.object
<CustomObject>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Sub Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PMO Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMO Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>PMO_Regional_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Needed in the MROD Approval process</description>
        <label>PMO Regional Director User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PMO_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>PMO Group Programs</relationshipLabel>
        <relationshipName>PMOGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PMO_SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Sub Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Sub Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>Programs (PMO Sub Group)</relationshipLabel>
        <relationshipName>PMOSubGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Needed for MROD Approval process</description>
        <label>Principal Program Manager User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Number__c</fullName>
        <externalId>true</externalId>
        <label>Program Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>Production</fullName>
        <active>true</active>
        <label>Production</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_PartsListApprovalView_Test.cls
/**
* @File Name          : PT_PartsListApprovalView_Test.cls
* @Description        : Test Class for PT_PartsListApprovalView
* @Author             :
* @Last Modified By   : MS Simplus Khrisna
* @Last Modified On   : Mar 31, 2022
* @Modification Log   : 
* Ver           Date           Author               Modification
*                                                   Initial Version
* W-001727      Mar 31 2022    MS Simplus Khrisna   Primary System Type Validation Rule
**/
@IsTest
private class PT_PartsListApprovalView_Test {
    @IsTest
    static void testPLApproval() {
        L2I_DataFactory factory = new L2I_DataFactory();
        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
    
        Opportunity dealOppty = factory.createDealOpportunity('Deal', 'Open', 30, namedCustomer.Id);
        insert dealOppty;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
		
        Opportunity salesOppty = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, namedCustomer.Id,
              dealOppty.Id, 200000, 'IFEC');
        salesOppty.L2I_Primary_System_Type__c = prodSysType.Id;
        salesOppty.PT_Program_Mgr__c = UserInfo.getUserId();
        salesOppty.L2I_Fit_Type__c = 'Production';
        insert salesOppty;
    
        User u = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(u) {
        
            //Create Parent Group
            Group grp = new Group();
            grp.DeveloperName = 'Program_PM_PPM_QueueTEST';
            grp.Name = 'Program_PM_PPM_QueueTEST';
            grp.Type = 'Queue';
            insert grp;
        
            //Create Group Member
            GroupMember grpMem1 = new GroupMember();
            grpMem1.UserOrGroupId = UserInfo.getUserId();
            grpMem1.GroupId = grp.Id;
            insert grpMem1;
            List<PT_PartsListApproval.PLApprovalParams> pppList = new List<PT_PartsListApproval.PLApprovalParams>();
            PT_PartsListApproval.PLApprovalParams ppp = new PT_PartsListApproval.PLApprovalParams();
            ppp.oppId = salesOppty.Id;
            pppList.add(ppp);
        
            PT_PartsListApproval.processPartsListApproval(pppList);
        }
    
        ProcessInstance objProcessInstance = [SELECT Id,TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :salesOppty.Id];
        System.assertNotEquals(null,objProcessInstance);
    
        List<PT_PartsListApprovalView.PLApprovalWrapper> pawList = PT_PartsListApprovalView.getPendingPLApprovals();
        System.assertEquals(1, pawList.size());
    }
    
    @IsTest
    static void testMRODApproval() {
        L2I_DataFactory factory = new L2I_DataFactory();
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'PAC Sales'].Id;
        User u1 = factory.createTestUser(null, profileId, 'User1', 'Test');
        insert u1;
        User u2 = factory.createTestUser(null, profileId, 'User2', 'Test');
        insert u2;
        User u3 = factory.createTestUser(null, profileId, 'User3', 'Test');
        insert u3;
        
        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        
        Opportunity dealOppty = factory.createDealOpportunity('Deal', 'Open', 30, namedCustomer.Id);
        insert dealOppty;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOppty = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, namedCustomer.Id,
              dealOppty.Id, 200000, 'IFEC');
        salesOppty.PT_Program_Mgr__c = UserInfo.getUserId();
        salesOppty.L2I_Fit_Type__c = 'Production';
        salesOppty.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesOppty;
    
        PT_PMO_Groups__c pg = new PT_PMO_Groups__c(
              Name = 'pgName',
              Group_Type__c = 'Group'
        );
        insert pg;
        pg.OwnerId = u1.Id;
        update pg;
    
        PT_PMO_Groups__c pg2 = new PT_PMO_Groups__c(
              Name = 'pgName2',
              Group_Type__c = 'Sub Group'
        );
        insert pg2;
        pg2.OwnerId = u2.Id;
        update pg2;
        
    
        PT_Program__c prog1 = new PT_Program__c();
        prog1.Name = 'Prog1';
        prog1.Program_Number__c = 'Prog1';
        prog1.PT_PMO_Group__c = pg.Id;
        prog1.PT_PMO_SubGroup__c = pg2.Id;
        prog1.Program_Manager__c = u1.Id;
        prog1.Principal_Program_Manager__c = u2.Id;
        prog1.PMO_Regional_Director__c = u3.Id;
        insert prog1;
        
        User u = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(u) {
            
            //Create Parent Group
            Group grp = new Group();
            grp.DeveloperName = 'Program_PM_PPM_QueueTEST';
            grp.Name = 'Program_PM_PPM_QueueTEST';
            grp.Type = 'Queue';
            insert grp;
            
            //Create Group Member
            GroupMember grpMem1 = new GroupMember();
            grpMem1.UserOrGroupId = UserInfo.getUserId();
            grpMem1.GroupId = grp.Id;
            insert grpMem1;
    
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setObjectId(prog1.Id);
            req1.setProcessDefinitionNameOrId('Program_MROD_Approval_v3');
            Approval.ProcessResult result = Approval.process(req1);
            
            System.assert(result.isSuccess());
        }
        
        ProcessInstance objProcessInstance = [SELECT Id,TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :prog1.Id];
        System.assertNotEquals(null,objProcessInstance);
        
        List<PT_PartsListApprovalView.PLApprovalWrapper> pawList = PT_PartsListApprovalView.getPendingPLApprovals();
        System.debug('*** pawList.size() ' + pawList.size());
    }
    
}