objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Order__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Aircraft Orders</relationshipLabel>
        <relationshipName>Aircraft_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aircraft Order</label>
    <nameField>
        <displayFormat>AO{0000}</displayFormat>
        <label>Aircraft Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Service__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxAircraft Order</label>
        <referenceTo>L2I_Aircraft_Order__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <formula>Aircraft__r.Aircraft_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Aircraft Service</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Aircraft Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/L2I_Aircraft_TriggerFunctions_Test.cls
/**
 *      @author       Raj Rajen
 *      @date         08/03/2019
 *      @description  Test class for L2I Aircraft Trigger Functions.
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Raj Rajen                     08/03/2019         Initial setup of tests
 *
 */
@isTest(SeeAllData=false)
public class L2I_Aircraft_TriggerFunctions_Test {

    @isTest
    static void test_unused_aircraft_deletion_as_non_system_administrator() {
        //Id salesProfileId = [SELECT Id, Name from Profile Where Name =: 'PAC Sales'].Id;

        L2I_DataFactory factory = new L2I_DataFactory();

        Profile salesProfile = L2I_StaticConstants.getProfileByName('PAC Sales');
        User salesUser = factory.createTestUser(null, salesProfile.Id, 'Sales', 'User');
        insert salesUser;

        System.assert(salesUser.Id != null, 'User Id cannot be null');

        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        System.assert(namedCustomer.Id != null, 'Named Customer Account must have an Id');

        L2I_Aircraft_Type__c att = factory.createAircraftType( namedCustomer.Id, 123456);
        insert att;
        System.assert(att.Id != null, 'Aircraft Type cannot be null');

        System.runAs(salesUser) {
            // Create the Aircraft as this user
            L2I_Aircraft__c ac = factory.createAircraft(att.Id, 'Name', '2333-11131133114499999988888805', namedCustomer.Id);
            insert ac;

            // Try to delete the aircraft, the system should *NOT* allow you to delete the aircraft
            try {
                delete ac;
            } catch (DmlException dmle) {
                System.assert(dmle.getMessage().containsIgnoreCase('Unauthorized Attempt to delete. Aircraft records can only be deleted by Administrators'));
            }
        }
    }

    @isTest
    static void test_unused_aircraft_deletion_as_system_administrator() {
        L2I_DataFactory factory = new L2I_DataFactory();

        Profile adminProfile = L2I_StaticConstants.getProfileByName('System Administrator');
        User adminUser = factory.createTestUser(null, adminProfile.Id, 'Super', 'User');
        insert adminUser;

        System.assert(adminUser.Id != null, 'User Id cannot be null');

        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        System.assert(namedCustomer.Id != null, 'Named Customer Account must have an Id');

        L2I_Aircraft_Type__c att = factory.createAircraftType( namedCustomer.Id, 123456);
        insert att;
        System.assert(att.Id != null, 'Aircraft Type cannot be null');

        System.runAs(adminUser) {
            // Create the Aircraft as this user
            L2I_Aircraft__c ac = factory.createAircraft(att.Id, 'Name', '2333-11131133114499999988888805', namedCustomer.Id);
            insert ac;

            // Try to delete the aircraft, the system should allow you to delete the aircraft
            delete ac;
        }
    }

    @isTest
    static void test_in_use_aircraft_deletion_as_system_administrator() {
        L2I_DataFactory factory = new L2I_DataFactory();

        Profile adminProfile = L2I_StaticConstants.getProfileByName('System Administrator');
        User adminUser = factory.createTestUser(null, adminProfile.Id, 'Super', 'User');
        insert adminUser;

        System.assert(adminUser.Id != null, 'User Id cannot be null');

        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        System.assert(namedCustomer.Id != null, 'Named Customer Account must have an Id');

        L2I_Aircraft_Type__c att = factory.createAircraftType( namedCustomer.Id, 123456);
        insert att;
        System.assert(att.Id != null, 'Aircraft Type cannot be null');

        System.runAs(adminUser) {
            // Create the Aircraft as this user
            L2I_Aircraft__c ac = factory.createAircraft(att.Id, 'Name', '2333-11131133114499999988888805', namedCustomer.Id);
            insert ac;

            L2I_Aircraft_Order__c ao = new L2I_Aircraft_Order__c(Aircraft__c = ac.id);
            insert ao;

            L2I_Aircraft_Service__c asvc = new L2I_Aircraft_Service__c(Aircraft__c = ac.Id,
                                                                       Aircraft_Order__c = ao.Id,
                                                                       Status__c = 'Pending Activation');
            insert asvc;
            System.assert(asvc.Id != null, 'Aircraft Service cannot be null');

            //ac = [select Id, Name, Total_Number_of_Services__c from L2I_Aircraft__c where Id =: ac.Id limit 1];
            //System.assert(ac.Total_Number_of_Services__c == 1, 'Number of Services on the Aircraft does not match expected value');

            // Try to delete the aircraft, the system should *NOT* allow you to delete the aircraft
            try {
                delete ac;
            } catch (DmlException dmle) {
                System.debug('====== EXCEPTION Message :' + dmle.getMessage());
                System.assert(dmle.getMessage().containsIgnoreCase('In-use Aircraft records cannot be deleted'));
            }
        }
    }


    @isTest
    static void test_in_use_aircraft_deletion_as_aircraft_data_steward() {
        L2I_DataFactory factory = new L2I_DataFactory();

        Profile salesProfile = L2I_StaticConstants.getProfileByName('PAC Sales');
        User stewardUser = factory.createTestUser(null, salesProfile.Id, 'Aircraft', 'Steward');
        insert stewardUser;

        System.assert(stewardUser.Id != null, 'User Id cannot be null');

        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Aircraft_Data_Steward'];
        insert new PermissionSetAssignment(AssigneeId = stewardUser.Id, PermissionSetId = ps.Id);

        System.runAs(stewardUser) {
            Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            System.assert(namedCustomer.Id != null, 'Named Customer Account must have an Id');

            L2I_Aircraft_Type__c att = factory.createAircraftType( namedCustomer.Id, 123456);
            insert att;
            System.assert(att.Id != null, 'Aircraft Type cannot be null');

            // Create the Aircraft as this user
            L2I_Aircraft__c ac = factory.createAircraft(att.Id, 'Name', '2333-11131133114499999988888805', namedCustomer.Id);
            insert ac;

            L2I_Aircraft_Order__c ao = new L2I_Aircraft_Order__c(Aircraft__c = ac.id);
            insert ao;

            L2I_Aircraft_Service__c asvc = new L2I_Aircraft_Service__c(Aircraft__c = ac.Id,
                                                                       Aircraft_Order__c = ao.Id,
                                                                       Status__c = 'Pending Activation');
            insert asvc;
            System.assert(asvc.Id != null, 'Aircraft Service cannot be null');

            //ac = [select Id, Name, Total_Number_of_Services__c from L2I_Aircraft__c where Id =: ac.Id limit 1];
            //System.assert(ac.Total_Number_of_Services__c == 1, 'Number of Services on the Aircraft does not match expected value');

            // Try to delete the aircraft, the system should *NOT* allow you to delete the aircraft
            try {
                delete ac;
            } catch (DmlException dmle) {
                System.debug('====== EXCEPTION Message :' + dmle.getMessage());
                System.assert(dmle.getMessage().containsIgnoreCase('In-use Aircraft records cannot be deleted'));
            }
        }
    }

    @isTest
    static void test_unused_aircraft_deletion_as_aircraft_data_steward() {
        L2I_DataFactory factory = new L2I_DataFactory();

        Profile salesProfile = L2I_StaticConstants.getProfileByName('PAC Sales');
        User stewardUser = factory.createTestUser(null, salesProfile.Id, 'Aircraft', 'Steward');
        insert stewardUser;
        System.assert(stewardUser.Id != null, 'User Id cannot be null');

        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Aircraft_Data_Steward'];
        insert new PermissionSetAssignment(AssigneeId = stewardUser.Id, PermissionSetId = ps.Id);

        System.runAs(stewardUser) {
            Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            System.assert(namedCustomer.Id != null, 'Named Customer Account must have an Id');

            L2I_Aircraft_Type__c att = factory.createAircraftType( namedCustomer.Id, 123456);
            insert att;
            System.assert(att.Id != null, 'Aircraft Type cannot be null');

            // Create the Aircraft as this user
            L2I_Aircraft__c ac = factory.createAircraft(att.Id, 'Name', '2333-11131133114499999988888805', namedCustomer.Id);
            insert ac;

            delete ac;
        }
    }

}