objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Account_Status__c</fullName>
        <description>Account Status</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Status-1</fullName>
                </value>
                <value>
                    <fullName>Status-2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Airline_Code__c</fullName>
        <description>3 digit Airline Code</description>
        <inlineHelpText>The 3-digit customer code is assigned by PAC and should be the ICAO code for airlines.</inlineHelpText>
        <label>Airline Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Customer_ID__c</fullName>
        <description>Customer Account ID. External ID of Account, not shown in UI; may be redundant with Party ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2I_Operator_Number__c</fullName>
        <description>Panasonic Operator Number 2 digit Airline Code; Not entered by sales</description>
        <inlineHelpText>The 2-digit customer code is assigned by PAC and should be the IATA code for airlines.</inlineHelpText>
        <label>Operator Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Party_Id__c</fullName>
        <description>Party Id</description>
        <externalId>true</externalId>
        <label>Party Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Payment_Term__c</fullName>
        <description>PAC Payment Terms</description>
        <inlineHelpText>Please select payment term</inlineHelpText>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NO TERMS</fullName>
                </value>
                <value>
                    <fullName>30 NET</fullName>
                </value>
                <value>
                    <fullName>Cash In Advance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Region_2</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <fields>
        <fullName>Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The type of the aircraft - may be a model (e.g. A380), master series (e.g. A380-800) or specific series (A380-841).  Contact Aircraft MDM to get a new type defined</inlineHelpText>
        <label>Aircraft Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>L2I_Aircraft_Type__c.L2I_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Aircrafts</relationshipLabel>
        <relationshipName>Aircrafts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether this value can be selected in pick lists/drop down boxes.  Used to prevent users from selecting old values which cannot be deleted.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Master_Series__c</fullName>
        <inlineHelpText>The general master series of the aircraft (e.g. 200, 300) - used to refer to many variants</inlineHelpText>
        <label>Master Series</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Model__c</fullName>
        <inlineHelpText>The high level name of the Aircraft Model (e.g. A380, 737) - groups many master series</inlineHelpText>
        <label>Model</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Series__c</fullName>
        <inlineHelpText>The specific series / subtype of the aircraft (e.g. 241, 341) - used in service to identify specific aircraft variants.</inlineHelpText>
        <label>Series</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <fields>
        <fullName>Aircraft_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Aircraft Type that is associated with this Delivery Schedule Header</description>
        <inlineHelpText>Aircraft Type that is associated with this Delivery Schedule Header</inlineHelpText>
        <label>xxAircraft Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>L2I_Aircraft_Type__c.L2I_Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedule_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Deal Opportunity with which this Delivery Schedule Header is associated with.</description>
        <inlineHelpText>Select the Deal Opportunity associated with this Delivery Schedule Header</inlineHelpText>
        <label>xxDeal Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Opportunity must be a &quot;Deal&quot; Opportunity</errorMessage>
            <filterItems>
                <field>Opportunity.L2I_Record_Type__c</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedule_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <recordTypes>
        <fullName>Hardware</fullName>
        <active>true</active>
        <description>Hardware DSH Record Type</description>
        <label>Hardware</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Opportunity__c</fullName>
        <description>Getting the Deal Opportunity record from the Delivery Schedule Header. (For use in the Flow on the Deal Lightning Page.</description>
        <formula>Delivery_Schedule_Header__r.Deal_Opportunity__c</formula>
        <label>xxDeal Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <inlineHelpText>This field is required for Hardware Delivery Schedule Lines</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Head_End_Date__c</fullName>
        <label>Head End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seat_End_Date__c</fullName>
        <label>Seat End Date</label>
        <type>Date</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <recordTypes>
        <fullName>Hardware</fullName>
        <active>true</active>
        <label>Hardware</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Type</label>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/L2I_Region_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Americas</fullName>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>South Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Oceana</fullName>
        <isActive>false</isActive>
        <label>Oceana</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

classes/L2I_DeliveryScheduleLineController_Test.cls
/**
 *      @author       Raj Rajen
 *      @date         12/12/2019
 *      @description  Test class for L2I_DeliveryScheduleLineController
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Raj Rajen                     12/12/2019         Initial setup of tests
 *
 */
@IsTest(SeeAllData=false)
public class L2I_DeliveryScheduleLineController_Test {

    @IsTest
    static void update_delivery_schedule_lines() {

        Account testAccount = new Account(Name = 'BRITISH AIRWAYS CORP',
                                          L2I_Payment_Term__c = '30 NET -a',
                                          L2I_Customer_Group__c = 'External',
                                          L2I_Customer_ID__c = '1083',
                                          L2I_Party_Id__c = '1083',
                                          L2I_Region__c = 'Europe',
                                          L2I_Operator_Number__c = 'BA',
                                          L2I_Airline_Code__c = 'BAW',
                                          AccountNumber = '1058',
                                          L2I_Account_Status__c = 'Active');
        insert testAccount;

        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);

        Opportunity testParentOpp = new Opportunity(Name = 'TestParentOpp',
                                                    StageName = 'Quotation',
                                                    CloseDate = Date.today(),
                                                    AccountId = testAccount.Id,
                                                    RecordTypeId = RecordTypeIdOpportunityDeal);
        insert testParentOpp;

        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);

        Opportunity testOpp = new Opportunity(Name = 'TestParentOpp',
                                              StageName = 'Quotation',
                                              CloseDate = Date.today(),
                                              L2I_Parent_Opportunity__c = testParentOpp.Id,
                                              RecordTypeId = RecordTypeIdOpportunitySales);
        insert testOpp;

        L2I_Aircraft_Type__c airType = new L2I_Aircraft_Type__c(Name = '737 MAX 10',
                                                                L2I_Model__c = '737',
                                                                L2I_Master_Series__c = 'G4',
                                                                L2I_Series__c = 'Max 10',
                                                                L2I_Is_Active__c = true);
        insert airType;

        L2I_DSH__c delSched = new L2I_DSH__c(deal_Opportunity__c = testParentOpp.Id,
                                             Aircraft_Type__c = airType.Id);
        insert delSched;

        testOpp.L2I_Delivery_Schedule__c = delSched.Id;
        update testOpp;

        Id RecordTypeIdDeliverySchedLine = Schema.SObjectType.L2I_DSL__c.getRecordTypeInfosByName().get('Hardware').getRecordTypeId();

        L2I_DSL__c delSchedLine1 = new L2I_DSL__c(Delivery_Schedule_Header__c = delSched.Id,
                                                  Line_Number__c = '01',
                                                  Delivery_Date__c = Date.today(),
                                                  Head_End_Date__c = Date.today().addMonths(-3),
                                                  Seat_End_Date__c = Date.today().addMonths(-6),
                                                  RecordTypeId = RecordTypeIdDeliverySchedLine);
        insert delSchedLine1;

        L2I_DSL__c delSchedLine2 = new L2I_DSL__c(Delivery_Schedule_Header__c = delSched.Id,
                                                  Line_Number__c = '02',
                                                  Delivery_Date__c = Date.today(),
                                                  Head_End_Date__c = Date.today().addMonths(-3),
                                                  Seat_End_Date__c = Date.today().addMonths(-6),
                                                  RecordTypeId = RecordTypeIdDeliverySchedLine);
        insert delSchedLine2;

        String dslsJSON = '{"data":[{"deliveryDate":"2099-01-01","dslId":"'+delSchedLine1.Id+'"},{"deliveryDate":"2099-02-01","dslId":"'+delSchedLine2.Id+'"}]}';
        L2I_DeliveryScheduleLineController.updateDSLs(dslsJSON);

        L2I_DataFactory factory = new L2I_DataFactory();

        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;

        L2I_Aircraft__c ac = factory.createAircraft( airType.Id, 'Test User Name', '2333-11131133114499999988888805', namedCustomer.Id);
        insert ac;

        String dslJSON = '{"aircraftConfirmation":false,"aircraftName":"","deliveryDate":"2099-09-02","dslId":"'+delSchedLine1.Id+'","headEndDate":"2099-06-01","seatEndDate":"2099-03-01"}';
        L2I_DeliveryScheduleLineController.updateDSL(dslJSON);

        Date dd1 = Date.valueOf('2099-09-02');
        L2I_DSL__c dsl1 = [select Id, Delivery_Date__c from L2I_DSL__c where Id = :delSchedLine1.Id limit 1];
        System.assert(dsl1 != null, 'Delivery Schedule Line must exist');
        System.assert(dsl1.Delivery_Date__c == dd1, 'Delivery Date must match');

        dslJSON = '{"aircraftConfirmation":false,"aircraftName":{"Id":"'+ac.Id+'"},"deliveryDate":"2199-09-02","dslId":"'+delSchedLine1.Id+'","headEndDate":"2099-06-01","seatEndDate":"2099-03-01"}';
        L2I_DeliveryScheduleLineController.updateDSL(dslJSON);

        Date dd2 = Date.valueOf('2199-09-02');
        dsl1 = [select Id, Delivery_Date__c from L2I_DSL__c where Id = :delSchedLine1.Id limit 1];
        System.assert(dsl1 != null, 'Delivery Schedule Line must exist');
        System.assert(dsl1.Delivery_Date__c == dd2, 'Delivery Date must match');
    }

}