objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>PT_Configured_Quantity__c</fullName>
        <label>Configured Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>XXPart List Note</label>
        <referenceTo>PT_Note__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Notes_Status__c</fullName>
        <label>Notes Status</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Original_Install_Location__c</fullName>
        <label>Original Install Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Pending_Notes__c</fullName>
        <label>Pending Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Pending__c</fullName>
        <label>Pending MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>PT Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Pending Replaced</fullName>
                </value>
                <value>
                    <fullName>Reinitialized</fullName>
                </value>
                <value>
                    <fullName>Pending Removed</fullName>
                </value>
                <value>
                    <fullName>Pending Move</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PT Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Num__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Number</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Date__c</fullName>
        <label>PL Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Status__c</fullName>
        <label>PL Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>PPM Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Parts_List_Revision_Number__c</fullName>
        <description>Parts List Revision Number starts with 1 and increments by 1 every time Part List is revised.</description>
        <inlineHelpText>Parts List Revision Number starts with 1 and increments by 1, every time Part List is revised.</inlineHelpText>
        <label>Parts List Revision Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <label>Install Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_List_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Install Location linked to Part List Opportunity</inlineHelpText>
        <label>Part List Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pending_MROD__c</fullName>
        <label>Pending MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShipSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ShipSet</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Note__c.object
<CustomObject>
    <fields>
        <fullName>PT_Note_Name__c</fullName>
        <label>Note Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Notes__c</fullName>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Pending_Notes__c</fullName>
        <label>Pending Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Part List Note</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part List Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program_Number__c</fullName>
        <externalId>true</externalId>
        <label>Program Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_PartsListPDFControllerTest.cls
/**
* @File Name          : PT_PartsListPDFControllerTest.cls
* @Description        : Test Class for PT_PartsListPDFController
* @Author             :
* @Last Modified By   : MS Simplus Khrisna
* @Last Modified On   : Mar 31, 2022
* @Modification Log   : 
* Ver           Date           Author               Modification
*                                                   Initial Version
* W-001727      Mar 31 2022    MS Simplus Khrisna   Primary System Type Validation Rule
**/
@IsTest
private class PT_PartsListPDFControllerTest {
    
    @IsTest
    static void testLoadData() {
        L2I_DataFactory factory = new L2I_DataFactory();
        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        
        Opportunity dealOppty = factory.createDealOpportunity('Deal', 'Open', 30, namedCustomer.Id);
        insert dealOppty;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;

        Opportunity salesOppty = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, namedCustomer.Id,
              dealOppty.Id, 200000, 'IFEC');
        salesOppty.OwnerId = UserInfo.getUserId();
        salesOppty.PT_Parts_List_Revision_Number__c = 0; //Khrisna W-003269
        salesOppty.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesOppty;
        L2I_DSH__c dsh = new L2I_DSH__c();
        insert dsh;
        
        PT_Program__c pgm = new PT_Program__c(
              Name = 'Prog1',
              Program_Number__c = 'Prog1'
        );
        insert pgm;
        System.debug('*** pgm ' + pgm);
        
        salesOppty.Pricebook2Id = Test.getStandardPricebookId();
        salesOppty.L2I_Delivery_Schedule__c = dsh.Id;
        update salesOppty;
        
        salesOppty.Pricebook2Id = Test.getStandardPricebookId();
        salesOppty.L2I_Program_Num__c = pgm.Id;
        update salesOppty;
        
        
        SBQQ__SolutionGroup__c sg = new SBQQ__SolutionGroup__c(
              Name = 'ALT'
        );
        insert sg;
        List<String> solGroupList = new List<String>{
              sg.Id
        };
        L2I_DSL__c dsl = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id,
              Original_Opportunity__c = salesOppty.Id
        );
        insert dsl;
        
        L2I_DSL__c dsl2 = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id,
              Original_Opportunity__c = salesOppty.Id
        );
        insert dsl2;
        
        PT_Install_Location__c instLoc = new PT_Install_Location__c(
              Name = 'CW',
              ShipSet__c = dsl.Id,
              Pending_MROD__c = Date.today(),
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc;
        
        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'BC',
              ShipSet__c = dsl2.Id,
              Pending_MROD__c = Date.today(),
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc2;
        
        Product2 prod = factory.createProduct('99999802', 'MediaServices', '', '', null);
        prod.productCode = 'MCS BUNDLE';
        insert prod;
        
        Asset ast = new Asset(
              Name = 'Asset Name',
              PT_Install_Location__c = instLoc.Id,
              PT_Original_Install_Location__c = instLoc2.Name,
              PT_Pending__c = Date.today(),
              PT_Program__c = pgm.Id,
              Product2Id = prod.Id,
              AccountId = namedCustomer.Id,
              PT_Configured_Quantity__c = 10,
              Quantity = 10,
              PT_Status__c = 'Active',
              PT_Pending_Notes__c = 'Remove Notes',
              PT_Notes__c = 'A,D',
              PT_Notes_Status__c = '[{"noteStatus":"Delete","noteName":"D"},{"noteStatus":"Delete","noteName":"C"}]'
        );
        insert ast;
    
        Asset ast2 = new Asset(
              Name = 'Asset Name',
              PT_Install_Location__c = instLoc2.Id,
              PT_Pending__c = Date.today(),
              PT_Program__c = pgm.Id,
              Product2Id = prod.Id,
              AccountId = namedCustomer.Id,
              PT_Configured_Quantity__c = 10,
              Quantity = 10,
              PT_Status__c = 'Active',
              PT_Notes__c = 'A,D'
        );
        insert ast2;
    
        Asset ast3 = new Asset(
              Name = 'Asset Name',
              PT_Install_Location__c = instLoc2.Id,
              PT_Pending__c = Date.today(),
              PT_Program__c = pgm.Id,
              Product2Id = prod.Id,
              AccountId = namedCustomer.Id,
              PT_Configured_Quantity__c = 10,
              Quantity = 10,
              PT_Status__c = 'Active',
              PT_Notes__c = 'A,D'
        );
        insert ast3;
        //Khrisna W-003269
        Product2 prod2 = factory.createProduct('90000000', 'IFE MISCELLANEOUS', '', '', null);
        prod2.productCode = 'IFE MISCELLANEOUS';
        insert prod2;

        Asset ast4 = new Asset(
              Name = 'Asset Name',
              PT_Install_Location__c = instLoc2.Id,
              PT_Pending__c = Date.today(),
              PT_Program__c = pgm.Id,
              Product2Id = prod2.Id,
              AccountId = namedCustomer.Id,
              PT_Configured_Quantity__c = 1,
              Quantity = 1,
              PT_Status__c = 'Active',
              PT_Notes__c = 'A,D'
        );
        insert ast4;
        //Khrisna W-003269
        PT_Note__c note = new PT_Note__c(
              PT_Note_Name__c = 'Note A',
              PT_Sequence__c = 1,
              PT_Opportunity__c = salesOppty.Id,
              PT_Notes__c = 'Note123'
        );
        insert note;
        List<Id> oppIdList = new List<Id>();
        oppIdList.add(salesOppty.Id);
        PT_PartList_Utils.createPendingPartListRecords(oppIdList);

        ApexPages.StandardController standardController = new ApexPages.StandardController(salesOppty);
        PT_PartsListPDFController plc = new PT_PartsListPDFController(standardController);
        System.assertEquals(pgm.Name, plc.oppw.program);
        System.assertEquals(1, plc.noteWrapperList.size());
        // Khrisna W-003269
        ast4.PT_Status__c = 'Pending Removed';
        update ast4;

        List<Id> updateOppIdList = new List<Id>();
        updateOppIdList.add(salesOppty.Id);
        PT_PartList_Utils.createPendingPartListRecords(updateOppIdList);

        salesOppty.PT_PL_Approval_Status__c = 'Approved';
        salesOppty.PT_PL_Approval_Date__c = System.now();
        update salesOppty;

        PT_PartList_Utils.updateOpportunityPostApproval(salesOppty.Id);
        PT_PartList_Utils.updatePartListPostApproval(salesOppty.Id);

        Test.startTest();
        ApexPages.StandardController standardController2 = new ApexPages.StandardController(salesOppty);
        PT_PartsListPDFController plc2 = new PT_PartsListPDFController(standardController2);
        System.assertNotEquals(null, plc2.plrListWrapper);
        Test.stopTest();
    }
}