objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IFE_Email_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Opt In</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Document__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Modified_Date__c</fullName>
        <inlineHelpText>Required to be set so that it can be picked up by weekly email batch</inlineHelpText>
        <label>Document Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Publication</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>GCS</fullName>
                </value>
                <value>
                    <fullName>Spare Parrs</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <label>Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>IFE Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IFE_Document_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFE_Document__c</fullName>
        <label>IFE Document</label>
        <referenceTo>IFE_Document__c</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IFE Customer Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Customer Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>IFE_Email_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Email Opt In for Technical Publications</description>
        <label>Tech Pub Email Opt In</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ife_DocumentSendEmailBatchTest.cls
@isTest
private class ife_DocumentSendEmailBatchTest {
    public static String CRON_EXP = '0 0 22 * * ? *';
    
    @isTest
    public static void executeTest1(){
        
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        system.debug('portalRole is ' + portalRole);
        
        User userObj = ife_TestDataUtil.CreateUser(true);
        userObj.UserRoleId =  portalRole.Id;
        update userObj;
        
        System.runAs ( userObj ) {
            
            Account acc = ife_TestDataUtil.createAccount(true);
            
            Contact con = ife_TestDataUtil.createContact(acc.Id, true);
            
            Profile portalProfile = [SELECT Id FROM Profile where name = 'PAC Customer' limit 1];
            User usr = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = con.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTesty',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                IFE_Email_Opt_In__c = true);
            
            insert usr;
            
            String strRecordTypeId = [Select Id From RecordType Where Name = 'Technical Publication'].Id;
            
            IFE_Document__c ifeDocument = new IFE_Document__c();
            ifeDocument.Description__c = 'Testring--';
            ifeDocument.Revision__c = 'Test';
            ifeDocument.File_Name__c = 'Test';
            ifeDocument.RecordTypeId = strRecordTypeId;
            ifeDocument.Document_Type__c = 'Technical Publication';
            ifeDocument.Document_Modified_Date__c = Date.today();
            insert ifeDocument;
            
            
            IFE_Document_Account__c docAccount = new IFE_Document_Account__c();
            docAccount.IFE_Document__c = ifeDocument.Id;
            docAccount.Account__c = acc.Id;
            insert docAccount;
            
            Test.startTest();
            ife_DocumentSendEmailBatch docSendEmail = new ife_DocumentSendEmailBatch();
            Database.executeBatch(docSendEmail);
            
            String jobId = System.schedule('ScheduleApexClassTest', CRON_EXP, docSendEmail);
            Test.stopTest();
        }
    }
}