objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Account_Status__c</fullName>
        <description>Account Status</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Status-1</fullName>
                </value>
                <value>
                    <fullName>Status-2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Airline_Code__c</fullName>
        <description>3 digit Airline Code</description>
        <inlineHelpText>The 3-digit customer code is assigned by PAC and should be the ICAO code for airlines.</inlineHelpText>
        <label>Airline Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Customer_Group__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Customer_ID__c</fullName>
        <description>Customer Account ID. External ID of Account, not shown in UI; may be redundant with Party ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2I_Operator_Number__c</fullName>
        <description>Panasonic Operator Number 2 digit Airline Code; Not entered by sales</description>
        <inlineHelpText>The 2-digit customer code is assigned by PAC and should be the IATA code for airlines.</inlineHelpText>
        <label>Operator Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Party_Id__c</fullName>
        <description>Party Id</description>
        <externalId>true</externalId>
        <label>Party Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Payment_Term__c</fullName>
        <description>PAC Payment Terms</description>
        <inlineHelpText>Please select payment term</inlineHelpText>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NO TERMS</fullName>
                </value>
                <value>
                    <fullName>30 NET</fullName>
                </value>
                <value>
                    <fullName>Cash In Advance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Region_2</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <recordTypes>
        <fullName>Hardware</fullName>
        <active>true</active>
        <description>Hardware DSH Record Type</description>
        <label>Hardware</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <inlineHelpText>This field is required for Hardware Delivery Schedule Lines</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <recordTypes>
        <fullName>Hardware</fullName>
        <active>true</active>
        <label>Hardware</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Revise</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/L2I_Region_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Americas</fullName>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>South Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Oceana</fullName>
        <isActive>false</isActive>
        <label>Oceana</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_DeliverySchedLWCController_Test.cls
/**
 *      @author       Raj Rajen
 *      @date         12/12/2019
 *      @description  Test class for L2I_DeliverySchedController_Test
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Raj Rajen                     12/12/2019         Initial setup of tests
 *      Sarah Kennedy                 01/04/2020         Initialized from L2I_DeliveryScheduleWizard
 *
 */
@isTest
public class L2I_DeliverySchedLWCController_Test {

    static testMethod void validateGetDeliverySchedules() {

        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;

        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);

        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;

        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);

        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunitySales
        );
        insert testOpp;

        L2I_DSH__c delSched = new L2I_DSH__c();
        insert delSched;

        testOpp.L2I_Delivery_Schedule__c = delSched.Id;
        update testOpp;

        Id RecordTypeIdDeliverySchedLine = Schema.SObjectType.L2I_DSL__c.getRecordTypeInfosByName().get('Hardware').getRecordTypeId();

        L2I_DSL__c delSchedLine = new L2I_DSL__c(
              Delivery_Schedule_Header__c = delSched.Id,
              Line_Number__c = '01',
              Delivery_Date__c = Date.today(),
              RecordTypeId = RecordTypeIdDeliverySchedLine
        );
        insert delSchedLine;

        L2I_DSL__c delSchedLine2 = new L2I_DSL__c(
              Delivery_Schedule_Header__c = delSched.Id,
              Line_Number__c = '02',
              Delivery_Date__c = Date.today(),
              RecordTypeId = RecordTypeIdDeliverySchedLine
        );
        insert delSchedLine2;

        L2I_DeliverySchedLWCController.getDeliverySchedules(testOpp.Id, null);
        L2I_DeliverySchedLWCController.getDeliverySchedules(testParentOpp.Id, null);
        L2I_DeliverySchedLWCController.getDeliverySchedules(null, delSched.Id);
        L2I_DeliverySchedLWCController.getDeliverySchedules(delSched.Id, null);
    }

    static testMethod void validateCreateDeliverySchedules() {

        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;

        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);

        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;

        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);

        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunitySales
        );
        insert testOpp;

        String deliveryScheduleInformation = '{"data":{"deliveryScheduleLines":[],"dsId":"","objectName":"Opportunity","recordId":"' + testOpp.Id + '"}}';
        L2I_DeliverySchedLWCController.createDeliveryScheduleHeader(deliveryScheduleInformation);

    }

    static testMethod void validateCreateDeliveryScheduleLines() {

        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;

        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);

        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;

        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);

        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunitySales
        );
        insert testOpp;

        // need to change once the aircraft qty gets moved to the opportunity
        L2I_DSH__c delSched = new L2I_DSH__c();
        insert delSched;

        testOpp.L2I_Delivery_Schedule__c = delSched.Id;
        update testOpp;

        String deliveryScheduleInformation = '{"data":{"accountName":"' + testAccount.Id + '","createdBy":"Blake Poutra","aircraftQuantity":"2","interval":"1","deliveryInterval":"Same Date","createdDate":"2019-08-22","deliveryScheduleLines":[],"dsId":"' + delSched.Id + '","dsName":"DSH-00115"}}';
        L2I_DeliverySchedLWCController.createDeliveryScheduleLines(deliveryScheduleInformation, Date.today(), testOpp.Id);
        L2I_DeliverySchedLWCController.createDeliveryScheduleLines(deliveryScheduleInformation, Date.today(), testOpp.Id);
        L2I_DeliverySchedLWCController.createDeliveryScheduleLines(deliveryScheduleInformation, Date.today(), testOpp.Id);
        L2I_DeliverySchedLWCController.createDeliveryScheduleLines(deliveryScheduleInformation, Date.today(), testOpp.Id);
        L2I_DeliverySchedLWCController.createDeliveryScheduleLines(deliveryScheduleInformation, Date.today(), testOpp.Id);

    }

    static testMethod void validateDeleteDeliveryScheduleLines() {

        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;

        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);

        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;

        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);

        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunitySales
        );
        insert testOpp;

        L2I_DSH__c delSched = new L2I_DSH__c();
        insert delSched;

        testOpp.L2I_Delivery_Schedule__c = delSched.Id;
        update testOpp;

        Id RecordTypeIdDeliverySchedLine = Schema.SObjectType.L2I_DSL__c.getRecordTypeInfosByName().get('Hardware').getRecordTypeId();

        L2I_DSL__c delSchedLine = new L2I_DSL__c(
              Delivery_Schedule_Header__c = delSched.Id,
              Line_Number__c = '01',
              Delivery_Date__c = Date.today(),
              RecordTypeId = RecordTypeIdDeliverySchedLine
        );
        insert delSchedLine;

        List<String> dslIdsList = new List<String>{
              delSchedLine.Id
        };
        L2I_DeliverySchedLWCController.deleteDeliveryScheduleLines(dslIdsList, testOpp.Id);

    }
    
    static testMethod void validateResetDeliveryScheduleLinesSalesOpp() {
        
        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;
        
        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);
        
        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;
        
        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);
        
        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunitySales
        );
        insert testOpp;
        
        L2I_DSH__c delSched = new L2I_DSH__c();
        insert delSched;
        
        testOpp.L2I_Delivery_Schedule__c = delSched.Id;
        update testOpp;
        
        Id RecordTypeIdDeliverySchedLine = Schema.SObjectType.L2I_DSL__c.getRecordTypeInfosByName().get('Hardware').getRecordTypeId();
        
        L2I_DSL__c delSchedLine = new L2I_DSL__c(
              Delivery_Schedule_Header__c = delSched.Id,
              Line_Number__c = '01',
              Delivery_Date__c = Date.today(),
              Original_Opportunity__c = testOpp.Id,
              RecordTypeId = RecordTypeIdDeliverySchedLine
        );
        insert delSchedLine;
        
        List<String> dslIdsList = new List<String>{
              delSchedLine.Id
        };
        L2I_DeliverySchedLWCController.resetDeliveryScheduleLines(testOpp.Id);
    
        System.assertEquals(1, [SELECT COUNT() FROM L2I_DSL__c]);
    }
    
    static testMethod void validateResetDeliveryScheduleLinesRenewal() {
        
        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;
        
        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);
        
        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;
        
        Id RecordTypeIdOpportunityRenewal = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Renewal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityRenewal: ' + RecordTypeIdOpportunityRenewal);
        
        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunityRenewal
        );
        insert testOpp;
        
        L2I_DSH__c delSched = new L2I_DSH__c();
        insert delSched;
        
        testOpp.L2I_Delivery_Schedule__c = delSched.Id;
        update testOpp;
        
        Id RecordTypeIdDeliverySchedLine = Schema.SObjectType.L2I_DSL__c.getRecordTypeInfosByName().get('Hardware').getRecordTypeId();
        
        L2I_DSL__c delSchedLine = new L2I_DSL__c(
              Delivery_Schedule_Header__c = delSched.Id,
              Line_Number__c = '01',
              Delivery_Date__c = Date.today(),
              Original_Opportunity__c = testOpp.Id,
              RecordTypeId = RecordTypeIdDeliverySchedLine
        );
        insert delSchedLine;
        
        List<String> dslIdsList = new List<String>{
              delSchedLine.Id
        };
        L2I_DeliverySchedLWCController.resetDeliveryScheduleLines(testOpp.Id);
        
        System.assertEquals(0, [SELECT COUNT() FROM L2I_DSL__c]);
    }

    static testMethod void validateSaveDeliveryScheduleToOpportunity() {

        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;

        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);

        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;

        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);

        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunitySales
        );
        insert testOpp;

        L2I_DSH__c delSched;
        try {
            delSched = new L2I_DSH__c();
            insert delSched;
        } catch (Exception e) {
            System.debug('error: ' + e);
        }

        System.debug('*** testOpp.Id ' + testOpp.Id);
        System.debug('*** delSched.Id ' + delSched.Id);

        L2I_DeliverySchedLWCController.saveDeliveryScheduleToOpportunity(testOpp.Id, delSched.Id);

    }

    static testMethod void validatePushPull() {

        Account testAccount = new Account(
              Name = 'BRITISH AIRWAYS CORP',
              L2I_Payment_Term__c = '30 NET -a',
              L2I_Customer_Group__c = 'External',
              L2I_Customer_ID__c = '1083',
              L2I_Party_Id__c = '1083',
              L2I_Region__c = 'Europe',
              L2I_Operator_Number__c = 'BA',
              L2I_Airline_Code__c = 'BAW',
              AccountNumber = '1058',
              L2I_Account_Status__c = 'Active'
        );
        insert testAccount;

        Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
        System.debug('RecordTypeIdOpportunityDeal: ' + RecordTypeIdOpportunityDeal);

        Opportunity testParentOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              AccountId = testAccount.Id,
              RecordTypeId = RecordTypeIdOpportunityDeal
        );
        insert testParentOpp;

        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        System.debug('RecordTypeIdOpportunitySales: ' + RecordTypeIdOpportunitySales);

        Opportunity testOpp = new Opportunity(
              Name = 'TestParentOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = testParentOpp.Id,
              AccountId = testAccount.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = RecordTypeIdOpportunitySales
        );
        insert testOpp;

        L2I_DSH__c sched = new L2I_DSH__c();
        insert sched;

        testOpp.L2I_Delivery_Schedule__c = sched.Id;
        update testOpp;

        Id RecordTypeIdDeliverySchedLine = Schema.SObjectType.L2I_DSL__c.getRecordTypeInfosByName().get('Hardware').getRecordTypeId();

        L2I_DSL__c schedLine = new L2I_DSL__c(
              Delivery_Schedule_Header__c = sched.Id,
              Line_Number__c = '01',
              Delivery_Date__c = Date.today(),
              RecordTypeId = RecordTypeIdDeliverySchedLine
        );
        insert schedLine;

        List<String> dslIdsList = new List<String>{
              schedLine.Id
        };
        L2I_DeliverySchedLWCController.pushPullDeliveryDates('+1', '1', dslIdsList, sched.Id);
        schedLine = [SELECT Id, Delivery_Date__c FROM L2I_DSL__c WHERE Id = :schedLine.Id];

        System.assertEquals(Date.today().addMonths(1), schedLine.Delivery_Date__c, 'Delivery Date is one month later');
    }

    @isTest
    static void testDeleteDeliverySchedule() {
        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupAccountThruOrder(null, null, false, 'Activated');
    
        Test.startTest();
        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity opp = [SELECT Id, L2I_Delivery_Schedule__c FROM Opportunity WHERE RecordTypeId = :RecordTypeIdOpportunitySales LIMIT 1];
        
        L2I_DeliverySchedLWCController.deleteDeliverySchedule(opp.L2I_Delivery_Schedule__c);
        Test.stopTest();
        System.assertEquals(0, [SELECT COUNT() FROM L2I_DSH__c]);
    }
    
    @IsTest
    static void testDSHUpdate(){
        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupAccountThruOrder(null, null, false, 'Activated');
    
        Test.startTest();
        Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity opp = [SELECT Id, L2I_Delivery_Schedule__c FROM Opportunity WHERE RecordTypeId = :RecordTypeIdOpportunitySales LIMIT 1];
        L2I_DSH__c dsh = [SELECT Id FROM L2I_DSH__c LIMIT 1];
        L2I_DeliverySchedLWCController.updateDeliverySchedule('{"data":[{"deliveryDateOffset":"5","dsId":"' + dsh.Id + '"}]}');
        Test.stopTest();
    }
}