objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <description>Used to track Competitor</description>
        <label>Competitor</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Competitors__c.object
<CustomObject>
    <description>Object to track competitors between Opportunity and Account (Record Type Competitor)</description>
    <fields>
        <fullName>CompetitorAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Competitor Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Competitors</relationshipLabel>
        <relationshipName>OpportunityCompetitors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IFEC</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>PTS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_Trigger_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Settings to manage execution of triggers per user or profile. This is very useful as a kill-switch to disable execution of a trigger during data migration</description>
    <fields>
        <fullName>Disable_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Quote</label>
        <type>Checkbox</type>
    </fields>
    <label>L2I Trigger Settings</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Closed_Lost_Reasoning__c</fullName>
        <label>Closed NOT WON Reasoning</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Fit_Type__c</fullName>
        <label>Fit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>L2I_Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell/Follow-on</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Win_Loss_Date__c</fullName>
        <description>This field will be used to capture Win/Loss Date when Opportunity stages reach Closed won, Closed lost, and no bid.</description>
        <label>Win/Loss Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Revise</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_QuoteTriggerFunctionsTest.cls
/**
 *      @author       Arun vadduri
 *      @date         07/12/2019
 *      @description  Test Class for L2I_QuoteTrigger
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Arun Vadduri                  07/12/2019            Test Class for L2I_QuoteTrigger
 *      Arun Vadduri                  08/19/2019            Refactored L2I_QuoteTriggerTest to cover L2I_Quote_TriggerFunctions
 *      Sarah Kennedy                 03/31/2020            US1618 added test for close Lost Renewal
 */
@isTest
private class L2I_QuoteTriggerFunctionsTest {
    
    @isTest
    private static void testQuoteClone() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;
        
        SBQQ__Quote__c quote2 = quote.clone(false, true, false, false);
        
        Test.startTest();
        try {
            insert quote2;
        } Catch (Exception e) {
        }
        Test.stopTest();
    }
    
    @isTest
    private static void testDisableTrigger() {
        insert new L2I_Trigger_Settings__c(SetupOwnerId = UserInfo.getUserId(), Disable_Quote__c = true);
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        
        Test.startTest();
        insert quote;
        Test.stopTest();
    }
    
    @IsTest
    static void testRenewalQuote() {
        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupTestContext(null, null, false);
        
        // create objects
        L2I_ObjectFactory objFactory = new L2I_ObjectFactory();
        objFactory.loadResource('Unit_Test_AccountThruQuote');
        
        Account acct = [SELECT Id FROM Account WHERE Name = 'Test Account Name' LIMIT 1];
    
        Account competitorCustomer = [SELECT Id FROM Account WHERE Recordtype.Developername = 'Competitor' LIMIT 1];
        
        Opportunity oppDeal = [
              SELECT Id, Name, L2I_Delivery_Schedule__c, StageName, L2I_Win_Loss_Date__c
              FROM Opportunity
              WHERE Recordtype.DeveloperName = 'Deal'
              LIMIT 1
        ];
        
        L2I_DSH__c dsh = [SELECT Id FROM L2I_DSH__c LIMIT 1];
        
        String renewId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Renewal').getRecordTypeId();
        Opportunity renewalOpp = new Opportunity(
              L2I_Parent_Opportunity__c = oppDeal.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = renewId,
              StageName = 'Quotation',
              L2I_Closed_Lost_Reasoning__c = 'test',
              L2I_Win_Loss_Date__c = Date.today(),
              L2I_Fit_Type__c = 'Renewal',
              Name = 'Renew Opp',
              CloseDate = Date.today(),
              L2I_Delivery_Schedule__c = dsh.Id
        );
        insert renewalOpp;
    
        L2I_Competitors__c comp = new L2I_Competitors__c();
        comp.Opportunity__c = renewalOpp.Id;
        comp.CompetitorAccount__c = competitorCustomer.Id;
        comp.Type__c = 'DSS';
        comp.Primary__c = true;
        insert comp;
        
        renewalOpp.StageName = 'Closed Lost';
        update renewalOpp;
        
        
        SBQQ__Quote__c quote = factory.createQuote('draft', acct.Id, renewalOpp.Id, true);
        insert quote;
    }
}