objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Order__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Aircraft Orders</relationshipLabel>
        <relationshipName>Aircraft_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Aircraft Orders</relationshipLabel>
        <relationshipName>Aircraft_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aircraft Order</label>
    <nameField>
        <displayFormat>AO{0000}</displayFormat>
        <label>Aircraft Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Service__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxAircraft Order</label>
        <referenceTo>L2I_Aircraft_Order__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <formula>Aircraft__r.Aircraft_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Deactivation_Date__c</fullName>
        <label>Deactivation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Aircraft Service</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Aircraft Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether this value can be selected in pick lists/drop down boxes.  Used to prevent users from selecting old values which cannot be deleted.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Master_Series__c</fullName>
        <inlineHelpText>The general master series of the aircraft (e.g. 200, 300) - used to refer to many variants</inlineHelpText>
        <label>Master Series</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Model__c</fullName>
        <inlineHelpText>The high level name of the Aircraft Model (e.g. A380, 737) - groups many master series</inlineHelpText>
        <label>Model</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Series__c</fullName>
        <inlineHelpText>The specific series / subtype of the aircraft (e.g. 241, 341) - used in service to identify specific aircraft variants.</inlineHelpText>
        <label>Series</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/L2I_ReactivateAircraftService_Test.cls
@isTest
public class L2I_ReactivateAircraftService_Test {

    static testMethod void validateGetAircraftServiceRecords() {
        /**
        L2I_Aircraft__c aircraft = new L2I_Aircraft__c();
        insert aircraft;

        L2I_Aircraft_Type__c airType = new L2I_Aircraft_Type__c(
            Name = '737 MAX 10',
            L2I_Model__c = '737',
            L2I_Master_Series__c = 'G4',
            L2I_Series__c = 'Max 10',
            L2I_Is_Active__c = true
        );
        insert airType;
        **/
        L2I_DataFactory factory = new L2I_DataFactory();

        Account namedCustomer = factory.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        System.assert(namedCustomer.Id != null, 'Named Customer Account must have an Id');

        L2I_Aircraft_Type__c att = factory.createAircraftType( namedCustomer.Id, 123456);
        att.Name = '737 MAX 10';
        att.L2I_Model__c = '737';
        att.L2I_Master_Series__c = 'G4';
        att.L2I_Series__c = 'Max 10';
        att.L2I_Is_Active__c = true;
        insert att;
        System.assert(att.Id != null, 'Aircraft Type cannot be null');

        L2I_Aircraft__c aircraft = factory.createAircraft(att.Id, 'Name', '2333-11131133114499999988888805', namedCustomer.Id);
        insert aircraft;

        /**
        L2I_Aircraft_Order__c airOrder = new L2I_Aircraft_Order__c(
            Aircraft__c = '',
            Order__c = ''
        );
        insert airOrder;
        **/

        L2I_Aircraft_Order__c airOrder = new L2I_Aircraft_Order__c(Aircraft__c = aircraft.Id, Order__c = null);
        insert airOrder;

        L2I_Aircraft_Service__c airService = new L2I_Aircraft_Service__c(
            Aircraft_Order__c = airOrder.Id,
            Status__c = 'Deactivated',
            L2I_Deactivation_Date__c = Date.today(),
            Aircraft__c = aircraft.Id
        );
        insert airService;

        airService.Status__c = 'Deactivated';
        airService.L2I_Deactivation_Date__c = Date.today();
        update airService;
        
        String serviceRecordResult = L2I_ReactivateAircraftService.getAircraftServiceRecords(airService.Id);
        System.assertEquals(serviceRecordResult, 'Success');
        
        String activateRecordResult = L2I_ReactivateAircraftService.activateServiceRecord(airService.Id, Date.today());
        System.assertNotEquals(activateRecordResult, 'There is an existing record with the same Billing Matching Id with a Status of Pending Activation or Activated.');

    }

}