objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Customer_ID__c</fullName>
        <description>Customer Account ID. External ID of Account, not shown in UI; may be redundant with Party ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Related_Account__c.object
<CustomObject>
    <description>Custom object to model the many-to-many relationships between PAC accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Account from which the relationship is being viewed</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related account</description>
        <label>Related To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Related To)</relationshipLabel>
        <relationshipName>Related_to_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Merger</fullName>
                </value>
                <value>
                    <fullName>Sister concern</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>MRO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Account</label>
    <nameField>
        <displayFormat>REL-{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Ife_AccountDropDownController.cls
public class Ife_AccountDropDownController{
	public Ife_AccountDropDownController(){
	}

	@AuraEnabled(cacheable = true)
	public static List<Account> getAccounts(List<String> accountRelationshipType){

		System.debug('accountRelationshipType----contains' + accountRelationshipType);
		User userObj = [SELECT Id, Name, Contact.AccountId, Contact.Account.L2I_Customer_ID__c
		                FROM User
		                WHERE Id = :UserInfo.getUserId()];
		if (userObj.Contact.AccountId != null){
			System.debug('userObj.Contact.AccountId----' + userObj.Contact.AccountId);
			return getRelatedAccounts(userObj.Contact.AccountId, accountRelationshipType);
		} else{
			return getRelatedAccounts(null, null);
		}
	}

	@AuraEnabled(cacheable = true)
	public static List<Account> getRelatedAccounts(String accountId, List<String> accountRelationshipType){
		Set<String> accountIds = new Set<String>();
		if (String.isNotBlank(accountId)){
			accountIds.add(accountId);
			for (L2I_Related_Account__c relatedAccount : [SELECT Id, Related_To__c, Relationship_Type__c
			                                              FROM L2I_Related_Account__c
			                                              WHERE Account__c = :accountId]){
				if (!accountRelationshipType.isEmpty()){
					if (accountRelationshipType.contains(relatedAccount.Relationship_Type__c)){
						accountIds.add(relatedAccount.Related_To__c);
					}
                }
                else{
                    accountIds.add(relatedAccount.Related_To__c);
                }
			}
		}
		System.debug('accountIds ----' + accountIds);
		if (!accountIds.isEmpty()){
			List<Account> accounts = [SELECT Id, Name, L2I_Customer_ID__c
			                          FROM Account
			                          WHERE Id = :accountIds AND L2I_Customer_ID__c != null];
			System.debug('accounts 1----' + accounts);

			return accounts;
		} else{
			List<Account> accounts = [SELECT Id, Name, L2I_Customer_ID__c
			                          FROM Account
			                          WHERE L2I_Customer_ID__c != null];
			System.debug('accounts 2----' + accounts);

			return accounts;

		}
	}
}