objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Account_Status__c</fullName>
        <description>Account Status</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Status-1</fullName>
                </value>
                <value>
                    <fullName>Status-2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_ConnectAPIService_Test.cls
/**
* @File Name          : L2I_ConnectAPIService_Test.cls
* @Description        : Test Class for L2I_ConnectAPIService
* @Author             :
* @Last Modified By   : MS Simplus Khrisna
* @Last Modified On   : Mar 31, 2022
* @Modification Log   : 
* Ver           Date           Author               Modification
*                                                   Initial Version
* W-001727      Mar 31 2022    MS Simplus Khrisna   Primary System Type Validation Rule
**/
@IsTest(SeeAllData=true)
private class L2I_ConnectAPIService_Test {
    // ConnectApi methods are not supported in data siloed tests. Please use @IsTest(SeeAllData=true).
    @IsTest
    static void testFeed() {
    
        L2I_DataFactory factory = new L2I_DataFactory();
        Profile salesProfile = L2I_StaticConstants.getProfileByName('PAC System Administrator');
        User salesUser = factory.createTestUser(null, salesProfile.Id, 'Sales', 'User');
        insert salesUser;
        
        test.startTest();  
        System.runAs(salesUser) {
            Account testAccount = new Account(Name = 'BRITISH AIRWAYS CORP',
                                              L2I_Account_Status__c = 'Active');
            insert testAccount;
            
            // Added for W-001727
            Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
            insert prodSysType;
            
            Id RecordTypeIdOpportunityDeal = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal').getRecordTypeId();
            Opportunity testParentOpp = new Opportunity(Name = 'TestParentOpp',
                                                        StageName = 'Quotation',
                                                        CloseDate = Date.today(),
                                                        AccountId = testAccount.Id,
                                                        RecordTypeId = RecordTypeIdOpportunityDeal);
            insert testParentOpp;
            
            Id RecordTypeIdOpportunitySales = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
            Opportunity testOpp = new Opportunity(Name = 'TestParentOpp',
                                                  StageName = 'Quotation',
                                                  CloseDate = Date.today(),
                                                  L2I_Parent_Opportunity__c = testParentOpp.Id,
                                                  L2I_Product_Category__c = 'IFEC',
                                                  RecordTypeId = RecordTypeIdOpportunitySales,
                                                  L2I_Primary_System_Type__c = prodSysType.Id);
            insert testOpp;
            
            List<L2I_ConnectAPIService.ConnectAPIWrap> caWrapList = new List<L2I_ConnectAPIService.ConnectAPIWrap>();
            L2I_ConnectAPIService.ConnectAPIWrap caWrap;
            caWrap = new L2I_ConnectAPIService.ConnectAPIWrap();
            caWrap.objectId = testOpp.Id;
            caWrap.ownerId = testOpp.OwnerId;
            caWrap.message = ' test message ';
            caWrapList.add(caWrap);
            
            Integer batchCount = L2I_ConnectAPIService.createChat(caWrapList);
            System.debug('*** batchCount ' + batchCount);
            System.assertEquals(1, batchCount);
        }       
    }
}