objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Customer_ID__c</fullName>
        <description>Customer Account ID. External ID of Account, not shown in UI; may be redundant with Party ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Related_Account__c.object
<CustomObject>
    <description>Custom object to model the many-to-many relationships between PAC accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Account from which the relationship is being viewed</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related account</description>
        <label>Related To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Related To)</relationshipLabel>
        <relationshipName>Related_to_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Merger</fullName>
                </value>
                <value>
                    <fullName>Sister concern</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>MRO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Account</label>
    <nameField>
        <displayFormat>REL-{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/MyIFECarrierRedirect__mdt.object
<CustomObject>
    <fields>
        <fullName>RedirectURL__c</fullName>
        <label>RedirectURL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MyIFECarrierRedirect</label>
    <pluralLabel>MyIFECarrierRedirects</pluralLabel>
</CustomObject>

objects/myifedeliverie__c.object
<CustomObject>
    <fields>
        <fullName>ACTUAL_SHIP_DATE__c</fullName>
        <label>Actual Ship Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DELIVERY_ID__c</fullName>
        <label>Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FREIGHT_CARRIER__c</fullName>
        <label>Freight Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITEM_DESCRIPTION__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITEM_NUMBER__c</fullName>
        <label>Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_ID__c</fullName>
        <label>Initiate RMA Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDER_NUMBER__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIPPED_QUANTITY_UOM__c</fullName>
        <label>UMO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIPPED_QUANTITY__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SHIP_FROM__c</fullName>
        <label>Ship From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIP_TO_LOCATION__c</fullName>
        <label>Ship To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>STATUS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WAYBILL__c</fullName>
        <label>WayBill</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WEIGHT__c</fullName>
        <label>WEIGHT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>myIfeDeliverie</label>
    <nameField>
        <label>myIfeDeliverie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>myIfeDeliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/myIfeDeliveries__x.object
<CustomObject>
    <description>myIfeDeliveries</description>
    <externalDataSource>Order_Status</externalDataSource>
    <externalName>myIfeDeliveries</externalName>
    <fields>
        <fullName>ACTUAL_SHIP_DATE__c</fullName>
        <description>ACTUAL_SHIP_DATE</description>
        <externalDeveloperName>ACTUAL_SHIP_DATE</externalDeveloperName>
        <label>ACTUAL_SHIP_DATE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_ID__c</fullName>
        <description>CUSTOMER_ID</description>
        <externalDeveloperName>CUSTOMER_ID</externalDeveloperName>
        <label>CUSTOMER_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DELIVERY_ID__c</fullName>
        <description>DELIVERY_ID</description>
        <externalDeveloperName>DELIVERY_ID</externalDeveloperName>
        <label>DELIVERY_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DELIVERY_NAME__c</fullName>
        <description>DELIVERY_NAME</description>
        <externalDeveloperName>DELIVERY_NAME</externalDeveloperName>
        <label>DELIVERY_NAME</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FREIGHT_CARRIER__c</fullName>
        <description>FREIGHT_CARRIER</description>
        <externalDeveloperName>FREIGHT_CARRIER</externalDeveloperName>
        <label>FREIGHT_CARRIER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INVOICE_NUMBER__c</fullName>
        <description>INVOICE_NUMBER</description>
        <externalDeveloperName>INVOICE_NUMBER</externalDeveloperName>
        <label>INVOICE_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITEM_DESCRIPTION__c</fullName>
        <description>ITEM_DESCRIPTION</description>
        <externalDeveloperName>ITEM_DESCRIPTION</externalDeveloperName>
        <label>ITEM_DESCRIPTION</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITEM_NUMBER__c</fullName>
        <description>ITEM_NUMBER</description>
        <externalDeveloperName>ITEM_NUMBER</externalDeveloperName>
        <label>ITEM_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_ID__c</fullName>
        <description>LINE_ID</description>
        <externalDeveloperName>LINE_ID</externalDeveloperName>
        <label>LINE_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_NUMBER__c</fullName>
        <description>LINE_NUMBER</description>
        <externalDeveloperName>LINE_NUMBER</externalDeveloperName>
        <label>LINE_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOT_NUMBER__c</fullName>
        <description>LOT_NUMBER</description>
        <externalDeveloperName>LOT_NUMBER</externalDeveloperName>
        <label>LOT_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDER_HEADER_ID__c</fullName>
        <description>ORDER_HEADER_ID</description>
        <externalDeveloperName>ORDER_HEADER_ID</externalDeveloperName>
        <label>ORDER_HEADER_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDER_NUMBER__c</fullName>
        <description>ORDER_NUMBER</description>
        <externalDeveloperName>ORDER_NUMBER</externalDeveloperName>
        <label>ORDER_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OTM_SHIPMENT_ID__c</fullName>
        <description>OTM_SHIPMENT_ID</description>
        <externalDeveloperName>OTM_SHIPMENT_ID</externalDeveloperName>
        <label>OTM_SHIPMENT_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REF_PO__c</fullName>
        <description>REF_PO</description>
        <externalDeveloperName>REF_PO</externalDeveloperName>
        <label>REF_PO</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REQUESTED_QUANTITY_UOM__c</fullName>
        <description>REQUESTED_QUANTITY_UOM</description>
        <externalDeveloperName>REQUESTED_QUANTITY_UOM</externalDeveloperName>
        <label>REQUESTED_QUANTITY_UOM</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REQUESTED_QUANTITY__c</fullName>
        <description>REQUESTED_QUANTITY</description>
        <externalDeveloperName>REQUESTED_QUANTITY</externalDeveloperName>
        <label>REQUESTED_QUANTITY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCHEDULE_SHIP_DATE__c</fullName>
        <description>SCHEDULE_SHIP_DATE</description>
        <externalDeveloperName>SCHEDULE_SHIP_DATE</externalDeveloperName>
        <label>SCHEDULE_SHIP_DATE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SERIAL_NUMBER__c</fullName>
        <description>SERIAL_NUMBER</description>
        <externalDeveloperName>SERIAL_NUMBER</externalDeveloperName>
        <label>SERIAL_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIPPED_QUANTITY_UOM__c</fullName>
        <description>SHIPPED_QUANTITY_UOM</description>
        <externalDeveloperName>SHIPPED_QUANTITY_UOM</externalDeveloperName>
        <label>SHIPPED_QUANTITY_UOM</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIPPED_QUANTITY__c</fullName>
        <description>SHIPPED_QUANTITY</description>
        <externalDeveloperName>SHIPPED_QUANTITY</externalDeveloperName>
        <label>SHIPPED_QUANTITY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIP_FROM__c</fullName>
        <description>SHIP_FROM</description>
        <externalDeveloperName>SHIP_FROM</externalDeveloperName>
        <label>SHIP_FROM</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIP_TO_LOCATION__c</fullName>
        <description>SHIP_TO_LOCATION</description>
        <externalDeveloperName>SHIP_TO_LOCATION</externalDeveloperName>
        <label>SHIP_TO_LOCATION</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <description>STATUS</description>
        <externalDeveloperName>STATUS</externalDeveloperName>
        <label>STATUS</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRIP_NAME__c</fullName>
        <description>TRIP_NAME</description>
        <externalDeveloperName>TRIP_NAME</externalDeveloperName>
        <label>TRIP_NAME</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WAYBILL__c</fullName>
        <description>WAYBILL</description>
        <externalDeveloperName>WAYBILL</externalDeveloperName>
        <label>WAYBILL</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WEIGHT__c</fullName>
        <description>WEIGHT</description>
        <externalDeveloperName>WEIGHT</externalDeveloperName>
        <label>WEIGHT</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>myIfeDeliveries</label>
    <pluralLabel>myIfeDeliveries</pluralLabel>
</CustomObject>

classes/ife_SearchDeliveryDetailsController.cls
public  class ife_SearchDeliveryDetailsController {
    public ife_SearchDeliveryDetailsController() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Account>  getAccounts(){
        User userObj =[SELECT Id ,Name,Contact.AccountId,Contact.Account.L2I_Customer_ID__c FROM User WHERE Id=:UserInfo.getUserId()];
        if(userObj.Contact.AccountId != null){
            System.debug('userObj.Contact.AccountId----'+userObj.Contact.AccountId);
           return getRelatedAccounts(userObj.Contact.AccountId);
        }  
        else{
           return getRelatedAccounts(null);
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Account> getRelatedAccounts(String accountId){
        Set<String> accountIds = new Set<String>();
        if(String.isNotBlank(accountId)){
            accountIds.add(accountId);
            for(L2I_Related_Account__c  relatedAccount :[SELECT Id, Related_To__c ,Relationship_Type__c
                                        FROM L2I_Related_Account__c 
                                        WHERE Account__c =: accountId])
            {
                accountIds.add(relatedAccount.Related_To__c);
            }
        }
        System.debug('accountIds ----'+accountIds);
        if(!accountIds.isEmpty()){
            List<Account> accounts = [SELECT Id, Name,L2I_Customer_ID__c FROM Account WHERE Id=:accountIds AND L2I_Customer_ID__c != null];
            System.debug('accounts 1----'+accounts);
            accounts.sort();
            return accounts;
        }
        else{
            List<Account> accounts = [SELECT Id, Name,L2I_Customer_ID__c FROM Account WHERE L2I_Customer_ID__c != null];
            System.debug('accounts 2----'+accounts);
            accounts.sort();
            return accounts;

        }
    }
    @AuraEnabled 
    public static  List<myIfeDeliveries__x> getMYIFDeliveryDetails(String deliveryNumber ,String referencePO ,String item ,String shipDate  , String Invoice ,String serial, String selectedAccount){
        System.debug('deliveryNumber--- '+deliveryNumber);
        System.debug('referencePO--- '+referencePO);
        System.debug('item--- '+item);
        System.debug('shipDate--- '+shipDate);
        System.debug('Invoice--- '+Invoice);
        System.debug('serial--- '+serial);
        System.debug('selectedAccount--- '+selectedAccount);
        String whereClause ='';
        if(String.isNotBlank(selectedAccount)){
            if(whereClause != ''){
                whereClause+= ' AND CUSTOMER_ID__c =: selectedAccount';
            }
            else{
                whereClause = ' CUSTOMER_ID__c =: selectedAccount';
            }
        }
        if(String.isNotBlank(deliveryNumber)){
            if(whereClause != ''){
                whereClause+= ' AND DELIVERY_ID__c =: deliveryNumber';
            }
            else{
                whereClause = ' DELIVERY_ID__c =: deliveryNumber';
            }
        }

        if(String.isNotBlank(referencePO)){
            if(whereClause != ''){
                whereClause+= ' AND REF_PO__c =: referencePO';
            }
            else{
                whereClause = ' REF_PO__c =: referencePO';
            }
        }

        if(String.isNotBlank(item)){
            if(whereClause !=''){
                whereClause+= ' AND ITEM_NUMBER__c =: item';
            }
            else{
                whereClause =' ITEM_NUMBER__c =: item';
            }
        }

        if(String.isNotBlank(shipDate)){
            if(whereClause != ''){
                whereClause+= ' AND ACTUAL_SHIP_DATE__c =: shipDate';
            }
            else{
                whereClause = ' ACTUAL_SHIP_DATE__c =: shipDate';
            }
        }

        if(String.isNotBlank(Invoice)){
            if(whereClause !=''){
                whereClause+= ' AND INVOICE_NUMBER__c=: Invoice';
            }
            else{
                whereClause= ' INVOICE_NUMBER__c=: Invoice';
            }
        }

        if(String.isNotBlank(serial)){
            if(whereClause != null ){
                whereClause+= ' AND SERIAL_NUMBER__c=: serial';
            }
            else{
                whereClause= ' SERIAL_NUMBER__c=: serial';
            }
        }
        
        System.debug('whereClause--- '+whereClause);
        String stringQuery ='SELECT Id,CUSTOMER_ID__c, LINE_ID__c, ORDER_HEADER_ID__c, DELIVERY_ID__c,ITEM_NUMBER__c, ORDER_NUMBER__c ,REF_PO__c, SCHEDULE_SHIP_DATE__c,ACTUAL_SHIP_DATE__c,FREIGHT_CARRIER__c,WEIGHT__c,SHIPPED_QUANTITY_UOM__c,STATUS__c,WAYBILL__c,SHIP_TO_LOCATION__c,TRIP_NAME__c,OTM_SHIPMENT_ID__c,INVOICE_NUMBER__c,SERIAL_NUMBER__c FROM myIfeDeliveries__x  WHERE '+   whereClause+ ' LIMIT 2000';
        System.debug('stringQuery--- '+stringQuery);
        List<myIfeDeliveries__x> MYIFEDeliveries = Database.query(stringQuery);
        System.debug('MYIFEDeliveries--- '+MYIFEDeliveries);
       // List<myIfeDeliveries__x> dd=[SELECT Id, DELIVERY_ID__c ,REF_PO__c, ITEM_NUMBER__c, ACTUAL_SHIP_DATE__c, INVOICE_NUMBER__c, SERIAL_NUMBER__c FROM myIfeDeliveries__x  WHERE   CUSTOMER_ID__c = '2318' LIMIT 5];
       // System.debug('dd ==== '+dd);
        return MYIFEDeliveries;

    }
    @AuraEnabled 
    public static  DataWrapper getMYIFdelivery(String lineId ,String headerId){
    System.debug('lineId ----   '+lineId);
    System.debug('headerId ----   '+headerId);
	DataWrapper dataWrapperObj = new DataWrapper();
      /*List<myifedeliverie__c> myifedeliveries =[SELECT Id, Name, STATUS__c, SHIP_TO_LOCATION__c, WAYBILL__c, ORDER_NUMBER__c, ITEM_NUMBER__c, SHIP_FROM__c, ACTUAL_SHIP_DATE__c, SHIPPED_QUANTITY__c, SHIPPED_QUANTITY_UOM__c, LINE_ID__c, ITEM_DESCRIPTION__c, FREIGHT_CARRIER__c, DELIVERY_ID__c, WEIGHT__c 
       FROM myifedeliverie__c WHERE ORDER_NUMBER__c =: lineId];*/
         List<myIfeDeliveries__x> myIfeDeliveries=[SELECT ITEM_NUMBER__c ,ITEM_DESCRIPTION__c,ORDER_NUMBER__c,
                                                    SHIP_FROM__c,SHIP_TO_LOCATION__c,SHIPPED_QUANTITY__c,SHIPPED_QUANTITY_UOM__c, LINE_ID__c, ORDER_HEADER_ID__c,
                                                    CUSTOMER_ID__c,DELIVERY_ID__c,DELIVERY_NAME__c,WAYBILL__c,STATUS__c,WEIGHT__c,FREIGHT_CARRIER__c
                                                    FROM myIfeDeliveries__x WHERE   LINE_ID__c =: lineId AND ORDER_HEADER_ID__c =: headerId];
         System.debug('myIfeDeliveries==== '+myIfeDeliveries);
         /*if(myifedeliveries.size() == 0){
            throw new AuraHandledException('No Record Found..'); 
         }*/
         String carrierTrackingURL = '';

       if(!myIfeDeliveries.isEmpty()){
            for(MyIFECarrierRedirect__mdt  carrierRedirecMdt : [SELECT Id, RedirectURL__c ,MasterLabel FROM MyIFECarrierRedirect__mdt ]){
                if(myIfeDeliveries[0].FREIGHT_CARRIER__c == carrierRedirecMdt.MasterLabel){
                    //carrierTrackingURL = carrierRedirecMdt.RedirectURL__c+myIfeDeliveries[0].WAYBILL__c;
                }
            }
        }
        Map<String,String> carrierWithRedirectURLMap = new Map<String,String>();
        for(MyIFECarrierRedirect__mdt  carrierRedirecMdt : [SELECT Id, RedirectURL__c ,MasterLabel FROM MyIFECarrierRedirect__mdt ]){
            carrierWithRedirectURLMap.put(carrierRedirecMdt.MasterLabel,carrierRedirecMdt.RedirectURL__c);
        }
         dataWrapperObj.myIFEDeliveries = myIfeDeliveries;
         dataWrapperObj.carrierWithRedirectURLMap = JSON.serialize(carrierWithRedirectURLMap);
        return dataWrapperObj;//myIfeDeliveries;//JSON.serialize(myifedeliveries) ;
    }
    public class DataWrapper{
        @AuraEnabled
        public List<myIfeDeliveries__x>  myIFEDeliveries {get;set;}
        @AuraEnabled
        public  String carrierWithRedirectURLMap {get;set;} 
        public DataWrapper(){
            myIFEDeliveries = new List<myIfeDeliveries__x>();
            carrierWithRedirectURLMap = null;
        }
    }
	@AuraEnabled 
	// Delivery Detail Line by Delivery ID Number April 2021
    public static  DataWrapper getMYIFdeliveryDetailLine(String lineId ,String headerId, String deliveryId){
		System.debug('line id ----   '+lineId);
		System.debug('header id ----   '+headerId);
		System.debug('delivery id ----   '+deliveryId);
		DataWrapper dataWrapperObj = new DataWrapper();
		List<myIfeDeliveries__x> myIfeDeliveryDetailLine=[SELECT ITEM_NUMBER__c,ITEM_DESCRIPTION__c,DELIVERY_ID__c, LINE_NUMBER__c, ORDER_NUMBER__c,
												  REQUESTED_QUANTITY__c, REQUESTED_QUANTITY_UOM__c, SHIPPED_QUANTITY__c, SHIPPED_QUANTITY_UOM__c, 
												  SHIP_FROM__c,SHIP_TO_LOCATION__c, STATUS__c, LOT_NUMBER__c, SCHEDULE_SHIP_DATE__c, LINE_ID__c, ORDER_HEADER_ID__c 
												  FROM myIfeDeliveries__x WHERE LINE_ID__c =: lineId AND ORDER_HEADER_ID__c =: headerId AND DELIVERY_ID__c =: deliveryId];
		System.debug('myIfeDelivery Detail Line ==== ' + myIfeDeliveryDetailLine);
		dataWrapperObj.myIFEDeliveries = myIfeDeliveryDetailLine;
		
		return dataWrapperObj;
	}
}