objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/IFE_Document__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Number__c</fullName>
        <externalId>true</externalId>
        <label>Document Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Publication</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>GCS</fullName>
                </value>
                <value>
                    <fullName>Spare Parrs</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Part_Description__c</fullName>
        <label>Part Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IFE Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IFE_Document_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFE_Document__c</fullName>
        <label>IFE Document</label>
        <referenceTo>IFE_Document__c</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IFE Customer Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Customer Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Part__c.object
<CustomObject>
    <fields>
        <fullName>Override__c</fullName>
        <label>Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Part_Description__c</fullName>
        <label>Part Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IFE Part</label>
    <nameField>
        <label>IFE Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IFE_Part_Document__c.object
<CustomObject>
    <fields>
        <fullName>IFE_Document__c</fullName>
        <label>IFE Document</label>
        <referenceTo>IFE_Document__c</referenceTo>
        <relationshipLabel>IFE Part Documents</relationshipLabel>
        <relationshipName>IFE_Part_Documents</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFE_Part__c</fullName>
        <label>IFE Part</label>
        <referenceTo>IFE_Part__c</referenceTo>
        <relationshipName>IFE_Part_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFE Part Document</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>IFE Part Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Part Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Part_Overide__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IFE Part Overrides</relationshipLabel>
        <relationshipName>IFE_Part_Overrides</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IFE_Part__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>IFE Part</label>
        <referenceTo>IFE_Part__c</referenceTo>
        <relationshipLabel>IFE Part Overrides</relationshipLabel>
        <relationshipName>IFE_Part_Overrides</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <label>Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                    <default>true</default>
                    <label>Add</label>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>IFE Part Overide</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>IFE Part Overide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Part Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ife_DocumentSearchControllerTest.cls
@isTest public class ife_DocumentSearchControllerTest {
    @isTest public static void ife_DocumentSearchControllerTest(){
        ife_DocumentSearchController controller = new ife_DocumentSearchController();
        ife_DocumentSearchController.getDocumentTypeValue();
    }
    
    @isTest public static void getDocumentSearchResultTest(){  
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        system.debug('portalRole is ' + portalRole);
        
        User userObj = ife_TestDataUtil.CreateUser(true);
        userObj.UserRoleId =  portalRole.Id;
        update userObj;
        
        System.runAs ( userObj ) {
            
            Account acc = ife_TestDataUtil.createAccount(true);
            
            Contact con = ife_TestDataUtil.createContact(acc.Id, true);
            
            Profile portalProfile = [SELECT Id FROM Profile where name = 'PAC Customer' limit 1];
            User usr = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = con.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTesty',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US');
            
            insert usr;
            
            System.runAs(usr){
                
                IFE_Document__c ifeDocument = new IFE_Document__c();
                ifeDocument.Name = 'Test';
                ifeDocument.Part_Number__c = '1234';
                ifeDocument.Document_Number__c = '1234';
                // ifeDocument.Document_Type__c = 'GCS';
                ifeDocument.Description__c = 'Testing for a ifeDocument';
                insert ifeDocument;  
                
                IFE_Part__c  ifePart = new IFE_Part__c();
                ifePart.Name = 'Test ifePart';
                insert ifePart;
                
                IFE_Part_Document__c partDocument = new IFE_Part_Document__c();
                partDocument.IFE_Document__c = ifeDocument.Id;
                partDocument.IFE_Part__c = ifePart.Id;
                insert partDocument;
                
                IFE_Part_Overide__c partOveride = new IFE_Part_Overide__c();
                partOveride.Account__c = acc.id;
                partOveride.IFE_Part__c = ifePart.Id;
                partOveride.Override__c = 'Add';
                insert partOveride;
                
             /*   IFE_Document_Account__c docAccount = new IFE_Document_Account__c();
                docAccount.IFE_Document__c = ifeDocument.Id;
                docAccount.Account__c = acc.ID;
                insert docAccount;*/
                
                Test.startTest(); 
                ife_DocumentSearchController.getDocumentSearchResult(ifeDocument.Part_Number__c, ifeDocument.Part_Description__c, ifeDocument.Document_Number__c, ifeDocument.Document_Type__c,'2020-12-24', '2020-12-24');
                Test.stopTest();
            }
        }  
    }
}