objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Airline_Code__c</fullName>
        <description>3 digit Airline Code</description>
        <inlineHelpText>The 3-digit customer code is assigned by PAC and should be the ICAO code for airlines.</inlineHelpText>
        <label>Airline Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Compliance_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>L2I_MIR_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MIR Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P_L_Approval__c</fullName>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>Compliance Matrix</relationshipLabel>
        <relationshipName>Compliance_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Compliance Matrix</label>
    <nameField>
        <displayFormat>CMP-{0000}</displayFormat>
        <label>Compliance Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_P_L_Approval__c.object
<CustomObject>
    <description>This object is used to track P&amp;L approvals submitted by Sales Team Members at a Deal Level</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Approval_Deal_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Deal Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select a Deal Opportunity for this field</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <infoMessage>You can only select a Deal Opportunity for this field</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>P&amp;L Approvals</relationshipLabel>
        <relationshipName>P_L_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_P_L_Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>P&amp;L Approvals</relationshipLabel>
        <relationshipName>P_L_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Revision_Status__c</fullName>
        <label>Revision Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Revision/BAFO</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Post Award</fullName>
                </value>
                <value>
                    <fullName>Initial?</fullName>
                    <isActive>false</isActive>
                    <label>Initial?</label>
                </value>
                <value>
                    <fullName>Initial </fullName>
                    <isActive>false</isActive>
                    <label>Initial </label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P_L_Version__c</fullName>
        <formula>&quot;PandL-&quot; &amp;  IF( ISBLANK(Snapshot_Text_Version__c ) ,  TEXT(Snapshot_Version__c) , Snapshot_Text_Version__c)</formula>
        <label>P&amp;L Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmittedDate__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>P&amp;L Approval</label>
    <nameField>
        <displayFormat>PandL-{00000}</displayFormat>
        <label>P&amp;L Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;L Approvals</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>New Record Type to accomodate IFC section</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_P_L_Sales_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>L2I_P_L_Approval__c</fullName>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>P&amp;L Sales Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Related_To_P_L</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>P&amp;L Sales Opportunity</label>
    <nameField>
        <displayFormat>ORPAL-{00000}</displayFormat>
        <label>Opportunities Related To P&amp;L Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;L Sales Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PTS_P_L_Files__c.object
<CustomObject>
    <fields>
        <fullName>PTS_P_L_Source__c</fullName>
        <label>PTS P&amp;L Source</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P_L_Approval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>PTS P&amp;L Files</relationshipLabel>
        <relationshipName>PTS_P_L_Files</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>PTS P&amp;L Files</label>
    <nameField>
        <displayFormat>PTS-{0000}</displayFormat>
        <label>PTS P&amp;L Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PTS P&amp;L Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2I_P_L_A_TriggerFunctions_Test.cls
/**
 * @Class Name  	: L2I_P_L_A_TriggerFunctions_Test
 * @Description		: Test Class for L2I_P_L_A_TriggerFunctions
 **/
@IsTest
private class L2I_P_L_A_TriggerFunctions_Test {
    
   /**
    * @Method Name  : testBehavior
    * @Description	: test Method for checking P_L_Version__c and Cloning Process
    **/
    @IsTest
    static void testBehavior() {
        L2I_DataFactory df = new L2I_DataFactory();
        Account namedCustomer = df.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        
        Opportunity dealOppty = df.createDealOpportunity('Deal', 'Open', 30, namedCustomer.Id);
        insert dealOppty;
    
        Opportunity salesOppty = df.createSalesOpportunity('SalesOpp', 'Quotation', 5, namedCustomer.Id, dealOppty.Id);
        insert salesOppty;
    
        SBQQ__Quote__c quote = df.createQuote('draft', namedCustomer.Id, salesOppty.Id, false);
        quote.SBQQ__Primary__c = true;
        quote.ApprovalStatus__c = 'Approved';
        quote.L2I_Final_Proposal_Submission_Date__c = Date.today();
        quote.SubmittedDate__c = Date.today(); // Added by Khrisna for W-004060
        insert quote;
        
        L2I_DSH__c dsh = df.createDeliverySchedule(namedCustomer.Id, null);
        insert dsh;
        
        L2I_DSL__c dsl = df.createDeliveryScheduleLine(dsh.Id);
        insert dsl;
    
        salesOppty.SBQQ__PrimaryQuote__c = quote.Id;
        salesOppty.StageName = 'Pending Close';
        salesOppty.L2I_Delivery_Schedule__c = dsh.Id;
        update salesOppty;
        
        L2I_P_L_Approval__c pla = df.createPLApproval(dealOppty.Id, 'Pending');
        pla.L2I_Revision_Status__c = 'Initial';
        insert pla;
    
        L2I_P_L_Sales_Opportunity__c plso = df.createPLSalesOpp( pla.Id, salesOppty.Id );
        insert plso;
        
        pla.ApprovalStatus__c = 'Approved';
        pla.L2I_Revision_Status__c = 'Award';
        update pla;
        
        //Added by Jan Geronga for W-003812: Start
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = pla.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'I';
        insert cdl;

        L2I_Compliance_Matrix__c cMatrix = new L2I_Compliance_Matrix__c();
        cMatrix.P_L_Approval__c = pla.Id;
        cMatrix.L2I_MIR_Flag__c = true;
		insert cMatrix;
        
        PTS_P_L_Files__c filesPTS = new PTS_P_L_Files__c();
        filesPTS.P_L_Approval__c = pla.Id;
        insert filesPTS;

        ContentDocumentLink cdl2 = new ContentDocumentLink();
        cdl2.LinkedEntityId = filesPTS.Id;
        cdl2.ContentDocumentId = documents[0].Id;
        cdl2.ShareType = 'I';
        insert cdl2;
        
        Test.startTest();
        L2I_P_L_Approval__c pla2 = pla.clone();
        insert pla2;
        Test.stopTest();
        //Added by Jan Geronga for W-003812: End
        system.assertEquals('PandL-B',[SELECT P_L_Version__c FROM L2I_P_L_Approval__c WHERE Id =: pla2.Id].P_L_Version__c);
        system.assertEquals(1,[SELECT Count() FROM PTS_P_L_Files__c WHERE P_L_Approval__c =: pla2.Id ]);
        system.assertEquals(1,[SELECT Count() FROM PTS_P_L_Files__c WHERE PTS_P_L_Source__c =: filesPTS.Id ]);
    }
    
    /**
    * @Method Name  : processPLAsAfterUpdate
    * @Description	: test Method for checking PDF generation and attachment after approval
    **/
    @IsTest
    static void testProcessPLAsAfterUpdate() {
        final string filenameDelim = ' - ';
        String approvalName = 'PAC - PandL-00443 - Initial - PandL-A';
        Account testAccount = new Account(Name = 'testAcc', L2I_Airline_Code__c = 'PAC');
        Opportunity testOpportunity;
        L2I_P_L_Approval__c pnlApproval;
        ContentVersion contentVer;
        ContentDocumentLink contentDocLink;
        
        Test.startTest();
        insert testAccount;
        
        testOpportunity = new Opportunity(Name = 'testOpp', 
                                          StageName = 'Open',
                                          CloseDate = Date.today(),
                                          AccountId = testAccount.Id);
        insert testOpportunity;
        
        pnlApproval = new L2I_P_L_Approval__c(ApprovalStatus__c = null,
                                             L2I_Approval_Deal_Opportunity__c = testOpportunity.Id,
                                             L2I_Revision_Status__c = 'Initial');
        insert pnlApproval;
        
        pnlApproval.ApprovalStatus__c = 'Approved';
        update pnlApproval;        
        Test.stopTest();
        
        pnlApproval = [SELECT Id, ApprovalStatus__c, L2I_Approval_Deal_Opportunity__c, L2I_Revision_Status__c, Name, P_L_Version__c
                      FROM L2I_P_L_Approval__c WHERE Id =: pnlApproval.Id]; 
           
        approvalName = testAccount.L2I_Airline_Code__c + filenameDelim +
            		   pnlApproval.Name + filenameDelim + 
                       pnlApproval.L2I_Revision_Status__c + filenameDelim + 
                       pnlApproval.P_L_Version__c;
        
        contentVer = [SELECT Id, VersionData, ContentLocation, PathOnClient, Title, ContentDocumentId
                      FROM ContentVersion WHERE Title =: approvalName];
        contentDocLink = [SELECT Id, LinkedEntityId, ContentDocumentId, shareType, Visibility 
                          FROM ContentDocumentLink WHERE LinkedEntityId =: pnlApproval.Id];
        
        system.assertEquals(approvalName, contentVer.Title);
        system.assertEquals(blob.valueof('testData').size(), contentVer.VersionData.size());
        system.assertEquals('S', contentVer.ContentLocation);
        system.assertEquals(approvalName +'.pdf', contentVer.PathOnClient);        
        system.assertEquals(pnlApproval.Id, contentDocLink.LinkedEntityId);
        system.assertEquals(contentVer.ContentDocumentId, contentDocLink.ContentDocumentId);
        system.assertEquals('V', contentDocLink.shareType);
        system.assertEquals('AllUsers', contentDocLink.Visibility);
    }
}