objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>Available_in_Oracle_PT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available in Oracle PT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <recordTypes>
        <fullName>Hardware</fullName>
        <active>true</active>
        <description>Hardware DSH Record Type</description>
        <label>Hardware</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <label>Shipset Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <recordTypes>
        <fullName>Hardware</fullName>
        <active>true</active>
        <label>Hardware</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_P_L_Approval__c.object
<CustomObject>
    <description>This object is used to track P&amp;L approvals submitted by Sales Team Members at a Deal Level</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_P_L_Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>P&amp;L Approvals</relationshipLabel>
        <relationshipName>P_L_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Revision_Status__c</fullName>
        <label>Revision Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Revision/BAFO</fullName>
                </value>
                <value>
                    <fullName>Award</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Post Award</fullName>
                </value>
                <value>
                    <fullName>Initial?</fullName>
                    <isActive>false</isActive>
                    <label>Initial?</label>
                </value>
                <value>
                    <fullName>Initial </fullName>
                    <isActive>false</isActive>
                    <label>Initial </label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedDate__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>P&amp;L Approval</label>
    <nameField>
        <displayFormat>PandL-{00000}</displayFormat>
        <label>P&amp;L Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;L Approvals</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>New Record Type to accomodate IFC section</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_P_L_Sales_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <formula>L2I_Sales_Opportunity__r.L2I_Aircraft_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_P_L_Approval__c</fullName>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>P&amp;L Sales Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Related_To_P_L</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <formula>Text(L2I_Sales_Opportunity__r.L2I_Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <label>P&amp;L Sales Opportunity</label>
    <nameField>
        <displayFormat>ORPAL-{00000}</displayFormat>
        <label>Opportunities Related To P&amp;L Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;L Sales Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Type</label>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Inventory_Item_Id__c</fullName>
        <description>EBS Item Id</description>
        <externalId>true</externalId>
        <label>Inventory Item Id</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2I_PMO_Install_Code__c</fullName>
        <label>PMO Install Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PMO_Install_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Primary_Charge_Method__c</fullName>
        <description>Charge method such as Per tail, per fleet or Media Set</description>
        <label>Primary Charge Method</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <label>Install Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ShipSet</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/PMO_Install_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALT</fullName>
    </customValue>
    <customValue>
        <fullName>ALT1</fullName>
    </customValue>
    <customValue>
        <fullName>ALT2</fullName>
    </customValue>
    <customValue>
        <fullName>ALT3</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
    </customValue>
    <customValue>
        <fullName>BC1</fullName>
    </customValue>
    <customValue>
        <fullName>BC2</fullName>
    </customValue>
    <customValue>
        <fullName>BCH</fullName>
    </customValue>
    <customValue>
        <fullName>BCH1</fullName>
    </customValue>
    <customValue>
        <fullName>BCH2</fullName>
    </customValue>
    <customValue>
        <fullName>BEDROOM</fullName>
    </customValue>
    <customValue>
        <fullName>BEDROOM1</fullName>
    </customValue>
    <customValue>
        <fullName>BEDROOM2</fullName>
    </customValue>
    <customValue>
        <fullName>CD</fullName>
    </customValue>
    <customValue>
        <fullName>CD1</fullName>
    </customValue>
    <customValue>
        <fullName>CD2</fullName>
    </customValue>
    <customValue>
        <fullName>CD3</fullName>
    </customValue>
    <customValue>
        <fullName>CD4</fullName>
    </customValue>
    <customValue>
        <fullName>CEC</fullName>
    </customValue>
    <customValue>
        <fullName>CEC1</fullName>
    </customValue>
    <customValue>
        <fullName>CERT</fullName>
    </customValue>
    <customValue>
        <fullName>CERT-BOEING</fullName>
    </customValue>
    <customValue>
        <fullName>COCKPIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONNECTIVITY</fullName>
    </customValue>
    <customValue>
        <fullName>CONNECTIVITY1</fullName>
    </customValue>
    <customValue>
        <fullName>CONNECTIVITY2</fullName>
    </customValue>
    <customValue>
        <fullName>CR</fullName>
    </customValue>
    <customValue>
        <fullName>CR1</fullName>
    </customValue>
    <customValue>
        <fullName>CR2</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>EC</fullName>
    </customValue>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <masterLabel>PMO Install Code</masterLabel>
</GlobalValueSet>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/PTI_CreateProgramController_Test.cls
/**
 * @Class Name    : PTI_CreateProgramController_Test
 * @Description    : Test Class for PTI_CreateProgramController
 **/
@IsTest
private class PTI_CreateProgramController_Test{
/**
    * @Method Name  : testCreateProgram
    * @Description  : test Method for covering PTI_CreateProgramController
    **/
    @IsTest
    public static void onCreateProgramFromFlow() {
        L2I_DataFactory df = new L2I_DataFactory();
        Account namedCustomer = df.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
        insert namedCustomer;
        
        Opportunity dealOppty = df.createDealOpportunity('Deal', 'Open', 30, namedCustomer.Id);
        insert dealOppty;
        
        L2I_Aircraft_Type__c airType = df.createAircraftType(namedCustomer.Id, null);        
        airType.Name = airType.Name + '1';
        airType.Available_in_Oracle_PT__c = TRUE;
        
        insert airType;
            
        L2I_Aircraft__c airCraft = df.createAircraft(airType.Id, 'Testac', 'A319-1100', namedCustomer.Id);
        insert airCraft;
            
        L2I_DSH__c dsh = df.createDeliverySchedule(namedCustomer.Id, airType.Id);
        insert dsh;

        L2I_DSL__c dsl = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id,
              PT_isActive__c = 'Active'
        );
        insert dsl;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
              ShipSet__c = dsl.Id,
              Status__c = 'Active'
        );
        insert instLoc2;        
        
        Product2 prodSysType = df.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesIFECOppty = df.createSalesOpportunity('SalesOppIFEC', 'Quotation', 5, namedCustomer.Id, dealOppty.Id);
        salesIFECOppty.L2I_Aircraft_Type__c = airType.Id;
        salesIFECOppty.L2I_Product_Category__c = 'IFEC';
        salesIFECOppty.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesIFECOppty;
        
        SBQQ__Quote__c IFECQuote = df.createQuote('draft', namedCustomer.Id, salesIFECOppty.Id, false);
        IFECQuote.SBQQ__Primary__c = true;
        IFECQuote.ApprovalStatus__c = 'Approved';
        IFECQuote.L2I_Final_Proposal_Submission_Date__c = Date.today();
        IFECQuote.SubmittedDate__c = Date.today(); // Added by Khrisna for W-004060
        insert IFECQuote;
        
                
        Product2 prodIFEC = new product2(Name = 'Test IFEC', productCode = 'TBD-Hardware', L2I_Inventory_Item_Id__c = '99999788', L2I_PMO_Install_Code__c = 'EC');
        insert prodIFEC;
        
        List<SBQQ__QuoteLine__c> qls = new List<SBQQ__QuoteLine__c>();
        qls.add(new SBQQ__QuoteLine__c(SBQQ__Quote__c = IFECQuote.Id, SBQQ__Product__c = prodIFEC.Id));
        insert qls;
        
                SBQQ__SolutionGroup__c sg = new SBQQ__SolutionGroup__c(
              Name = 'EC'
        );
        insert sg;

        List<SBQQ__QuoteLineGroup__c> qlgList = new List<SBQQ__QuoteLineGroup__c>();
        for (SBQQ__QuoteLine__c ql : qls) {
            if(ql.SBQQ__Product__c == prodIFEC.Id){
                SBQQ__QuoteLineGroup__c qlg = new SBQQ__QuoteLineGroup__c();
                qlg.SBQQ__Account__c = namedCustomer.id;
                qlg.SBQQ__SolutionGroup__c = sg.Id;
                qlg.SBQQ__Quote__c = IFECQuote.Id;
                qlgList.add(qlg);
            }
        }
        insert qlgList;
        
        for (SBQQ__QuoteLine__c ql : qls) {
            if(ql.SBQQ__Product__c == prodIFEC.Id){ql.SBQQ__Group__c = qlgList[0].Id;}
        }
        update qls;

        Test.startTest();
        Opportunity salesDSSOppty = df.createSalesOpportunity('SalesOppDSS', 'Quotation', 5, namedCustomer.Id, dealOppty.Id);
        salesDSSOppty.L2I_Aircraft_Type__c = airType.Id;
        salesDSSOppty.L2I_Product_Category__c = 'DSS';
        salesDSSOppty.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesDSSOppty;
        
        SBQQ__Quote__c DSSQuote = df.createQuote('draft', namedCustomer.Id, salesDSSOppty.Id, false);
        DSSQuote.SBQQ__Primary__c = true;
        DSSQuote.ApprovalStatus__c = 'Approved';
        DSSQuote.L2I_Final_Proposal_Submission_Date__c = Date.today();
        DSSQuote.SubmittedDate__c = Date.today(); // Added by Khrisna for W-004060
        insert DSSQuote;
        
        Product2 prodY = new product2(Name = 'Test YYY', productCode = 'TBD-OneTime', L2I_Inventory_Item_Id__c = '99999804', L2I_PMO_Install_Code__c = 'EC',L2I_Primary_Charge_Method__c  = 'AIRLINE');
        insert prodY;
        
        Product2 prodRecurY = new product2(Name = 'Test Rec', productCode = 'TBD-Recurring', L2I_Inventory_Item_Id__c = '99999448', L2I_PMO_Install_Code__c = 'EC',L2I_Primary_Charge_Method__c  = 'AIRCRAFT');
        insert prodRecurY;
        
        qls = new List<SBQQ__QuoteLine__c>();
        qls.add(new SBQQ__QuoteLine__c(SBQQ__Quote__c = DSSQuote.Id, SBQQ__Product__c = prodRecurY.Id));
        insert qls;

        
        salesDSSOppty.SBQQ__PrimaryQuote__c = DSSQuote.Id;
        salesDSSOppty.StageName = 'Handoff';
        salesDSSOppty.L2I_Delivery_Schedule__c = dsh.Id;
        update salesDSSOppty;
        
        salesIFECOppty.SBQQ__PrimaryQuote__c = IFECQuote.Id;
        salesIFECOppty.StageName = 'Handoff';
        salesIFECOppty.L2I_Delivery_Schedule__c = dsh.Id;
        update salesIFECOppty;
        
        L2I_P_L_Approval__c pla = df.createPLApproval(dealOppty.Id, 'Pending');
        pla.L2I_Revision_Status__c = 'Initial';
        insert pla;
    
        L2I_P_L_Sales_Opportunity__c plso = df.createPLSalesOpp( pla.Id, salesDSSOppty.Id );
        insert plso;
        
        L2I_P_L_Sales_Opportunity__c plso2 = df.createPLSalesOpp( pla.Id, salesIFECOppty.Id );
        insert plso2;
        
        pla.ApprovalStatus__c = 'Approved';
        pla.L2I_Revision_Status__c = 'Award';
        update pla;
        List<Id> plSalesOpp = new List<Id>{pla.Id};
        
        
        PTI_CreateProgramController.onCreateProgramFromFlow(plSalesOpp);
        Test.stopTest();
             
    }
  
}