objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_PriceList__c.object
<CustomObject>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Program Price List</relationshipLabel>
        <relationshipName>Program_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <label>Price List Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Sequence__c</fullName>
        <label>Price List Sequence</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Program Price List</relationshipLabel>
        <relationshipName>Program_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>PT_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integration Pending</fullName>
                </value>
                <value>
                    <fullName>Integration Completed</fullName>
                </value>
                <value>
                    <fullName>Retry Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Price List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_PriceList_Entry__c.object
<CustomObject>
    <fields>
        <fullName>PT_CanEscalate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CanEscalate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <formula>PT_Program_Price_List__r.PT_Price_List_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price List Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Price List</label>
        <referenceTo>PT_PriceList__c</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Added</fullName>
                </value>
                <value>
                    <fullName>Reconcile</fullName>
                </value>
                <value>
                    <fullName>Integrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Price List Entry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Price List Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <inlineHelpText>Active state of the Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/PT_ProgramPriceListEscalationTest.cls
/**
* @File Name          : PT_ProgramPriceListEscalationTest.cls
* @Description        : Test Class for PT_ProgramPriceListEscalation
* @Author             :
* @Last Modified By   : MS Simplus Khrisna
* @Last Modified On   : Mar 31, 2022
* @Modification Log   : 
* Ver           Date           Author               Modification
*                                                   Initial Version
* W-001727      Mar 31 2022    MS Simplus Khrisna   Primary System Type Validation Rule
**/
@isTest
public class PT_ProgramPriceListEscalationTest {
    private static L2I_DataFactory factory;
    @isTest
    static void escalateProgramPriceListFromFlowTest() {
        factory = new L2I_DataFactory();
        List<PT_PriceList_Entry__c> insertPLE = new List<PT_PriceList_Entry__c>();
        Account acc = factory.createCustomerAccount('Test Customer', '123 Augustine Street', 'San Diego', 'CA', '91890');
        insert acc;

        Opportunity dealOpp = factory.createDealOpportunity('Deal', 'Open', 30, acc.Id);
        insert dealOpp;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
		
        Opportunity salesOpp = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp.L2I_Product_Category__c = 'IFEC';
        salesOpp.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesOpp;

        Product2 product = factory.createProduct('99999801', 'MediaServices', null, null, null);
        product.productCode = 'MCS BUNDLE';
        insert product;

        Product2 product1 = factory.createProduct('99999802', 'MediaServices', null, null, null);
        product1.productCode = 'MCS BUNDLE';
        insert product1;

        PT_PriceList__c priceList = new PT_PriceList__c(PT_Program__c = null,
                                                        PT_Description__c = 'TBD',
                                                        PT_IsActive__c = TRUE,
                                                        PT_Price_List_Sequence__c = '01',
                                                        PT_Price_List_Name__c = 'TestPL',
                                                        PT_Opportunity__c = salesOpp.Id);
        insert priceList;
        insertPLE.add(new PT_PriceList_Entry__c(
                        PT_Program_Price_List__c = priceList.Id,
                        PT_CanEscalate__c = TRUE,
                        PT_isActive__c = TRUE,
                        PT_StartDate__c = Date.today(),
                        PT_Status__c = 'Approved',
                        PT_Product__c = product.Id,
                        PT_UnitPrice__c = 20.0,
                        Name = 'Test123'
        ));
        insertPLE.add(new PT_PriceList_Entry__c(
                        PT_Program_Price_List__c = priceList.Id,
                        PT_CanEscalate__c = TRUE,
                        PT_isActive__c = TRUE,
                        PT_StartDate__c = Date.today(),
                        PT_Status__c = 'Approved',
                        PT_Product__c = product1.Id,
                        PT_UnitPrice__c = 30.0,
                        Name = 'Test1234'
        ));

        if (insertPLE.size() > 0) {
            insert insertPLE;
        }

        List<PT_ProgramPriceListEscalationController.FlowInput> requests = new List<PT_ProgramPriceListEscalationController.FlowInput>();
        PT_ProgramPriceListEscalationController.FlowInput req = new PT_ProgramPriceListEscalationController.FlowInput();
        req.progPriceListId = priceList.Id;
        req.escalationPercentage = 1.20;
        req.description = 'Test';
        requests.add(req);

        PT_ProgramPriceListEscalationController.escalateProgramPriceListFromFlow(requests);
    }
}