objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Customer_ID__c</fullName>
        <description>Customer Account ID. External ID of Account, not shown in UI; may be redundant with Party ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/myIfeOrderHeaders__x.object
<CustomObject>
    <description>myIfeOrderHeaders</description>
    <externalDataSource>Order_Status</externalDataSource>
    <externalName>myIfeOrderHeaders</externalName>
    <fields>
        <fullName>BILL_TO__c</fullName>
        <description>BILL_TO</description>
        <externalDeveloperName>BILL_TO</externalDeveloperName>
        <label>BILL_TO</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_ID__c</fullName>
        <description>CUSTOMER_ID</description>
        <externalDeveloperName>CUSTOMER_ID</externalDeveloperName>
        <label>CUSTOMER_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_NAME__c</fullName>
        <description>CUSTOMER_NAME</description>
        <externalDeveloperName>CUSTOMER_NAME</externalDeveloperName>
        <label>CUSTOMER_NAME</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_PO__c</fullName>
        <description>CUSTOMER_PO</description>
        <externalDeveloperName>CUSTOMER_PO</externalDeveloperName>
        <label>CUSTOMER_PO</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FREIGHT_TERMS__c</fullName>
        <description>FREIGHT_TERMS</description>
        <externalDeveloperName>FREIGHT_TERMS</externalDeveloperName>
        <label>FREIGHT_TERMS</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HEADER_ID__c</fullName>
        <description>HEADER_ID</description>
        <externalDeveloperName>HEADER_ID</externalDeveloperName>
        <label>HEADER_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INCO_TERMS__c</fullName>
        <description>INCO_TERMS</description>
        <externalDeveloperName>INCO_TERMS</externalDeveloperName>
        <label>INCO_TERMS</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDERED_DATE__c</fullName>
        <description>ORDERED_DATE</description>
        <externalDeveloperName>ORDERED_DATE</externalDeveloperName>
        <label>ORDERED_DATE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDER_NUMBER__c</fullName>
        <description>ORDER_NUMBER</description>
        <externalDeveloperName>ORDER_NUMBER</externalDeveloperName>
        <label>ORDER_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAYMENT_TERMS__c</fullName>
        <description>PAYMENT_TERMS</description>
        <externalDeveloperName>PAYMENT_TERMS</externalDeveloperName>
        <label>PAYMENT_TERMS</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRICE_LIST_NAME__c</fullName>
        <description>PRICE_LIST_NAME</description>
        <externalDeveloperName>PRICE_LIST_NAME</externalDeveloperName>
        <label>PRICE_LIST_NAME</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PROGRAM_NUMBER__c</fullName>
        <description>PROGRAM_NUMBER</description>
        <externalDeveloperName>PROGRAM_NUMBER</externalDeveloperName>
        <label>PROGRAM_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALES_ADMIN__c</fullName>
        <description>SALES_ADMIN</description>
        <externalDeveloperName>SALES_ADMIN</externalDeveloperName>
        <label>SALES_ADMIN</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALES_ORDER__c</fullName>
        <description>SALES_ORDER</description>
        <externalDeveloperName>SALES_ORDER</externalDeveloperName>
        <label>SALES_ORDER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIPMENT_PRIORITY__c</fullName>
        <description>SHIPMENT_PRIORITY</description>
        <externalDeveloperName>SHIPMENT_PRIORITY</externalDeveloperName>
        <label>SHIPMENT_PRIORITY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHIPSET__c</fullName>
        <description>SHIPSET</description>
        <externalDeveloperName>SHIPSET</externalDeveloperName>
        <label>SHIPSET</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPECIAL_QA_INSP__c</fullName>
        <description>SPECIAL_QA_INSP</description>
        <externalDeveloperName>SPECIAL_QA_INSP</externalDeveloperName>
        <label>SPECIAL_QA_INSP</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <description>STATUS</description>
        <externalDeveloperName>STATUS</externalDeveloperName>
        <label>STATUS</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TOTAL__c</fullName>
        <description>TOTAL</description>
        <externalDeveloperName>TOTAL</externalDeveloperName>
        <label>TOTAL</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WEB_ORDER__c</fullName>
        <description>WEB_ORDER</description>
        <externalDeveloperName>WEB_ORDER</externalDeveloperName>
        <label>WEB_ORDER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>myIfeOrderHeaders</label>
    <pluralLabel>myIfeOrderHeaders</pluralLabel>
</CustomObject>

objects/myIfeOrderLines__x.object
<CustomObject>
    <description>myIfeOrderLines</description>
    <externalDataSource>Order_Status</externalDataSource>
    <externalName>myIfeOrderLines</externalName>
    <fields>
        <fullName>CUSTOMER_PO_LINE__c</fullName>
        <description>CUSTOMER_PO_LINE</description>
        <externalDeveloperName>CUSTOMER_PO_LINE</externalDeveloperName>
        <label>CUSTOMER_PO_LINE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DELIVERY_ID__c</fullName>
        <description>DELIVERY_ID</description>
        <externalDeveloperName>DELIVERY_ID</externalDeveloperName>
        <label>DELIVERY_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXTENDED_PRICE__c</fullName>
        <description>EXTENDED_PRICE</description>
        <externalDeveloperName>EXTENDED_PRICE</externalDeveloperName>
        <label>EXTENDED_PRICE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FULFILLED_QUANTITY__c</fullName>
        <description>FULFILLED_QUANTITY</description>
        <externalDeveloperName>FULFILLED_QUANTITY</externalDeveloperName>
        <label>FULFILLED_QUANTITY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HEADER_ID__c</fullName>
        <description>HEADER_ID</description>
        <externalDeveloperName>HEADER_ID</externalDeveloperName>
        <label>HEADER_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INSTALL_LOCATION__c</fullName>
        <description>INSTALL_LOCATION</description>
        <externalDeveloperName>INSTALL_LOCATION</externalDeveloperName>
        <label>INSTALL_LOCATION</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITEM_DESCRIPTION__c</fullName>
        <description>ITEM_DESCRIPTION</description>
        <externalDeveloperName>ITEM_DESCRIPTION</externalDeveloperName>
        <label>ITEM_DESCRIPTION</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITEM__c</fullName>
        <description>ITEM</description>
        <externalDeveloperName>ITEM</externalDeveloperName>
        <label>ITEM</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_ID__c</fullName>
        <description>LINE_ID</description>
        <externalDeveloperName>LINE_ID</externalDeveloperName>
        <label>LINE_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_NUMBER__c</fullName>
        <description>LINE_NUMBER</description>
        <externalDeveloperName>LINE_NUMBER</externalDeveloperName>
        <label>LINE_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDERED_QUANTITY__c</fullName>
        <description>ORDERED_QUANTITY</description>
        <externalDeveloperName>ORDERED_QUANTITY</externalDeveloperName>
        <label>ORDERED_QUANTITY</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDER_NUMBER__c</fullName>
        <description>ORDER_NUMBER</description>
        <externalDeveloperName>ORDER_NUMBER</externalDeveloperName>
        <label>ORDER_NUMBER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALES_ORDER__c</fullName>
        <description>SALES_ORDER</description>
        <externalDeveloperName>SALES_ORDER</externalDeveloperName>
        <label>SALES_ORDER</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCHEDULE_SHIP_DATE__c</fullName>
        <description>SCHEDULE_SHIP_DATE</description>
        <externalDeveloperName>SCHEDULE_SHIP_DATE</externalDeveloperName>
        <label>SCHEDULE_SHIP_DATE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <description>STATUS</description>
        <externalDeveloperName>STATUS</externalDeveloperName>
        <label>STATUS</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNIT_SELLING_PRICE__c</fullName>
        <description>UNIT_SELLING_PRICE</description>
        <externalDeveloperName>UNIT_SELLING_PRICE</externalDeveloperName>
        <label>UNIT_SELLING_PRICE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UOM__c</fullName>
        <description>UOM</description>
        <externalDeveloperName>UOM</externalDeveloperName>
        <label>UOM</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WAREHOUSE__c</fullName>
        <description>WAREHOUSE</description>
        <externalDeveloperName>WAREHOUSE</externalDeveloperName>
        <label>WAREHOUSE</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>myIfeOrderLines</label>
    <pluralLabel>myIfeOrderLines</pluralLabel>
</CustomObject>

classes/ife_OrderHeaderListController.cls
public class ife_OrderHeaderListController{
	public ife_OrderHeaderListController(){
	}

	@AuraEnabled(cacheable = true)
	public static String getMYIFEorderHeader(){
		FieldSetWrapper fieldsWrapper = new FieldSetWrapper();
		List<Schema.FieldSetMember> getFields = SObjectType.myIfeOrderHeaders__x.FieldSets.MYIFE_OrderHeaderFields.getFields();
		String query = 'SELECT ';
		for (Schema.FieldSetMember f : getFields){
			query += f.getFieldPath()+', ';
		}
		query += 'Id FROM myIfeOrderHeaders__x LIMIT 20';
		System.debug('***query===>>> ' + query);
		System.debug('*** Database.query(query)===>>> ' + Database.query(query));
		List<myIfeOrderHeaders__x> mYIFEorderHeader = Database.query(query);
		System.debug('***erpOrderStatus===>>> ' + mYIFEorderHeader);
		fieldsWrapper.mYIFEorderHeaderList.addAll(mYIFEorderHeader);
		fieldsWrapper.headerFields.addAll(getFields);
		return JSON.serialize(fieldsWrapper);
	}

	@AuraEnabled(cacheable = true)
	public static OrderHeaderAndOrderLinesWrapper getMYIForderHeaderDetails(String orderHeaderId, Boolean isExternalPage){
		OrderHeaderAndOrderLinesWrapper orderHeaderAndLinesWrapperObj = new OrderHeaderAndOrderLinesWrapper();
		System.debug('orderHeaderId---' + orderHeaderId);
		myIfeOrderHeaders__x orderHeaderObj;
		if (Test.isRunningTest()){

			orderHeaderObj = ife_OrderHeaderListCtrlMockRecords.getRecords();
			System.debug('OrderHeaderObj>>>' + OrderHeaderObj);

		} else{
			if (isExternalPage){
				String customerId = getCurrentUser();
				if (customerId != null){
					System.debug('customerId---' + customerId);
					try{
						orderHeaderObj = [SELECT Id, HEADER_ID__c, ORDER_NUMBER__c, CUSTOMER_NAME__c, CUSTOMER_PO__c, ORDERED_DATE__c, STATUS__c, PROGRAM_NUMBER__c, SALES_ADMIN__c, SPECIAL_QA_INSP__c, SHIPSET__c, FREIGHT_TERMS__c, SHIPMENT_PRIORITY__c, INCO_TERMS__c, BILL_TO__c, PAYMENT_TERMS__c, PRICE_LIST_NAME__c, TOTAL__c
						                  FROM myIfeOrderHeaders__x
						                  WHERE CUSTOMER_ID__c = :customerId AND WEB_ORDER__c = :orderHeaderId  LIMIT 1];
						System.debug('orderHeaderObj test----' + orderHeaderObj);
					} Catch (Exception e){
						
						system.debug('Exception----- ' + e);
						//throw new DMLException('My DML EXCEPTION');
						return null;
					}
				}

			} else{
				orderHeaderObj = [SELECT Id, HEADER_ID__c, ORDER_NUMBER__c, CUSTOMER_NAME__c, CUSTOMER_PO__c, ORDERED_DATE__c, STATUS__c, PROGRAM_NUMBER__c, SALES_ADMIN__c, SPECIAL_QA_INSP__c, SHIPSET__c, FREIGHT_TERMS__c, SHIPMENT_PRIORITY__c, INCO_TERMS__c, BILL_TO__c, PAYMENT_TERMS__c, PRICE_LIST_NAME__c, TOTAL__c
				                  FROM myIfeOrderHeaders__x
				                  WHERE Id = :orderHeaderId  LIMIT 1];
			}
		}

		System.debug('orderHeaderObj---' + orderHeaderObj);

		List<myIfeOrderLines__x> orderLines = [SELECT Id, HEADER_ID__c, LINE_NUMBER__c, ITEM__c, ITEM_DESCRIPTION__c, ORDERED_QUANTITY__c, UOM__c, UNIT_SELLING_PRICE__c, EXTENDED_PRICE__c, CUSTOMER_PO_LINE__c, INSTALL_LOCATION__c, STATUS__c, WAREHOUSE__c, SCHEDULE_SHIP_DATE__c, LINE_ID__c, FULFILLED_QUANTITY__c, DELIVERY_ID__c, SALES_ORDER__c
		                                       FROM myIfeOrderLines__x
		                                       WHERE HEADER_ID__c = :orderHeaderObj.HEADER_ID__c];
		orderHeaderAndLinesWrapperObj.orderHeaderObj = orderHeaderObj;
		orderHeaderAndLinesWrapperObj.orderLineList = orderLines;
		System.debug('orderHeaderAndLinesWrapperObj>>>' + orderHeaderAndLinesWrapperObj);

		return orderHeaderAndLinesWrapperObj;
	}

	public static String getCurrentUser(){
		User userObj = [SELECT Id, Name, Contact.AccountId, Contact.Account.L2I_Customer_ID__c
		                FROM User
		                WHERE Id = :UserInfo.getUserId()];
		if (userObj.Contact.AccountId != null){
			System.debug('Contact.Account.L2I_Customer_ID__c-----' + userObj.Contact.Account.L2I_Customer_ID__c);
			return userObj.Contact.Account.L2I_Customer_ID__c;
		}
		return null;
	}

	@AuraEnabled(cacheable = true)
	public static List<String> getMYIFE_OrderHeaderDetailsFields(){
		List<String> detailsFields = new List<String>();
		for (Schema.FieldSetMember field : SObjectType.myIfeOrderHeaders__x.FieldSets.MYIFE_OrderHeaderDetailsFields.getFields()){
			detailsFields.add(field.getFieldPath());
		}
		System.debug('detailsFields==== ' + detailsFields);
		return detailsFields;
	}

	@AuraEnabled(cacheable = true)
	public static List<myIfeOrderLines__x> getMYIFE_OrderLines(String orderHeaderId){
		List<myIfeOrderLines__x> orderLines = [SELECT ORDERED_QUANTITY__c, WAREHOUSE__c, Id, CurrencyIsoCode, ExternalId, DisplayUrl, EXTENDED_PRICE__c, HEADER_ID__c, ITEM_DESCRIPTION__c, LINE_ID__c, LINE_NUMBER__c, ITEM__c, UOM__c, SCHEDULE_SHIP_DATE__c, UNIT_SELLING_PRICE__c, DELIVERY_ID__c
		                                       FROM myIfeOrderLines__x
		                                       LIMIT 5];
		System.debug('orderLines>>>' + orderLines);
		return orderLines;
	}

	public class FieldSetWrapper{
		@AuraEnabled
		public List<myIfeOrderHeaders__x> mYIFEorderHeaderList{ get; set; }

		@AuraEnabled
		public List<Schema.FieldSetMember> headerFields{ get; set; }

		public FieldSetWrapper(){
			mYIFEorderHeaderList = new List<myIfeOrderHeaders__x>();
			headerFields = new List<Schema.FieldSetMember>();
		}
	}

	public class OrderHeaderAndOrderLinesWrapper{
		@AuraEnabled
		public myIfeOrderHeaders__x orderHeaderObj{ get; set; }

		@AuraEnabled
		public List<myIfeOrderLines__x> orderLineList{ get; set; }

		public OrderHeaderAndOrderLinesWrapper(){
			orderHeaderObj = new myIfeOrderHeaders__x();
			orderLineList = new List<myIfeOrderLines__x>();
		}
	}
}