objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Customer_ID__c</fullName>
        <description>Customer Account ID. External ID of Account, not shown in UI; may be redundant with Party ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/IFE_Document__c.object
<CustomObject>
    <fields>
        <fullName>All_Customers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Document should be displayed to all customers</description>
        <label>All Customers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Modified_Date__c</fullName>
        <inlineHelpText>Required to be set so that it can be picked up by weekly email batch</inlineHelpText>
        <label>Document Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Number__c</fullName>
        <externalId>true</externalId>
        <label>Document Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Publication</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>GCS</fullName>
                </value>
                <value>
                    <fullName>Spare Parrs</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Number__c</fullName>
        <label>Folder Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Version__c</fullName>
        <label>Folder Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Part_Description__c</fullName>
        <label>Part Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <label>Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Pub_Document_Type__c</fullName>
        <label>Tech Pub Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Document_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aircraft Illustrated Parts Catalog</fullName>
                </value>
                <value>
                    <fullName>Aircraft Maintenance Manual</fullName>
                </value>
                <value>
                    <fullName>AIRCRAFT SCHEMATIC MANUAL</fullName>
                </value>
                <value>
                    <fullName>AIRCRAFT WIRING MANUAL</fullName>
                </value>
                <value>
                    <fullName>Component Maintenance Manual</fullName>
                </value>
                <value>
                    <fullName>COMPONENT MAINTENANCE PUBLICATION</fullName>
                </value>
                <value>
                    <fullName>Customer Information Letter</fullName>
                </value>
                <value>
                    <fullName>Fault Isolation Manual</fullName>
                </value>
                <value>
                    <fullName>Illustrated Parts Catalog</fullName>
                </value>
                <value>
                    <fullName>ILLUSTRATED PARTS DATA</fullName>
                </value>
                <value>
                    <fullName>INSTALLATION SERVICE BULLETIN</fullName>
                </value>
                <value>
                    <fullName>MAINTENANCE PRACTICE</fullName>
                </value>
                <value>
                    <fullName>Master BITE Fault List</fullName>
                </value>
                <value>
                    <fullName>ON-AIRCRAFT TEST PROCEDURE</fullName>
                </value>
                <value>
                    <fullName>Operations Maintenance Manual</fullName>
                </value>
                <value>
                    <fullName>Publications Indexes</fullName>
                </value>
                <value>
                    <fullName>Reference Document</fullName>
                </value>
                <value>
                    <fullName>REMOVAL SERVICE BULLETIN</fullName>
                </value>
                <value>
                    <fullName>REQUEST FORMS</fullName>
                </value>
                <value>
                    <fullName>Service Bulletin</fullName>
                </value>
                <value>
                    <fullName>Service Information Letter</fullName>
                </value>
                <value>
                    <fullName>STANDARD PRACTICE MANUAL</fullName>
                </value>
                <value>
                    <fullName>Standard Wiring Practices Manual</fullName>
                </value>
                <value>
                    <fullName>SYSTEM SCHEMATIC MANUAL</fullName>
                </value>
                <value>
                    <fullName>TASK CARDS</fullName>
                </value>
                <value>
                    <fullName>TEAC CMM</fullName>
                </value>
                <value>
                    <fullName>Technical Information Letter</fullName>
                </value>
                <value>
                    <fullName>Trouble Shooting Manual</fullName>
                </value>
                <value>
                    <fullName>Video Control Center Component Maintenance Manual</fullName>
                </value>
                <value>
                    <fullName>﻿WIRING DIAGRAM MANUAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IFE Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IFE_Document_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFE_Document__c</fullName>
        <label>IFE Document</label>
        <referenceTo>IFE_Document__c</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IFE Customer Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Customer Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Part__c.object
<CustomObject>
    <fields>
        <fullName>Override__c</fullName>
        <label>Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Part_Description__c</fullName>
        <label>Part Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IFE Part</label>
    <nameField>
        <label>IFE Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IFE_Part_Document__c.object
<CustomObject>
    <fields>
        <fullName>IFE_Document__c</fullName>
        <label>IFE Document</label>
        <referenceTo>IFE_Document__c</referenceTo>
        <relationshipLabel>IFE Part Documents</relationshipLabel>
        <relationshipName>IFE_Part_Documents</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFE_Part__c</fullName>
        <label>IFE Part</label>
        <referenceTo>IFE_Part__c</referenceTo>
        <relationshipName>IFE_Part_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFE Part Document</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>IFE Part Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Part Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Part_Overide__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IFE Part Overrides</relationshipLabel>
        <relationshipName>IFE_Part_Overrides</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IFE_Part__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>IFE Part</label>
        <referenceTo>IFE_Part__c</referenceTo>
        <relationshipLabel>IFE Part Overrides</relationshipLabel>
        <relationshipName>IFE_Part_Overrides</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <label>Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                    <default>true</default>
                    <label>Add</label>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>IFE Part Overide</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>IFE Part Overide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Part Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ife_DocumentSearchController.cls
public class ife_DocumentSearchController{
	public ife_DocumentSearchController(){
	}

	@AuraEnabled
	public static List<String> getDocumentTypeValue(){
		String objectName = 'IFE_Document__c';
		String fieldName = 'Tech_Pub_Document_Type__c';
		List<String> pickValues = new List<String>();
		Schema.SObjectType s = Schema.getGlobalDescribe().get(objectName);
		Schema.DescribeSObjectResult r = s.getDescribe();
		Map<String, Schema.SObjectField> fields = r.fields.getMap();
		Schema.DescribeFieldResult fieldResult = fields.get(fieldName).getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for (Schema.PicklistEntry pickListVal : ple){
			System.debug(pickListVal.getLabel()+' ' + pickListVal.getValue());
			pickValues.add(pickListVal.getValue());
		}
		return pickValues;
	}
    @AuraEnabled
	public static List<IFE_Document__c> getDocumentSearchResult(String partNumber, String partDescription, String documentNumber, String techPubDocumentType, String dateTo, String dateFrom){
        //Set<String> documentIdsLoginUser = getLoginUserDocuments();
        Set<String> documentPartNumbers = new Set<String>();
        Set<String> documentIds = new Set<String>();
        Set<String> resultDocuments = new Set<String>();
        
        User userObj = [SELECT Id, Name, Contact.AccountId, Contact.Account.L2I_Customer_ID__c
		                FROM User
						WHERE Id = :UserInfo.getUserId()];
		
		Set<String> documentIdsLoginUser = getLoginUserDocuments(userObj);
        
        String customerId='';
		if (userObj.Contact.AccountId != null){
			System.debug('userObj.Contact.AccountId--- ' + userObj.Contact.AccountId);

			customerId = userObj.Contact.Account.L2I_Customer_ID__c;

		}
       
        List<String> overrideParts = new List<String>();
         for (IFE_Part_Overide__c part :[SELECT Account__c, Override__c, IFE_Part__r.name, Name, Id
		                                 FROM IFE_Part_Overide__c
		                                 WHERE Override__c = 'Add' AND Account__c = :userObj.Contact.AccountId ]){
			overrideParts.add(part.IFE_Part__r.name);
		}
        List<String> partNumsToQuery = new List<String>();
         //partNumPresentInOverride
        If(String.isNotBlank(partNumber) && overrideParts.contains(partNumber)){
             for(IFE_Part_Document__c partDocument : [SELECT Id, IFE_Document__c, IFE_Part__c, Name, IFE_Part__r.Name
		                                          FROM IFE_Part_Document__c
		                                          WHERE IFE_Part__r.Name = :partNumber ]){
					documentPartNumbers.add(partDocument.IFE_Part__r.Name);
            		resultDocuments.add(partDocument.IFE_Document__c);    
                    documentIds.add(partDocument.IFE_Document__c);
		 	}
        }
        //partNumPresentButNotInOverride            
        for (IFE_Part_Document__c partDocument : [SELECT Id, IFE_Document__c, IFE_Part__c, Name
		                                          FROM IFE_Part_Document__c
		                                          WHERE IFE_Part__r.Name = :partNumber AND IFE_Document__c = :documentIdsLoginUser]){
			resultDocuments.add(partDocument.IFE_Document__c);
            documentIds.add(partDocument.IFE_Document__c);
		 }
        //getAllPartDocumentsRelatedToOverride
        for (IFE_Part_Document__c partDocument : [SELECT Id, IFE_Document__c, IFE_Part__c, Name
		                                          FROM IFE_Part_Document__c
		                                          WHERE IFE_Part__r.Name = :overrideParts]){
			//resultDocuments.add(partDocument.IFE_Document__c);
            documentIds.add(partDocument.IFE_Document__c);
		 }
        //alldocumemtIdsfromOverride
        //searchBasedOnOtherCriteria
        documentIdsLoginUser.addAll(documentIds);
        List<IFE_Document__c> matchingDocuments = getMatchingDocuments(partNumber, partDescription, documentNumber, techPubDocumentType, dateTo, dateFrom, documentIdsLoginUser, resultDocuments);    
                                                               
        return matchingDocuments;                                                
    }
    
	public static List<IFE_Document__c> getMatchingDocuments(String partNumber, String partDescription, String documentNumber, String techPubDocumentType, String dateTo, String dateFrom,  Set<String> documentIdsLoginUser, Set<String> resultDocuments){
		//Set<String> documentIdsLoginUser = getLoginUserDocuments();
		
		System.debug('techPubDocumentType--- ' + techPubDocumentType);
		String DOCUMENT_TYPE = 'Technical Publication';
		String whereClause = 'Document_Type__c =: DOCUMENT_TYPE';	
	    Boolean additionalFilter = false;

			if (String.isNotBlank(partDescription)){
				whereClause += '  AND Description__c =: partDescription';
                 additionalFilter = true;
			}
			if (String.isNotBlank(documentNumber)){
				whereClause += '  AND Document_Number__c =: documentNumber';
                additionalFilter = true;
			}
			if (String.isNotBlank(techPubDocumentType)){
				whereClause += ' AND Tech_Pub_Document_Type__c =: techPubDocumentType';
                 additionalFilter = true;
			}
			if (String.isNotBlank(dateTo) && String.isNotBlank(dateFrom)){
				Date fromDate = date.valueOf(dateFrom);
				Date toDate = date.valueOf(dateTo);
				whereClause += '  AND Document_Modified_Date__c >=:fromDate  AND Document_Modified_Date__c <=: toDate ';
                additionalFilter = true;
			}
            if (documentIdsLoginUser != null && documentIdsLoginUser.size() > 0 && additionalFilter){
				whereClause += ' AND Id =: documentIdsLoginUser';
			}
        	else{
            	whereClause += ' AND Id =: resultDocuments';
        	}
			System.debug('whereClause--- ' + whereClause);
			String stringQuery = 'SELECT Id,File_Name__c,Folder_Version__c,Folder_Number__c, Part_Number__c,Revision__c,CreatedDate, Part_Description__c, Document_Type__c, Document_Number__c, Description__c FROM IFE_Document__c  WHERE ' + whereClause + ' ORDER BY CreatedDate  DESC';
			System.debug('stringQuery--- ' + stringQuery);
			List<IFE_Document__c> documents = Database.query(stringQuery);
			System.debug('documents--- ' + documents);
			return documents;
	}

	public static Set<String> getLoginUserDocuments(User userObj){
		Set<String> documentIds = new Set<String>();
	
		if (userObj.Contact.AccountId != null){
			System.debug('userObj.Contact.AccountId--- ' + userObj.Contact.AccountId);

			documentIds = getDocuments(new Set<String>{userObj.Contact.AccountId});

		}
		System.debug('documentIds--- ' + documentIds);
		return documentIds;
	}

	public static Set<String> getDocuments(Set<String> accountIds){
		Set<String> documentIds = new Set<String>();
		for (IFE_Document_Account__c docAccount : [SELECT Id, Account__c, IFE_Document__c
		                                           FROM IFE_Document_Account__c
		                                           WHERE Account__c = :accountIds]){
			System.debug('**docAccount-----' + docAccount);
			documentIds.add(docAccount.IFE_Document__c);
		}
		for (IFE_Document__c techPubDocs : [SELECT Id
												   FROM IFE_Document__c
												   WHERE All_Customers__c = true]){
			
			documentIds.add(techPubDocs.Id);
		}
		System.debug('**documentIds-----' + documentIds);
		return documentIds;
	}

	
}