objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Region_2</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Oppt_Region__c</fullName>
        <formula>TEXT(Account.L2I_Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PL Approval Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval flow</description>
        <label>Program Mgr</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_PriceList__c.object
<CustomObject>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Program Price List</relationshipLabel>
        <relationshipName>Program_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <label>Price List Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Sequence__c</fullName>
        <label>Price List Sequence</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Program Price List</relationshipLabel>
        <relationshipName>Program_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>PT_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integration Pending</fullName>
                </value>
                <value>
                    <fullName>Integration Completed</fullName>
                </value>
                <value>
                    <fullName>Retry Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Price List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_PriceList_Entry__c.object
<CustomObject>
    <fields>
        <fullName>PT_CanEscalate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CanEscalate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <formula>PT_Program_Price_List__r.PT_Price_List_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price List Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Price List</label>
        <referenceTo>PT_PriceList__c</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Added</fullName>
                </value>
                <value>
                    <fullName>Reconcile</fullName>
                </value>
                <value>
                    <fullName>Integrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Price List Entry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Price List Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <inlineHelpText>Active state of the Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Send_Email_Notification_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Additional_Emails__c</fullName>
        <description>Additional emails that will receive the email notification</description>
        <inlineHelpText>Additional emails that will receive the email notification</inlineHelpText>
        <label>Additional Emails</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Emails__c</fullName>
        <description>Emails that will not be notified even if they are on the Additional Emails or part of a Group</description>
        <inlineHelpText>Emails that will not be notified even if they are on the Additional Emails or part of a Group. Use semi-colon to separate more than one email entry.</inlineHelpText>
        <label>Exception Emails</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicator if this setting is currently in use.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public_Group__c</fullName>
        <description>Name of the Public Group that need to receive the email notification on BCC</description>
        <label>Public Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Send Email Notification Setting</label>
</CustomObject>

globalValueSets/L2I_Region_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Americas</fullName>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>South Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>South America</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Oceana</fullName>
        <isActive>false</isActive>
        <label>Oceana</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_SendEmailNotificationsTest.cls
/**
 *  @author       Ryan Lobitana (Simplus)
 *  @date         JUL/20/2021
 *  @description  L2I_SendEmailNotifications class
 *
 *  Modification Log:
 *  ------------------------------------------------------------------------------------
 *  Developer                       Date                Description
 *  ------------------------------------------------------------------------------------
 *  Ryan Lobitana                  7/20/2020         Initial scaffold
 *  MS Simplus Khrisna             03/31/2022        W-001727 Primary System Type Validation Rule
 */
@isTest(SeeAllData=false)
public class L2I_SendEmailNotificationsTest {
    
    private static L2I_DataFactory factory;
    
    @testSetup static void testSetup() {
        factory = new L2I_DataFactory();

        Account acc = factory.createCustomerAccount('Test Customer', '123 Augustine Street', 'San Diego', 'CA', '91890');
        acc.L2I_Region__c = 'Europe';
        insert acc;
        System.assert(acc.Id != null, 'Named Customer Account must have an Id');

        Opportunity dealOpp = factory.createDealOpportunity('Deal', 'Open', 30, acc.Id);
        insert dealOpp;
        System.assert(dealOpp.Id != null, 'Deal Opportunity must have an Id');
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOpp = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesOpp;

        SBQQ__Quote__c quote = factory.createQuote('draft', acc.Id, salesOpp.Id, false);
        insert quote;
        
        blng__BillingRule__c billingRule = new blng__BillingRule__c(Name = 'Test Billable Rule', blng__InitialBillingTrigger__c = 'Order Product Activation Date', blng__PartialPeriodTreatment__c = 'Separate', blng__AmendmentBillCycleDateAlignment__c = 'Align to original Order Product', blng__GenerateInvoices__c = 'No', blng__Active__c = True);
        insert billingRule;

        blng__RevenueRecognitionRule__c revRec = new blng__RevenueRecognitionRule__c(name = 'Test Revenue Recognition Rule', blng__Active__c = true, blng__CreateRevenueSchedule__c = 'No');
        insert revRec;

        blng__TaxRule__c taxRule = new blng__TaxRule__c(Name = 'Test tax Rule', blng__Active__c = true, blng__TaxableYesNo__c = 'No');
        insert taxRule;

        List<Product2> products = new List<Product2>();
        Product2 testProd = factory.createProduct('905647-TEST10', 'Test product', 'IFEC','IFE HW', 'X-Series');
        testProd.blng__BillingRule__c = billingRule.Id;
        testProd.blng__RevenueRecognitionRule__c = revRec.Id;
        testProd.blng__TaxRule__c = taxRule.Id;
        products.add(testProd);
        insert products;

        List<PricebookEntry> entries = new List<PricebookEntry>();
        for (SObject prod : products) {
            PricebookEntry pbe = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
            entries.add(pbe);
        }
        insert entries;

        PT_PriceList__c priceList = new PT_PriceList__c(PT_Program__c = null, PT_Description__c = 'TBD', PT_IsActive__c = TRUE, PT_Price_List_Sequence__c = '01', PT_Price_List_Name__c = 'TestPL', PT_Opportunity__c = salesOpp.Id);
        insert priceList;

        PT_PriceList_Entry__c plEntry = new PT_PriceList_Entry__c(PT_Program_Price_List__c = priceList.Id, PT_CanEscalate__c = TRUE, PT_isActive__c = TRUE, PT_StartDate__c = Date.today(), PT_Status__c = 'Approved', PT_Product__c = products[0].Id, PT_UnitPrice__c = 30.0, Name = 'Test1234');
        insert plEntry;

        SBQQ__SolutionGroup__c sg = new SBQQ__SolutionGroup__c(
              Name = 'ALT'
        );
        insert sg;
    
        SBQQ__QuoteLineGroup__c qlg1 = new SBQQ__QuoteLineGroup__c(
              Name = sg.Name,
              SBQQ__SolutionGroup__c = sg.Id,
              SBQQ__Quote__c = quote.Id
        );
        insert qlg1;
        
        List<SBQQ__QuoteLine__c> qlList = new List<SBQQ__QuoteLine__c>();

        for (Product2 prod : products) {
            SBQQ__QuoteLine__c quoteLine = factory.createQuoteLine( quote.Id, prod.Id, null );
            quoteLine.SBQQ__Quantity__c = 1;
            quoteLine.PT_Price_List_Entry__c = plEntry.Id;
            quoteLine.SBQQ__Group__c = qlg1.Id;
            qlList.add(quoteLine);
        }
        insert qlList;
    }
    
    @isTest
    static void closedWonOppty() {
        
        Send_Email_Notification_Setting__c settings = new Send_Email_Notification_Setting__c();
        settings.Is_Active__c = TRUE;
        settings.Additional_Emails__c = 'test@email.com';
        settings.Exception_Emails__c = 'test1@email.com';
        settings.Public_Group__c = 'Program Approval DL';
        
        insert settings;
        
        Opportunity oppty = [SELECT Id, StageName, L2I_Product_Category__c, L2I_Oppt_Region__c FROM Opportunity LIMIT 1];
        oppty.StageName = 'Closed Won';
        oppty.L2I_Product_Category__c = 'IFEC';
        
        User userRec = [SELECT Id, Email FROM User WHERE Profile.Name = 'System Administrator' ORDER BY Name LIMIT 1];
        oppty.PT_Program_Mgr__c = userRec.Id;
        oppty.PT_PL_Approval_Approver__c = userRec.Id;
        
        test.startTest();
        
        update oppty;
        
        oppty.StageName = 'Handoff';        
        update oppty;
        
        oppty.StageName = 'Delivery';
        update oppty;
        
        test.stopTest();
    }
	
}