objects/Account.object
<CustomObject>
    <fields>
        <fullName>L2I_Operator_Number__c</fullName>
        <description>Panasonic Operator Number 2 digit Airline Code; Not entered by sales</description>
        <inlineHelpText>The 2-digit customer code is assigned by PAC and should be the IATA code for airlines.</inlineHelpText>
        <label>Operator Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_AC_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (A/C Operator)</relationshipLabel>
        <relationshipName>AircraftOperatorOpportunties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Type</label>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Deal_Opportunity_Description__c</fullName>
        <label>Deal Oppty Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PL_Business_Pillars__c</fullName>
        <formula>SBQQ__PrimaryQuote__r.PL_Business_Pillars__c</formula>
        <label>Product Groups</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_AutomateExistingDealOppBatch_Test.cls
@isTest
public with sharing class L2I_AutomateExistingDealOppBatch_Test {
    private static L2I_DataFactory factory;
    
    @isTest
    static void dealOpptyWithSalesOppty_Test() {
        factory = new L2I_DataFactory();
        Account acc = factory.createCustomerAccount('Test Customer', '123 Augustine Street', 'San Diego', 'CA', '91890');
        acc.L2I_Operator_Number__c = 'AC';
        insert acc;
        
        Opportunity dealOpp = factory.createDealOpportunity('Deal', 'Open', 30, acc.Id);
        insert dealOpp;
        
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOpp = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp.L2I_Product_Category__c = 'IFEC';
        salesOpp.L2I_AC_Operator__c = acc.Id;
        salesOpp.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesOpp;
        
        L2I_Aircraft_Type__c att = factory.createAircraftType( acc.Id, 123456);
        insert att;
        
        L2I_DSH__c dsHeaderlList = factory.createDeliverySchedule( acc.Id, att.Id);
        insert dsHeaderlList;
        
        L2I_DSL__c dsLineList = factory.createDeliveryScheduleLine( dsHeaderlList.Id );
        dsLineList.Original_Opportunity__c = salesOpp.Id;
        insert dsLineList;
        
        Boolean isPrimaryQuote = true;
        SBQQ__Quote__c quote = factory.createQuote('Draft', acc.Id, salesOpp.Id, isPrimaryQuote);
        quote.L2I_Reviewed_PO_Required__c = true;
        quote.SBQQ__BillingFrequency__c = 'Monthly';
        quote.SBQQ__StartDate__c =  Date.today();
        quote.ApprovalStatus__c = 'Approved';
        quote.SubmittedDate__c = Date.today();
        quote.L2I_Final_Proposal_Submission_Date__c = Date.today();
        insert quote;
        
        quote.PL_Business_Pillars__c = 'PTS';
        update quote;
    
        Test.startTest();
        L2I_AutomateExistingDealOppBatch batch = new L2I_AutomateExistingDealOppBatch();
        DataBase.executeBatch(batch);
        Test.stopTest();
        
        Opportunity opptyDealConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id];        
       	System.assertEquals(opptyDealConfirm.L2I_Deal_Opportunity_Description__c, 'AC / PTS');
        
        Opportunity opptySalesConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id];        
       	System.assertEquals(opptySalesConfirm.L2I_Deal_Opportunity_Description__c, 'AC / PTS');
    }
    
        
    @isTest
    static void dealOpptyWithSalesOpptys_Test() {
        factory = new L2I_DataFactory();
        Account acc = factory.createCustomerAccount('Test Customer', '123 Augustine Street', 'San Diego', 'CA', '91890');
        acc.L2I_Operator_Number__c = 'AC';
        insert acc;
        
        Opportunity dealOpp = factory.createDealOpportunity('Deal', 'Open', 30, acc.Id);
        insert dealOpp;
        
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOpp1 = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp1.L2I_Product_Category__c = 'IFEC';
        salesOpp1.L2I_Primary_System_Type__c = prodSysType.Id;
        salesOpp1.L2I_AC_Operator__c = acc.Id;
        insert salesOpp1;
        
        Opportunity salesOpp2 = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp2.L2I_Product_Category__c = 'IFEC';
        salesOpp2.L2I_Primary_System_Type__c = prodSysType.Id;
        salesOpp2.L2I_AC_Operator__c = acc.Id;
        insert salesOpp2;
        
        L2I_Aircraft_Type__c att = factory.createAircraftType( acc.Id, 123456);
        insert att;
        
        L2I_DSH__c dsHeaderlList = factory.createDeliverySchedule( acc.Id, att.Id);
        insert dsHeaderlList;
        
        L2I_DSL__c dsLineList1 = factory.createDeliveryScheduleLine( dsHeaderlList.Id );
        dsLineList1.Original_Opportunity__c = salesOpp1.Id;
        insert dsLineList1;
        
        L2I_DSL__c dsLineList2 = factory.createDeliveryScheduleLine( dsHeaderlList.Id );
        dsLineList2.Original_Opportunity__c = salesOpp2.Id;
        insert dsLineList2;
        
        Boolean isPrimaryQuote = true;
        SBQQ__Quote__c quote1 = factory.createQuote('Draft', acc.Id, salesOpp1.Id, isPrimaryQuote);
        quote1.L2I_Reviewed_PO_Required__c = true;
        quote1.SBQQ__BillingFrequency__c = 'Monthly';
        quote1.SBQQ__StartDate__c =  Date.today();
        quote1.ApprovalStatus__c = 'Approved';
        quote1.SubmittedDate__c = Date.today();
        quote1.L2I_Final_Proposal_Submission_Date__c = Date.today();
        insert quote1;
        
        quote1.PL_Business_Pillars__c = 'PTS';
        update quote1;
        
        SBQQ__Quote__c quote2 = factory.createQuote('Draft', acc.Id, salesOpp2.Id, isPrimaryQuote);
        quote2.L2I_Reviewed_PO_Required__c = true;
        quote2.SBQQ__BillingFrequency__c = 'Monthly';
        quote2.SBQQ__StartDate__c =  Date.today();
        quote2.ApprovalStatus__c = 'Approved';
        quote2.SubmittedDate__c = Date.today();
        quote2.L2I_Final_Proposal_Submission_Date__c = Date.today();
        quote2.PL_Business_Pillars__c = 'IFE';
        insert quote2;
    
        Test.startTest();
        L2I_AutomateExistingDealOppBatch batch = new L2I_AutomateExistingDealOppBatch();
        DataBase.executeBatch(batch);
        Test.stopTest();
        
        Opportunity opptyDealConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id];        
       	System.assertEquals(opptyDealConfirm.L2I_Deal_Opportunity_Description__c, 'AC / PTS-IFE');
        
        Opportunity opptySalesConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id LIMIT 1];        
       	System.assertEquals(opptySalesConfirm.L2I_Deal_Opportunity_Description__c, 'AC / PTS-IFE');
    }
    
    @isTest
    static void dealOpptyNoACWithSalesOppty_Test() {
        factory = new L2I_DataFactory();
        Account acc = factory.createCustomerAccount('Test Customer', '123 Augustine Street', 'San Diego', 'CA', '91890');
        insert acc;
        
        Opportunity dealOpp = factory.createDealOpportunity('Deal', 'Open', 30, acc.Id);
        insert dealOpp;
        
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOpp = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp.L2I_Product_Category__c = 'IFEC';
        salesOpp.L2I_Primary_System_Type__c = prodSysType.Id;
        insert salesOpp;
        
        L2I_Aircraft_Type__c att = factory.createAircraftType( acc.Id, 123456);
        insert att;
        
        L2I_DSH__c dsHeaderlList = factory.createDeliverySchedule( acc.Id, att.Id);
        insert dsHeaderlList;
        
        L2I_DSL__c dsLineList = factory.createDeliveryScheduleLine( dsHeaderlList.Id );
        dsLineList.Original_Opportunity__c = salesOpp.Id;
        insert dsLineList;
        
        Boolean isPrimaryQuote = true;
        SBQQ__Quote__c quote = factory.createQuote('Draft', acc.Id, salesOpp.Id, isPrimaryQuote);
        quote.L2I_Reviewed_PO_Required__c = true;
        quote.SBQQ__BillingFrequency__c = 'Monthly';
        quote.SBQQ__StartDate__c =  Date.today();
        quote.ApprovalStatus__c = 'Approved';
        quote.SubmittedDate__c = Date.today();
        quote.L2I_Final_Proposal_Submission_Date__c = Date.today();
        insert quote;
        
        quote.PL_Business_Pillars__c = 'PTS';
        update quote;
    
        Test.startTest();
        L2I_AutomateExistingDealOppBatch batch = new L2I_AutomateExistingDealOppBatch();
        DataBase.executeBatch(batch);
        Test.stopTest();
        
        Opportunity opptyDealConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id];        
       	System.assertEquals(opptyDealConfirm.L2I_Deal_Opportunity_Description__c, 'Unavailable / PTS');
        
        Opportunity opptySalesConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id];        
       	System.assertEquals(opptySalesConfirm.L2I_Deal_Opportunity_Description__c, 'Unavailable / PTS');
    }
    
    @isTest
    static void dealOpptyNoACWithSalesOpptys_Test() {
        factory = new L2I_DataFactory();
        Account acc = factory.createCustomerAccount('Test Customer', '123 Augustine Street', 'San Diego', 'CA', '91890');
        insert acc;
        
        Opportunity dealOpp = factory.createDealOpportunity('Deal', 'Open', 30, acc.Id);
        insert dealOpp;
        
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOpp1 = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp1.L2I_Product_Category__c = 'IFEC';
        salesOpp1.L2I_Primary_System_Type__c = prodSysType.Id;
        salesOpp1.L2I_AC_Operator__c = acc.Id;
        insert salesOpp1;
        
        Opportunity salesOpp2 = factory.createSalesOpportunityWithAmount('Sales', 'Open', 30, acc.Id, dealOpp.Id, 200000, 'IFEC');
        salesOpp2.L2I_Product_Category__c = 'IFEC';
        salesOpp2.L2I_Primary_System_Type__c = prodSysType.Id;
        salesOpp2.L2I_AC_Operator__c = acc.Id;
        insert salesOpp2;
        
        L2I_Aircraft_Type__c att = factory.createAircraftType( acc.Id, 123456);
        insert att;
        
        L2I_DSH__c dsHeaderlList = factory.createDeliverySchedule( acc.Id, att.Id);
        insert dsHeaderlList;
        
        L2I_DSL__c dsLineList1 = factory.createDeliveryScheduleLine( dsHeaderlList.Id );
        dsLineList1.Original_Opportunity__c = salesOpp1.Id;
        insert dsLineList1;
        
        L2I_DSL__c dsLineList2 = factory.createDeliveryScheduleLine( dsHeaderlList.Id );
        dsLineList2.Original_Opportunity__c = salesOpp2.Id;
        insert dsLineList2;
        
        Boolean isPrimaryQuote = true;
        SBQQ__Quote__c quote1 = factory.createQuote('Draft', acc.Id, salesOpp1.Id, isPrimaryQuote);
        quote1.L2I_Reviewed_PO_Required__c = true;
        quote1.SBQQ__BillingFrequency__c = 'Monthly';
        quote1.SBQQ__StartDate__c =  Date.today();
        quote1.ApprovalStatus__c = 'Approved';
        quote1.SubmittedDate__c = Date.today();
        quote1.L2I_Final_Proposal_Submission_Date__c = Date.today();
        insert quote1;
        
        quote1.PL_Business_Pillars__c = 'PTS';
        update quote1;
        
        SBQQ__Quote__c quote2 = factory.createQuote('Draft', acc.Id, salesOpp2.Id, isPrimaryQuote);
        quote2.L2I_Reviewed_PO_Required__c = true;
        quote2.SBQQ__BillingFrequency__c = 'Monthly';
        quote2.SBQQ__StartDate__c =  Date.today();
        quote2.ApprovalStatus__c = 'Approved';
        quote2.SubmittedDate__c = Date.today();
        quote2.L2I_Final_Proposal_Submission_Date__c = Date.today();
        quote2.PL_Business_Pillars__c = 'IFE';
        insert quote2;
    
        Test.startTest();
        L2I_AutomateExistingDealOppBatch batch = new L2I_AutomateExistingDealOppBatch();
        DataBase.executeBatch(batch);
        Test.stopTest();
        
        Opportunity opptyDealConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id];        
       	System.assertEquals(opptyDealConfirm.L2I_Deal_Opportunity_Description__c, 'Unavailable / PTS-IFE');
        
        Opportunity opptySalesConfirm = [SELECT Id, L2I_Deal_Opportunity_Description__c FROM Opportunity WHERE Id =: dealOpp.Id LIMIT 1];        
       	System.assertEquals(opptySalesConfirm.L2I_Deal_Opportunity_Description__c, 'Unavailable / PTS-IFE');
    }
}