objects/Asset.object
<CustomObject>
    <fields>
        <fullName>PT_Airbus_D1_Date__c</fullName>
        <label>Airbus D1 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Expedited_D1__c</fullName>
        <formula>IF (OR(ISBLANK(PT_Airbus_D1_Date__c),PT_Lead_Time__c &lt; PT_Airbus_D1_Date__c)
    , &#39;No&#39;
    ,IF (ISBLANK(PT_MROD__c)
        , &#39;Yes&#39;
        ,IF (PT_Airbus_D1_Date__c &lt; PT_MROD__c
            , &#39;Yes&#39;
            , &#39;No&#39;
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expedited D1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Expedited__c</fullName>
        <formula>IF (OR(ISBLANK(PT_Pending__c),PT_Lead_Time__c &lt; PT_Pending__c)
    , &#39;No&#39;
    ,IF (ISBLANK(PT_MROD__c)
        , &#39;Yes&#39;
        ,IF (PT_Pending__c &lt; PT_MROD__c
            , &#39;Yes&#39;
            , &#39;No&#39;
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expedited</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Lead_Time__c</fullName>
        <description>Required Lead Time (Number of Days) for this Product to achieve MROD</description>
        <formula>PT_Program__r.PT_Program_Type_Lead__c
+
TODAY()
+
Product2.L2I_Cumulative_Lead_Time__c
+
IF (PT_Conformity_Required__c
,7
,0
)
+
Product2.L2I_Item_Post_Processing_Days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Required Lead Time (Number of Days) for this Product to achieve MROD</inlineHelpText>
        <label>PMO Lead Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_MROD_Forecast_Date__c</fullName>
        <description>Roll up look for MROD dates</description>
        <formula>if(isblank(PT_MROD__c)
, if(isblank(PT_Install_Location__r.MROD__c),
  if(isblank( PT_Install_Location__r.ShipSet__c ),null, PT_Install_Location__r.ShipSet__r.Delivery_Date__c )
  ,PT_Install_Location__r.MROD__c)
,  PT_MROD__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Roll up look for MROD dates</inlineHelpText>
        <label>MROD Forecast Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_MROD__c</fullName>
        <label>MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Pending__c</fullName>
        <label>Pending MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Use_D1_Date__c</fullName>
        <defaultValue>&#39;Yes&#39;</defaultValue>
        <label>Use D1 Date?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name_Rev__c</fullName>
        <formula>Original_Opportunity__r.PT_Part_List_Name_Rev__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part List Name Rev</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PT Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_AC_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (A/C Operator)</relationshipLabel>
        <relationshipName>AircraftOperatorOpportunties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_CPL_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CPL Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Program Part Lists</relationshipLabel>
        <relationshipName>PT_PPL_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name_Rev__c</fullName>
        <formula>PT_Part_List_Name__c &amp; &#39;_&#39; &amp;  PT_Revised_Parts_List_Version_Trans__c
+
IF( PT_Is_PPL__c ,  &quot; (&quot; + TEXT(PT_PPL_Type__c) + &quot;)&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part List Name Rev</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Exclude_From_Orders__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this box is checked the Product cannot be ordered.</inlineHelpText>
        <label>Exclude From Orders</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <label>Install Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_List_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Install Location linked to Part List Opportunity</inlineHelpText>
        <label>Part List Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ShipSet</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_MROD_Revision__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>MROD Revisions</relationshipLabel>
        <relationshipName>MROD_Revisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D1_Date__c</fullName>
        <label>D1 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>MROD Revisions</relationshipLabel>
        <relationshipName>MROD_Revisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latest_Approval_Process_Type__c</fullName>
        <label>Latest Approval Process Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <label>Lead Time</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MROD_FORECAST_DATE__c</fullName>
        <label>MROD FORECAST DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_List_Name_Rev__c</fullName>
        <label>Part List Name Rev</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_List_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part List Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>MROD Revisions</relationshipLabel>
        <relationshipName>MROD_Revisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Administrator__c</fullName>
        <label>Program Administrator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <label>Program Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>MROD Revisions</relationshipLabel>
        <relationshipName>MROD_Revisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipset__c</fullName>
        <label>Shipset</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>MROD Revision</label>
    <nameField>
        <label>MROD Revision</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MROD Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>Is_Airbus__c</fullName>
        <formula>IF ( OR(PT_Program_Type__c == &#39;Production-AIRBUS&#39;, PT_Program_Type__c == &#39;Production-Airbus&#39;), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Airbus?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latest_Approval_Process_Type__c</fullName>
        <label>Latest Approval Process Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MROD_Revision__c</fullName>
        <label>MROD Revision</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Operator)</relationshipLabel>
        <relationshipName>Programs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PMO_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>PMO Group Programs</relationshipLabel>
        <relationshipName>PMOGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PMO_SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Sub Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Sub Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>Programs (PMO Sub Group)</relationshipLabel>
        <relationshipName>PMOSubGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Administrator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Administrator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_BuildMRODRevisions.cls
/**
 *  @author       Sarah Kennedy
 *  @date         12/18/2020
 *  @description  PT_BuildMRODRevisions class - runs prior to submitting the MROD approval
 *
 *  Modification Log:
 *  ------------------------------------------------------------------------------------
 *  Developer                       Date                Description
 *  ------------------------------------------------------------------------------------
 *  Sarah Kennedy                  12/18/2020         Initial scaffold
 *
 */
public class PT_BuildMRODRevisions {
    @InvocableMethod(Label = 'Build Pending MROD Revisions')
    public static List<Boolean> buildPendingMRODRecords(List<Id> programId) {
        List<Asset> astList = new List<Asset>();
        List<PT_MROD_Revision__c> mrList = new List<PT_MROD_Revision__c>();
        //
        // first delete any revision rcds to avoid duplicates
        List<PT_MROD_Revision__c> mrListRemove = new List<PT_MROD_Revision__c>();
        mrListRemove = [
                SELECT Id, Asset__r.PT_Pending__c
                FROM PT_MROD_Revision__c
                WHERE (Program__c = :programId[0])
        ];
        System.debug('*** mrListRemove ' + mrListRemove);
        if (!mrListRemove.isEmpty() && mrListRemove.size() > 0) {
            System.debug('*** delete mrListRemove ' + mrListRemove);
            delete mrListRemove;
        }
        // Get all Assets related to the Program Id
        astList = [
                SELECT Id,
                        PT_Program__r.Is_Airbus__c,
                        PT_Program__r.PT_PMO_Group__r.Name,
                        PT_Program__r.PT_PMO_SubGroup__r.Name,
                        PT_Install_Location__r.Part_List_Opportunity__c,
                        PT_Install_Location__r.Part_List_Opportunity__r.L2I_AC_Operator__r.Name,
                        PT_Install_Location__r.ShipSet__r.Original_Opportunity__r.L2I_AC_Operator__r.Name,
                        PT_Install_Location__r.Part_List_Opportunity__r.PT_CPL_Opportunity__r.L2I_AC_Operator__r.Name,
                        PT_Install_Location__r.Part_List_Opportunity__r.PT_Part_List_Name_Rev__c,
                        PT_Program__r.Program_Manager__c,
                        PT_Program__r.Program_Manager__r.Name,
                        PT_Program__r.Program_Administrator__r.Name,
                        PT_Program__r.Name,
                        PT_Program__r.Latest_Approval_Process_Type__c,
                        PT_Program__r.MROD_Revision__c,
                        PT_Program__c,
                        PT_Install_Location__r.ShipSet__r.Name,
                        PT_Install_Location__r.ShipSet__c,
                        PT_Install_Location__r.Name,
                        ProductCode,
                        Name,
                        Quantity,
                        Product2.L2I_Exclude_From_Orders__c,
                        PT_MROD__c,
                        PT_Pending__c,
                        PT_MROD_Forecast_Date__c,
                        PT_Airbus_D1_Date__c,
                        PT_Use_D1_Date__c,
                        PT_Expedited__c,
                        PT_Expedited_D1__c,
                        PT_Lead_Time__c,
                        Product2.L2I_Lead_Time__c,
                        PT_Default_Shipping_Org__c,
                        PT_Extended_Price__c,
                        Shipset_PPL_Link__c,
                        PT_Install_Location_Parent__c,
                        PT_PPL_Type__c
                FROM Asset
                WHERE PT_Program__c = :programId[0]
                AND ((PT_Pending__c <> null AND PT_Program__r.Latest_Approval_Process_Type__c = 'MROD')
                   OR (PT_Airbus_D1_Date__c <> null  AND PT_Program__r.Latest_Approval_Process_Type__c = 'Airbus MROD' AND
                (PT_Use_D1_Date__c = 'Yes' OR (PT_Use_D1_Date__c = 'No' AND PT_Pending__c <> null))))
                AND PT_Install_Location_Parent__c <> NULL
                AND PT_Can_be_Processed__c = true
                AND isPTAsset__c = true
        ];
        System.debug('*** astList.size() ' + astList.size());
        if (astList.isEmpty() || astList.size() == 0){
            return new List<Boolean>{false};   // no changes are pending
        }
        if (!astList.isEmpty() &&
                astList.size() > 0) {
            for (Asset ast2 : astList) {
                PT_MROD_Revision__c mr = new PT_MROD_Revision__c();
                mr.Asset__c = ast2.Id;
                mr.Region__c = ast2.PT_Program__r.PT_PMO_Group__r.Name;
                mr.Sub_Group__c = ast2.PT_Program__r.PT_PMO_SubGroup__r.Name;
                if (ast2.PT_Install_Location__c != NULL) {
                    if (ast2.PT_Install_Location__r.ShipSet__c == NULL) {
                        if (ast2.PT_Install_Location__r.Part_List_Opportunity__c != NULL &&
                                ast2.PT_Install_Location__r.Part_List_Opportunity__r.PT_CPL_Opportunity__c != NULL &&
                                ast2.PT_Install_Location__r.Part_List_Opportunity__r.PT_CPL_Opportunity__r.L2I_AC_Operator__c != NULL) {
                            mr.Operator__c = ast2.PT_Install_Location__r.Part_List_Opportunity__r.PT_CPL_Opportunity__r.L2I_AC_Operator__r.Name;
                            mr.PPL_Type__c = ast2.PT_PPL_Type__c;
                        }
                    } else {
                        if (ast2.PT_Install_Location__r.ShipSet__c != NULL &&
                                ast2.PT_Install_Location__r.ShipSet__r.Original_Opportunity__c != NULL &&
                                ast2.PT_Install_Location__r.ShipSet__r.Original_Opportunity__r.L2I_AC_Operator__c != NULL) {
                            mr.Operator__c = ast2.PT_Install_Location__r.ShipSet__r.Original_Opportunity__r.L2I_AC_Operator__r.Name;
                        }
                    }
                }
                mr.Program_Manager__c = ast2.PT_Program__r.Program_Manager__r.Name;
                mr.Program_Administrator__c = ast2.PT_Program__r.Program_Administrator__r.Name;
                mr.Program_Number__c = ast2.PT_Program__r.Name;
                mr.Program_MROD_Rev__c = ast2.PT_Program__r.MROD_Revision__c;
                mr.Shipset__c = ast2.PT_Install_Location__r.ShipSet__r.Name;
                mr.Install_Location__c = ast2.PT_Install_Location__c;
                mr.Installation_Location__c = ast2.PT_Install_Location__r.Name;
                mr.Part_Number__c = ast2.ProductCode;
                mr.Description__c = ast2.Name;
                mr.Purchase_Qty__c = ast2.Quantity;
                mr.Orderable_Item__c = !ast2.Product2.L2I_Exclude_From_Orders__c;
                mr.Current_MROD__c = ast2.PT_MROD__c;
                mr.Requested_MROD__c = ast2.PT_Pending__c;
                mr.Expedite__c = ast2.PT_Expedited__c;
                mr.Lead_Time__c = ast2.PT_Lead_Time__c;
                mr.Lead_Time_Days__c = ast2.Product2.L2I_Lead_Time__c;
                mr.Default_Shipping_Org__c = ast2.PT_Default_Shipping_Org__c;
                mr.Extended_Price__c = ast2.PT_Extended_Price__c;
                mr.Program__c = ast2.PT_Program__c;
                mr.Part_List_Opportunity__c = ast2.PT_Install_Location__r.Part_List_Opportunity__c;
                mr.ShipsetId__c = ast2.PT_Install_Location__r.ShipSet__c;
                mr.Part_List_Name_Rev__c = ast2.PT_Install_Location__r.Part_List_Opportunity__r.PT_Part_List_Name_Rev__c;
                mr.MROD_FORECAST_DATE__c = ast2.PT_MROD_Forecast_Date__c;
                mr.Latest_Approval_Process_Type__c = ast2.PT_Program__r.Latest_Approval_Process_Type__c;
//                if (ast2.PT_Program__r.Is_Airbus__c) {
                    mr.D1_Date__c = ast2.PT_Airbus_D1_Date__c;
                    mr.Expedite_D1__c = ast2.PT_Expedited_D1__c;
                    mr.Use_D1__c = ast2.PT_Use_D1_Date__c;
//                } else {
                    mr.Requested_MROD__c = ast2.PT_Pending__c;
                    mr.Expedite__c = ast2.PT_Expedited__c;
//                }

                mrList.add(mr);
            }
        }

        if (!mrList.isEmpty() &&
                mrList.size() > 0) {
            insert mrList;
        }
    
        return new List<Boolean>{true};
    }
}