objects/Asset.object
<CustomObject>
    <fields>
        <fullName>PT_Airbus_D1_Date__c</fullName>
        <label>Airbus D1 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Pending__c</fullName>
        <label>Pending MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>canBulkChangePendingMROD__c</fullName>
        <description>Boolean to identify assets where the Pending MROD date will be updatable when changing the related Install Location Pending MROD date</description>
        <formula>IF( OR(ISBLANK( PT_Install_Location__c ), ISBLANK( Quantity), Quantity = 0), false
, IF(OR(PT_MROD__c=PT_Install_Location__r.MROD__c,AND(ISBLANK(PT_MROD__c),ISBLANK(PT_Install_Location__r.MROD__c))) , true, false )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Boolean to identify assets where the Pending MROD date will be updatable when changing the related Install Location Pending MROD date</inlineHelpText>
        <label>canBulkChangePendingMROD</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>PT_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <label>Install Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Seat_Count__c</fullName>
        <label>Seat Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PT_Seat_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seat Model</label>
        <referenceTo>PT_Seat_Model__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Seat_Vendor__c</fullName>
        <label>Seat Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Seat_Vendor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pending_D1_Date__c</fullName>
        <label>Pending D1 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pending_MROD__c</fullName>
        <label>Pending MROD</label>
        <type>Date</type>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Seat_Model__c.object
<CustomObject>
    <label>Seat Model</label>
    <nameField>
        <label>Seat Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seat Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Seat_Vendor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1 Viscount Road</fullName>
    </customValue>
    <customValue>
        <fullName>AAR</fullName>
    </customValue>
    <customValue>
        <fullName>Acro Aircraft Seating (Sussex, UK)</fullName>
    </customValue>
    <customValue>
        <fullName>Adient Aerospace</fullName>
    </customValue>
    <customValue>
        <fullName>AIM (Henshalls)</fullName>
    </customValue>
    <customValue>
        <fullName>AIM (Renton)</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Altitude</fullName>
    </customValue>
    <customValue>
        <fullName>AIM Aviation (Dorset)</fullName>
    </customValue>
    <customValue>
        <fullName>AIP, Aircraft Interior Products (Paris)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus (Alabama)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus (DSM)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus (Hamburg)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus (Saint-Nazaire)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus (Tianjin)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus (Toulouse)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus (ZOCI)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus Canada Limited Partnership (ACLP)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus HUA (Montauban)</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus Operations SAS - Airlog II</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus PM5 (Cornebarrieu)</fullName>
    </customValue>
    <customValue>
        <fullName>Air Cabin (Toulouse)</fullName>
    </customValue>
    <customValue>
        <fullName>Airline (Customer Facility)</fullName>
    </customValue>
    <customValue>
        <fullName>Airline Services Ltd. (Manchester)</fullName>
    </customValue>
    <customValue>
        <fullName>AIS (Airbus Interior Services) - Toulouse</fullName>
    </customValue>
    <customValue>
        <fullName>Atlas Air</fullName>
    </customValue>
    <customValue>
        <fullName>ATS (Everett)</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation Business Park</fullName>
    </customValue>
    <customValue>
        <fullName>Avio (Latina)</fullName>
    </customValue>
    <customValue>
        <fullName>BE (Bedfordshire)</fullName>
    </customValue>
    <customValue>
        <fullName>BE (Everett)</fullName>
    </customValue>
    <masterLabel>Seat Vendor</masterLabel>
</GlobalValueSet>

classes/PT_InstallLocTriggerFunctions.cls
/**
 *      @author       Sarah Kennedy
 *      @date         09/27/2020
 *      @description  Trigger Functions for PT_InstallLocationTrigger
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Sarah Kennedy               09/27/2020          Initial scaffold
 */
public without sharing class PT_InstallLocTriggerFunctions {
    
    public static void setInstallLocsName(List<PT_Install_Location__c> newInstallLocList) {
        for (PT_Install_Location__c newInstLoc : newInstallLocList) {
            newInstLoc.PT_Install_Location__c = newInstLoc.Name;
        }
    }

//    public static void setInstallLocs(List<PT_Install_Location__c> newInstallLocList) {
//        // populate the install_locations picklist for the Grid Buddy droprown
//        for (PT_Install_Location__c newInstLoc : newInstallLocList) {
//            newInstLoc.Install_Locations__c = newInstLoc.Name;
//        }
//    }
    
    public static void updateInstallLocsName(List<PT_Install_Location__c> newInstallLocList, Map<Id, PT_Install_Location__c> oldInstallLocMap) {
        for (PT_Install_Location__c newInstallLoc : newInstallLocList) {
            PT_Install_Location__c oldInstallLoc = oldInstallLocMap.get(newInstallLoc.Id);
            if (newInstallLoc.Name != oldInstallLoc.Name) {
                newInstallLoc.Name = oldInstallLoc.Name;
                newInstallLoc.PT_Install_Location__c = oldInstallLoc.Name;
            }
        }
    }
    
    public static void updatePendingMRODs(Map<Id, PT_Install_Location__c> newInstallLocMap) {
        Set<Id> ilIds = newInstallLocMap.keySet();
        List<Asset> updateAssets = [
              SELECT Id, PT_Install_Location__c, PT_Pending__c, PT_Airbus_D1_Date__c
              FROM Asset
              WHERE PT_Install_Location__c IN :ilIds
              AND isDeleted = false
              AND canBulkChangePendingMROD__c = true
        ];
        for (Asset a : updateAssets) {
            a.PT_Pending__c = newInstallLocMap.get(a.PT_Install_Location__c).Pending_MROD__c;
            a.PT_Airbus_D1_Date__c = newInstallLocMap.get(a.PT_Install_Location__c).Pending_D1_Date__c;
        }
        update updateAssets;
        System.debug('======= PT_InstallLocTriggerFunctions::updatePendingMRODs() updated ' + updateAssets.size() + ' records');
    }

    /*
    * @author           Lipton Abillar
    * @date             09/21/2021
    * @workitem         W-003567
    * @description      If Seat Count, Model, or Vendor is changed, set approval status to pending
    * @trigger          PT_InstallLocationTriggerHandler.beforeUpdate()
    * Developer:        Lipton Abillar      09/21/2021      Create
    */
    public static void setPendingStatus(List<PT_Install_Location__c> newInstallLocList, Map<Id, PT_Install_Location__c> oldInstallLocMap) {
        for (PT_Install_Location__c il : newInstallLocList) {
            if (
                il.PT_Seat_Count__c != oldInstallLocMap.get(il.Id).PT_Seat_Count__c ||
                il.PT_Seat_Model__c != oldInstallLocMap.get(il.Id).PT_Seat_Model__c ||
                il.PT_Seat_Vendor__c != oldInstallLocMap.get(il.Id).PT_Seat_Vendor__c
            ) {
                il.PT_Approval_Status__c = 'Pending';
            }
        }
    }
}