objects/Asset.object
<CustomObject>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_MROD__c</fullName>
        <label>MROD</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <label>Install Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ShipSet</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_AssetsWithFutureMROD.cls
public class PT_AssetsWithFutureMROD {

    @InvocableMethod
    public static List<boolean> assetsWithFutureMROD (List<Requests> requests) {
        Boolean futureMRODAsset = false;
        List<Asset> assets = [SELECT Id FROM Asset
                                WHERE PT_Install_Location__r.ShipSet__c =: requests[0].dslId AND PT_MROD__c != null AND PT_MROD__c > Today LIMIT 1];
        if(assets.size() > 0) {
            futureMRODAsset = true;
        }
        return new List<Boolean>{futureMRODAsset};
    }

    public class Requests {
        @InvocableVariable
        public Id dslId;
    }
}