objects/Asset.object
<CustomObject>
    <fields>
        <fullName>PT_Configured_Quantity__c</fullName>
        <label>Configured Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_MROD__c</fullName>
        <label>MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Pending__c</fullName>
        <label>Pending MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>PT Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Pending Replaced</fullName>
                </value>
                <value>
                    <fullName>Reinitialized</fullName>
                </value>
                <value>
                    <fullName>Pending Removed</fullName>
                </value>
                <value>
                    <fullName>Pending Move</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <inlineHelpText>This field is required for Hardware Delivery Schedule Lines</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PT Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Fit_Type__c</fullName>
        <label>Fit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>L2I_Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell/Follow-on</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Fit_Type__c</fullName>
        <label>Fit Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <label>Install Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pending_MROD__c</fullName>
        <label>Pending MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShipSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ShipSet</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_PMO_Groups__c.object
<CustomObject>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Sub Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PMO Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMO Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>MROD_Approval_Status__c</fullName>
        <label>MROD Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMO_Regional_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Needed in the MROD Approval process</description>
        <label>PMO Regional Director User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_First_Aircraft_Delivery__c</fullName>
        <inlineHelpText>Date that the first aircraft of this program has been delivered</inlineHelpText>
        <label>First Aircraft Delivery</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_PMO_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>PMO Group Programs</relationshipLabel>
        <relationshipName>PMOGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PMO_SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Sub Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Sub Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>Programs (PMO Sub Group)</relationshipLabel>
        <relationshipName>PMOSubGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Needed for MROD Approval process</description>
        <label>Principal Program Manager User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Number__c</fullName>
        <externalId>true</externalId>
        <label>Program Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/PT_Program_TriggerFunctionsTest.cls
/**
* @File Name          : PT_Program_TriggerFunctionsTest.cls
* @Description        : Test Class for PT_Program_TriggerFunctions
* @Author             :
* @Last Modified By   : MS Simplus Khrisna
* @Last Modified On   : Mar 31, 2022
* @Modification Log   : 
* Ver           Date           Author               Modification
*                                                   Initial Version
* W-001727      Mar 31 2022    MS Simplus Khrisna   Primary System Type Validation Rule
**/
@isTest
private class PT_Program_TriggerFunctionsTest {
    @isTest
    private static void addUpdateProgramNameTest() {
        PT_Program__c prog = new PT_Program__c();
        prog.Name = 'Test1234';
        prog.Program_Number__c = 'Test1234';
        insert prog;

        prog.Program_Number__c = 'Test7890';
        prog.Name = 'Test7890';
        update prog;
    }

    @isTest
    private static void addMemberToQueueTest() {

        setupForQueues();

        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PM Group' LIMIT 1];
        System.runAs(u1) {
            PT_Program__c prog = new PT_Program__c();
            prog.Name = 'Test1234';
            prog.Program_Number__c = 'Test1234';
            prog.Program_Manager__c = u1.Id;
            Test.startTest();
            insert prog;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
    }

    @isTest
    private static void deleteMemberToQueueTest() {

        setupForQueues();

        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PM Group' LIMIT 1];
        System.runAs(u1) {
            PT_Program__c prog = new PT_Program__c();
            prog.Name = 'Test1234';
            prog.Program_Number__c = 'Test1234';
            prog.Program_Manager__c = u1.Id;
            insert prog;
            Test.startTest();
            delete prog;
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
    }

    @isTest
    private static void deleteMemberMultipleToQueueTest() {

        setupForQueues();

        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id FROM User WHERE FirstName = 'User2' LIMIT 1];
        User u3 = [SELECT Id FROM User WHERE FirstName = 'User3' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PM Group' LIMIT 1];
        System.runAs(u1) {
            PT_Program__c prog1 = new PT_Program__c();
            prog1.Name = 'Test12345';
            prog1.Program_Number__c = 'Test12345';
            prog1.Program_Manager__c = u1.Id;
            insert prog1;
            PT_Program__c prog2 = new PT_Program__c();
            prog2.Name = 'Test1234';
            prog2.Program_Number__c = 'Test1234';
            prog2.Program_Manager__c = u1.Id;
            insert prog2;
            PT_Program__c prog3 = new PT_Program__c();
            prog3.Name = 'Test12346';
            prog3.Program_Number__c = 'Test12346';
            prog3.Program_Manager__c = u2.Id;
            insert prog3;
            Test.startTest();
            delete prog2;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
    }

    @isTest
    private static void changeMemberToQueueTest() {

        setupForQueues();

        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id FROM User WHERE FirstName = 'User2' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PM Group' LIMIT 1];
        System.runAs(u1) {
            PT_Program__c prog = new PT_Program__c();
            prog.Program_Manager__c = u1.Id;
            prog.Name = 'Test1234';
            prog.Program_Number__c = 'Test1234';
            insert prog;
            System.debug('*** ' + [SELECT Name, Program_Number__c FROM PT_Program__c]);
            Test.startTest();
            prog.Program_Manager__c = u2.Id;
            update prog;
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u2.Id]);
    }

    @isTest
    private static void addnewPMOGroup() {
        setupForQueues();

        User u1 = [SELECT Id, Name FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id, Name FROM User WHERE FirstName = 'User2' LIMIT 1];

        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupTestContext(null, null, false);

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
              Name = 'Acct1',
              RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
              Name = 'Deal Opp',
              CloseDate = Date.today(),
              StageName = 'Open'
        );
        insert dealOppty;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;

        Opportunity salesOppty = new Opportunity(
              Name = 'Sales Opp',
              AccountId = acctCustomer.Id,
              RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
              L2I_Product_Category__c = 'IFEC',
              CloseDate = Date.today(),
              StageName = 'Quotation',
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Fit_Type__c = '',
              L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;
        L2I_DSH__c dsh = new L2I_DSH__c();
        insert dsh;
        update dsh;

        L2I_DSL__c dsl = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id
        );
        insert dsl;

        PT_PMO_Groups__c pg = new PT_PMO_Groups__c(
              Name = 'pgName',
              Group_Type__c = 'Group'
        );
        insert pg;
        pg.OwnerId = u1.Id;
        update pg;

        PT_PMO_Groups__c pg2 = new PT_PMO_Groups__c(
              Name = 'pgName2',
              Group_Type__c = 'Sub Group'
        );
        insert pg2;
        pg2.OwnerId = u2.Id;
        update pg2;

        PT_Program__c pgm = new PT_Program__c(
              Name = 'Test1234',
              Program_Number__c = 'Test1234',
              PT_PMO_Group__c = pg.Id,
              PT_PMO_SubGroup__c = pg2.Id
        );
        Test.startTest();
        insert pgm;
        Test.stopTest();
        System.assertEquals(u1.Id, [SELECT PMO_Regional_Director__c FROM PT_Program__c].PMO_Regional_Director__c, 'Regional Directory is PMO Group Owner');
        System.assertEquals(u2.Id, [SELECT Principal_Program_Manager__c FROM PT_Program__c].Principal_Program_Manager__c, 'PPM is PMO Sub Group Owner');

    }

    @isTest
    private static void changePMOGroup() {
        setupForQueues();

        User u1 = [SELECT Id, Name FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id, Name FROM User WHERE FirstName = 'User2' LIMIT 1];

        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupTestContext(null, null, false);

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
              Name = 'Acct1',
              RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
              Name = 'Deal Opp',
              CloseDate = Date.today(),
              StageName = 'Open'
        );
        insert dealOppty;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
		
        Opportunity salesOppty = new Opportunity(
              Name = 'Sales Opp',
              AccountId = acctCustomer.Id,
              RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
              L2I_Product_Category__c = 'IFEC',
              CloseDate = Date.today(),
              StageName = 'Quotation',
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;
        L2I_DSH__c dsh = new L2I_DSH__c();
        insert dsh;
        update dsh;

        L2I_DSL__c dsl = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id
        );
        insert dsl;

        PT_PMO_Groups__c pg = new PT_PMO_Groups__c(
              Name = 'pgName',
              Group_Type__c = 'Group'
        );
        insert pg;
        pg.OwnerId = u1.Id;
        update pg;

        PT_PMO_Groups__c pg2 = new PT_PMO_Groups__c(
              Name = 'pgName2',
              Group_Type__c = 'Sub Group'
        );
        insert pg2;
        pg2.OwnerId = u2.Id;
        update pg2;

        PT_PMO_Groups__c pg3 = new PT_PMO_Groups__c(
              Name = 'pgName3',
              Group_Type__c = 'Group'
        );
        insert pg3;
        pg3.OwnerId = u2.Id;
        update pg3;

        PT_PMO_Groups__c pg4 = new PT_PMO_Groups__c(
              Name = 'pgName4',
              Group_Type__c = 'Sub Group'
        );
        insert pg4;
        pg4.OwnerId = u1.Id;
        update pg4;

        PT_Program__c pgm = new PT_Program__c(
              Name = 'Test1234',
              Program_Number__c = 'Test1234',
              PT_PMO_Group__c = pg.Id,
              PT_PMO_SubGroup__c = pg2.Id
        );
        insert pgm;
        pgm.PT_PMO_Group__c = pg3.Id;
        pgm.PT_PMO_SubGroup__c = pg4.Id;
        Test.startTest();
        update pgm;
        Test.stopTest();
        System.assertEquals(u2.Id, [SELECT PMO_Regional_Director__c FROM PT_Program__c].PMO_Regional_Director__c, 'Regional Directory is PMO Group Owner');
        System.assertEquals(u1.Id, [SELECT Principal_Program_Manager__c FROM PT_Program__c].Principal_Program_Manager__c, 'PPM is PMO Sub Group Owner');

    }


    @isTest
    private static void approveMROD() {
        L2I_DataFactory factory = new L2I_DataFactory();
//        factory.setupTestContext(null, null, false);
        
        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
              Name = 'Acct1',
              RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
              Name = 'Deal Opp',
              CloseDate = Date.today(),
              StageName = 'Open'
        );
        insert dealOppty;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;

        Opportunity salesOppty = new Opportunity(
              Name = 'Sales Opp',
              AccountId = acctCustomer.Id,
              RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
              L2I_Product_Category__c = 'IFEC',
              CloseDate = Date.today(),
              StageName = 'Quotation',
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;
        L2I_DSH__c dsh = new L2I_DSH__c();
        insert dsh;
        update dsh;

        L2I_DSL__c dsl = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id,
              Delivery_Date__c = Date.today()
        );
        insert dsl;

        PT_Program__c pgm = new PT_Program__c(
              Name = 'Test1234',
              Program_Number__c = 'Test1234'
        );
        insert pgm;
        System.debug('*** insert pgm');

        PT_Install_Location__c instLoc = new PT_Install_Location__c(
              Name = 'CW',
              ShipSet__c = dsl.Id,
              Pending_MROD__c = Date.today(),
              Status__c = 'Active'
        );
        insert instLoc;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
              ShipSet__c = dsl.Id,
              Status__c = 'Active'
        );
        insert instLoc2;
    
        Product2 prod = factory.createProduct('99999802', 'MediaServices', '', '', null);
        prod.productCode = 'MCS BUNDLE';
        insert prod;
        
        Asset ast = new Asset(
              Name = 'Asset Name',
              PT_Install_Location__c = instLoc.Id,
              PT_Pending__c = Date.today(),
              PT_Program__c = pgm.Id,
              Product2Id = prod.Id,
              AccountId = acctCustomer.Id,
              PT_Configured_Quantity__c = 10,
              Quantity = 10,
              PT_Status__c = 'Active'
        );
        insert ast;
        System.debug('*** inserted ast ' + ast);
        pgm.MROD_Approval_Status__c = 'Approved';
        Test.startTest();
        
        dsl.PT_Program__c = pgm.Id;
        update dsl;                
        
        System.debug('*** pgm ' + pgm);
        update pgm;
        Test.stopTest();

        System.assertEquals(Date.today(), [SELECT PT_MROD__c FROM Asset LIMIT 1].PT_MROD__c, 'Asset MROD Date set from Pending MROD');
    }

@isTest
    private static void updateFirstDeliveryDate() {
        L2I_DataFactory factory = new L2I_DataFactory();
//        factory.setupTestContext(null, null, false);
        
        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
              Name = 'Acct1',
              RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
              Name = 'Deal Opp',
              CloseDate = Date.today(),
              StageName = 'Open'
        );
        insert dealOppty;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
		
        Opportunity salesOppty = new Opportunity(
              Name = 'Sales Opp',
              AccountId = acctCustomer.Id,
              RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
              L2I_Product_Category__c = 'IFEC',
              CloseDate = Date.today(),
              StageName = 'Quotation',
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;
        L2I_DSH__c dsh = new L2I_DSH__c();
        insert dsh;
        update dsh;
		
        List<L2I_DSL__c> dslList = new List<L2I_DSL__c>();
        
        L2I_DSL__c dsl = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id,
              Delivery_Date__c = Date.today()
        );
        dslList.add(dsl);
        
        L2I_DSL__c dsl2 = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id,
              Delivery_Date__c = Date.today().addDays(-30)
        );
        dslList.add(dsl2);
        
        L2I_DSL__c dsl3 = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id,
              Delivery_Date__c = Date.today().addDays(30)
        );
        dslList.add(dsl3);
        
        insert dslList;

        PT_Program__c pgm = new PT_Program__c(
              Name = 'Test1234',
              Program_Number__c = 'Test1234',
              PT_First_Aircraft_Delivery__c = Date.today().addDays(100),
              Airbus_MROD_Approval_Status__c = 'Approved'
        );
        insert pgm;
        System.debug('*** insert pgm');

        PT_Install_Location__c instLoc = new PT_Install_Location__c(
              Name = 'CW',
              ShipSet__c = dsl.Id,
              Pending_MROD__c = Date.today(),
              Status__c = 'Active'
        );
        insert instLoc;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
              ShipSet__c = dsl.Id,
              Status__c = 'Active'
        );
        insert instLoc2;
    
        Product2 prod = factory.createProduct('99999802', 'MediaServices', '', '', null);
        prod.productCode = 'MCS BUNDLE';
        insert prod;
        
        Asset ast = new Asset(
              Name = 'Asset Name',
              PT_Install_Location__c = instLoc.Id,
              PT_Pending__c = Date.today(),
              PT_Program__c = pgm.Id,
              Product2Id = prod.Id,
              AccountId = acctCustomer.Id,
              PT_Configured_Quantity__c = 10,
              Quantity = 10,
              PT_Status__c = 'Active'
        );
        insert ast;
        System.debug('*** inserted ast ' + ast);
        pgm.MROD_Approval_Status__c = 'Approved';
        pgm.Airbus_MROD_Approval_Status__c = 'Approved';
        Test.startTest();
        
        dslList[0].PT_Program__c = pgm.Id;
        dslList[1].PT_Program__c = pgm.Id;
        update dsl;                
        
        System.debug('*** pgm ' + pgm);
        update pgm;
        Test.stopTest();

        System.assertEquals(Date.today(), [SELECT PT_MROD__c FROM Asset LIMIT 1].PT_MROD__c, 'Asset MROD Date set from Pending MROD');
    }
    private static void setupForQueues() {
        L2I_DataFactory df = new L2I_DataFactory();
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'PAC Sales'].Id;
        User u1 = df.createTestUser(null, profileId, 'User1', 'Test');
        insert u1;
        User u2 = df.createTestUser(null, profileId, 'User2', 'Test');
        insert u2;
        User u3 = df.createTestUser(null, profileId, 'User3', 'Test');
        insert u3;
    }
}