objects/Asset.object
<CustomObject>
    <fields>
        <fullName>PT_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.PT_Program__c</field>
                <operation>equals</operation>
                <valueField>Case.PT_Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>PT Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Pending Replaced</fullName>
                </value>
                <value>
                    <fullName>Reinitialized</fullName>
                </value>
                <value>
                    <fullName>Pending Removed</fullName>
                </value>
                <value>
                    <fullName>Pending Move</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <formula>L2I_Order__r.L2I_Product_Category_2__c</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_AircraftQuantity__c</fullName>
        <label>Aircraft Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Program_Num__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Number</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Status__c</fullName>
        <label>PL Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>PPM Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_PMO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PMO Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_PMO_SubGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PMO SubGroup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Sub Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>Opportunities (Proposed PMO SubGroup)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Inventory_Item_Id__c</fullName>
        <description>EBS Item Id</description>
        <externalId>true</externalId>
        <label>Inventory Item Id</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>PT_Install_Location__c</fullName>
        <label>Install Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_List_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Install Location linked to Part List Opportunity</inlineHelpText>
        <label>Part List Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipSet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ShipSet</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_PMO_Groups__c.object
<CustomObject>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Sub Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PMO Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMO Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>MROD_Approval_Status__c</fullName>
        <label>MROD Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Number__c</fullName>
        <externalId>true</externalId>
        <label>Program Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/PT_AssetTriggerFunctionsTest.cls
/**
* @File Name          : PT_AssetTriggerFunctionsTest.cls
* @Description        : Test Class for PT_AssetTriggerFunctions
* @Author             :
* @Last Modified By   : MS Simplus Khrisna
* @Last Modified On   : Mar 31, 2022
* @Modification Log   : 
* Ver           Date           Author               Modification
*                                                   Initial Version
* W-001727      Mar 31 2022    MS Simplus Khrisna   Primary System Type Validation Rule
**/
@IsTest
private class PT_AssetTriggerFunctionsTest {
    @IsTest
    static void testInsertAssetOnProgramPending() {
        L2I_DataFactory factory = new L2I_DataFactory();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'PAC System Administrator' LIMIT 1];
        User u = new User(
              LastName = 'SMITH',
              FirstName = 'JOHN',
              Alias = 'main',
              Email = 'testPACuser@testfactory.com',
              Phone = '1234567890',
              Username = 'testPACuser@testfactory.com.' + Math.random(),
              TimeZoneSidKey = 'Europe/Berlin',
              LanguageLocaleKey = 'en_US',
              EmailEncodingKey = 'UTF-8',
              LocaleSidKey = 'en_US',
              ProfileId = profile.Id);
        insert u;
//        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PAC_PMO_Admin'];
//        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
            Name = 'Acct1',
            RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
            Name = 'Deal Opp',
            CloseDate = Date.today(),
            StageName = 'Open'
        );
        insert dealOppty;

        PT_Program__c prog = new PT_Program__c();
        prog.Name = 'prog';
        prog.Program_Number__c = 'prog';
        insert prog;
        // Added for W-001727
        Product2 prodSysType = factory.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;

        Opportunity salesOppty = new Opportunity(
            Name = 'Sales Opp',
            AccountId = acctCustomer.Id,
            RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
            L2I_Product_Category__c = 'IFEC',
            CloseDate = Date.today(),
            StageName = 'Handoff',
            L2I_Parent_Opportunity__c = dealOppty.Id,
            L2I_AircraftQuantity__c = 1,
            L2I_Program_Num__c = prog.Id,
            PT_PL_Approval_Status__c = 'Approved',
            L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
            //   ShipSet__c = dsl.Id,
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc2;
        
        Boolean gotError = false;
        System.runAs(u) {
            
            L2I_DataFactory dt = new L2I_DataFactory();
            Account namedCustomer = dt.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            
            Product2 p = new Product2(Name = 'TestProd', ProductCode = 'ProdCode', L2I_Inventory_Item_Id__c = '99999803');
            
            PT_Program__c prog1 = new PT_Program__c();
            prog1.MROD_Approval_Status__c = 'Pending';
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            insert prog1;
            
            Asset ast = new Asset(
                  Name = 'AssetName',
                  AccountId = namedCustomer.Id,
                  Product2Id = p.Id,
                  PT_Program__c = prog1.Id,
                  PT_Install_Location__c = instLoc2.Id
            );
            
            Test.startTest();
            
            try {
                insert ast;
            } catch (Exception e) {
                gotError = true;
                System.debug('*** e ' + e.getMessage());
            }
            Test.stopTest();
        }
        System.assertEquals(true, gotError);
    }
    
    @IsTest
    static void testChangeAssetOnProgramPending() {
        L2I_DataFactory dt = new L2I_DataFactory();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'PAC System Administrator' LIMIT 1];
        User u = new User(
              LastName = 'SMITH',
              FirstName = 'JOHN',
              Alias = 'main',
              Email = 'testPACuser@testfactory.com',
              Phone = '1234567890',
              Username = 'testPACuser@testfactory.com.' + Math.random(),
              TimeZoneSidKey = 'Europe/Berlin',
              LanguageLocaleKey = 'en_US',
              EmailEncodingKey = 'UTF-8',
              LocaleSidKey = 'en_US',
              ProfileId = profile.Id);
        insert u;
//        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PAC_PMO_Admin'];
//        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        Boolean gotError = false;

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
            Name = 'Acct1',
            RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
            Name = 'Deal Opp',
            CloseDate = Date.today(),
            StageName = 'Open'
        );
        insert dealOppty;
        
        List<PT_PMO_Groups__c> lGroups = new List<PT_PMO_Groups__c>();
        PT_PMO_Groups__c pmoG = new PT_PMO_Groups__c();
        pmoG.Name = 'TestG';
        pmoG.Group_Type__c = 'Group';
        lGroups.add(pmoG);
        
        PT_PMO_Groups__c pmoSG = new PT_PMO_Groups__c();
        pmoSG.Name = 'TestSG';
        pmoSG.Group_Type__c = 'Sub Group';
        lGroups.add(pmoSG);
        
        insert lGroups;

        PT_Program__c prog = new PT_Program__c();
        prog.Name = 'prog';
        prog.Program_Number__c = 'prog';
        insert prog;
        
        // Added for W-001727
        Product2 prodSysType = dt.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOppty = new Opportunity(
            Name = 'Sales Opp',
            AccountId = acctCustomer.Id,
            RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
            L2I_Product_Category__c = 'IFEC',
            CloseDate = Date.today(),
            StageName = 'Handoff',
            L2I_Parent_Opportunity__c = dealOppty.Id,
            L2I_AircraftQuantity__c = 1,
            L2I_Program_Num__c = prog.Id,
            PT_PL_Approval_Status__c = 'Approved',
            L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
            //   ShipSet__c = dsl.Id,
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc2;
        
        System.runAs(u) {
            
            Account namedCustomer = dt.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            
            Product2 p = new Product2(Name = 'TestProd', ProductCode = 'ProdCode', L2I_Inventory_Item_Id__c = '99999803');
            
            PT_Program__c prog1 = new PT_Program__c();
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            insert prog1;
            
            Case cases = new Case(Status ='New', Priority = 'Medium', Origin = 'Email', PT_Program__c = prog1.Id,AccountId =namedCustomer.id );
            insert cases;
            Asset ast = new Asset(
                  Name = 'AssetName',
                  AccountId = namedCustomer.Id,
                  Product2Id = p.Id,
                  PT_Program__c = prog1.Id,
                  PT_Install_Location__c = instLoc2.Id,
                  PT_Status__c = 'Active',
                  PT_Case__c = cases.Id
            );
            insert ast;

            Asset astCloned = ast.Clone();
            astCloned.ParentId = ast.Id;
            insert astCloned;

            salesOppty.PT_PL_Approval_Status__c = 'Pending';
            salesOppty.Proposed_Program_Manager__c = u.Id;
            salesOppty.Proposed_PMO_Group__c = lGroups[0].Id;
            salesOppty.Proposed_PMO_SubGroup__c = lGroups[1].Id;
            update salesOppty;

            prog1.MROD_Approval_Status__c = 'Pending';
            update prog1;
            ast.Quantity = 3;
            ast.PT_Status__c = 'Pending Move';
            ast.PT_Warehouse__c = 'BOT';
            
            Test.startTest();
            try {
                update ast;
            } catch (Exception e) {
                gotError = true;
                System.debug('*** e ' + e.getMessage());
            }
            Test.stopTest();
        }
        System.assertEquals(true, gotError);
    }
    
    @IsTest
    static void testDeleteAssetOnProgramPending() {
        L2I_DataFactory dt = new L2I_DataFactory();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'PAC System Administrator' LIMIT 1];
        User u = new User(
              LastName = 'SMITH',
              FirstName = 'JOHN',
              Alias = 'main',
              Email = 'testPACuser@testfactory.com',
              Phone = '1234567890',
              Username = 'testPACuser@testfactory.com.' + Math.random(),
              TimeZoneSidKey = 'Europe/Berlin',
              LanguageLocaleKey = 'en_US',
              EmailEncodingKey = 'UTF-8',
              LocaleSidKey = 'en_US',
              ProfileId = profile.Id);
        insert u;
//        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PAC_PMO_Admin'];
//        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        Boolean gotError = false;

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
            Name = 'Acct1',
            RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
            Name = 'Deal Opp',
            CloseDate = Date.today(),
            StageName = 'Open'
        );
        insert dealOppty;

        PT_Program__c prog = new PT_Program__c();
        prog.Name = 'prog';
        prog.Program_Number__c = 'prog';
        insert prog;

        // Added for W-001727
        Product2 prodSysType = dt.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOppty = new Opportunity(
            Name = 'Sales Opp',
            AccountId = acctCustomer.Id,
            RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
            L2I_Product_Category__c = 'IFEC',
            CloseDate = Date.today(),
            StageName = 'Handoff',
            L2I_Parent_Opportunity__c = dealOppty.Id,
            L2I_AircraftQuantity__c = 1,
            L2I_Program_Num__c = prog.Id,
            PT_PL_Approval_Status__c = 'Approved',
            L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
            //   ShipSet__c = dsl.Id,
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc2;

        System.runAs(u) {
 
            Account namedCustomer = dt.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            
            Product2 p = new Product2(Name = 'TestProd', ProductCode = 'ProdCode', L2I_Inventory_Item_Id__c = '99999803');
            
            List<PT_PMO_Groups__c> lGroups = new List<PT_PMO_Groups__c>();
            PT_PMO_Groups__c pmoG = new PT_PMO_Groups__c();
            pmoG.Name = 'TestG';
            pmoG.Group_Type__c = 'Group';
            lGroups.add(pmoG);
            
            PT_PMO_Groups__c pmoSG = new PT_PMO_Groups__c();
            pmoSG.Name = 'TestSG';
            pmoSG.Group_Type__c = 'Sub Group';
            lGroups.add(pmoSG);
            
            insert lGroups;
            
            PT_Program__c prog1 = new PT_Program__c();
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            insert prog1;
            
            Asset ast = new Asset(
                  Name = 'AssetName',
                  AccountId = namedCustomer.Id,
                  Product2Id = p.Id,
                  PT_Program__c = prog1.Id,
                  PT_Install_Location__c = instLoc2.Id,
                  PT_Status__c = 'Active'
            );
            insert ast;

            salesOppty.PT_PL_Approval_Status__c = 'Pending';
            salesOppty.Proposed_Program_Manager__c = u.Id;
            salesOppty.Proposed_PMO_Group__c = lGroups[0].Id;
            salesOppty.Proposed_PMO_SubGroup__c = lGroups[1].Id;
            update salesOppty;

            prog1.MROD_Approval_Status__c = 'Pending';
            update prog1;
            
            Test.startTest();
            try {
                delete ast;
            } catch (Exception e) {
                gotError = true;
                System.debug('*** e ' + e.getMessage());
            }
            Test.stopTest();
        }
        System.assertEquals(true, gotError);
    }
    
    @IsTest
    static void testInsertAssetOnProgramNOTPending() {
        L2I_DataFactory dt = new L2I_DataFactory();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'PAC System Administrator' LIMIT 1];
        User u = new User(
              LastName = 'SMITH',
              FirstName = 'JOHN',
              Alias = 'main',
              Email = 'testPACuser@testfactory.com',
              Phone = '1234567890',
              Username = 'testPACuser@testfactory.com.' + Math.random(),
              TimeZoneSidKey = 'Europe/Berlin',
              LanguageLocaleKey = 'en_US',
              EmailEncodingKey = 'UTF-8',
              LocaleSidKey = 'en_US',
              ProfileId = profile.Id);
        insert u;
//        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PAC_PMO_Admin'];
//        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        Boolean gotError = false;

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
            Name = 'Acct1',
            RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
            Name = 'Deal Opp',
            CloseDate = Date.today(),
            StageName = 'Open'
        );
        insert dealOppty;

        PT_Program__c prog = new PT_Program__c();
        prog.Name = 'prog';
        prog.Program_Number__c = 'prog';
        insert prog;
        // Added for W-001727
        Product2 prodSysType = dt.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOppty = new Opportunity(
            Name = 'Sales Opp',
            AccountId = acctCustomer.Id,
            RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
            L2I_Product_Category__c = 'IFEC',
            CloseDate = Date.today(),
            StageName = 'Handoff',
            L2I_Parent_Opportunity__c = dealOppty.Id,
            L2I_AircraftQuantity__c = 1,
            L2I_Program_Num__c = prog.Id,
            PT_PL_Approval_Status__c = 'Approved',
            L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
            //   ShipSet__c = dsl.Id,
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc2;

        System.runAs(u) {
            
            Account namedCustomer = dt.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            
            Product2 p = new Product2(Name = 'TestProd', ProductCode = 'ProdCode', L2I_Inventory_Item_Id__c = '99999803');
            
            PT_Program__c prog1 = new PT_Program__c();
            prog1.MROD_Approval_Status__c = 'Approved';
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            insert prog1;
            
            Asset ast = new Asset(
                  Name = 'AssetName',
                  AccountId = namedCustomer.Id,
                  Product2Id = p.Id,
                  PT_Program__c = prog1.Id,
                  PT_Install_Location__c = instLoc2.Id,
                  PT_Status__c = 'Active'
            );
            
            
            Test.startTest();
            try {
                insert ast;
            } catch (Exception e) {
                gotError = true;
                System.debug('*** e ' + e.getMessage());
            }
            Test.stopTest();
        }
        System.assertEquals(false, gotError);
    }
    
    @IsTest
    static void testChangeAssetOnProgramNOTPending() {
        L2I_DataFactory dt = new L2I_DataFactory();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'PAC System Administrator' LIMIT 1];
        User u = new User(
              LastName = 'SMITH',
              FirstName = 'JOHN',
              Alias = 'main',
              Email = 'testPACuser@testfactory.com',
              Phone = '1234567890',
              Username = 'testPACuser@testfactory.com.' + Math.random(),
              TimeZoneSidKey = 'Europe/Berlin',
              LanguageLocaleKey = 'en_US',
              EmailEncodingKey = 'UTF-8',
              LocaleSidKey = 'en_US',
              ProfileId = profile.Id);
        insert u;
//        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PAC_PMO_Admin'];
//        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        Boolean gotError = false;

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
            Name = 'Acct1',
            RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
            Name = 'Deal Opp',
            CloseDate = Date.today(),
            StageName = 'Open'
        );
        insert dealOppty;

        PT_Program__c prog = new PT_Program__c();
        prog.Name = 'prog';
        prog.Program_Number__c = 'prog';
        insert prog;
        // Added for W-001727
        Product2 prodSysType = dt.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;
        
        Opportunity salesOppty = new Opportunity(
            Name = 'Sales Opp',
            AccountId = acctCustomer.Id,
            RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
            L2I_Product_Category__c = 'IFEC',
            CloseDate = Date.today(),
            StageName = 'Handoff',
            L2I_Parent_Opportunity__c = dealOppty.Id,
            L2I_AircraftQuantity__c = 1,
            L2I_Program_Num__c = prog.Id,
            PT_PL_Approval_Status__c = 'Approved',
            L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
            //   ShipSet__c = dsl.Id,
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc2;
        
        System.runAs(u) {
            Account namedCustomer = dt.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            
            Product2 p = new Product2(Name = 'TestProd', ProductCode = 'ProdCode', L2I_Inventory_Item_Id__c = '99999803');
            
            PT_Program__c prog1 = new PT_Program__c();
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            insert prog1;
            
            Asset ast = new Asset(
                  Name = 'AssetName',
                  AccountId = namedCustomer.Id,
                  Product2Id = p.Id,
                  PT_Program__c = prog1.Id,
                  PT_Install_Location__c = instLoc2.Id,
                  PT_Status__c = 'Active'
            );
            insert ast;

            prog1.MROD_Approval_Status__c = 'Approved';
            update prog1;
            ast.Quantity = 3;
            ast.PT_Status__c = 'Pending Move';
            ast.PT_Warehouse__c = 'BOT';
            
            Test.startTest();
            try {
                update ast;
            } catch (Exception e) {
                gotError = true;
                System.debug('*** e ' + e.getMessage());
            }
            Test.stopTest();
        }
        System.assertEquals(false, gotError);
    }
    
    @IsTest
    static void testDeleteAssetOnProgramNOTPending() {
        L2I_DataFactory dt = new L2I_DataFactory();
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'PAC System Administrator' LIMIT 1];
        User u = new User(
              LastName = 'SMITH',
              FirstName = 'JOHN',
              Alias = 'main',
              Email = 'testPACuser@testfactory.com',
              Phone = '1234567890',
              Username = 'testPACuser@testfactory.com.' + Math.random(),
              TimeZoneSidKey = 'Europe/Berlin',
              LanguageLocaleKey = 'en_US',
              EmailEncodingKey = 'UTF-8',
              LocaleSidKey = 'en_US',
              ProfileId = profile.Id);
        insert u;
//        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PAC_PMO_Admin'];
//        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        Boolean gotError = false;

        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
            Name = 'Acct1',
            RecordTypeId = customerRecordTypeId);
        insert acctCustomer;

        Opportunity dealOppty = new Opportunity(
            Name = 'Deal Opp',
            CloseDate = Date.today(),
            StageName = 'Open'
        );
        insert dealOppty;

        PT_Program__c prog = new PT_Program__c();
        prog.Name = 'prog';
        prog.Program_Number__c = 'prog';
        insert prog;
        // Added for W-001727
        Product2 prodSysType = dt.createProduct('9876543','EX3','IFEC','IFE HW', 'X-Series');
        insert prodSysType;

        Opportunity salesOppty = new Opportunity(
            Name = 'Sales Opp',
            AccountId = acctCustomer.Id,
            RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
            L2I_Product_Category__c = 'IFEC',
            CloseDate = Date.today(),
            StageName = 'Handoff',
            L2I_Parent_Opportunity__c = dealOppty.Id,
            L2I_AircraftQuantity__c = 1,
            L2I_Program_Num__c = prog.Id,
            PT_PL_Approval_Status__c = 'Approved',
            L2I_Primary_System_Type__c = prodSysType.Id
        );
        insert salesOppty;

        PT_Install_Location__c instLoc2 = new PT_Install_Location__c(
              Name = 'EC',
            //   ShipSet__c = dsl.Id,
              Status__c = 'Active',
              Part_List_Opportunity__c = salesOppty.Id
        );
        insert instLoc2;
        
        System.runAs(u) {
            Account namedCustomer = dt.createCustomerAccount('Airline Customer', '123 Jump Street', 'San Diego', 'CA', '92122');
            insert namedCustomer;
            
            Product2 p = new Product2(Name = 'TestProd', ProductCode = 'ProdCode', L2I_Inventory_Item_Id__c = '99999803');
            
            PT_Program__c prog1 = new PT_Program__c();
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            insert prog1;
            
            
            Asset ast = new Asset(
                  Name = 'AssetName',
                  AccountId = namedCustomer.Id,
                  Product2Id = p.Id,
                  PT_Program__c = prog1.Id,
                  PT_Install_Location__c = instLoc2.Id
            );
            insert ast;

            prog1.MROD_Approval_Status__c = 'Approved';
            update prog1;
            
            Test.startTest();
            try {
                delete ast;
            } catch (Exception e) {
                gotError = true;
                System.debug('*** e ' + e.getMessage());
            }
            Test.stopTest();
        }
        System.assertEquals(false, gotError);
    }
}