objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Case_Process__c</fullName>
        <label>Case Process</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule Line</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (Opportunity Lookup to Opportunity)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Original_Sales_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Sales Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.Opportunity_Recordtype_Name__c</field>
                <operation>equals</operation>
                <value>Sales</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <formula>L2I_Order__r.L2I_Product_Category_2__c</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Routing_Path__c</fullName>
        <label>Routing Path</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSL</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Identifier__c</fullName>
        <formula>IF(ISBLANK( IFEC_DSL__c ), Aircraft__r.Name,
IFEC_DSL__r.Aircraft__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link by custom field to the associated aircraft object</inlineHelpText>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked when aircraft has been verified and ready for services to be turned on.</description>
        <label>Aircraft Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Modified_on_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modified on Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines (Deleted on Opportunity)</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_AutoExtend__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoExtend</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Opportunity_Number__c</fullName>
        <description>Using Record Type Name to show RecordType Label with Opportunity Number.</description>
        <formula>IF( ( (RecordType.Name = &#39;PPL&#39; &amp;&amp; ISPICKVAL(PT_PPL_Type__c  , &#39;CR&#39;)|| Change_Request__c = TRUE) ) , &quot;CR-&quot; + L2I_Opportunity_ID__c, RecordType.Name+&quot;-&quot; + L2I_Opportunity_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Amendment</fullName>
        <active>true</active>
        <businessProcess>Amendment Process</businessProcess>
        <label>Cancellation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Fulfillment</fullName>
        <active>true</active>
        <businessProcess>Fulfillment Process</businessProcess>
        <label>Fulfillment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Revise</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>L2I_AutoActivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoActivate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Order_Process__c</fullName>
        <label>Order Process</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Order_Process</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Original_Sales_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Sales Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Revise_Modified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revise Modified</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>L2I_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Order_Process__c</fullName>
        <formula>Text(Order.L2I_Order_Process__c)</formula>
        <label>Order Process</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_ProductName__c</fullName>
        <formula>IF(!ISBLANK(SBQQ__QuoteLine__c), SBQQ__QuoteLine__r.L2I_ProductName_Display__c, Product2.Name)</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Service_Activation_Type__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.L2I_Service_Activation_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Activation Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Start_Date__c</fullName>
        <formula>Order.Opportunity.L2I_Campaign_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>L2I_Sub_Category_2__c</fullName>
        <label>Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_blng_MatchingId__c</fullName>
        
        <externalId>true</externalId>
        <label>Matching ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Service_Activation_Type__c</fullName>
        <label>Service Activation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>OneTime</fullName>
                </value>
                <value>
                    <fullName>Monthly-DR</fullName>
                    <isActive>false</isActive>
                    <label>Monthly-DR</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Sub_Category_2__c</fullName>
        <label>Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/L2I_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <customValue>
        <fullName>Placeholder Products</fullName>
        <isActive>false</isActive>
        <label>Placeholder Products</label>
    </customValue>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

globalValueSets/L2I_Order_Process.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Contract Management</fullName>
    </customValue>
    <customValue>
        <fullName>Shadow</fullName>
    </customValue>
    <customValue>
        <fullName>Program Table</fullName>
    </customValue>
    <customValue>
        <fullName>Advertising Brand</fullName>
    </customValue>
    <masterLabel>Order Process</masterLabel>
</GlobalValueSet>

globalValueSets/L2I_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advertisers/Brands</fullName>
    </customValue>
    <customValue>
        <fullName>Advertising</fullName>
    </customValue>
    <customValue>
        <fullName>Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Cabin</fullName>
    </customValue>
    <customValue>
        <fullName>Connectivity</fullName>
    </customValue>
    <customValue>
        <fullName>DMPES</fullName>
    </customValue>
    <customValue>
        <fullName>eXLite</fullName>
    </customValue>
    <customValue>
        <fullName>Games</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Interactives</fullName>
    </customValue>
    <customValue>
        <fullName>K-Series</fullName>
    </customValue>
    <customValue>
        <fullName>MAPS</fullName>
    </customValue>
    <customValue>
        <fullName>MCS</fullName>
    </customValue>
    <customValue>
        <fullName>Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>NEXT Series</fullName>
    </customValue>
    <customValue>
        <fullName>PRAM</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>TV/Media</fullName>
    </customValue>
    <customValue>
        <fullName>WiFi</fullName>
    </customValue>
    <customValue>
        <fullName>X-Series</fullName>
    </customValue>
    <customValue>
        <fullName>Cell Modem</fullName>
    </customValue>
    <customValue>
        <fullName>eFX</fullName>
    </customValue>
    <customValue>
        <fullName>eX1</fullName>
    </customValue>
    <customValue>
        <fullName>eX1/eXLite</fullName>
    </customValue>
    <customValue>
        <fullName>eX1/eXLite/eXO</fullName>
    </customValue>
    <customValue>
        <fullName>eX2</fullName>
    </customValue>
    <customValue>
        <fullName>eX2/eX3</fullName>
    </customValue>
    <masterLabel>Sub Category 2</masterLabel>
</GlobalValueSet>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_CaseMgmtCROrderDAO.cls
/**
 *      @author       Andy Fang
 *      @date         04/04/2020
 *      @description  L2I_CaseMgmtCROrderDAO
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Andy Fang                    04/04/2020          Initial scaffold
 *      Sarah Kennedy                07/16/2020          US2104 - add query fields for Revise Modify process
 *                                                          Also removed this class from the L2I_CaseMgmtDAO interface class as the
 *                                                          Order query was moved into L2I_CaseMgmtFrom CROrderBatch
 */

//public with sharing class L2I_CaseMgmtCROrderDAO implements L2I_CaseMgmtDAO {
public with sharing class L2I_CaseMgmtCROrderDAO {
    
//    private Set<String> allowedProducts;
//    private Set<String> oppoProductCategories;
    private Set<String> skipFulfillmentCategories;
    
    public L2I_CaseMgmtCROrderDAO() {
//        allowedProducts = L2I_JSON_Settings.getSpecificSettingCollection('Aircraft_Services_Management_Settings',
//              'Allowed Products');
//        oppoProductCategories = L2I_JSON_Settings.getSpecificSettingCollection('Aircraft_Services_Management_Settings',
//              'Product Category');
        skipFulfillmentCategories = L2I_JSON_Settings.getSpecificSettingCollection('Aircraft_Services_Management_Settings',
              'Skip Fulfillment');
        System.debug('*** skipFulfillmentCategories ' + skipFulfillmentCategories);
    }
//
    //DE417 - Adding End date to the query to ensure order isn't expired
    //Updating query to remove date comparison on the Order level, due to a recursive trigger error

//    public List<Order> getOrderRecords(List<Id> quoteId, List<Id> dslList) {
//        List<Order> orderList = [
//              SELECT Id,
//                    L2I_Original_Sales_Opportunity__c,
//                    L2I_Original_Sales_Opportunity__r.L2I_Opportunity_Number__c,
//                    OpportunityId,
//                    L2I_Product_Category_2__c,
//                    AccountId,
//                    L2I_Revise_Modified__c,
//                    Opportunity.L2I_AutoExtend__c,
//                    Type,
//                    L2I_Order_Process__c,
//                    Opportunity.L2I_Opportunity_Number__c, (select Id from OrderItems where EndDate >= Today)
//              FROM Order
//              WHERE L2I_Product_Category_2__c IN:allowedProducts
//              AND Opportunity.SBQQ__PrimaryQuote__r.SBQQ__Ordered__c = true AND
//              Opportunity.L2I_Product_Category__c IN:oppoProductCategories AND Order.SBQQ__Quote__c IN:quoteId
//        ];
//        List<Order> finalOrderList = new List<Order>();
//
//        for (Order o : orderList) {
//            if (o.OrderItems.size() > 0) {
//                finalOrderList.add(o);
//            }
//        }
//
//        return finalOrderList;
//    }
    
    public List<L2I_DSL__c> getDSLRecords(Set<Id> quoteIds) {
        System.debug('*** L2I_CaseMgmtCROrderDAO.getDSLRecords ' + quoteIds);
        
        List<L2I_DSL__c> dslList = [
              SELECT Id, Aircraft__c, Aircraft__r.Name, Aircraft_Identifier__c, Modified_on_Opportunity__c,
                    Status__c, Original_Opportunity__c
              FROM L2I_DSL__c
              WHERE L2I_Aircraft_Confirmation__c = true
              AND Delivery_Schedule_Header__c IN (
                    SELECT L2I_Delivery_Schedule__c
                    FROM Opportunity
                    WHERE SBQQ__PrimaryQuote__c IN:quoteIds
              )
        ];
        
        //patching IFE records
        Map<String, Id> ACNameIDMap = new Map<String, Id>();
        Set<String> ACNameSets = new Set<String>();
        
        for (L2I_DSL__c dsl : dslList) {
            if (dsl.Aircraft__c == null && dsl.Aircraft_Identifier__c != null) {
                ACNameSets.add(dsl.Aircraft_Identifier__c);
            }
        }
        
        if (ACNameSets.size() > 0) {
            List<L2I_Aircraft__c> acInfo = [SELECT Id, Name from L2I_Aircraft__c WHERE Name IN:ACNameSets];
            for (L2I_Aircraft__c ac : acInfo) {
                ACNameIDMap.put(ac.Name, ac.Id);
            }
        }
        
        for (L2I_DSL__c dsl : dslList) {
            if (dsl.Aircraft__c == null && dsl.Aircraft_Identifier__c != null) {
                dsl.Aircraft__c = ACNameIDMap.get(dsl.Aircraft_Identifier__c);
            }
        }
        
        return dslList;
    }
    
    public List<Case> getExistingCaseByDSL(Set<Id> orderIdSets, Set<Id> acIdSets, Set<Id> dslIdSets) {
        System.debug('*** L2I_CaseMgmtCROrderDAO.getExistingCaseByDSL ' + orderIdSets + ' ' + acIdSets + ' ' + dslIdSets);
        List<Case> existingCase = [
              SELECT Id
              FROM Case
              where
              L2I_Order__c IN:orderIdSets AND
              L2I_Aircraft__c IN:acIdSets AND
              L2I_Delivery_Schedule_Line__c IN:dslIdSets
        ];
        
        return existingCase;
    }
    
//    public List<OrderItem> getOrderItemByOrderId(Set<Id> OrderId) {
//        System.debug('*** L2I_CaseMgmtCROrderDAO.getOrderItemByOrderId ' + OrderId);
//              // will clean with minium data
//        List<OrderItem> orderItemList = [
//              SELECT Order.OpportunityId, L2I_Category__c, Id, Product2Id, L2I_ProductName__c, Quantity,
//                    L2I_Sub_Category_2__c, SBQQ__Subscription__c, OrderId, PricebookEntry.Product2.L2I_Service_Activation_Type__c,
//                    SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Type__c, L2I_Start_Date__c, ServiceDate, EndDate,
//                    Order.L2I_Original_Sales_Opportunity__c, L2I_blng_MatchingId__c, SBQQ__QuoteLine__c,
//                    Order.L2I_Original_Sales_Opportunity__r.L2I_Opportunity_Number__c
//              FROM Orderitem
//              WHERE Order.L2I_Product_Category_2__c IN:allowedProducts
//              AND Order.Opportunity.SBQQ__PrimaryQuote__r.SBQQ__Ordered__c = true AND EndDate >= TODAY AND
//              Order.Opportunity.L2I_Product_Category__c IN:oppoProductCategories AND
//              (SBQQ__TerminatedDate__c = null OR SBQQ__TerminatedDate__c >= TODAY) AND
//              PricebookEntry.Product2.L2I_Service_Activation_Type__c != null and OrderId IN:OrderId
//        ];
//
//        return orderItemList;
//        return null;
//    }
    
    public Set<Id> CreateCases(List<L2I_DSL__c> dslList, List<Order> orderList, Set<String> uniqueCaseSet) {
        System.debug('*** CaseMgmtCROrderDao create cases');
        Set<Id> newCaseIds = new Set<Id>();
        List<Case> newCaseList = new List<Case>();
        Map<Id, Order> skipFulfillmentOrderMap = new Map<Id, Order>();
        String caseProcess = '';
        
        for (L2I_DSL__c dslRecord : dslList) {
            
            for (Order orderRecord : orderList) {
                System.debug('*** orderRecord ' + orderRecord);
                caseProcess = getCaseProcess(orderRecord, dslRecord);
                if (caseProcess == 'Skip'){
                    orderRecord.L2I_AutoActivate__c = true;
                    skipFulfillmentOrderMap.put(orderRecord.Id, orderRecord);
                }
                String uniqueKey = orderRecord.Id + '' + dslRecord.Aircraft__c + '' + dslRecord.Id;
                System.debug('*** uniqueKey ' + uniqueKey);
                
                //Only add cases if it's unique based on the unique key above
                if (!uniqueCaseSet.contains(uniqueKey) && caseProcess != '' && caseProcess != 'Skip') {
                    Case acCase = new Case();
                    acCase.L2I_Aircraft__c = dslRecord.Aircraft__c;
                    acCase.L2I_Original_Sales_Opportunity__c = orderRecord.L2I_Original_Sales_Opportunity__c;
                    acCase.L2I_Opportunity__c = orderRecord.OpportunityId;
                    acCase.L2I_Product_Category_2__c = orderRecord.L2I_Product_Category_2__c;
                    acCase.L2I_Order__c = orderRecord.Id;
                    acCase.L2I_Delivery_Schedule_Line__c = dslRecord.Id;
                    acCase.AccountId = orderRecord.AccountId;
                    acCase.Origin = 'CPQ Order';
                    acCase.L2I_Routing_Path__c = 'Order';
                    List<String> parameters = new List<String>();
                    if (dslRecord.Aircraft__r.Name != null) {
                        parameters.add(dslRecord.Aircraft__r.Name);
                    }
                    if (dslRecord.Aircraft__r.Name == null && dslRecord.Aircraft_Identifier__c != null) {
                        parameters.add(dslRecord.Aircraft_Identifier__c);
                    }
                    parameters.add(orderRecord.L2I_Product_Category_2__c);
                    parameters.add(orderRecord.L2I_Original_Sales_Opportunity__r.L2I_Opportunity_Number__c);
                    
                    acCase.Subject = String.format(Label.L2I_Case_Subject, parameters);
                    acCase.L2I_Case_Process__c = caseProcess;
                    
                    newCaseList.add(acCase);
                    
                    // set AutoActivate for Orders with a SkipFulfillment product
                    System.debug('*** checking for skip ' + orderRecord.L2I_Product_Category_2__c.toLowerCase());
                    if (skipFulfillmentCategories.contains(orderRecord.L2I_Product_Category_2__c.toLowerCase()) &&
                          orderRecord.Type == 'Renewal'){
                        System.debug('*** found skip match');
                        orderRecord.L2I_AutoActivate__c = true;
                        skipFulfillmentOrderMap.put(orderRecord.Id, orderRecord);
                    }
                }
            }
        }
        System.debug('*** skipFulfillmentOrderMap.size() ' + skipFulfillmentOrderMap.size());
        if (!skipFulfillmentOrderMap.isEmpty()){
            Database.SaveResult[] skipSR = Database.update(skipFulfillmentOrderMap.values(), false);
            for (Database.SaveResult sr : skipSR) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully updated AutoActivate on Order: ' + sr.getId());
                } else {
                    // Operation failed, so get all errors
                    for (Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred updating AutoActivate on Order: ' + err.getStatusCode() + ': ' + err.getMessage());
                    }
                }
            }
        }
        
        if (newCaseList.size() > 0) {
            Database.SaveResult[] caseSR = Database.insert(newCaseList, false);
            for (Case c : newCaseList) {
                newCaseIds.add(c.Id);
            }
        }
        return newCaseIds;
    }
    
    private String getCaseProcess(Order orderRecord, L2I_DSL__c dslRecord) {
        System.debug('*** orderRecord ' + orderRecord);
        System.debug('*** dslRecord ' + dslRecord);
        String caseProcess = '';
        if (orderRecord.Type == 'New') {     // Sales
            caseProcess = 'New';
        } else if (orderRecord.Type == 'Amendment') {
            caseProcess = 'Cancel';
        } else {        // Renewal/Revise
            System.debug('*** Revise Order Type');
            if (dslRecord.Status__c == NULL ||
                  (dslRecord.Status__c == 'Deactivate' &&
                        dslRecord.Modified_on_Opportunity__c == orderRecord.OpportunityId)) {
                if (dslRecord.Status__c == 'Deactivate'){
                    caseProcess = 'Cancel';
                } else {
                    System.debug('*** dslRecord.Original_Opportunity__c ' + dslRecord.Original_Opportunity__c);
                    if (dslRecord.Original_Opportunity__c == orderRecord.OpportunityId){
                        caseProcess = 'New';
                    } else {
                        System.debug('*** Revise Modified ' + orderRecord.L2I_Revise_Modified__c);
                        if (orderRecord.L2I_Revise_Modified__c){
                            caseProcess = 'Revise';
                        } else {
                            System.debug('*** not new, cancel, revise - check for skip ');
                            System.debug('*** orderRecord.L2I_Product_Category_2__c ' + orderRecord.L2I_Product_Category_2__c.toLowerCase());
                            System.debug('*** skipFulfillmentCategories ' + skipFulfillmentCategories);
                            if (skipFulfillmentCategories.contains(orderRecord.L2I_Product_Category_2__c.toLowerCase())){
                                caseProcess = 'Skip';
                            }
                        }
                    }
                }
            } else {
                System.debug('*** not rcds ');
                System.debug('*** orderRecord.L2I_Product_Category_2__c ' + orderRecord.L2I_Product_Category_2__c.toLowerCase());
                System.debug('*** skipFulfillmentCategories ' + skipFulfillmentCategories);
                if (skipFulfillmentCategories.contains(orderRecord.L2I_Product_Category_2__c.toLowerCase())){
                    caseProcess = 'Skip';
                }
            }
        }
        System.debug('*** caseProcess ' + caseProcess);
        return caseProcess;
    }

}