objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule Line</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link by custom field to the associated aircraft object</inlineHelpText>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/L2I_CaseMgmtFromDSLController.cls
/**
 *      @author       Andy Fang
 *      @date         03/17/2020
 *      @description  L2I_CaseMgmtFromDSLController
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Andy Fang                    03/17/2020         Initial scaffold
 *      Sarah Kennedy                06/10/2020         US1979 changed getOrderRecords to accept List<L2I_DSL__c> instead of List<Id>
 */
global class L2I_CaseMgmtFromDSLController {
    
    // A platform builder will be calling this function
    // The purpose of this cass is to create the case with the associated information for the batch class
    // to process.  The L2I_Related_Order_Item__c fields will contains information for the batch class
    // without running the query once again and it can be used as a validation for troubleshooting.
    
//    @InvocableMethod
//    global static void autoCreateAircraftServices(List<Id> dslIdList) {
//        System.debug('*** L2I_CaseMgmtFromDSLController dslIdList ' + dslIdList.size() + ' ' + dslIdList);
//        Set<Id> newCaseIds = new Set<Id>();
//        L2I_CaseMgmtDSLDAO dsldao = new L2I_CaseMgmtDSLDAO();
//        try {
//            // This process support only aircraft at a time
//            List<L2I_DSL__c> dsLineList = new List<L2I_DSL__c>();
//            dsLineList = dsldao.getDSLRecords(null, dslIdList);
//
//            if (dsLineList.size() > 0) {
//                List<Id> dshList = new List<Id>();
//                Set<Id> acIdSets = new Set<Id>();
//                Set<Id> dslIdSets = new Set<Id>();
//
//                //This is a default delivery scheduler header for aircrafts
//                for (L2I_DSL__c dsl : dsLineList) {
//                    dshList.add(dsl.Delivery_Schedule_Header__c);
//                    acIdSets.add(dsl.Aircraft__c);
//                    dslIdSets.add(dsl.Id);
//                }
//
//                List<Order> orderList = dsldao.getOrderRecords(null, dshList);
//
//                List<Case> existingCase = new List<Case>();
//                existingCase = dsldao.getExistingCaseByDSL(null, acIdSets, dslIdSets);
//
//                Set<String> uniqueCaseSet = New Set<String>();
//
//                //Check only if there is available data to compare with
//                if (existingCase.size() > 0) {
//                    for (case c : existingCase) {
//                        system.debug('Existing is : ' + c.L2I_Aircraft__c + '' + c.L2I_Delivery_Schedule_Line__c);
//                        uniqueCaseSet.add(c.L2I_Aircraft__c + '' + c.L2I_Delivery_Schedule_Line__c);
//                    }
//                }
//
//                if (dshList.size() > 0) {
//                    newCaseIds = dsldao.CreateCases(dsLineList, orderList, uniqueCaseSet);
//                }
//            }
//        } catch (Exception ex) {
//            System.debug('L2I_CaseMgmtFromDSLController has an issue : ' + ex.getMessage());
//        }
//    }

}