objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Allow_To_Reprocess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow To Reprocess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (Opportunity Lookup to Opportunity)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Related_Order__c</fullName>
        <label>xxRelated Order</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Service__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxAircraft Order</label>
        <referenceTo>L2I_Aircraft_Order__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Matching_Id__c</fullName>
        <label>Matching Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxOrder Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Aircraft Service</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Aircraft Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_ASA__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>No Action</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Aircraft_Order__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Aircraft Service Actions</relationshipLabel>
        <relationshipName>Aircraft_Service_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Aircraft_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Service</label>
        <referenceTo>L2I_Aircraft_Service__c</referenceTo>
        <relationshipLabel>Aircraft Service Actions</relationshipLabel>
        <relationshipName>Aircraft_Service_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matching_Id__c</fullName>
        <formula>Aircraft_Service__r.Matching_Id__c</formula>
        <label>Matching Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Aircraft Service Actions</relationshipLabel>
        <relationshipName>Aircraft_Service_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Aircraft Service Action</label>
    <nameField>
        <label>Aircraft Service Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Service Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Sub_Category_2__c</fullName>
        <label>Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_blng_MatchingId__c</fullName>
        
        <externalId>true</externalId>
        <label>Matching ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/L2I_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advertisers/Brands</fullName>
    </customValue>
    <customValue>
        <fullName>Advertising</fullName>
    </customValue>
    <customValue>
        <fullName>Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Cabin</fullName>
    </customValue>
    <customValue>
        <fullName>Connectivity</fullName>
    </customValue>
    <customValue>
        <fullName>DMPES</fullName>
    </customValue>
    <customValue>
        <fullName>eXLite</fullName>
    </customValue>
    <customValue>
        <fullName>Games</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Interactives</fullName>
    </customValue>
    <customValue>
        <fullName>K-Series</fullName>
    </customValue>
    <customValue>
        <fullName>MAPS</fullName>
    </customValue>
    <customValue>
        <fullName>MCS</fullName>
    </customValue>
    <customValue>
        <fullName>Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>NEXT Series</fullName>
    </customValue>
    <customValue>
        <fullName>PRAM</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>TV/Media</fullName>
    </customValue>
    <customValue>
        <fullName>WiFi</fullName>
    </customValue>
    <customValue>
        <fullName>X-Series</fullName>
    </customValue>
    <customValue>
        <fullName>Cell Modem</fullName>
    </customValue>
    <customValue>
        <fullName>eFX</fullName>
    </customValue>
    <customValue>
        <fullName>eX1</fullName>
    </customValue>
    <customValue>
        <fullName>eX1/eXLite</fullName>
    </customValue>
    <customValue>
        <fullName>eX1/eXLite/eXO</fullName>
    </customValue>
    <customValue>
        <fullName>eX2</fullName>
    </customValue>
    <customValue>
        <fullName>eX2/eX3</fullName>
    </customValue>
    <masterLabel>Sub Category 2</masterLabel>
</GlobalValueSet>

classes/L2I_CM_FromDSL_Batch.cls
/**
 *      @author       Andy Fang
 *      @date         03/17/2020
 *      @description  L2I_CM_FromDSL_Batch
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Andy Fang                    03/17/2020         Initial scaffold
 */
    // This batch gets call from L2I_CaseMgmtFromDSLController
    // It creates Aircraft Service Action
    // Then it creates Aircraft Service record
    // Then it update Aircraft Service Action record with the associated Aircraft service
global class L2I_CM_FromDSL_Batch{
//    global class L2I_CM_FromDSL_Batch implements Database.Batchable<sObject>, Database.Stateful {

//        private Set<Id> caseIdSets;
//        private Boolean hasError;
//
//        public L2I_CM_FromDSL_Batch( Set<Id> caseIdSetsParam ){
//            caseIdSets = caseIdSetsParam;
//        }
//
//        global Database.QueryLocator start(Database.BatchableContext bc) {
//            return Database.getQueryLocator(
//                    'SELECT Id, L2I_Aircraft__c, L2I_Opportunity__r.L2I_Delivery_Schedule__c, ' +
//                            ' L2I_Product_Category_2__c FROM Case WHERE Id in: caseIdSets'
//            );
//
//        }
//
//        global void execute(Database.BatchableContext bc, List<Case> scope) {
//
//            hasError = false;
//            Savepoint sp = Database.setSavepoint();
//
//            try {
//
//                L2I_CaseMgmtDSLDAO dslDAO = new L2I_CaseMgmtDSLDAO();
//                Map<String, Set<Id>> ACDSLOrderIDMap = new Map<String, Set<Id>>();
//                Set<Id> OrderIdSet = New Set<Id>();
//                Set<Id> aircraftIds = new Set<Id>();
//                Set<String> matchingIdSet = new Set<String>();
//                List<L2I_ASA__c> newASARecords = new List<L2I_ASA__c>();
//
//                for ( Case c : scope ){
//                    aircraftIds.add( c.L2I_Aircraft__c );
//                    String key = c.L2I_Aircraft__c + '' + c.L2I_Opportunity__r.L2I_Delivery_Schedule__c;
////                    Set<Id> temp = (Set<Id>)Json.deserialize( c.L2I_Related_Order__c, Set<Id>.class );
////                    ACDSLOrderIDMap.put( key, temp );
////                    OrderIdSet.addAll( temp );
//                }
//
//                List<OrderItem> orderItemList = dslDAO.getOrderItemByOrderId( OrderIdSet );
//
//                Map<Id, Set<Id>> orderIdOrderItemsMap = new Map<Id, Set<Id>>();
//
//                //This variable is to use for calculation for Order to order item mapping
//                Map<String, Set<Id>> categoryOrderItemsMap = new Map<String, Set<Id>>();
//                Set<String> categorySet = new Set<String>();
//                Map<Id, Id> ExistingProd2IdOrderItemIdMap = new Map<Id, Id>();
//                Map<Id, Orderitem> oiProductMap = new Map<Id, Orderitem>();
//
//                for( OrderItem oi : orderItemList ){
//                    if ( categorySet.contains( oi.L2I_Sub_Category_2__c ) ){
//                        Set<Id> caseSet = categoryOrderItemsMap.get( oi.L2I_Sub_Category_2__c );
//                        if ( oi.Quantity >= 1 ) {
//                            caseSet.add(oi.Id);
//                            ExistingProd2IdOrderItemIdMap.put( oi.Product2Id, oi.Id );
//                        }
//                        if ( oi.Quantity <= -1 ) {
//                            caseSet.remove( ExistingProd2IdOrderItemIdMap.get(oi.Product2Id) );
//                        }
//                        categoryOrderItemsMap.put( oi.L2I_Sub_Category_2__c, caseSet );
//                    } else {
//                        categorySet.add( oi.L2I_Sub_Category_2__c );
//                        Set<Id> caseSet = new Set<Id>();
//                        caseSet.add( oi.Id );
//                        categoryOrderItemsMap.put( oi.L2I_Sub_Category_2__c, caseSet );
//                    }
//                    oiProductMap.put(oi.Id, oi);
//                    matchingIdSet.add(oi.L2I_blng_MatchingId__c);
//                }
//
//                //Existing AS record
//                List<L2I_Aircraft_Service__c> existingASRecords = [
//                        SELECT Id, Matching_Id__c, Aircraft__c
//                        FROM L2I_Aircraft_Service__c
//                        WHERE Aircraft__c IN:aircraftIds AND Matching_Id__c IN:matchingIdSet
//                ];
//
//                Map<String, Id> existingASMap = new Map<String, Id>();
//
//                for (L2I_Aircraft_Service__c asTemp : existingASRecords) {
//                    existingASMap.put(asTemp.Aircraft__c + '' + asTemp.Matching_Id__c, asTemp.Id);
//                }
//
//                //Create AS record
//                List<L2I_Aircraft_Service__c> newASRecords = new List<L2I_Aircraft_Service__c>();
//                Set<Id> existingIdSet = new Set<Id>();
//
//                for (Case c : scope) {
//
//                    Set<Id> temp = categoryOrderItemsMap.get( c.L2I_Product_Category_2__c );
//
//                    for (String oiId : temp) {
//                        String key = c.L2I_Aircraft__c + '' + oiProductMap.get(oiId).L2I_blng_MatchingId__c;
//                        if (existingASMap.get(key) == null) {
//                            L2I_Aircraft_Service__c newAS = new L2I_Aircraft_Service__c();
//                            newAS.Aircraft__c = c.L2I_Aircraft__c;
//                            newAS.Matching_Id__c = oiProductMap.get(oiId).L2I_blng_MatchingId__c;
//                            newAS.Product2__c = oiProductMap.get(oiId).Product2Id;
//                            newAS.Status__c = 'Pending Activation';
//                            newASRecords.add(newAS);
//                        } else {
//                            existingIdSet.add(existingASMap.get(key));
//                        }
//                    }
//                }
//
//                Database.SaveResult[] srList = Database.insert(newASRecords, false);
//                Set<Id> UpdatedId = new Set<Id>();
//
//                for (Database.SaveResult sr : srList) {
//                    if (sr.isSuccess()) {
//                        UpdatedId.add(sr.getId());
//                    }
//                }
//
//                //Update ASA with AS ID
//                UpdatedId.addAll(existingIdSet);
//
//                // Being of Req 06
//                Set<String> as_Filter =
//                        L2I_JSON_Settings.getSpecificSettingCollection('Aircraft_Services_Management_Settings',
//                                'AS Filter');
//
//                List<L2I_Aircraft_Service__c> oldASRecords = [
//                        SELECT Id, Matching_Id__c, Status__c, Aircraft__c
//                        FROM L2I_Aircraft_Service__c
//                        WHERE id IN:UpdatedId AND Status__c NOT IN: as_Filter
//                ];
//                // End of Req 06
//
//                Map<String, L2I_Aircraft_Service__c> MatchingIdASMap = new Map<String, L2I_Aircraft_Service__c>();
//
//                for ( L2I_Aircraft_Service__c asRecord : oldASRecords ){
//                    MatchingIdASMap.put( asRecord.Aircraft__c+''+asRecord.Matching_Id__c, asRecord );
//                }
//
//                for (Case c : scope) {
//
//                    Set<Id> temp = categoryOrderItemsMap.get( c.L2I_Product_Category_2__c );
//
//                    for (Id oi : temp) {
//                        if ( MatchingIdASMap.get( c.L2I_Aircraft__c +''+ oiProductMap.get(oi).L2I_blng_MatchingId__c ) != null ) {
//
//                            L2I_ASA__c newASA = new L2I_ASA__c();
//                            newASA.Order_Product__c = oi;
//                            newASA.Aircraft_Order__c = c.Id;
//                            newASA.Aircraft_Service__c = MatchingIdASMap.get(c.L2I_Aircraft__c +''+ oiProductMap.get(oi).L2I_blng_MatchingId__c).Id;
//                            newASA.Action__c = 'Activate';
//
//                            newASARecords.add(newASA);
//                        }
//                    }
//                }
//
//                Database.SaveResult[] asaList = Database.insert(newASARecords, false);
//
//                for (Case c : scope) {
//                    c.L2I_Allow_To_Reprocess__c = false;
//                }
//                update scope;
//
//            } catch ( Exception ex ){
//                Database.rollback( sp );
//                hasError = true;
//                for (Case c : scope) {
//                    c.L2I_Allow_To_Reprocess__c = true;
//                }
//                update scope;
//                system.debug( ex.getLineNumber() + ' ' + ex.getMessage() );
//            }
//        }
//
//        global void finish(Database.BatchableContext bc) {
//            if ( !hasError ){
//                if ( caseIdSets.size() > 0 ){
//                    L2I_UtilityHelper.createPlatformEvent( caseIdSets );
//                }
//            }
//        }

    }