objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Case_Process__c</fullName>
        <label>Case Process</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Revise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule Line</label>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases (Opportunity Lookup to Opportunity)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Original_Sales_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Sales Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.Opportunity_Recordtype_Name__c</field>
                <operation>equals</operation>
                <value>Sales</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <formula>L2I_Order__r.L2I_Product_Category_2__c</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Routing_Path__c</fullName>
        <label>Routing Path</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DSL</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Identifier__c</fullName>
        <formula>IF(ISBLANK( IFEC_DSL__c ), Aircraft__r.Name,
IFEC_DSL__r.Aircraft__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Identifier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link by custom field to the associated aircraft object</inlineHelpText>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked when aircraft has been verified and ready for services to be turned on.</description>
        <label>Aircraft Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT(Delivery_Schedule_Header__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Opportunity_Number__c</fullName>
        <description>Using Record Type Name to show RecordType Label with Opportunity Number.</description>
        <formula>IF( ( (RecordType.Name = &#39;PPL&#39; &amp;&amp; ISPICKVAL(PT_PPL_Type__c  , &#39;CR&#39;)|| Change_Request__c = TRUE) ) , &quot;CR-&quot; + L2I_Opportunity_ID__c, RecordType.Name+&quot;-&quot; + L2I_Opportunity_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Original Opportunity)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Quote_Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quote Ordered</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Revise</label>
    </recordTypes>
    <recordTypes>
        <fullName>Replace</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Replace</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Original_Sales_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Sales Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Service_Activation_Types__c</fullName>
        <label>Service Activation Types</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Terminated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Terminated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_DSLService.cls
/**
 *      @author       Sarah Kennedy
 *      @date         02/18/2020
 *      @description  Service class for DSL object
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Sarah Kennedy                 06/05/2020         Initial creation
 *      Sarah Kennedy                 02/03 20201        replace filter for L2I_Product_Category_2__c with L2I_Service_Activation_Type__c
 *
 */
public with sharing class L2I_DSLService {
    
    public static List<L2I_DSL__c> pruneDSLList(List<L2I_DSL__c> dslList, Id currentOpptyId) {
        // return the list of DSLs that we want to display
        List<L2I_DSL__c> dslsToReturnList = new List<L2I_DSL__c>();
        
        // select the DSLs to display
        for (L2I_DSL__c dsl : dslList) {
//            System.debug('*** currentOpptyId ' + currentOpptyId);
//            System.debug('*** prune dsl prodcat ' + dsl.Delivery_Schedule_Header__r.Product_Category__c);
//            System.debug('*** prune dsl Original_Opportunity__c ' + dsl.Original_Opportunity__c);
//            if (dsl.Delivery_Schedule_Header__r.Product_Category__c == 'DSS' ||
//                  dsl.Delivery_Schedule_Header__r.Product_Category__c == 'PTS') {
////                if (dsl.Original_Opportunity__c == currentOpptyId) {
//                    dslsToReturnList.add(dsl);
//                } else {
//                    if (dsl.Original_Opportunity__r.StageName == 'Pending Close' ||
//                          dsl.Original_Opportunity__r.StageName == 'Closed Won') {
//                        dslsToReturnList.add(dsl);
//                    }
//                }
//            } else {
//                dslsToReturnList.add(dsl);
//            }
            dslsToReturnList.add(dsl);    //Show all DSLs (US2020)
        }
        return dslsToReturnList;
    }
    
    public static Set<Id> countCases4DSLAircraft(Map<Id, Id> dslAircraftMap) {
        // return any DSLs that have any Cases created
        System.debug('*** dslAircraftMap ' + dslAircraftMap);
        Set<Id> dslIds = new Set<Id>();
        AggregateResult [] results = [
              SELECT COUNT(Id), L2I_Aircraft__c, L2I_Delivery_Schedule_Line__c
              FROM Case
              WHERE L2I_Delivery_Schedule_Line__c IN :dslAircraftMap.keySet()
              AND L2I_Aircraft__c IN :dslAircraftMap.values()
              GROUP BY L2I_Delivery_Schedule_Line__c, L2I_Aircraft__c
              HAVING COUNT(Id) > 0
        ];
        for (AggregateResult ar : results) {
            dslIds.add((Id)ar.get('L2I_Delivery_Schedule_Line__c'));
        }
        return dslIds;
    }
    
    public static void createCasesFromDSLs(List<L2I_DSL__c> newDSLList, Map<Id, L2I_DSL__c> newDSLMap, Map<Id, L2I_DSL__c> oldDSLMap) {
        System.debug('*** L2I_DSLService - createCasesFromDSLs');
        Set<Id> dslIds = new Set<Id>();
        Set<Id> newCaseIds = new Set<Id>();
        Map<Id, List<Order>> origSalesOppOrderMap = new Map<Id, List<Order>>();
        // get confirmed DSLs
        for (L2I_DSL__c dsl : newDSLList) {
            L2I_DSL__c oldDSL = oldDSLMap.get(dsl.Id);
            L2I_DSL__c newDSL = newDSLMap.get(dsl.Id);
            
            if (newDSL.L2I_Aircraft_Confirmation__c == true &&
                  newDSL.L2I_Aircraft_Confirmation__c != oldDSL.L2I_Aircraft_Confirmation__c) {
                dslIds.add(dsl.Id);
            }
        }
        // get DSL details
        List<L2I_DSL__c> dsLineList = new List<L2I_DSL__c>();
        dsLineList = getDSLRecords(dslIds);
        
        if (dsLineList.size() > 0) {
            Set<Id> dshList = new Set<Id>();
            Set<Id> dslIdSets = new Set<Id>();
            
            for (L2I_DSL__c dsl : dsLineList) {
                dshList.add(dsl.Delivery_Schedule_Header__c);
                dslIdSets.add(dsl.Id);
            }
            // get the Order details
            if (dshList.size() > 0) {
                origSalesOppOrderMap = getOrderRecords(dshList);
            }
            
            if (dshList.size() > 0) {
                newCaseIds = createCases(dsLineList, origSalesOppOrderMap);
            }
        }
    
    }
    
    private static List<L2I_DSL__c> getDSLRecords(Set<Id> dslIds) {
        List<L2I_DSL__c> dslList = [
              SELECT Aircraft__c, Aircraft__r.Name, Delivery_Schedule_Header__c,
                    Aircraft_Identifier__c, Original_Opportunity__c,
                    Original_Opportunity__r.L2I_Original_Opportunity__c,
                    Original_Opportunity__r.L2I_Quote_Ordered__c
              FROM L2I_DSL__c
              WHERE Id IN:dslIds
              AND L2I_Aircraft_Confirmation__c = true
              AND Original_Opportunity__r.L2I_Quote_Ordered__c = true
        
        ];
        
        //get IFEC aircraft
        Map<String, Id> ACNameIDMap = new Map<String, Id>();
        Set<String> ACNameSets = new Set<String>();
        
        for (L2I_DSL__c dsl : dslList) {
            if (dsl.Aircraft__c == null && dsl.Aircraft_Identifier__c != null) {
                ACNameSets.add(dsl.Aircraft_Identifier__c);
            }
        }
        
        if (ACNameSets.size() > 0) {
            List<L2I_Aircraft__c> acInfo = [SELECT Id, Name from L2I_Aircraft__c WHERE Name IN:ACNameSets];
            for (L2I_Aircraft__c ac : acInfo) {
                ACNameIDMap.put(ac.Name, ac.Id);
            }
        }
        
        for (L2I_DSL__c dsl : dslList) {
            if (dsl.Aircraft__c == null && dsl.Aircraft_Identifier__c != null) {
                dsl.Aircraft__c = ACNameIDMap.get(dsl.Aircraft_Identifier__c);
            }
            System.debug('*** dsl ' + dsl);
        }
        System.debug('*** getDSLRecords dslList ' + dslList.size());
        
        return dslList;
    }
    
    private static Map<Id, List<Order>> getOrderRecords(Set<Id> dshIds) {
//        Set<String> allowedProducts;
        Set<String> oppoProductCategories;
        Map<Id, List<Order>> origSalesOppOrderMap = new Map<Id, List<Order>>();
        Map<Id, Map<DateTime, Id>> origSalesDateOpp = new Map<Id, Map<DateTime, Id>>();
        Map<Id, DateTime> origSalesDate = new Map<Id, DateTime>();
        Map<Id, Id> origSalesOppId = new Map<Id, Id>();
        List<Order> newRenewOrderList = new List<Order>();
        
//        allowedProducts = L2I_JSON_Settings.getSpecificSettingCollection('Aircraft_Services_Management_Settings',
//              'Allowed Products');
        oppoProductCategories = L2I_JSON_Settings.getSpecificSettingCollection('Aircraft_Services_Management_Settings',
              'Product Category');
        
        List<Order> orderList = new List<Order>();


        orderList = [
              SELECT Id,
                    L2I_Original_Sales_Opportunity__c, Type,
                    L2I_Original_Sales_Opportunity__r.L2I_Opportunity_Number__c,
                    OpportunityId,
                    Opportunity.CreatedDate,
                    L2I_Product_Category_2__c,
                    AccountId, (select Id from OrderItems where EndDate >= Today)
              FROM Order
              WHERE L2I_Terminated__c = false
              AND Opportunity.L2I_Delivery_Schedule__c IN:dshIds
              AND Type IN ('New', 'Renewal')
              AND L2I_Service_Activation_Types__c != NULL
              AND L2I_Service_Activation_Types__c != ''
              AND Opportunity.SBQQ__PrimaryQuote__r.SBQQ__Ordered__c = true
              AND Opportunity.L2I_Product_Category__c IN:oppoProductCategories
        ];
        // get the latest opp for each origSalesOpp based on the opp createdDate
        for (Order o : orderList) {
            System.debug('*** o ' + o);
            if (!origSalesDateOpp.containsKey(o.L2I_Original_Sales_Opportunity__c)) {
                origSalesDate.put(o.L2I_Original_Sales_Opportunity__c, o.Opportunity.CreatedDate);
                origSalesOppId.put(o.L2I_Original_Sales_Opportunity__c, o.OpportunityId);
            }
            if (o.Opportunity.CreatedDate > origSalesDate.get(o.L2I_Original_Sales_Opportunity__c)) {
                origSalesDate.put(o.L2I_Original_Sales_Opportunity__c, o.Opportunity.CreatedDate);
                origSalesOppId.put(o.L2I_Original_Sales_Opportunity__c, o.OpportunityId);
            }
        }
        
        System.debug('*** origSalesDate ' + origSalesDate);
        System.debug('*** origSalesOppId ' + origSalesOppId);
        // get orders for only the latest Opp for each origSalesOpp
        for (Order o : orderList) {
            List<Order> ordList = new List<Order>();
            // only get the latest orders for each origSalesOpp
            System.debug('*** o.L2I_Original_Sales_Opportunity__c ' + o.L2I_Original_Sales_Opportunity__c);
            System.debug('*** o.OpportunityId ' + o.OpportunityId);
            // find the latest Opp for the orig Sales Opp - and get those orders
            if (origSalesOppId.containsKey(o.L2I_Original_Sales_Opportunity__c) &&
                  origSalesOppId.get(o.L2I_Original_Sales_Opportunity__c) == o.OpportunityId) {
                System.debug('*** adding order ' + o);
                if (!origSalesOppOrderMap.containsKey(o.L2I_Original_Sales_Opportunity__c)) {
                    origSalesOppOrderMap.put(o.L2I_Original_Sales_Opportunity__c, new List<Order>());
                }
                ordList = origSalesOppOrderMap.get(o.L2I_Original_Sales_Opportunity__c);
                ordList.add(o);
                origSalesOppOrderMap.put(o.L2I_Original_Sales_Opportunity__c, ordList);
            }
        }
        
        System.debug('*** getOrders origSalesOppOrderMap size ' + origSalesOppOrderMap.size());
        
        return origSalesOppOrderMap;
    }
    
    private static Set<Id> CreateCases(List<L2I_DSL__c> dslList, Map<Id, List<Order>> origSalesOppOrderMap) {
        System.debug('*** createCases ');
        Set<Id> newCaseIds = new Set<Id>();
        List<Case> newCaseList = new List<Case>();
        
        for (L2I_DSL__c dsl : dslList) {
            Id origSalesOpp;
            if (dsl.Original_Opportunity__c != NULL) {
                if (dsl.Original_Opportunity__r.L2I_Original_Opportunity__c == NULL) {
                    // for Sales
                    origSalesOpp = dsl.Original_Opportunity__c;
                } else {
                    // for Revise
                    origSalesOpp = dsl.Original_Opportunity__r.L2I_Original_Opportunity__c;
                
                }
            }
            System.debug('*** origSalesOpp ' + origSalesOpp);
            List<Order> orderList = new List<Order>();
            if (origSalesOppOrderMap.containsKey(origSalesOpp)) {
                orderList = origSalesOppOrderMap.get(origSalesOpp);
                
                for (Order o : orderList) {
                    System.debug('*** create cases o ' + o);
                    Case acCase = new Case();
                    acCase.L2I_Aircraft__c = dsl.Aircraft__c;
                    acCase.L2I_Original_Sales_Opportunity__c = o.L2I_Original_Sales_Opportunity__c;
                    acCase.L2I_Opportunity__c = o.OpportunityId;
                    acCase.L2I_Product_Category_2__c = o.L2I_Product_Category_2__c;
                    acCase.L2I_Order__c = o.Id;
                    acCase.AccountId = o.AccountId;
                    acCase.L2I_Case_Process__c = 'New';
                    acCase.L2I_Delivery_Schedule_Line__c = dsl.Id;
                    acCase.Origin = 'CPQ Order';
                    acCase.L2I_Routing_Path__c = 'DSL';
                    List<String> parameters = new List<String>();
                    if (dsl.Aircraft__r.Name != null) {
                        parameters.add(dsl.Aircraft__r.Name);
                    }
                    if (dsl.Aircraft__r.Name == null && dsl.Aircraft_Identifier__c != null) {
                        parameters.add(dsl.Aircraft_Identifier__c);
                    }
                    parameters.add(o.L2I_Product_Category_2__c);
                    parameters.add(o.L2I_Original_Sales_Opportunity__r.L2I_Opportunity_Number__c);
                    
                    acCase.Subject = String.format(Label.L2I_Case_Subject, parameters);
                    
                    newCaseList.add(acCase);
                }
            }
        }
        
        if (newCaseList.size() > 0) {
            System.debug('*** Inserting Cases ' + newCaseList.size() + ' ' + newCaseList);
            insert newCaseList;
            for (Case c : newCaseList) {
                newCaseIds.add(c.Id);
            }
        }
        return newCaseIds;
    }
}