objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_End_User_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Customer PO Case process</description>
        <label>End User Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>L2I_Site__c.L2I_Site_Use_Code__c</field>
                <operation>equals</operation>
                <value>Deliver_To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_Site__c</referenceTo>
        <relationshipLabel>Cases (End User Location)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_CR_Number__c</fullName>
        <label>CR Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Comments__c</fullName>
        <label>Comments</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Freight_Terms__c</fullName>
        <label>Freight Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bill Third Party</fullName>
                </value>
                <value>
                    <fullName>Bill 3rd Party (old)</fullName>
                </value>
                <value>
                    <fullName>Collect</fullName>
                </value>
                <value>
                    <fullName>Collect (Old)</fullName>
                </value>
                <value>
                    <fullName>Counter to Counter Shipment (old)</fullName>
                </value>
                <value>
                    <fullName>Prepay &amp; Add with cost conversion (old)</fullName>
                </value>
                <value>
                    <fullName>Prepay &amp; Add (old)</fullName>
                </value>
                <value>
                    <fullName>PA Pays Freight (old)</fullName>
                </value>
                <value>
                    <fullName>Prepaid, Add to Invoice</fullName>
                </value>
                <value>
                    <fullName>PA Pays Freight, Add to Customer Invoice (old)</fullName>
                </value>
                <value>
                    <fullName>Prepaid (old)</fullName>
                </value>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>To Be Determined (old)</fullName>
                </value>
                <value>
                    <fullName>Third Party Billing (old)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_PO_Number__c</fullName>
        <label>PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_PO_Received_Date__c</fullName>
        <label>PO Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Packing_Instructions__c</fullName>
        <label>Packing Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_Purpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bug Fix</fullName>
                </value>
                <value>
                    <fullName>ISE Update</fullName>
                </value>
                <value>
                    <fullName>Interactive</fullName>
                </value>
                <value>
                    <fullName>MCS Update</fullName>
                </value>
                <value>
                    <fullName>Maps CoK</fullName>
                </value>
                <value>
                    <fullName>New Line Station</fullName>
                </value>
                <value>
                    <fullName>Non Flight Software</fullName>
                </value>
                <value>
                    <fullName>PostProd Cust Update</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Reconfiguration</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>SCR</fullName>
                </value>
                <value>
                    <fullName>SW Tools</fullName>
                </value>
                <value>
                    <fullName>SW UPDATE</fullName>
                </value>
                <value>
                    <fullName>Spares</fullName>
                </value>
                <value>
                    <fullName>Voyager</fullName>
                </value>
                <value>
                    <fullName>iXplor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Ship_to_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship to Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value in Ship to Contact does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Contact.PT_Site__c</field>
                <operation>equals</operation>
                <valueField>$Source.PT_Ship_to_Location__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Ship_to_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer that drives Ship to Information for Parts</description>
        <label>Ship to Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PO_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Ship_to_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Site (Address) for shipping parts</description>
        <label>Ship to Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value in Ship to Location does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>L2I_Site__c.PT_AccountId__c</field>
                <operation>equals</operation>
                <valueField>$Source.PT_Ship_to_Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>L2I_Site__c.L2I_Site_Use_Code__c</field>
                <operation>equals</operation>
                <value>Ship_To</value>
            </filterItems>
            <filterItems>
                <field>L2I_Site__c.L2I_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_Site__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Shipping_Instructions__c</fullName>
        <label>Shipping Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_Shipping_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Method</label>
        <referenceTo>Shipping_Method__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>DSS_PO_Case_2_Closed</fullName>
        <active>true</active>
        <businessProcess>DSS PO Case</businessProcess>
        <label>DSS PO Case 2- Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>L2I_Aircraft_Order</fullName>
        <active>true</active>
        <businessProcess>L2I_Aircraft_Order</businessProcess>
        <label>Aircraft Order</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipping_Method__c.object
<CustomObject>
    <description>Used by Order Administration to manage Shipping Methods</description>
    <label>Shipping Method</label>
    <nameField>
        <label>Shipping Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2I_InvoiceLine_TriggerFunctionsTest.cls
@IsTest
private class L2I_InvoiceLine_TriggerFunctionsTest {
    @TestSetup
    static void testSetup() {
        
        System.debug('*** Start Invoice Lines Trigger Functions Setup');
        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupAccountThruOrder(null, null, false, 'Activated');
    }
    
    @IsTest
    static void testCaseToInvoice() {
        Test.startTest();
        Id aircraftOrder = L2I_UtilityHelper.getRecordTypeId('L2I_Aircraft_Order', 'Case');
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Opportunity dealOppty = [SELECT Id FROM Opportunity WHERE RecordType.DeveloperName = 'Deal' LIMIT 1];
        L2I_DSH__c dsh = [SELECT Id FROM L2I_DSH__c LIMIT 1];

        Contact c = new Contact(
              LastName = 'MyName'
        );
        insert c;
        
        Shipping_Method__c sm = new Shipping_Method__c(
        Name = 'SM1'
        );
        insert sm;
        
        Order ord = [SELECT Id, PT_Case__c FROM Order LIMIT 1];
        Id ordItemId = [SELECT Id FROM OrderItem LIMIT 1].Id;
        
        Id rtId = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'DSS_PO_Case_2_Closed'].Id;
        Case cse = new Case(
              RecordTypeId = rtId,
              PT_PO_Number__c = '123',
              PT_PO_Received_Date__c = Date.today(),
              PT_Freight_Terms__c = 'Prepaid',
              PT_Ship_to_Customer__c = acct.Id,
              PT_Ship_to_Location__c = null,
              PT_Shipping_Method__c = sm.Id,
              PT_Packing_Instructions__c = 'do this',
              PT_Ship_to_Contact__c = c.Id,
              PT_Shipping_Instructions__c = 'do that',
              PT_Purpose__c = 'Interactive',
              PT_CR_Number__c = 'cr123',
              PT_Comments__c = 'here are comments',
              L2I_End_User_Location__c = null,
              L2I_Product_Category_2__c = 'games'
        );
        insert cse;
        
        ord.PT_Case__c = cse.Id;
        update ord;
        
        blng__Invoice__c inv = new blng__Invoice__c();
        inv.blng__InvoiceStatus__c = 'Draft';
        inv.blng__Account__c = acct.Id;
        inv.blng__DueDate__c = Date.today();
        inv.blng__InvoiceDate__c = Date.today();
        inv.blng__TargetDate__c = Date.today();
        insert inv;
        
        blng__InvoiceLine__c invLine = new blng__InvoiceLine__c();
        invLine.blng__Invoice__c = inv.Id;
        invLine.blng__OrderProduct__c = ordItemId;
        insert invLine;
        
        Test.stopTest();
    
        System.assertEquals('Interactive', [SELECT PT_Purpose__c FROM blng__Invoice__c LIMIT 1].PT_Purpose__c);
        System.assertEquals('Prepaid', [SELECT PT_Freight_Terms__c FROM blng__Invoice__c LIMIT 1].PT_Freight_Terms__c);
    }

}