objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <formula>L2I_Order__r.L2I_Product_Category_2__c</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>L2I_Aircraft_Order</fullName>
        <active>true</active>
        <businessProcess>L2I_Aircraft_Order</businessProcess>
        <label>Aircraft Order</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link by custom field to the associated aircraft object</inlineHelpText>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked when aircraft has been verified and ready for services to be turned on.</description>
        <label>Aircraft Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category_2__c</fullName>
        <label>Product Category 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Ext_Order_Header_Status__c</fullName>
        <label>Ext Order Header Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_Order_TriggerFunctions2_Test.cls
@IsTest
private class L2I_Order_TriggerFunctions2_Test {
    @TestSetup
    static void testSetup() {
        
        System.debug('*** Start Order Trigger Functions Setup');
        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupAccountThruOrder(null, null, false, 'Activated');
    }
    
    @IsTest
    static void testOrderNotClosed() {
        Test.startTest();
        Id aircraftOrder = L2I_UtilityHelper.getRecordTypeId('L2I_Aircraft_Order', 'Case');
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Opportunity dealOppty = [SELECT Id FROM Opportunity WHERE RecordType.DeveloperName = 'Deal' LIMIT 1];
        L2I_DSH__c dsh = [SELECT Id FROM L2I_DSH__c LIMIT 1];
        SBQQ__Quote__c qt = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Id salesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity salesOppty = new Opportunity(
              Name = 'TestSalesOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = salesId);
        insert salesOppty;
        qt.SBQQ__Opportunity2__c = salesOppty.Id;
        update qt;
        salesOppty.L2I_Delivery_Schedule__c = dsh.Id;
        salesOppty.SBQQ__PrimaryQuote__c = qt.Id;
        update salesOppty;
        
        L2I_Aircraft__c ac = [SELECT Id FROM L2I_Aircraft__c LIMIT 1];
        L2I_DSL__c dsl = [SELECT Id, Name, L2I_Aircraft_Confirmation__c, Aircraft__c,  Aircraft__r.Name FROM L2I_DSL__c LIMIT 1];
        dsl.Aircraft__c = ac.Id;
        dsl.L2I_Aircraft_Confirmation__c = true;
        update dsl;
    
        Case cse = new Case(
              Status = 'New'
        );
        insert cse;
        
        Order theTestOrder = new Order(AccountId = acct.Id,
              PoNumber = 'Test',
              EffectiveDate = Date.today(),
              Status = 'Draft',
              Pricebook2Id = Test.getStandardPricebookId(),
              blng__BillingDayOfMonth__c = '30',
              OpportunityId = salesOppty.Id,
              SBQQ__Quote__c = qt.Id,
              L2I_Product_Category_2__c = 'games',
              L2I_Delivery_Schedule__c = dsh.Id,
              PT_Case__c = cse.Id);
        insert theTestOrder;
        
        theTestOrder.PT_Ext_Order_Header_Status__c = 'NOT CLOSED';
        update theTestOrder;
        
        Test.stopTest();
        
        System.assertEquals('New',[SELECT Status FROM CASE WHERE ID = : cse.Id].Status );
    }
    
    @IsTest
    static void testOrderClosed() {
        Test.startTest();
        Id aircraftOrder = L2I_UtilityHelper.getRecordTypeId('L2I_Aircraft_Order', 'Case');
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Opportunity dealOppty = [SELECT Id FROM Opportunity WHERE RecordType.DeveloperName = 'Deal' LIMIT 1];
        L2I_DSH__c dsh = [SELECT Id FROM L2I_DSH__c LIMIT 1];
        SBQQ__Quote__c qt = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Id salesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity salesOppty = new Opportunity(
              Name = 'TestSalesOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = salesId);
        insert salesOppty;
        qt.SBQQ__Opportunity2__c = salesOppty.Id;
        update qt;
        salesOppty.L2I_Delivery_Schedule__c = dsh.Id;
        salesOppty.SBQQ__PrimaryQuote__c = qt.Id;
        update salesOppty;
        
        L2I_Aircraft__c ac = [SELECT Id FROM L2I_Aircraft__c LIMIT 1];
        L2I_DSL__c dsl = [SELECT Id, Name, L2I_Aircraft_Confirmation__c, Aircraft__c,  Aircraft__r.Name FROM L2I_DSL__c LIMIT 1];
        dsl.Aircraft__c = ac.Id;
        dsl.L2I_Aircraft_Confirmation__c = true;
        update dsl;
        
        Case cse = new Case(
              Status = 'New'
        );
        insert cse;
        
        Order theTestOrder = new Order(AccountId = acct.Id,
              PoNumber = 'Test',
              EffectiveDate = Date.today(),
              Status = 'Draft',
              Pricebook2Id = Test.getStandardPricebookId(),
              blng__BillingDayOfMonth__c = '30',
              OpportunityId = salesOppty.Id,
              SBQQ__Quote__c = qt.Id,
              L2I_Product_Category_2__c = 'games',
              L2I_Delivery_Schedule__c = dsh.Id,
              PT_Case__c = cse.Id);
        insert theTestOrder;
        
        theTestOrder.PT_Ext_Order_Header_Status__c = 'CLOSED';
        update theTestOrder;
        
        Test.stopTest();
        
        System.assertEquals('Order Closed',[SELECT Status FROM CASE WHERE ID = : cse.Id].Status );
    }
    
    @IsTest
    static void testOrderMixed() {
        Test.startTest();
        Id aircraftOrder = L2I_UtilityHelper.getRecordTypeId('L2I_Aircraft_Order', 'Case');
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Opportunity dealOppty = [SELECT Id FROM Opportunity WHERE RecordType.DeveloperName = 'Deal' LIMIT 1];
        L2I_DSH__c dsh = [SELECT Id FROM L2I_DSH__c LIMIT 1];
        SBQQ__Quote__c qt = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Id salesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity salesOppty = new Opportunity(
              Name = 'TestSalesOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = salesId);
        insert salesOppty;
        qt.SBQQ__Opportunity2__c = salesOppty.Id;
        update qt;
        salesOppty.L2I_Delivery_Schedule__c = dsh.Id;
        salesOppty.SBQQ__PrimaryQuote__c = qt.Id;
        update salesOppty;
        
        L2I_Aircraft__c ac = [SELECT Id FROM L2I_Aircraft__c LIMIT 1];
        L2I_DSL__c dsl = [SELECT Id, Name, L2I_Aircraft_Confirmation__c, Aircraft__c,  Aircraft__r.Name FROM L2I_DSL__c LIMIT 1];
        dsl.Aircraft__c = ac.Id;
        dsl.L2I_Aircraft_Confirmation__c = true;
        update dsl;
        
        Case cse = new Case(
              Status = 'New'
        );
        insert cse;
        
        Order theTestOrder0 = [SELECT Id, PT_Case__c, PT_Ext_Order_Header_Status__c FROM Order LIMIT 1];
        Order theTestOrder = new Order(AccountId = acct.Id,
              PoNumber = 'Test',
              EffectiveDate = Date.today(),
              Status = 'Draft',
              Pricebook2Id = Test.getStandardPricebookId(),
              blng__BillingDayOfMonth__c = '30',
              OpportunityId = salesOppty.Id,
              SBQQ__Quote__c = qt.Id,
              L2I_Product_Category_2__c = 'games',
              L2I_Delivery_Schedule__c = dsh.Id,
              PT_Case__c = cse.Id);
        insert theTestOrder;
        
        theTestOrder0.PT_Ext_Order_Header_Status__c = 'NOT CLOSED';
        theTestOrder0.PT_Case__c = cse.Id;
        update theTestOrder0;
    
        theTestOrder.PT_Ext_Order_Header_Status__c = 'CLOSED';
        update theTestOrder;
        
        Test.stopTest();
        
        System.assertEquals('New',[SELECT Status FROM CASE WHERE ID = : cse.Id].Status );
    }
    
    @IsTest
    static void testOrderMixedClosed() {
        Test.startTest();
        Id aircraftOrder = L2I_UtilityHelper.getRecordTypeId('L2I_Aircraft_Order', 'Case');
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Opportunity dealOppty = [SELECT Id FROM Opportunity WHERE RecordType.DeveloperName = 'Deal' LIMIT 1];
        L2I_DSH__c dsh = [SELECT Id FROM L2I_DSH__c LIMIT 1];
        SBQQ__Quote__c qt = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Id salesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity salesOppty = new Opportunity(
              Name = 'TestSalesOpp',
              StageName = 'Quotation',
              CloseDate = Date.today(),
              L2I_Parent_Opportunity__c = dealOppty.Id,
              L2I_Product_Category__c = 'DSS',
              RecordTypeId = salesId);
        insert salesOppty;
        qt.SBQQ__Opportunity2__c = salesOppty.Id;
        update qt;
        salesOppty.L2I_Delivery_Schedule__c = dsh.Id;
        salesOppty.SBQQ__PrimaryQuote__c = qt.Id;
        update salesOppty;
        
        L2I_Aircraft__c ac = [SELECT Id FROM L2I_Aircraft__c LIMIT 1];
        L2I_DSL__c dsl = [SELECT Id, Name, L2I_Aircraft_Confirmation__c, Aircraft__c,  Aircraft__r.Name FROM L2I_DSL__c LIMIT 1];
        dsl.Aircraft__c = ac.Id;
        dsl.L2I_Aircraft_Confirmation__c = true;
        update dsl;
        
        Case cse = new Case(
              Status = 'New'
        );
        insert cse;
        
        Order theTestOrder0 = [SELECT Id, PT_Case__c, PT_Ext_Order_Header_Status__c FROM Order LIMIT 1];
        Order theTestOrder = new Order(AccountId = acct.Id,
              PoNumber = 'Test',
              EffectiveDate = Date.today(),
              Status = 'Draft',
              Pricebook2Id = Test.getStandardPricebookId(),
              blng__BillingDayOfMonth__c = '30',
              OpportunityId = salesOppty.Id,
              SBQQ__Quote__c = qt.Id,
              L2I_Product_Category_2__c = 'games',
              L2I_Delivery_Schedule__c = dsh.Id,
              PT_Case__c = cse.Id);
        insert theTestOrder;
        
        theTestOrder0.PT_Ext_Order_Header_Status__c = 'CANCELLED';
        theTestOrder0.PT_Case__c = cse.Id;
        update theTestOrder0;
        
        theTestOrder.PT_Ext_Order_Header_Status__c = 'CLOSED';
        update theTestOrder;
        
        Test.stopTest();
        
        System.assertEquals('Order Closed',[SELECT Status FROM CASE WHERE ID = : cse.Id].Status );
    }
}