objects/Case.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <formula>L2I_Order__r.L2I_Product_Category_2__c</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>PT_IntegrationType__c</fullName>
        <label>Integration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>PPL</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/L2I_Aircraft_Service__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxAircraft Order</label>
        <referenceTo>L2I_Aircraft_Order__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <formula>Aircraft__r.Aircraft_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Type</label>
        <type>Text</type>
    </fields>
    <label>Aircraft Service</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Aircraft Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_ASA__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Order__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Aircraft Service Actions</relationshipLabel>
        <relationshipName>Aircraft_Service_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Aircraft_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Service</label>
        <referenceTo>L2I_Aircraft_Service__c</referenceTo>
        <relationshipLabel>Aircraft Service Actions</relationshipLabel>
        <relationshipName>Aircraft_Service_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aircraft Service Action</label>
    <nameField>
        <label>Aircraft Service Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Service Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link by custom field to the associated aircraft object</inlineHelpText>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_P_L_Sales_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <formula>L2I_Sales_Opportunity__r.L2I_Aircraft_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <formula>Text(L2I_Sales_Opportunity__r.L2I_Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <label>P&amp;L Sales Opportunity</label>
    <nameField>
        <displayFormat>ORPAL-{00000}</displayFormat>
        <label>Opportunities Related To P&amp;L Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;L Sales Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_Trigger_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Settings to manage execution of triggers per user or profile. This is very useful as a kill-switch to disable execution of a trigger during data migration</description>
    <fields>
        <fullName>Disable_AircraftServiceAction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable AircraftServiceAction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_AircraftService__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable AircraftService</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Aircraft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Aircraft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Attachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Attachment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_ContentVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable ContentVersion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_DSH__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable DSH</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_DSL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable DSL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_InstallLoc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable InstallLoc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to disable the execution of trigger associated with the Opportunity object.</description>
        <label>Disable Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_OrderItem__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to disable the execution of trigger associated with the OrderItem (Order Product) object.</description>
        <label>Disable OrderItem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to disable the execution of trigger associated with the Order object.</description>
        <label>Disable Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_PLSalesOpportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to disable the execution of trigger associated with the P&amp;L Sales Opportunity object.</description>
        <label>Disable PLSalesOpportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_PMO_Groups__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable PMO Groups</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_QuoteLine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable QuoteLine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Quote</label>
        <type>Checkbox</type>
    </fields>
    <label>L2I Trigger Settings</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Type</label>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>L2I_Sub_Category_2__c</fullName>
        <label>Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>L2I_Migrate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to determine if product will be moved to upper orgs.</description>
        <label>Migrate</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Migrate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to determine if product will be moved to upper orgs.</description>
        <label>Migrate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Sub_Category_2__c</fullName>
        <label>Sub Category 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2I_Sub_Category_2</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/L2I_Sub_Category_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Advertisers/Brands</fullName>
    </customValue>
    <customValue>
        <fullName>Advertising</fullName>
    </customValue>
    <customValue>
        <fullName>Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Cabin</fullName>
    </customValue>
    <customValue>
        <fullName>Connectivity</fullName>
    </customValue>
    <customValue>
        <fullName>DMPES</fullName>
    </customValue>
    <customValue>
        <fullName>eXLite</fullName>
    </customValue>
    <customValue>
        <fullName>Games</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Interactives</fullName>
    </customValue>
    <customValue>
        <fullName>K-Series</fullName>
    </customValue>
    <customValue>
        <fullName>MAPS</fullName>
    </customValue>
    <customValue>
        <fullName>MCS</fullName>
    </customValue>
    <customValue>
        <fullName>Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>NEXT Series</fullName>
    </customValue>
    <customValue>
        <fullName>PRAM</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>TV/Media</fullName>
    </customValue>
    <customValue>
        <fullName>WiFi</fullName>
    </customValue>
    <customValue>
        <fullName>X-Series</fullName>
    </customValue>
    <customValue>
        <fullName>Cell Modem</fullName>
    </customValue>
    <customValue>
        <fullName>eFX</fullName>
    </customValue>
    <customValue>
        <fullName>eX1</fullName>
    </customValue>
    <customValue>
        <fullName>eX1/eXLite</fullName>
    </customValue>
    <customValue>
        <fullName>eX1/eXLite/eXO</fullName>
    </customValue>
    <customValue>
        <fullName>eX2</fullName>
    </customValue>
    <customValue>
        <fullName>eX2/eX3</fullName>
    </customValue>
    <masterLabel>Sub Category 2</masterLabel>
</GlobalValueSet>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_BypassTriggers_Test.cls
@IsTest
private class L2I_BypassTriggers_Test {
    @IsTest
    static void testTriggers() {
        L2I_Trigger_Settings__c settings = new L2I_Trigger_Settings__c(
              SetupOwnerId = UserInfo.getUserId(),
              Disable_DSH__c = true,
              Disable_DSL__c = true,
              Disable_Aircraft__c = true,
              Disable_AircraftService__c = true,
              Disable_Case__c = true,
              Disable_AircraftServiceAction__c = true,
              Disable_Opportunity__c = true,
              Disable_Order__c = true,
              Disable_Quote__c = true,
              Disable_OrderItem__c = true,
              Disable_QuoteLine__c = true,
              Disable_PLSalesOpportunity__c = true,
              Disable_Attachment__c = true,
              Disable_PMO_Groups__c = true,
              Disable_ContentVersion__c = true,
              Disable_InstallLoc__c = true
        );
        insert settings;
        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupTestContext(null, null, false);
        
        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
        Account acctCustomer = new Account(
              Name = 'Acct1',
              RecordTypeId = customerRecordTypeId);
        insert acctCustomer;
        
        Opportunity dealOppty = new Opportunity(
              Name = 'Deal Opp',
              CloseDate = Date.today(),
              StageName = 'Open'
        );
        insert dealOppty;
        
        Opportunity salesOppty = new Opportunity(
              Name = 'Sales Opp',
              AccountId = acctCustomer.Id,
              RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
              L2I_Product_Category__c = 'DSS',
              CloseDate = Date.today(),
              StageName = 'Quotation',
              L2I_Parent_Opportunity__c = dealOppty.Id
        );
        insert salesOppty;
    
//        Attachment attach=new Attachment();
//        attach.Name='Unit Test Attachment Anon';
//        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
//        attach.body=bodyBlob;
//        attach.parentId=salesOppty.id;
//        insert attach;
        
        L2I_DSH__c dsh = new L2I_DSH__c();
        insert dsh;
        update dsh;
        
        L2I_DSL__c dsl = new L2I_DSL__c(
              Delivery_Schedule_Header__c = dsh.Id
        );
        insert dsl;
        
        L2I_Aircraft_Type__c att = factory.createAircraftType(acctCustomer.Id, 123456);
        insert att;
        
        L2I_Aircraft__c ac = factory.createAircraft(att.Id, 'Name', '2333-11131133114499999988888805', acctCustomer.Id);
        insert ac;
        
        L2I_Aircraft_Service__c arcs = new L2I_Aircraft_Service__c(
              Aircraft__c = ac.Id
        );
        insert arcs;
        
        Case cse = new Case();
        insert cse;
        
        L2I_ASA__c asa = new L2I_ASA__c(
              Aircraft_Order__c = cse.Id,
              Aircraft_Service__c = arcs.Id
        );
        insert asa;
        
        delete ac;
        
        SBQQ__Quote__c qt = new SBQQ__Quote__c(
              RecordTypeId = L2I_StaticConstants.APPROVED_QUOTE_RT_ID,
              SBQQ__Account__c = acctCustomer.Id,
              SBQQ__Opportunity2__c = salesOppty.Id,
              SBQQ__Primary__c = true
        );
        insert qt;
//
//        ContentVersion cVer = new ContentVersion();
//        cVer.ContentLocation = 'S';             // document is in Salesforce
//        cVer.PathOnClient = attach.Name;        // filename with extension
//        cVer.Title = attach.Name;
//        cVer.VersionData = attach.Body;
//        cVer.PT_IntegrationType__c = 'CPL';
//        cVer.tagCsv = 'SBQQ__Quote__c:' + qt.Id;
//        cVer.FirstPublishLocationId = attach.ParentId;  // creates ContentDocumentLink also
//        insert cVer;

        Map<Id, String> prodCategoryMap = new Map<Id, String>();
        
        List<Product2> prodList = [SELECT Id, Name, L2I_Sub_Category_2__c FROM Product2];
        Map<String, Id> prodIdMap = new Map<String, Id>();
        List<Product2> updateProdList = new List<Product2>();
        
        for (Product2 p : prodList) {
            p.L2I_Migrate__c = true;
            p.SBQQ__ChargeType__c = 'Usage';
            p.SBQQ__BillingType__c = '';
            p.L2I_Service_Activation_Type__c = 'Monthly';
            updateProdList.add(p);
            prodIdMap.put(p.Name, p.Id);
            prodCategoryMap.put(p.Id, p.L2I_Sub_Category_2__c);
        }
        
        update updateProdList;
        
        Set<String> ProductNameList = new Set<String>();
        
        ProductNameList.add('Toca Boca - Toca Cars');
        Set<Id> prodIdList = New Set<Id>();
        
        List<SBQQ__QuoteLine__c> qlList = new List<SBQQ__QuoteLine__c>();
        for (String s : ProductNameList) {
            Id pid = prodIdMap.get(s);
            prodIdList.add(pid);
            SBQQ__QuoteLine__c quoteLine = factory.createQuoteLine(qt.Id, pid, null);
            quoteLine.SBQQ__Quantity__c = 1;
            quoteLine.SBQQ__SpecialPrice__c = 5;
            qlList.add(quoteLine);
        }
        insert qlList;
        List<PricebookEntry> pbeList = [
              SELECT Id,
                    Product2Id,
                    Pricebook2Id,
                    UnitPrice,
                    IsActive
              FROM PricebookEntry
              WHERE Product2Id IN:prodIdList
        ];
        
        Map<Id, PricebookEntry> pricebookMap = new Map<Id, PricebookEntry>();
        for (PricebookEntry pbe : pbeList) {
            pricebookMap.put(pbe.Product2Id, pbe);
        }
    
        Order ord = new Order(AccountId = acctCustomer.Id,
              PoNumber = 'Test',
              EffectiveDate = Date.today() - 2,
              Status = 'Draft',
              Pricebook2Id = Test.getStandardPricebookId(),
              blng__BillingDayOfMonth__c = '20',
              OpportunityId = salesOppty.Id,
              SBQQ__Quote__c = qt.Id,
              L2I_Delivery_Schedule__c = dsh.Id);
        insert ord;
    
//        List<OrderItem> orderItemList = new List<OrderItem>();
//        blng__BillingRule__c billingrule = [SELECT Id FROM blng__BillingRule__c WHERE Name = 'Non-Billable Product Rule' LIMIT 1];
//        for (Id pid : prodIdList) {
//            OrderItem theTestOrderItem = new OrderItem(OrderId = ord.Id,
//                  Quantity = 1,
//                  Product2Id = pid,
//                  PricebookEntryId = pricebookMap.get(pid).Id,
//                  UnitPrice = pricebookMap.get(pid).UnitPrice,
//                  L2I_Sub_Category_2__c = prodCategoryMap.get( pid ),
//                  SBQQ__ChargeType__c = 'Usage',
//                  SBQQ__BillingFrequency__c = 'Monthly',
//                  blng__BillingRule__c = billingrule.Id,
//                  SBQQ__Status__c = 'Draft',
//                  ServiceDate = Date.today()-2,
//                  EndDate = Date.today()+363,
//                  SBQQ__DefaultSubscriptionTerm__c = 24,
//                  L2I_blng_MatchingId__c = '1234567891011');
//            orderItemList.add(theTestOrderItem);
//        }

//        insert orderItemList;
    
        L2I_P_L_Approval__c plApproval = factory.createPLApproval(dealOppty.Id, 'Approved');
        insert plApproval;
    
        L2I_P_L_Sales_Opportunity__c plSalesOpp = factory.createPLSalesOpp(plApproval.Id, salesOppty.Id);
        insert plSalesOpp;
    
        PT_PMO_Groups__c pg = new PT_PMO_Groups__c(
              Name = 'pgName',
              Group_Type__c = 'Group'
        );
        insert pg;
        
        PT_Install_Location__c instLoc = new PT_Install_Location__c(
                Name = 'CW',
                ShipSet__c = dsl.Id
        );
        insert instLoc;
    }
}