objects/Case.object
<CustomObject>
    <fields>
        <fullName>IFE_Program_Number__c</fullName>
        <label>Program Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Number__c</fullName>
        <formula>L2I_Order__r.L2I_Program_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_SCMDB_Release_Date__c</fullName>
        <label>SCMDB Release Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>IFEC_DSL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IFEC DSL</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>L2I_DSL__c.Product_Category__c</field>
                <operation>equals</operation>
                <value>IFEC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>DSLs</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_SCM_Confirmations__c.object
<CustomObject>
    <fields>
        <fullName>L2I_Feature_Part_Numbers__c</fullName>
        <label>Feature Part Numbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Number__c</fullName>
        <label>Program Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>L2I_Related_DSS__c</fullName>
        <label>Related DSS</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>L2I_Related__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Related</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_SCMDB_Release_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SCMDB Release Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>L2I_Salesforce_Opportunity_Identifier__c</fullName>
        <label>Salesforce Opportunity Identifier</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>SCM Confirmations</relationshipLabel>
        <relationshipName>SCM_Confirmations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SCM Confirmation</label>
    <nameField>
        <displayFormat>SCM-{0000}</displayFormat>
        <label>SCM Confirmations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCM Confirmations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Opportunity_Number__c</fullName>
        <description>Using Record Type Name to show RecordType Label with Opportunity Number.</description>
        <formula>IF( ( (RecordType.Name = &#39;PPL&#39; &amp;&amp; ISPICKVAL(PT_PPL_Type__c  , &#39;CR&#39;)|| Change_Request__c = TRUE) ) , &quot;CR-&quot; + L2I_Opportunity_ID__c, RecordType.Name+&quot;-&quot; + L2I_Opportunity_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Number__c</fullName>
        <label>MCS Program Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>L2I_Feature_ID__c</fullName>
        <label>Feature ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Number__c</fullName>
        <inlineHelpText>This is for Media Products Only</inlineHelpText>
        <label>Program Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_SCM_Release_Date_Captured__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SCM Release Date Captured</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>L2I_Feature_ID__c</fullName>
        <inlineHelpText>Twin Field, originating from the product2</inlineHelpText>
        <label>Feature ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Number__c</fullName>
        <formula>IF(
ISPICKVAL(L2I_Sub_Category_2__c, &quot;MCS&quot;), Order.L2I_Program_Number__c,
&quot;NA&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Number</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/L2I_SCMInfoTriggerHandler.cls
public without sharing class L2I_SCMInfoTriggerHandler extends L2I_TriggerHandler {
    
    public static void scmBeforeInsert (List<L2I_SCM_Confirmations__c> newSCMList) {
        
        Map<String, L2I_SCM_Confirmations__c> newSCMMap =  new Map<String, L2I_SCM_Confirmations__c>();
        List<String> newSalesNumList = new List<String>();
        Map<Id,L2I_SCM_Confirmations__c> insertSCMList = new Map<Id,L2I_SCM_Confirmations__c>();
        Map<String,Set<String>> mapRelatedDSS = new Map<String,Set<String>>();
        Map<String, String> mapSCMFeature = new Map<String, String>();
        
        for (L2I_SCM_Confirmations__c scm : newSCMList ) {
            if ( scm.L2I_Related__c == FALSE) {
                newSalesNumList.add(scm.L2I_Salesforce_Opportunity_Identifier__c);
                newSCMMap.put(scm.L2I_Salesforce_Opportunity_Identifier__c, scm);
                if (scm.L2I_Feature_Part_Numbers__c != null) {
                    mapSCMFeature.put(scm.L2I_Salesforce_Opportunity_Identifier__c,scm.L2I_Feature_Part_Numbers__c);
                }
                scm.L2I_Related__c = TRUE;
            }
        }
        
        if (!newSalesNumList.isEmpty()) {
            Map<Id, L2I_DSL__c> mapDSL = new Map<Id, L2I_DSL__c> ([SELECT ID, 
                                                                       (SELECT ID, 
                                                                            Original_Opportunity__c, 
                                                                            Original_Opportunity__r.Name 
                                                                        FROM Delivery_Schedule_Lines__r),
                                                                       Original_Opportunity__r.L2I_Opportunity_Number__c 
                                                                   FROM L2I_DSL__c 
                                                                   WHERE Original_Opportunity__c IN 
                                                                       (SELECT ID 
                                                                        FROM Opportunity 
                                                                        WHERE L2I_Opportunity_Number__c  IN : newSalesNumList)
                                                                  ]);
            System.debug('mapDSL is ' +mapDSL);
            System.debug('mapDSL.values is ' +mapDSL.values());
            if (!mapDSL.isEmpty()) {
                for (L2I_DSL__c dslLineItem :  mapDSL.values()) {
                    L2I_SCM_Confirmations__c cloneRec = newSCMMap.get(dslLineItem.Original_Opportunity__r.L2I_Opportunity_Number__c).clone(false, true, false, false);
                    System.debug('dslLineItem.Delivery_Schedule_Lines__r is ' +dslLineItem.Delivery_Schedule_Lines__r);
                    L2I_DSL__c dslRec = dslLineItem.Delivery_Schedule_Lines__r;
                    System.debug('dslRec is ' +dslRec);
                    cloneRec.Opportunity__c = dslRec.Original_Opportunity__c;
                    System.debug('mapRelatedDSS is ' +mapRelatedDSS);
                    System.debug('dslLineItem.Original_Opportunity__r.L2I_Opportunity_Number__c is ' +dslLineItem.Original_Opportunity__r.L2I_Opportunity_Number__c);
                    if (mapRelatedDSS.containsKey(dslLineItem.Original_Opportunity__r.L2I_Opportunity_Number__c)) {
                        System.debug('In the if loop ' );
                        Set<String> existingList = mapRelatedDSS.get(dslLineItem.Original_Opportunity__r.L2I_Opportunity_Number__c);
                        existingList.add(dslRec.Original_Opportunity__r.Name);
                        mapRelatedDSS.put(dslLineItem.Original_Opportunity__r.L2I_Opportunity_Number__c,existingList);
                    } else {
                        if (dslRec.Original_Opportunity__r.Name != null) {
                            Set<String> newList = new Set<String>{dslRec.Original_Opportunity__r.Name};
                            mapRelatedDSS.put(dslLineItem.Original_Opportunity__r.L2I_Opportunity_Number__c,newList); 
                        }
                    }
                    System.debug('cloneRec is ' +cloneRec);
                    insertSCMList.put(dslRec.Original_Opportunity__c,cloneRec);
                }
            }
            
            if (!mapRelatedDSS.isEmpty()) {
                for (String salesKey:mapRelatedDSS.keySet()) {
                    for (String setVal: mapRelatedDSS.get(salesKey)) {
                        if (setVal != null && setVal != 'null' ) {
                            String newString = newSCMMap.get(salesKey).L2I_Related_DSS__c;
                            if (newString != null) {
                                newString += setVal + ',';
                            } else {
                                newString = setVal;
                            }
                            newSCMMap.get(salesKey).L2I_Related_DSS__c = newString;
                        }
                    }
                }
            }
            if(!insertSCMList.isEmpty()){
                insert insertSCMList.values();
            }
        }
        
        if (!mapSCMFeature.isEmpty()) {
            List<String> queryString = new List<String>();
            List<String> returnString = new List<String>();
            Set<Id> setOrderId = new Set<Id>();
            Map<Id, OrderItem> mapCaseId = new Map<Id, OrderItem>();
            Map<String, DateTime> mapFeatureDate = new Map<String, DateTime>();
            Map<String, String> mapFeatureProgram = new Map<String, String>();
            List<Order> updateOrder = new List<Order>();
            List<Case> updateCase = new List<Case>();
            Set<String> setStringVal = new  Set<String>();
            
            for(String scmString : mapSCMFeature.keySet()){
                returnString = mapSCMFeature.get(scmString).split(',');
                queryString.addAll(returnString);
                if(!returnString.isEmpty()){
                    for(String featureItem : returnString){  
                        mapFeatureDate.put(featureItem, System.Now());
                        mapFeatureProgram.put(featureItem, newSCMMap.get(scmString).L2I_Program_Number__c);
                    }
                }
            }
            
            if(!queryString.isEmpty()){
                Map<Id, OrderItem> mapOrderItem = new Map<Id, OrderItem> ([ SELECT ID,L2I_Feature_ID__c, OrderId, Order.Status, Order.PT_Case__c, Order.PT_Case__r.IFE_Program_Number__c FROM OrderItem WHERE L2I_Feature_ID__c IN: queryString AND Order.Status = 'Draft']);
                for(OrderItem orderLine: mapOrderItem.values()){
                    if(orderLine.OrderId != null && orderLine.Order.PT_Case__c != null){
                        mapCaseId.put(orderLine.Order.PT_Case__c,orderLine);
                        setOrderId.add(orderLine.OrderId);
                        //mapCaseId.put(orderLine.Order.PT_Case__c,mapFeatureDate.get(orderLine.L2I_Feature_ID__c));
                    }
                }
            }
            
            if(!mapCaseId.isEmpty()){
                for(Id caseId: mapCaseId.keySet()){
                    Case modifyCase = new Case();
                    modifyCase.Id = caseId;
                    modifyCase.L2I_SCMDB_Release_Date__c = mapFeatureDate.get(mapCaseId.get(caseId).L2I_Feature_ID__c);
                            String newString = mapCaseId.get(caseId).Order.PT_Case__r.IFE_Program_Number__c;
                            if(newString != null){
                                setStringVal.addAll(newString.split(','));
                                setStringVal.add(mapFeatureProgram.get(mapCaseId.get(caseId).L2I_Feature_ID__c));
                                //newString += mapFeatureProgram.get(mapCaseId.get(caseId).L2I_Feature_ID__c) + ',';
                            } else{
                                setStringVal.add(mapFeatureProgram.get(mapCaseId.get(caseId).L2I_Feature_ID__c));
                                //newString = mapFeatureProgram.get(mapCaseId.get(caseId).L2I_Feature_ID__c) + ',';
                            }
                    modifyCase.IFE_Program_Number__c = String.join(new List<String>(setStringVal), ',');
                    updateCase.add(modifyCase);
                    
                    if(mapCaseId.get(caseId).OrderId != null){
                        Order modifyOrder = new Order();
                        modifyOrder.Id = mapCaseId.get(caseId).OrderId;
                        modifyOrder.L2I_SCM_Release_Date_Captured__c = TRUE;
                        updateOrder.add(modifyOrder);
                    }
                }
            }
            
            
            
            if(!updateCase.isEmpty()){
                update updateCase;
            }
            if(!updateOrder.isEmpty()){
                update updateOrder;
            }
        }
    }
}