objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IFE_B2B_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>B2B Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IFE_Document_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Document Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IFE_Maintenance_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Maintenance Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IFE_Repair_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Repair Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IFE_Sales_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Access</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/L2I_Related_Account__c.object
<CustomObject>
    <description>Custom object to model the many-to-many relationships between PAC accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Account from which the relationship is being viewed</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The related account</description>
        <label>Related To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Accounts (Related To)</relationshipLabel>
        <relationshipName>Related_to_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Merger</fullName>
                </value>
                <value>
                    <fullName>Sister concern</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>MRO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Account</label>
    <nameField>
        <displayFormat>REL-{00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ife_TestDataUtil.cls
@isTest
public class ife_TestDataUtil {
     
    public static Account createAccount(boolean isInsert){
        Account accVariable = new Account();
        accVariable.name = 'Acc Tets';
                
        if(isInsert){
            insert accVariable;
        }
        return accVariable;
    }
    public static Contact createContact(String accId, boolean isInsert){
        
            Contact con = new Contact();
                con.LastName = 'Name';
                con.AccountId = accId;
                con.lastName = 'Testing LastName';
                con.IFE_Sales_Access__c = true;
                con.IFE_Document_Access__c = true;
                con.IFE_Maintenance_Access__c = true;
                con.IFE_Repair_Access__c = true;
                con.IFE_B2B_Access__c = true;   
                
        if(isInsert){
           insert con; 
        }
        return con;
    } 
    public static User CreateUser( boolean isInsert){
      Profile profileId = [Select Id from Profile where name = 'System Administrator'];
        //  Account acc = ife_TestDataUtil.createAccount(true);
        //  Contact con = ife_TestDataUtil.createContact(acc.id, true);
        User usr = new User();
        usr.LastName = 'Testing';
        usr.FirstName='test';
        usr.Alias = 'pbhar';
        usr.Email = 'Pranav.Bhardwaj@asdf.com';
        usr.Username = System.now().millisecond() + 'test2@testpan.com';
        usr.ProfileId = profileId.id;
        usr.TimeZoneSidKey = 'GMT';
        usr.LanguageLocaleKey = 'en_US';
        usr.EmailEncodingKey = 'UTF-8';
        usr.LocaleSidKey = 'en_US';
    //    usr.ContactId = con.Id;
        if(isInsert){
            insert usr;
        }
       return usr; 
    }
    public static L2I_Related_Account__c createRelatedAccount(String accId, boolean isInsert){
        L2I_Related_Account__c relAccount = new L2I_Related_Account__c();
        relAccount.Account__c = accId;
        relAccount.Related_To__c = accId;
        relAccount.Relationship_Type__c = 'Both';
        
        if(isInsert){
            insert relAccount;
        }
        return relAccount;
    }
}