objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IFE_Email_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Opt In</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Modified_Date__c</fullName>
        <inlineHelpText>Required to be set so that it can be picked up by weekly email batch</inlineHelpText>
        <label>Document Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Number__c</fullName>
        <externalId>true</externalId>
        <label>Document Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Publication</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>GCS</fullName>
                </value>
                <value>
                    <fullName>Spare Parrs</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Alert__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Email to subscribed customers when a new version of this document is published.</description>
        <label>Email Alert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <label>Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>IFE Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IFE_Document_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFE_Document__c</fullName>
        <label>IFE Document</label>
        <referenceTo>IFE_Document__c</referenceTo>
        <relationshipName>IFE_Documents_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IFE Customer Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Customer Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Part__c.object
<CustomObject>
    <fields>
        <fullName>Override__c</fullName>
        <label>Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IFE Part</label>
    <nameField>
        <label>IFE Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IFE_Part_Document__c.object
<CustomObject>
    <fields>
        <fullName>IFE_Document__c</fullName>
        <label>IFE Document</label>
        <referenceTo>IFE_Document__c</referenceTo>
        <relationshipLabel>IFE Part Documents</relationshipLabel>
        <relationshipName>IFE_Part_Documents</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFE_Part__c</fullName>
        <label>IFE Part</label>
        <referenceTo>IFE_Part__c</referenceTo>
        <relationshipName>IFE_Part_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFE Part Document</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>IFE Part Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Part Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IFE_Part_Overide__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IFE Part Overrides</relationshipLabel>
        <relationshipName>IFE_Part_Overrides</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IFE_Part__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>IFE Part</label>
        <referenceTo>IFE_Part__c</referenceTo>
        <relationshipLabel>IFE Part Overrides</relationshipLabel>
        <relationshipName>IFE_Part_Overrides</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <label>Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                    <default>true</default>
                    <label>Add</label>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IFE Part Overide</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>IFE Part Overide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFE Part Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>IFE_Email_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Email Opt In for Technical Publications</description>
        <label>Tech Pub Email Opt In</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ife_DocumentSendEmailBatch.cls
global class ife_DocumentSendEmailBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful{
	public Map<String, List<IFE_Document__c>> mapOfAccountIdAndDocumentalist;
	public List<sObject> start(Database.BatchableContext c){

		mapOfAccountIdAndDocumentalist = getDocument();
		system.debug('mapOfAccountIdAndDocumentalist>>>' + mapOfAccountIdAndDocumentalist);

		List<User> userList = [SELECT Id, Name, Email, ContactId, Contact.AccountId
		                       FROM User
		                       WHERE IFE_Email_Opt_In__c = true];
		System.debug('userList----' + userList);
		return userList;
	}

	global void execute(SchedulableContext ctx){
		Database.executebatch(new ife_DocumentSendEmailBatch());

		Datetime sysTime = System.now();
		sysTime = sysTime.addDays(7);
		String chron_exp = '' + sysTime.second()+' ' + sysTime.minute()+' ' + sysTime.hour()+' ' + sysTime.day()+' ' + sysTime.month()+' ? ' + sysTime.year();
		system.debug('ife_DocumentSendEmailBatch --> ' + chron_exp);
		System.schedule('ife_DocumentSendEmailBatchJob' + System.now(), chron_exp, new ife_DocumentSendEmailBatch());
		Id cronTrigId = ctx.getTriggerId();
		System.abortJob(cronTrigId);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope){
		System.debug('scope=== ' + mapOfAccountIdAndDocumentalist);
		List<Messaging.SingleEmailMessage> lstEmails = new List<Messaging.SingleEmailMessage>();


		for (User userObj : (List<User>)scope){
			
			if (mapOfAccountIdAndDocumentalist.containsKey(userObj.Contact.AccountId)){
				Integer item = 1;
				String htmlBody = '<h1:>Technical Library Document Notification</h1><br/><br/';
				htmlBody += userObj.Name + ', <br/>';
				htmlBody += 'This is a Technical Document Library email from Panasonic Avionics Corporation.<br/>';
				htmlBody += 'The following are document numbers of newly released or revised Technical Publication uploaded to the MyIFE Technical Library on the dates shown.<br/><br/>';

				htmlBody += '<table border="1" style="border-collapse: collapse"><caption></caption><tr><th>Item#</th><th>Document#</th><th>Rev#</th><th>Doc Type</th><th>Date</th></tr>';

				for (IFE_Document__c doc : mapOfAccountIdAndDocumentalist.get(userObj.Contact.AccountId)){
					htmlBody += '<tr><td>' + item++ + '</td><td>' + doc.Document_Number__c + '</td><td>' + doc.Revision__c + '</td><td>' + doc.Document_Type__c + '</td><td>' + doc.Document_Modified_Date__c + '</td></tr>';

				}
				Messaging.SingleEmailMessage objEmail = new Messaging.SingleEmailMessage();

				objEmail.setToAddresses(new List<String>{userObj.Email});
				htmlBody += '</table>';
				htmlBody += '<br/><br/>If you do not want to receive these email notifcations, please log in to MyIFE at https://myife.panasonic.aero. Access the "My Profile" option, uncheck the box for "Email Opt In" and submit the change.<br/>';
				htmlBody += 'If you have questions about the contents of this notification use the "Technical Publication Support" option on the Support Page.';
				objEmail.setHtmlBody(htmlBody);
				objEmail.setSubject('Technical Library Document Notification');
				lstEmails.add(objEmail);

			}
            if(String.isBlank(userObj.ContactId)){
                getEmailForInternalUser(userObj, mapOfAccountIdAndDocumentalist, lstEmails);
            }
		}
		System.debug('lstEmails====' + lstEmails);
		Messaging.sendEmail(lstEmails);
	}

	global void finish(Database.BatchableContext BC){
	}

	public Map<String, List<IFE_Document__c>> getDocument(){
		Date currDate = Date.today();
		Date dayBefore = currDate.addDays(-7);
		Set<String> documentIds = new Set<String>();
		Map<String, List<IFE_Document__c>> accountaIdWithDocumentObj = new Map<String, List<IFE_Document__c>>();
		/*for (IFE_Document_Account__c docAccount : [SELECT Id, Account__c, IFE_Document__c, IFE_Document__r.Document_Modified_Date__c, IFE_Document__r.Revision__c, IFE_Document__r.Document_Type__c, IFE_Document__r.Document_Number__c
		 FROM IFE_Document_Account__c
		 WHERE IFE_Document__r.Document_Type__c = 'Technical Publication' AND IFE_Document__r.Document_Modified_Date__c <= :currDate AND IFE_Document__r.Document_Modified_Date__c > :dayBefore]){
		 System.debug('docAccount>><<<' + docAccount);

		 if (accountaIdWithDocumentObj.containsKey(docAccount.Account__c)){
		 accountaIdWithDocumentObj.get(docAccount.Account__c).add(docAccount.IFE_Document__r);
		 } else{
		 accountaIdWithDocumentObj.put(docAccount.Account__c, new List<IFE_Document__c>{docAccount.IFE_Document__r});
		 }
		 }*/

		Map<String, IFE_Document__c> idWirhDocument = new Map<String, IFE_Document__c>([SELECT Id, Document_Type__c, Email_Alert__c, Document_Modified_Date__c, Revision__c, Document_Number__c
		                                                                                FROM IFE_Document__c
		                                                                                WHERE Document_Type__c = 'Technical Publication' AND Email_Alert__c = true AND Document_Modified_Date__c <= :currDate AND Document_Modified_Date__c > :dayBefore]);
		
		for (IFE_Document_Account__c docAccount : [SELECT Id, Account__c, IFE_Document__c
		                                           FROM IFE_Document_Account__c
		                                           WHERE IFE_Document__c IN :idWirhDocument.keySet() AND Account__c != null]){
			if (docAccount.Account__c != null && idWirhDocument.containsKey(docAccount.IFE_Document__c)){
				if (accountaIdWithDocumentObj.containsKey(docAccount.Account__c)){
					accountaIdWithDocumentObj.get(docAccount.Account__c).add(idWirhDocument.get(docAccount.IFE_Document__c));
				} else{
					accountaIdWithDocumentObj.put(docAccount.Account__c, new List<IFE_Document__c>{idWirhDocument.get(docAccount.IFE_Document__c)});
				}
			}
		}
		
		Map<String, IFE_Document__c> partIdWithPartDocument = new Map<String, IFE_Document__c>();
		for (IFE_Part_Document__c partDoc : [SELECT Id, IFE_Document__c, IFE_Part__c
		                                     FROM IFE_Part_Document__c
		                                     WHERE IFE_Document__c IN :idWirhDocument.keySet()]){
			partIdWithPartDocument.put(partDoc.IFE_Part__c, idWirhDocument.get(partDoc.IFE_Document__c));
			
		}
		for (IFE_Part_Overide__c partOveridr : [SELECT Id, Account__c, IFE_Part__c, Override__c
		                                        FROM IFE_Part_Overide__c
		                                        WHERE IFE_Part__c IN :partIdWithPartDocument.keySet() AND Override__c = 'Add' AND Account__c != null]){
			
			if (partIdWithPartDocument.containsKey(partOveridr.IFE_Part__c)){
				if (accountaIdWithDocumentObj.containsKey(partOveridr.Account__c)){
					accountaIdWithDocumentObj.get(partOveridr.Account__c).add(partIdWithPartDocument.get(partOveridr.IFE_Part__c));
				} else{
					accountaIdWithDocumentObj.put(partOveridr.Account__c, new List<IFE_Document__c>{partIdWithPartDocument.get(partOveridr.IFE_Part__c)});
				}
			}
		}
		System.debug('accountaIdWithDocumentObj   ====' + accountaIdWithDocumentObj);
		return accountaIdWithDocumentObj;
	}
    
    public void getEmailForInternalUser(User userObj, Map<String, List<IFE_Document__c>>mapOfAccountIdAndDocumentalist, List<Messaging.SingleEmailMessage> lstEmails){
   
			
			if (mapOfAccountIdAndDocumentalist.values().size()>0){
				Integer item = 1;
				String htmlBody = '<h1:>Technical Library Document Notification</h1><br/><br/';
				htmlBody += userObj.Name + ', <br/>';
				htmlBody += 'This is a Technical Document Library email from Panasonic Avionics Corporation.<br/>';
				htmlBody += 'The following are document numbers of newly released or revised Technical Publication uploaded to the MyIFE Technical Library on the dates shown.<br/><br/>';

				htmlBody += '<table border="1" style="border-collapse: collapse"><caption></caption><tr><th>Item#</th><th>Document#</th><th>Rev#</th><th>Doc Type</th><th>Date</th></tr>';
                
                Set<IFE_Document__c> alldocs = new Set<IFE_Document__c>();
                for (Id key : mapOfAccountIdAndDocumentalist.keySet()) {   
                	alldocs.addAll(mapOfAccountIdAndDocumentalist.get(key));
				}

            
				for (IFE_Document__c doc : alldocs){
					htmlBody += '<tr><td>' + item++ + '</td><td>' + doc.Document_Number__c + '</td><td>' + doc.Revision__c + '</td><td>' + doc.Document_Type__c + '</td><td>' + doc.Document_Modified_Date__c + '</td></tr>';
				}
				Messaging.SingleEmailMessage objEmail = new Messaging.SingleEmailMessage();

				objEmail.setToAddresses(new List<String>{userObj.Email});
				htmlBody += '</table>';
				htmlBody += '<br/><br/>If you do not want to receive these email notifcations, please log in to MyIFE at https://myife.panasonic.aero. Access the "My Profile" option, uncheck the box for "Email Opt In" and submit the change.<br/>';
				htmlBody += 'If you have questions about the contents of this notification use the "Technical Publication Support" option on the Support Page.';
				objEmail.setHtmlBody(htmlBody);
				objEmail.setSubject('Technical Library Document Notification');
				lstEmails.add(objEmail);

			}
    }
    
}