objects/IFE_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Publication</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>GCS</fullName>
                </value>
                <value>
                    <fullName>Spare Parrs</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Number__c</fullName>
        <label>Folder Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Version__c</fullName>
        <label>Folder Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IFE Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ife_Integration__mdt.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ife_Integration</label>
    <pluralLabel>ife_Integrations</pluralLabel>
</CustomObject>

classes/ife_DownloadRepairPolicyController.cls
public class ife_DownloadRepairPolicyController {
    public ife_DownloadRepairPolicyController() {

    }
    @AuraEnabled
	public static  List<IFE_Document__c> getDocuments(){
        List<IFE_Document__c>  documents =[SELECT Id, Name,Document_Type__c,File_Name__c,Folder_Version__c,Folder_Number__c FROM IFE_Document__c WHERE Document_Type__c = 'Repair'];
        return documents;
    }
    @AuraEnabled
	public static String urlDownloadDocument(String folderNumber, String folderVersion, String fileName){
		ife_Integration__mdt integrationMdtObj = [SELECT Id, Client_Secret__c, Client_Id__c, URL__c, MasterLabel
		                                          FROM ife_Integration__mdt
		                                          WHERE MasterLabel = 'AgileDocument'
		                                          LIMIT 1];
		String url = integrationMdtObj.URL__c + 'agileDocument/' + folderNumber + ':' + folderVersion + ':' + fileName;
		return url;
	}
}