objects/IFE_Document__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Publication</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>GCS</fullName>
                </value>
                <value>
                    <fullName>Spare Parrs</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <label>Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>IFE Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ife_DownloadDocumentsControllerTest.cls
@isTest
public class ife_DownloadDocumentsControllerTest {
    @isTest
    public static void getDocumentsTest(){
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData = Blob.valueOf('Test Content');         
        insert cv; 
        
        ContentVersion testContent = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
        system.debug('@@@testContent'+testContent);
    	        
        String strRecordTypeId = [Select Id From RecordType Where Name = 'Agile Document'].Id;
            
        IFE_Document__c ifeDocument = new IFE_Document__c();
        ifeDocument.Description__c = 'Testring--';
        ifeDocument.Revision__c = 'Test';
        ifeDocument.File_Name__c = 'Test';
        ifeDocument.RecordTypeId = strRecordTypeId;
        ifeDocument.Document_Type__c = 'Products';
        insert ifeDocument;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = ifeDocument.Id;
        contentlink.ShareType = 'I'; 
        contentlink.ContentDocumentId = testContent.ContentDocumentId;
        contentlink.Visibility = 'AllUsers'; 
		insert contentlink;
        
        ife_DownloadDocumentsController downloadDocObj = new ife_DownloadDocumentsController();
        List<ife_DownloadDocumentsController.DataWrapper> dw = new List<ife_DownloadDocumentsController.DataWrapper>();
        
       dw =  ife_DownloadDocumentsController.getDocuments();
        System.assertEquals('Test', dw[0].Revision);
       
    }
}