objects/Ife_LeadConfirmation__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <label>Lead Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Ife Lead Confirmation</label>
    <nameField>
        <displayFormat>Ife_LC-{0000}</displayFormat>
        <label>Ife_LeadConfirmation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ife_LeadConfirmation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>IFE_Email_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IFE Email Verified</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/Ife_LeadConfirmationTriggerHandler.cls
public  class Ife_LeadConfirmationTriggerHandler {
    public static void afterInsert(List<Ife_LeadConfirmation__c> leadConfirmations){
        List<Lead> leadList = new List<Lead>();
        for(Ife_LeadConfirmation__c lcObj : leadConfirmations){
            if(lcObj.Lead_Id__c != null){
                Lead leadObj = new Lead();
                leadObj.Id= lcObj.Lead_Id__c;
                leadObj.IFE_Email_Verified__c = true;
                leadList.add(leadObj);
            }

        }
        update leadList;

    }
}