objects/IFE_Document__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Number__c</fullName>
        <externalId>true</externalId>
        <label>Document Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Publication</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>GCS</fullName>
                </value>
                <value>
                    <fullName>Spare Parrs</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <label>Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>IFE Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFE Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ife_DownloadDocumentsController.cls
public class ife_DownloadDocumentsController{
	public ife_DownloadDocumentsController(){
	}

	@AuraEnabled
	public static List<DataWrapper> getDocuments(){
		List<DataWrapper> dataWrappers = new List<DataWrapper>();
		for (IFE_Document__c document : [SELECT Id, Document_Type__c, Name, Description__c, Revision__c, Document_Number__c, Part_Number__c, (SELECT ContentDocumentId, visibility
		                                                                                                                                      FROM ContentDocumentLinks
		                                                                                                                                      ORDER BY ContentDocument.CreatedDate DESC
		                                                                                                                                      NULLS LAST
		                                                                                                                                      LIMIT 1)
		                                 FROM IFE_Document__c WHERE Document_Type__c = 'Products']){
            DataWrapper wrapperObj = new DataWrapper();
            wrapperObj.Name = document.Name;
            wrapperObj.Revision = document.Revision__c;
            wrapperObj.DocumentNumber = document.Document_Number__c;
			for (ContentDocumentLink att : document.ContentDocumentLinks){
                wrapperObj.AttachmentId = att.ContentDocumentId;

			}
            dataWrappers.add(wrapperObj);
		}
        System.debug('dataWrappers>>>'+dataWrappers);
		return dataWrappers;
	}

	public class DataWrapper{
		@AuraEnabled
		public String Name{ get; set; }

		@AuraEnabled
		public String Revision{ get; set; }

		@AuraEnabled
		public String DocumentNumber{ get; set; }

		@AuraEnabled
		public String AttachmentId{ get; set; }

		public DataWrapper(){
			Name = '';
			Revision = '';
			DocumentNumber = '';
			AttachmentId = '';
		}
	}
}