objects/L2I_Aircraft_Service__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxAircraft Order</label>
        <referenceTo>L2I_Aircraft_Order__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Activation_Date__c</fullName>
        <label>Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>L2I_Deactivation_Date__c</fullName>
        <label>Deactivation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Matching_Id__c</fullName>
        <label>Matching Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxOrder Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>xxSubscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aircraft Service</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Aircraft Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/L2I_ReactivateAircraftService.cls
// Removed the following field Subscription__c online 12,21,50,58,70

public class L2I_ReactivateAircraftService {
    
    //Send back a string with a message instead of a boolean
    @AuraEnabled
    public static String getAircraftServiceRecords(Id recordId) {
        
        String result = '';
        L2I_Aircraft_Service__c asRecord = new L2I_Aircraft_Service__c();
        
        asRecord = [SELECT Id, Status__c, L2I_Deactivation_Date__c, Aircraft__c, Order_Product__c,
                    L2I_Activation_Date__c, Matching_Id__c
                    FROM L2I_Aircraft_Service__c 
                    WHERE Id = :recordId];
        
        // Separate function and run this method again before the insert.
        if(asRecord.Status__c == 'Deactivated' && asRecord.L2I_Deactivation_Date__c != null) {

            List<L2I_Aircraft_Service__c> asRecords = new List<L2I_Aircraft_Service__c>();
            asRecords = [SELECT Id, Status__c, L2I_Deactivation_Date__c, Aircraft__c, Order_Product__c,
                         L2I_Activation_Date__c, Matching_Id__c
                         FROM L2I_Aircraft_Service__c 
                         WHERE Aircraft__c = :asRecord.Aircraft__c 
                         AND Matching_Id__c = :asRecord.Matching_Id__c
                         AND (Status__c = 'Pending Activation' OR Status__c = 'Activated')];
            
            if(asRecords.size() == 0) {
                result = 'Success';
            } else {
                System.debug('asRecords: ' + asRecords[0].Id);
                result = 'There is an existing record with the same Billing Matching Id with a Status of Pending Activation or Activated.';
            }
            
        } else {
            result = 'This record\'s Status is not Deactivated or the Deactivation Date is missing.';
        }
        
        System.debug('result: ' + result);
        return result;
        
    }
    
    @AuraEnabled
    public static String activateServiceRecord(Id recordId, Date activationDate) {
        
        String result = '';
        L2I_Aircraft_Service__c asRecord = new L2I_Aircraft_Service__c();
        
        asRecord = [SELECT Id, Status__c, L2I_Deactivation_Date__c, Aircraft__c, Order_Product__c,
                    L2I_Activation_Date__c, Matching_Id__c, Product2__c
                    FROM L2I_Aircraft_Service__c 
                    WHERE Id = :recordId];
        
        if(asRecord.Status__c == 'Deactivated' && asRecord.L2I_Deactivation_Date__c != null) {
            
            List<L2I_Aircraft_Service__c> asRecords = new List<L2I_Aircraft_Service__c>();
            asRecords = [SELECT Id, Status__c, L2I_Deactivation_Date__c, Aircraft__c, Order_Product__c,
                         L2I_Activation_Date__c, Matching_Id__c
                         FROM L2I_Aircraft_Service__c 
                         WHERE Aircraft__c = :asRecord.Aircraft__c 
                         AND Matching_Id__c = :asRecord.Matching_Id__c
                         AND (Status__c = 'Pending Activation' OR Status__c = 'Activated')];
            
            if(asRecords.size() == 0) {
                
                L2I_Aircraft_Service__c newAsRecord = new L2I_Aircraft_Service__c(
                    Aircraft__c = asRecord.Aircraft__c,
                    Matching_Id__c = asRecord.Matching_Id__c,
                    //Aircraft_Order__c = asRecord.Aircraft_Order__c,
                    Order_Product__c = asRecord.Order_Product__c,
                    //Subscription__c = asRecord.Subscription__c,
                    L2I_Activation_Date__c = activationDate,
                    Product2__c = asRecord.Product2__c
                );
                
                try {
                    
                    insert newAsRecord;
                    result = newAsRecord.Id;
                    
                } catch(DmlException e) {
                    
                    for (Integer i = 0; i < e.getNumDml(); i++) {
                        System.debug('error: ' + e.getDmlMessage(i));
                        result = e.getDmlMessage(i);
                    }
                    
                }
                
            } else {
                System.debug('asRecords: ' + asRecords[0].Id);
                result = 'There is an existing record with the same Billing Matching Id with a Status of Pending Activation or Activated.';
            }
            
        }
        
        System.debug('result: ' + result);
        return result;
        
    }
    
    
}