objects/L2I_Aircraft_Service__c.object
<CustomObject>
    <fields>
        <fullName>L2I_Activation_Date__c</fullName>
        <label>Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>L2I_Deactivation_Date__c</fullName>
        <label>Deactivation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>L2I_Suspended__c</fullName>
        <formula>IF(Sub_Category_2__c = &quot;WiFi&quot; , INCLUDES( Aircraft__r.L2I_Suspended_Products__c  , &quot;WiFi&quot;), 
			IF(Sub_Category_2__c = &quot;Games&quot; , INCLUDES( Aircraft__r.L2I_Suspended_Products__c  , &quot;Games&quot;), 
			IF(Sub_Category_2__c = &quot;TV/Media&quot; , INCLUDES( Aircraft__r.L2I_Suspended_Products__c  , &quot;TV/Media&quot;), 
			IF(Sub_Category_2__c = &quot;Advertising&quot; , INCLUDES( Aircraft__r.L2I_Suspended_Products__c  , &quot;Advertising&quot;), 
			IF(Sub_Category_2__c = &quot;Cell Modem&quot; , INCLUDES( Aircraft__r.L2I_Suspended_Products__c  , &quot;Cell Modem&quot;), 
			False)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Suspended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Matching_Id__c</fullName>
        <label>Matching Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Aircraft Services</relationshipLabel>
        <relationshipName>Aircraft_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Aircraft Service</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Aircraft Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aircraft Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Service_Activation_Type__c</fullName>
        <label>Service Activation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>OneTime</fullName>
                </value>
                <value>
                    <fullName>Monthly-DR</fullName>
                    <isActive>false</isActive>
                    <label>Monthly-DR</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2I_ASAggregateResultIterator.cls
/**
 *      @author       Sarah Kennedy
 *      @date         03/16/2020
 *      @description  Iterator class called from L2I_ASAggregateResultIterable class for use in allowing
 *                    aggregate SOQL in L2I_AircraftServiceUsageBatch
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Sarah Kennedy                 01/03/2020         Initial creation based on https://help.salesforce.com/articleView?id=000333422&type=1&mode=1
 *      Sanjay Singhal                07/23/2020         US2009 - added a filter to not count suspended ASA records L2I_Suspended__c = false
 */
global class L2I_ASAggregateResultIterator Implements Iterator<AggregateResult> {
    AggregateResult [] results { get; set; }
    Integer index { get; set; }
    global L2I_ASAggregateResultIterator(Date BATCH_RUN_DATE) {
        index = 0;
        results = Database.query( 'SELECT Count(Id) recCount, ' +
                    '     Matching_Id__c billMatch ' +
                    'FROM L2I_Aircraft_Service__c ' +
                    '  WHERE Product2__r.L2I_Service_Activation_Type__c like \'Monthly%\' ' +
                    '    AND Product2__r.SBQQ__ChargeType__c = \'Usage\' ' +
                    '    AND L2I_Activation_Date__c != null ' +
                    '    AND L2I_Activation_Date__c <= :BATCH_RUN_DATE ' +
                    '    AND (L2I_Deactivation_Date__c = null OR L2I_Deactivation_Date__c > :BATCH_RUN_DATE) ' +
                    '    AND Status__c <> \'Canceled\' ' +
                    '    AND Matching_Id__c != null ' +
                    '    AND L2I_Suspended__c = false ' +
                    'GROUP BY Matching_Id__c ');
    }
    
    global boolean hasNext() {
        return results != null && !results.isEmpty() && index < results.size();
    }
    global AggregateResult next() {
        // index gets incremented after return
        return results[index++];
    }
}