objects/L2I_Order_Activation_Execution_Log__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Execution_Date__c</fullName>
        <label>Execution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Name__c</fullName>
        <label>Log Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step1_Entry_Time__c</fullName>
        <label>Step1 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step1_Exit_Time__c</fullName>
        <label>Step1 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step1_Log_Message__c</fullName>
        <label>Step1 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step1_Name__c</fullName>
        <label>Step1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step1_Status__c</fullName>
        <label>Step1 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step2_Entry_Time__c</fullName>
        <label>Step2 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step2_Exit_Time__c</fullName>
        <label>Step2 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step2_Log_Message__c</fullName>
        <label>Step2 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step2_Name__c</fullName>
        <label>Step2 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step2_Status__c</fullName>
        <label>Step2 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step3_Entry_Time__c</fullName>
        <label>Step3 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step3_Exit_Time__c</fullName>
        <label>Step3 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step3_Log_Message__c</fullName>
        <label>Step3 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step3_Name__c</fullName>
        <label>Step3 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step3_Status__c</fullName>
        <label>Step3 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step4_Entry_Time__c</fullName>
        <label>Step4 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step4_Exit_Time__c</fullName>
        <label>Step4 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step4_Log_Message__c</fullName>
        <label>Step4 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step4_Name__c</fullName>
        <label>Step4 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step4_Status__c</fullName>
        <label>Step4 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step5_Entry_Time__c</fullName>
        <label>Step5 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step5_Exit_Time__c</fullName>
        <label>Step5 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step5_Log_Message__c</fullName>
        <label>Step5 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step5_Name__c</fullName>
        <label>Step5 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step5_Status__c</fullName>
        <label>Step5 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step6_Entry_Time__c</fullName>
        <label>Step6 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step6_Exit_Time__c</fullName>
        <label>Step6 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step6_Log_Message__c</fullName>
        <label>Step6 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step6_Name__c</fullName>
        <label>Step6 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step6_Status__c</fullName>
        <label>Step6 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step7_Entry_Time__c</fullName>
        <label>Step7 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step7_Exit_Time__c</fullName>
        <label>Step7 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step7_Log_Message__c</fullName>
        <label>Step7 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step7_Name__c</fullName>
        <label>Step7 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step7_Status__c</fullName>
        <label>Step7 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step8_Entry_Time__c</fullName>
        <label>Step8 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step8_Exit_Time__c</fullName>
        <label>Step8 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step8_Log_Message__c</fullName>
        <label>Step8 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step8_Name__c</fullName>
        <label>Step8 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step8_Status__c</fullName>
        <label>Step8 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Order Contract Management Log</label>
    <nameField>
        <displayFormat>OAL-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Contract Management Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2I_OAExecutionLog_Helper.cls
/**
 *      @author       Raj Rajen
 *      @date         08/17/2019
 *      @description  Helper Class L2I Order Activation Execution Log
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Raj Rajen                     08/17/2019            Initial Setup
 *      Sarah Kennedy                 06/26/2020            US2046 expand to allow other types of logginf
 *
 */
public without sharing class L2I_OAExecutionLog_Helper {
    public static String logName = 'Order Activation';
    
    public L2I_OAExecutionLog_Helper() {
        this(logName);
    }
    
    public L2I_OAExecutionLog_Helper(String logName) {
        logName = logName;
    }
    
    public static L2I_Order_Activation_Execution_Log__c createLogEntry() {
        L2I_Order_Activation_Execution_Log__c oaeLog = createLogEntry(logName);
        return oaeLog;
    }
    
    public static L2I_Order_Activation_Execution_Log__c createLogEntry(String logName) {
        L2I_Order_Activation_Execution_Log__c log = new L2I_Order_Activation_Execution_Log__c();
        log.Step1_Log_Message__c = '';
        log.Step2_Log_Message__c = '';
        log.Step3_Log_Message__c = '';
        log.Step4_Log_Message__c = '';
        log.Step5_Log_Message__c = '';
        log.Step6_Log_Message__c = '';
        log.Step7_Log_Message__c = '';
        log.Step8_Log_Message__c = '';
        log.Log_Name__c = logName;
        insert log;
        
        L2I_Order_Activation_Execution_Log__c logEntry = [
              SELECT Id,
                    GUID__c,
                    Batch_Date__c,
                    Execution_Date__c,
                    Step1_Name__c,
                    Step2_Name__c,
                    Step3_Name__c,
                    Step4_Name__c,
                    Step5_Name__c,
                    Step6_Name__c,
                    Step7_Name__c,
                    Step8_Name__c,
                    Step1_Entry_Time__c,
                    Step1_Exit_Time__c,
                    Step1_Status__c,
                    Step1_Log_Message__c,
                    Step2_Entry_Time__c,
                    Step2_Exit_Time__c,
                    Step2_Status__c,
                    Step2_Log_Message__c,
                    Step3_Entry_Time__c,
                    Step3_Exit_Time__c,
                    Step3_Status__c,
                    Step3_Log_Message__c,
                    Step4_Entry_Time__c,
                    Step4_Exit_Time__c,
                    Step4_Status__c,
                    Step4_Log_Message__c,
                    Step5_Entry_Time__c,
                    Step5_Exit_Time__c,
                    Step5_Status__c,
                    Step5_Log_Message__c,
                    Step6_Entry_Time__c,
                    Step6_Exit_Time__c,
                    Step6_Status__c,
                    Step6_Log_Message__c,
                    Step7_Entry_Time__c,
                    Step7_Exit_Time__c,
                    Step7_Status__c,
                    Step7_Log_Message__c,
                    Step8_Entry_Time__c,
                    Step8_Exit_Time__c,
                    Step8_Status__c,
                    Step8_Log_Message__c,
                    Log_Name__c
              FROM L2I_Order_Activation_Execution_Log__c
              WHERE Id = :log.Id
              LIMIT 1
        ];
        return logEntry;
    }
    
    public static String getGUID(L2I_Order_Activation_Execution_Log__c logEntry) {
        return logEntry.GUID__c;
    }
    
    public static L2I_Order_Activation_Execution_Log__c getLogEntry(String guid) {
        
        L2I_Order_Activation_Execution_Log__c logEntry = [
              SELECT Id,
                    GUID__c,
                    Batch_Date__c,
                    Execution_Date__c,
                    Step1_Name__c,
                    Step2_Name__c,
                    Step3_Name__c,
                    Step4_Name__c,
                    Step5_Name__c,
                    Step6_Name__c,
                    Step7_Name__c,
                    Step8_Name__c,
                    Step1_Entry_Time__c,
                    Step1_Exit_Time__c,
                    Step1_Status__c,
                    Step1_Log_Message__c,
                    Step2_Entry_Time__c,
                    Step2_Exit_Time__c,
                    Step2_Status__c,
                    Step2_Log_Message__c,
                    Step3_Entry_Time__c,
                    Step3_Exit_Time__c,
                    Step3_Status__c,
                    Step3_Log_Message__c,
                    Step4_Entry_Time__c,
                    Step4_Exit_Time__c,
                    Step4_Status__c,
                    Step4_Log_Message__c,
                    Step5_Entry_Time__c,
                    Step5_Exit_Time__c,
                    Step5_Status__c,
                    Step5_Log_Message__c,
                    Step6_Entry_Time__c,
                    Step6_Exit_Time__c,
                    Step6_Status__c,
                    Step6_Log_Message__c,
                    Step7_Entry_Time__c,
                    Step7_Exit_Time__c,
                    Step7_Status__c,
                    Step7_Log_Message__c,
                    Step8_Entry_Time__c,
                    Step8_Exit_Time__c,
                    Step8_Status__c,
                    Step8_Log_Message__c,
                    Log_Name__c
              FROM L2I_Order_Activation_Execution_Log__c
              WHERE GUID__c = :guid
              ORDER BY CreatedDate DESC
              LIMIT 1
        ];
        return logEntry;
    }
    
    public static void updateLogEntry(L2I_Order_Activation_Execution_Log__c logEntry) {
        update logEntry;
    }

}