objects/L2I_System_Alert__c.object
<CustomObject>
    <description>A custom object that can be used to store system alerts, which upon creation will notify designated email addresses or perhaps post to slack channel etc.</description>
    <fields>
        <fullName>Alert_Code__c</fullName>
        <description>A compound key unique identifier. This will be a concatenation of Alert_Type__c and Timestamp__c .</description>
        <externalId>true</externalId>
        <label>Alert Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <label>Alert Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Connection Timeout</fullName>
                </value>
                <value>
                    <fullName>Invalid Value for Setting</fullName>
                </value>
                <value>
                    <fullName>Missing Custom Metadata Type</fullName>
                </value>
                <value>
                    <fullName>Missing Custom Setting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Batch Job Exception</fullName>
                </value>
                <value>
                    <fullName>Callout Exception</fullName>
                </value>
                <value>
                    <fullName>Internal Server Error</fullName>
                </value>
                <value>
                    <fullName>JSON Parsing Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message associated with the Alert</description>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to indicate if notification email has been sent for this alert.</description>
        <label>Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Ids__c</fullName>
        <label>Object Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>System_Alerts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <description>Timestamp is stored as YYYYMMDDhhmm note that the mm part will be rounded off to 00, 15, 30 or 45 so that at most only 4 records per hour will be stored. This is to prevent the email inbox of alert recipients from getting flooded with messages.</description>
        <label>Timestamp</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>System Alert</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>System Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2I_SystemAlertNotifier.cls
/**
 *      @author       Raj Rajen
 *      @date         08/07/2019
 *      @description  Alert Notifier helper class

        Modification Log:
        ------------------------------------------------------------------------------------
        Developer                       Date                Description
        ------------------------------------------------------------------------------------
        Raj Rajen                     08/07/2019         Initial setup of class

 */
global class L2I_SystemAlertNotifier {
    
    //private static final String ALERT_RECIPIENT = 'rrajen@salesforce.com';
    //private static final String ALERT_SENDER = 'cep-alert-notifier@panasonic.aero';
    
    public static void createSystemAlert(String type, String message) {
        
        if (type == null || String.isEmpty(type)) {
            type = 'Unknown';
        }
        
        String currentTS = getTimeStamp();
        String uniqueId = type + ':' + currentTS;
        
        L2I_System_Alert__c alert = new L2I_System_Alert__c();
        alert.Alert_Type__c = type;
        alert.Timestamp__c = currentTS;
        alert.Alert_Code__c = uniqueId;
        alert.Notification_Sent__c = false;
        alert.Message__c = message;
        
        System.debug('====== Attempting to upsert System_Alert__c with uniqueId :' + uniqueId);
        Database.upsert(alert, L2I_System_Alert__c.Fields.Alert_Code__c);
    }
    
    public static Id createSystemAlert(String type, String message, String objectName, String objectIds, String userId, Boolean sendEmail) {
        
        if (type == null || String.isEmpty(type)) {
            type = 'Unknown';
        }
        
        String currentTS = getTimeStamp();
//        String uniqueId = type + ':' + currentTS;
        String uniqueId = type + ':' + L2I_UtilityHelper.generateGuid();
        
        Id alertId;
        List<L2I_System_Alert__c> alertList = new List<L2I_System_Alert__c>();
        alertList = [
              select Id,
                    Alert_Type__c,
                    Timestamp__c,
                    Alert_Code__c,
                    Notification_Sent__c,
                    Message__c,
                    Object_Name__c,
                    Object_Ids__c,
                    Running_User__c,
                    Send_Email__c
              FROM L2I_System_Alert__c
              WHERE Alert_Code__c = :uniqueId
        ];
        if (alertList != NULL && alertList.size() > 0) {
            alertList[0].Alert_Type__c = type;
            alertList[0].Timestamp__c = currentTS;
            alertList[0].Notification_Sent__c = false;
            alertList[0].Message__c = message.length() > 131000 ? message.substring(0, 131000) : message;
            alertList[0].Object_Name__c = objectName;
            alertList[0].Object_Ids__c = (objectIds != NULL && objectIds.length() > 255) ? objectIds.abbreviate(255) : objectIds;
            alertList[0].Running_User__c = userId;
            alertList[0].Send_Email__c = sendEmail;
            update alertList;
            alertId = alertList[0].Id;
        } else {
            L2I_System_Alert__c alert = new L2I_System_Alert__c();
            alert.Alert_Type__c = type;
            alert.Timestamp__c = currentTS;
            alert.Alert_Code__c = uniqueId;
            alert.Notification_Sent__c = false;
            alert.Message__c = message.length() > 131000 ? message.substring(0, 131000) : message;
            alert.Object_Name__c = objectName;
            alert.Object_Ids__c = (objectIds != NULL && objectIds.length() > 255) ? objectIds.abbreviate(255) : objectIds;
            alert.Running_User__c = userId;
            alert.Send_Email__c = sendEmail;
            
            System.debug('====== Attempting to upsert System_Alert__c with uniqueId :' + uniqueId);
            insert alert;
            alertId = alert.Id;
        }
        System.debug('====== Attempting to upsert System_Alert__c with uniqueId :' + uniqueId);
        return alertId;
    }
    
    //@future(callout=true)
    public static void sendEmailNotifications(Set<Id> alertIds) {
        
        //Set<String> ALERT_RECIPIENTS = L2I_GeneralSettings.getSystemAlertRecipients();
        //String ALERT_SENDER = L2I_GeneralSettings.getSystemAlertSender();
        // modifications to use JSON Settings instead of GeneralSettings
        Set<String> ALERT_RECIPIENTS = L2I_JSON_Settings.getSpecificSettingCollection('System_Alert_Settings', 'Recipients');
        String ALERT_SENDER = L2I_JSON_Settings.getSpecificSetting('System_Alert_Settings', 'Sender');
        
        List<L2I_System_Alert__c> alerts = [
              select Id,
                    Alert_Type__c,
                    Timestamp__c,
                    Alert_Code__c,
                    Notification_Sent__c,
                    Message__c,
                    Object_Name__c,
                    Object_Ids__c,
                    Running_User__c,
                    Send_Email__c
              
              from L2I_System_Alert__c
              where Id in :alertIds
        ];
        
        System.debug('===== Number of alerts to send emails for :' + alerts.size());
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>{
        };
        
        for (L2I_System_Alert__c alert : alerts) {
            if (alert.Send_Email__c) {
//build the message
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setSaveAsActivity(false);
                message.setSubject('System Alert (Org Id:' + UserInfo.getOrganizationId() + ') -- ' + alert.Alert_Type__c);
//message.setPlainTextBody(body);
                message.setHtmlBody('Link: ' + Url.getSalesforceBaseUrl().toExternalForm() + '/' + alert.Id + ':<br/> ' + alert.Message__c);
                message.setToAddresses(new List<String>(ALERT_RECIPIENTS));
                message.setReplyTo(ALERT_SENDER);
                
                messages.add(message);
            }
        }
        
        if (!messages.isEmpty()) {
            System.debug('====== Sending all System Alert email messages. Size :' + messages.size());
            List<Messaging.SendEmailResult> res = Messaging.sendEmail(messages);
        } else {
            System.debug('====== No System Alert email messages to send');
        }
    
    }

//@future(callout=true)
//public static void sendSlackNotifications(Set<Id> alertIds) {
//
//}
    
    public static String getTimeStamp() {
        String ts = '';
        Datetime now = System.now();
        
        Integer min = now.minute();
        String quarterDescriptor = '';
        if (min < 15) {
            quarterDescriptor = '00';
        } else if (min < 30) {
            quarterDescriptor = '15';
        } else if (min < 45) {
            quarterDescriptor = '30';
        } else {
            quarterDescriptor = '45';
        }
        
        ts = now.format('yyyyMMddHH') + quarterDescriptor;
        
        return ts;
    }

}