objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link by custom field to the associated aircraft object</inlineHelpText>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Aircraft_Program_Identification_Field__c</fullName>
        <description>The Program specific Identifier of the Aircraft</description>
        <formula>if( Text(PT_Program__r.Aircraft_Identifier_Field__c) = &#39;Block Number&#39;, Aircraft__r.L2I_Block_Number__c
,IF(Text(PT_Program__r.Aircraft_Identifier_Field__c) = &#39;Fleet Number&#39;, Aircraft__r.L2I_Fleet_Number__c
,IF(Text(PT_Program__r.Aircraft_Identifier_Field__c) = &#39;Line Number&#39;, Aircraft__r.L2I_Line_Number__c
,IF(Text(PT_Program__r.Aircraft_Identifier_Field__c) = &#39;Serial Number&#39;, Aircraft__r.L2I_Serial_Number__c
,IF(Text(PT_Program__r.Aircraft_Identifier_Field__c) = &#39;Tail Number&#39;, Aircraft__r.L2I_Registration_Number__c
, Aircraft_Identifier__c
)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Program specific Identifier of the Aircraft</inlineHelpText>
        <label>Aircraft Program Identification Field</label>
        <type>Text</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_AC_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (A/C Operator)</relationshipLabel>
        <relationshipName>AircraftOperatorOpportunties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Aircraft Owner)</relationshipLabel>
        <relationshipName>Aircraft_Owner_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Type</label>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Fit_Type__c</fullName>
        <label>Fit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>L2I_Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell/Follow-on</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2I_Primary_System_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary System Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.L2I_System_Type_Translation__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>System Type Translation must not be blank.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Num__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Number</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Approver_Comments__c</fullName>
        <label>PL Approval Approver Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PL Approval Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Date__c</fullName>
        <label>PL Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Submitter_Comments__c</fullName>
        <label>PL Approval Submitter Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval</description>
        <label>PL Approval Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name__c</fullName>
        <label>Part List Name</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PT_Program_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval flow</description>
        <label>Program Mgr</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Revised_Parts_List_Version_Trans__c</fullName>
        <label>Revised Parts List Version Trans</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Fit_Type__c</fullName>
        <label>Fit Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestExportToExcelController.cls
public with sharing class TestExportToExcelController
{
    public Opportunity oppty { get; set; }
//    public List<PartListRevision> plrListWrapper { get; set; }
//    public List<NoteWrapper> noteWrapperList { get; set; }
//    public List<InstallLocWrapper> iLocWrapperList { get; set; }
    public OppWrapper oppw { get; set; }

    public List<Account> accountList{get;set;}
    public List<Contact> contactList{get;set;}
    public String xlsHeader
    {
        get {
            String strHeader = '';
            strHeader += '<?xml version="1.0"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }

    public TestExportToExcelController(ApexPages.StandardController controller)
    {
        accountList = [select id, name from Account LIMIT 50];
        contactList = [Select id, name, account.name, email from Contact LIMIT 50];
        oppty = [
              SELECT Id, Name, PT_Program_Mgr__r.email, PT_Program_Mgr__r.Name,
                    PT_PL_Approval_Approver__r.Name, PT_PL_Approval_Approver_Comments__c,
                    PT_PL_Approval_Submitter__r.Name, PT_PL_Approval_Submitter_Comments__c,
                    PT_Part_List_Name__c, PT_Revised_Parts_List_Version_Trans__c,
                    PT_PL_Approval_Date__c, L2I_Program_Num__r.Name, L2I_AC_Operator__r.Name, L2I_Aircraft_Owner__r.Name,
                    L2I_Fit_Type__c, L2I_Aircraft_Type__r.Name,
                    L2I_Primary_System_Type__r.Name
              FROM Opportunity
              WHERE Id = :controller.getId()
        ];

        oppw = new OppWrapper();
        oppw.aircraftType = oppty.L2I_Aircraft_Type__r.Name;
        oppw.fitType = oppty.L2I_Fit_Type__c + ' - ' + oppty.L2I_Primary_System_Type__r.Name;
        oppw.operator = oppty.L2I_AC_Operator__r.Name;
        oppw.owner = oppty.L2I_Aircraft_Owner__r.Name;
        oppw.program = oppty.L2I_Program_Num__r.Name;
        oppw.partListName = oppty.PT_Part_List_Name__c;
        oppw.rev = oppty.PT_Revised_Parts_List_Version_Trans__c;

        for (L2I_DSL__c dsl : [
              SELECT Id, PT_Aircraft_Program_Identification_Field__c, Aircraft__r.Name
              FROM L2I_DSL__c
              WHERE Original_Opportunity__c = :controller.getId()
        ]) {
            SSWrapper ssw = new SSWrapper();
            ssw.ssName = dsl.Aircraft__c != null ? dsl.Aircraft__r.Name : '';
            ssw.programAircraftField = dsl.PT_Aircraft_Program_Identification_Field__c;
            oppw.ssWrapperList.add(ssw);
            if (ssw.ssName != '') {
                oppw.eff += oppw.eff == '' ? ssw.ssName : ';' + ssw.ssName;
            }
        }

    }

    public Pagereference TestExportToExcel2()
    {
        return new Pagereference('/apex/TestExportToExcel2');
    }

    public class OppWrapper {
        public String operator { get; set; }
        public String owner { get; set; }
        public String fitType { get; set; }
        public String aircraftType { get; set; }
        public String program { get; set; }
        public String partListName { get; set; }
        public String rev { get; set; }
        public String eff { get; set; }
        public String seats { get; set; }
        public List<SSWrapper> ssWrapperList { get; set; }

        public OppWrapper() {
            this.ssWrapperList = new List<SSWrapper>();
            this.eff = '';
        }
    }

    public class SSWrapper {
        public String ssName { get; set; }
        public String programAircraftField { get; set; }
    }
}