objects/L2I_General_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Usage_Batch_Size__c</fullName>
        <label>Usage Batch Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>L2I General Settings</label>
    <pluralLabel>L2I General Settings</pluralLabel>
</CustomObject>

classes/L2I_AutomateExistingDealOppSched.cls
global class L2I_AutomateExistingDealOppSched implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        
        Integer batchSize = Integer.valueOf([SELECT Usage_Batch_Size__c 
                                             FROM L2I_General_Settings__mdt 
                                             LIMIT 1].Usage_Batch_Size__c);
        System.debug('batchSize: ' + batchSize);
        
        L2I_AutomateExistingDealOppBatch b = new L2I_AutomateExistingDealOppBatch();
        
        database.executebatch(b, 200);
    }
    
}