objects/L2I_P_L_Approval__c.object
<CustomObject>
    <description>This object is used to track P&amp;L approvals submitted by Sales Team Members at a Deal Level</description>
    <fields>
        <fullName>L2I_P_L_Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>P&amp;L Approvals</relationshipLabel>
        <relationshipName>P_L_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>P&amp;L Approval</label>
    <nameField>
        <displayFormat>PandL-{00000}</displayFormat>
        <label>P&amp;L Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;L Approvals</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>New Record Type to accomodate IFC section</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_P_L_Sales_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>L2I_P_L_Approval__c</fullName>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipLabel>P&amp;L Sales Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Related_To_P_L</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>L2I_Total_Seat_Count__c</fullName>
        <formula>L2I_Sales_Opportunity__r.L2I_Total_Seat_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Seat Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>P&amp;L Sales Opportunity</label>
    <nameField>
        <displayFormat>ORPAL-{00000}</displayFormat>
        <label>Opportunities Related To P&amp;L Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;L Sales Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Total_Seat_Count__c</fullName>
        <formula>SBQQ__PrimaryQuote__r.L2I_Total_Seat_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Seat Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <businessProcess>Deal Process</businessProcess>
        <label>Deal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PL_CAL__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Type__c</fullName>
        <label>Allocation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of COST</fullName>
                </value>
                <value>
                    <fullName>% of NET SALES</fullName>
                </value>
                <value>
                    <fullName>Warranty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost_Allocation_Item__c</fullName>
        <formula>PL_MD__r.Cost_Allocation_Item__c</formula>
        <label>Cost Allocation Item</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Allocation__c</fullName>
        <formula>PL_MD__r.Cost_Allocation__c</formula>
        <label>Cost Allocation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Migration_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PL_MD__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Master Data</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PL_MD__c.MD_Type__c</field>
                <operation>equals</operation>
                <value>Cost Allocation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PL_MD__c</referenceTo>
        <relationshipLabel>Cost Allocations</relationshipLabel>
        <relationshipName>Cost_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <referenceTo>PL_Product_Group__c</referenceTo>
        <relationshipLabel>Cost Allocations</relationshipLabel>
        <relationshipName>Cost_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>PL_MD__r.Sort_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cost Allocation</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PL_MD__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Display Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Allocation_Item__c</fullName>
        <label>Cost Allocation Item</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Allocation__c</fullName>
        <label>Cost Allocation</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Migration_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MD_Type__c</fullName>
        <label>Master Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost Allocation</fullName>
                </value>
                <value>
                    <fullName>Product Group</fullName>
                </value>
                <value>
                    <fullName>Product Summary</fullName>
                </value>
                <value>
                    <fullName>CreditType2PS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>P&amp;L Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Master Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PL_Product_Group__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>Start_Date__c &lt;= TODAY() &amp;&amp; (ISNULL(End_Date__c) || End_Date__c &gt;=Today())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Migration_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PL_MD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Data</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PL_MD__c.MD_Type__c</field>
                <operation>equals</operation>
                <value>Product Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PL_MD__c</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <formula>PL_MD__r.Product_Group__c</formula>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PL_PS__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <label>Credit</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Sales__c</fullName>
        <description>Hold total Standard Price from all Quote Lines.</description>
        <label>Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Sales__c</fullName>
        <label>Net Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Group</label>
        <referenceTo>PL_Product_Group__c</referenceTo>
        <relationshipName>Product_Summary_by_Ins_Loc</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>Product_Summary_by_Ins_Loc</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>Product_Summary__r.Sort_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Product Summary</label>
    <nameField>
        <label>Product Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PLA_Page_ConsolidatedList__c.object
<CustomObject>
    <description>Stores the data in the Consolidated list from the PL_Calculate Page/Controller (VFP). Then it is is used to render the data in the PL_View page for Product Services</description>
    <fields>
        <fullName>P_L_Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipName>PLA_Page_ConsolidatedLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Archived Consolidated Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived Consolidated Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PLA_Page_ProductServices_List__c.object
<CustomObject>
    <description>Stores the data in the Product Service list from the PL_Calculate Page/Controller (VFP). Then it is is used to render the data in the PL_View page for Product Services</description>
    <fields>
        <fullName>Gross_Sales__c</fullName>
        <label>Gross Sales</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P_L_Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>P&amp;L Approval</label>
        <referenceTo>L2I_P_L_Approval__c</referenceTo>
        <relationshipName>PLA_Page_ProductServices_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Archived ProductServices Data</label>
    <nameField>
        <label>Product Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived ProductServices Data Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PLA_Page_ShipsetList__c.object
<CustomObject>
    <description>Stores the data in the Shipset list from the PL_Calculate Page/Controller (VFP). Then it is is used to render the data in the PL_View page for Product Services</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Archived Shipset Data</label>
    <nameField>
        <label>PLA Page_ShipsetList Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archived Shipset Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PL_newView2ControllerTest.cls
@isTest
public with sharing class PL_newView2ControllerTest {
   
    private static L2I_P_L_Approval__c plApproval;
    private static void setupHeader(){

        List<PL_MD__c> lstPlmd = new List<PL_MD__c>();
        PL_MD__c plmd = new PL_MD__c();
        plmd.Name='IFE Hardware';
        plmd.Pillar__c='IFE';
        plmd.Product_Group__c='IFE Hardware';
        plmd.Sort_Order__c=1;
        plmd.Sort_Order__c=90;
        plmd.MD_Type__c ='Product Group';
        lstPlmd.add(plmd);
       
        PL_MD__c plmd1 = new PL_MD__c();
        plmd1.Name='IFE Services';
        plmd1.Pillar__c='IFE';
        plmd1.Product_Group__c='IFE Hardware';
        plmd1.Sort_Order__c=2;
        plmd1.Sort_Order__c=80;
        plmd1.MD_Type__c ='Product Group';
        lstPlmd.add(plmd1);
        
        PL_MD__c plmd2 = new PL_MD__c();
        plmd2.Name='IFC Hardware';
        plmd2.Pillar__c='IFC';
        plmd2.Product_Group__c='IFC Hardware';
        plmd2.Sort_Order__c=3;
        plmd2.Sort_Order__c=70;
        plmd2.MD_Type__c ='Product Group';
        lstPlmd.add(plmd2);
        
        PL_MD__c plmd3 = new PL_MD__c();
        plmd3.Name='IFC Services';
        plmd3.Pillar__c='IFC';
        plmd3.Product_Group__c='IFC Hardware';
        plmd3.Sort_Order__c=4;
        plmd3.Sort_Order__c=60;
        plmd3.MD_Type__c ='Product Group';
        lstPlmd.add(plmd3);
        
        PL_MD__c plmd4 = new PL_MD__c();
        plmd4.Name='DSS';
        plmd4.Pillar__c='DSS';
        plmd4.Product_Group__c='IFE Hardware';
        plmd4.Sort_Order__c=5;
        plmd4.Sort_Order__c=500;
        plmd4.MD_Type__c ='Product Group';
        lstPlmd.add(plmd4);
        
        PL_MD__c plmd5 = new PL_MD__c();
        plmd5.Name='PTS';
        plmd5.Pillar__c='PTS';
        plmd5.Product_Group__c='IFE Hardware';
        plmd5.Sort_Order__c=6;
        plmd5.Sort_Order__c=500;
        plmd5.MD_Type__c ='Product Group';
        lstPlmd.add(plmd5);
        insert lstPlmd;

    }
    private static void setupTestData()
    {
        L2I_DataFactory factory = new L2I_DataFactory();
        factory.setupTestContext(null, null, false);
        
        List<PL_MD__c> lstPlmd = new List<PL_MD__c>();
        
        PL_MD__c plmd6 = new PL_MD__c();
        plmd6.Name='PTS';
        plmd6.Pillar__c='PTS';
        plmd6.Product_Group__c='IFE Hardware';
        plmd6.Sort_Order__c=6;
        plmd6.Sort_Order__c=500;
        plmd6.MD_Type__c ='Product Summary';
        lstPlmd.add(plmd6);
        
        PL_MD__c plmd7 = new PL_MD__c();
        plmd7.Name='DSS';
        plmd7.Pillar__c='DSS';
        plmd7.Product_Group__c='IFE Hardware';
        plmd7.Sort_Order__c=105;
        plmd7.Sort_Order__c=500;
        plmd7.MD_Type__c ='Product Summary';
        lstPlmd.add(plmd7);
        
        PL_MD__c plmd8 = new PL_MD__c();
        plmd8.Name='DSS';
        plmd8.Pillar__c='DSS';
        plmd8.Product_Group__c='IFE Hardware';
        plmd8.Sort_Order__c=105;
        plmd7.Sort_Order__c=500;
        plmd8.MD_Type__c ='-PCT';
        //lstPlmd.add(plmd8);
        
        insert lstPlmd;
        //---------------------------------
        List<PL_MD__c> lstPlSum = new List<PL_MD__c>();
        PL_MD__c Prod = new PL_MD__c();
        Prod.Name='SEATEND LRU';
        Prod.Pillar__c='PTS';
        Prod.Product_Group__c='IFE Hardware';
        Prod.Sort_Order__c=6;
        Prod.MD_Type__c ='Product Summary';
        lstPlSum.add(Prod);
        
        insert lstPlSum;
        //----------------------------------------------------------------
        
        List<PL_MD__c> lstcost = new List<PL_MD__c>();
        PL_MD__c ProdSum1 = new PL_MD__c();
        ProdSum1.Name='Gross Sales';
        ProdSum1.Pillar__c='PTS';
        ProdSum1.Product_Group__c='IFE Hardware';
        ProdSum1.Sort_Order__c=6;
        ProdSum1.L2I_Migration_External_Id__c='CAL-COGS-GM';
        ProdSum1.MD_Type__c ='Cost Allocation';
        ProdSum1.Cost_Allocation__c='Gross Sales';
        ProdSum1.color__c='#8da2c1';
        lstcost.add(ProdSum1);
        
        PL_MD__c ProdSum11 = new PL_MD__c();
        ProdSum11.Name='Gross';
        ProdSum11.Pillar__c='PTS';
        ProdSum11.Product_Group__c='IFE Hardware';
        ProdSum11.Sort_Order__c=6;
        ProdSum11.color__c='#8da2c1';
        ProdSum11.L2I_Migration_External_Id__c='-SALES-';
        ProdSum11.MD_Type__c ='Cost Allocation';
        ProdSum11.Cost_Allocation__c='Gross Sales';
        lstcost.add(ProdSum11);
        
        PL_MD__c ProdSum2 = new PL_MD__c();
        ProdSum2.Name='Discount & Allowances';
        ProdSum2.Pillar__c='PTS';
        ProdSum2.Product_Group__c='IFE Hardware';
        ProdSum2.Sort_Order__c=6;
        ProdSum2.L2I_Migration_External_Id__c='123456782-PCT';
        ProdSum2.MD_Type__c ='Cost Allocation';
        ProdSum2.color__c='#8da2c1';
        lstcost.add(ProdSum2);
        
        PL_MD__c ProdSum3 = new PL_MD__c();
        ProdSum3.Name='Pct (%) Discount/Credits';
        ProdSum3.Pillar__c='PTS';
        ProdSum3.Product_Group__c='IFE Hardware';
        ProdSum3.Sort_Order__c=6;
        ProdSum3.L2I_Migration_External_Id__c='CAL-AC-PBT';
        ProdSum3.MD_Type__c ='Cost Allocation';
        ProdSum3.color__c='#8da2c1';
        lstcost.add(ProdSum3);
        
        PL_MD__c ProdSum4 = new PL_MD__c();
        ProdSum4.Name='TOTAL - SALES';
        ProdSum4.Pillar__c='PTS';
        ProdSum4.Product_Group__c='IFE Hardware';
        ProdSum4.Sort_Order__c=6;
        ProdSum4.L2I_Migration_External_Id__c='123456784-PCT';
        ProdSum4.MD_Type__c ='Cost Allocation';
        ProdSum4.color__c='#8da2c1';
        ProdSum4.Sort_Order__c=500;
        lstcost.add(ProdSum4);
        insert lstcost;
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        quote.SBQQ__Type__c='Quote';
        //quote.L2I_Total_Seat_Count__c='190';
        insert quote;

        PL_MD__c plmd = new PL_MD__c();
        plmd.Name='IFE Hardware';
        plmd.Pillar__c='IFE';
        plmd.Product_Group__c='IFE Hardware';
        plmd.Sort_Order__c=1;
        plmd.Sort_Order__c=90;
        plmd.MD_Type__c ='Product';
        
        PL_Product_Group__c pg = new PL_Product_Group__c();
        pg.PL_MD__c = plmd.id;
        pg.Start_Date__c = system.today().addDays(-1);
        //pg.is_Active__c=true;
        insert pg;       
        
        PL_MD__c PL_MD = new PL_MD__c();
        PL_MD.Name='Administration';
        PL_MD.Sort_Order__c=630;
        PL_MD.color__c='#8da2c1';
        PL_MD.Cost_Allocation__c	='ALLOCATION COST';
        PL_MD.Cost_Allocation_Item__c	='Administration';
        PL_MD.MD_Type__c ='Cost Allocation';
        PL_MD.L2I_Migration_External_Id__c	='CAL-AC-ADMIN';
        insert PL_MD;

        
        PL_CAL__c cal = new PL_CAL__c();
        cal.Percent__c= 10; 
        //cal.Cost_Allocation__c	='ALLOCATION COST';
        //cal.Cost_Allocation_Item__c	='Administration';
        cal.Allocation_Type__c	='% of NET SALES';
        cal.pl_MD__c=PL_MD.id;  
        cal.Product_Group__c=pg.id;
        Insert cal;
        
        List<PL_PS__c> lstPs = new List<PL_PS__c>();
        PL_PS__c plps = new PL_PS__c();
        plps.Name='IFE Hardware';       
        plps.Cost__c=500;
        plps.Credit__c=100;
        plps.Quote__c=quote.Id;
        plps.Gross_Sales__c=5000;
        plps.Net_Sales__c=4500;
        plps.Product_Group__c=pg.Id;
        plps.Product_Summary__c=lstPlSum[0].id;
        lstPs.add(plps);
        
        PL_PS__c plps2 = new PL_PS__c();
        plps2.Name='IFE Services';       
        plps2.Cost__c=500;
        plps2.Credit__c=100;
        plps2.Quote__c=quote.Id;
        plps2.Gross_Sales__c=5000;
        plps2.Net_Sales__c=4500;
        plps2.Product_Group__c=pg.Id;
        plps2.Product_Summary__c=lstPlSum[0].id;
        lstPs.add(plps2);
        Insert lstPs;
        
        Id customerRecordTypeId = L2I_StaticConstants.CUSTOMER_ACCOUNT_RT_ID;
         Account acctCustomer = new Account(
              Name = 'Acct1',
              RecordTypeId = customerRecordTypeId);
        insert acctCustomer;
        
        Opportunity dealOppty = new Opportunity(
              Name = 'Deal Opp',
              CloseDate = Date.today(),
              StageName = 'Open'
        );               
        insert dealOppty;
        
         Opportunity salesOppty = new Opportunity(
              Name = 'Sales Opp',
              AccountId = acctCustomer.Id,
              RecordTypeId = L2I_StaticConstants.SALES_OPPORTUNITY_RT_ID,
              L2I_Product_Category__c = 'DSS',
              CloseDate = Date.today(),
              StageName = 'Quotation',
              L2I_Parent_Opportunity__c = dealOppty.Id
        );
        insert salesOppty;
        
         plApproval = factory.createPLApproval(dealOppty.Id, 'Approved');
        insert plApproval;
   
        L2I_P_L_Sales_Opportunity__c plSalesOpp = factory.createPLSalesOpp(plApproval.Id, salesOppty.Id);
        insert plSalesOpp;
        List<PLA_Page_ShipsetList__c> shipset = new List<PLA_Page_ShipsetList__c>();
        PLA_Page_ShipsetList__c row1 = new PLA_Page_ShipsetList__c(name = 'Row 1', PL_Approval__c = plApproval.id, Sort_order__c=0 );
        PLA_Page_ShipsetList__c row2 = new PLA_Page_ShipsetList__c(name = 'Row 2', PL_Approval__c = plApproval.id, Sort_order__c= 2);
        PLA_Page_ShipsetList__c row3 = new PLA_Page_ShipsetList__c(name = 'Row 3', PL_Approval__c = plApproval.id, Sort_order__c= 50);
        shipset.add(row1);
        shipset.Add(row2);
        shipset.Add(row3);
        insert shipset; 
        PLA_Page_ProductServices_List__c  service = new PLA_Page_ProductServices_List__c (name ='Test 4',P_L_Approval__c = plApproval.id );
        insert service; 
        PLA_Page_ConsolidatedList__c consolidated = new PLA_Page_ConsolidatedList__c(name = 'Test1', 
                                                                                    P_L_Approval__c = plApproval.id,
                                                                                    isCol_Display__c = TRUE,
            Row_Color_Code__c = 'blue',
            Row_Span_Count__c = 1,
            IFE_Hardware0__c = '1',
            IFE_Services1__c = '2',
            IFE_SubTotal2__c = '3',
            IFC_Hardware3__c = '4',
            IFC_Services4__c = '5',
            IFC_SubTotal5__c = '6',
            DSS6__c = '7',
            PTS7__c = '8',
            Total_Program8__c= '100',
            Net_Sales9__c= '500',
            Vertical_Header_Color__c= 'blue',
            Group_NameList__c ='A,B,C');
        insert consolidated;
        PLA_Page_Header__c  header = new PLA_Page_Header__c (name = 'Test2', Pl_Approval__c  = plApproval.id);
        insert header;
       
       
        PLA_Page_Opportunity_List__c opportunity = new  PLA_Page_Opportunity_List__c(name = 'Test5',pl_approval__c = PlApproval.id  );
        insert opportunity;     
      
    }

    @isTest
    private static void TestDataOnLoad() 
    {
        Test.startTest();
 
        setupTestData();
        ApexPages.StandardController standardController = new ApexPages.StandardController(plApproval); 
        PL_newViewController plview = new PL_newViewController(standardController);
        plview.bindConsolidatedHeader();
     
        Test.stopTest();
       
    }
    @isTest
    private static void TestDataOnLoadWithHeader() 
    {
        Test.startTest();
 
        setupTestData();
        ApexPages.StandardController standardController = new ApexPages.StandardController(plApproval); 
        PL_newViewController plview = new PL_newViewController(standardController);
        setupHeader();
        plview.bindConsolidatedHeader();
     
        Test.stopTest();
       
    }
}