objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_AircraftQuantity__c</fullName>
        <label>Aircraft Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Type</label>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_OppAircraftLWCController.cls
/**
 *      @author       Sarah Kennedy
 *      @date         03/31/2020
 *      @description  Manage Aircraft data for Opportunity
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Sarah Kennedy                 03/31/2020         Initial Creation
 */
public with sharing class L2I_OppAircraftLWCController {
    
    @AuraEnabled
    public static oppAircraft getAircraft(String recordId) {
        System.debug('*** oppAircraft recordId ' + recordId);
        try {
            Opportunity opp = [
                  SELECT Id,
                        L2I_Aircraft_Type__c,
                        L2I_Aircraft_Type__r.Name,
                        L2I_AircraftQuantity__c,
                        L2I_Product_Category__c
                  FROM Opportunity
                  WHERE Id = :recordId
            ];
            System.debug('*** opp ' + opp);
            oppAircraft aircraft = new oppAircraft();
            aircraft.oppId = opp.Id;
            aircraft.aircraftTypeName = opp.L2I_Aircraft_Type__r.Name;
            aircraft.aircraftTypeId = opp.L2I_Aircraft_Type__c;
            aircraft.aircraftQty = opp.L2I_AircraftQuantity__c;
            aircraft.prodCategory = opp.L2I_Product_Category__c;
            System.debug('*** aircraft ' + aircraft);
            return aircraft;
        } catch (DmlException e) {
            System.debug('error: ' + e);
            throw new AuraHandledException('There was an error retrieving the Aircraft Qty and Type on Opportunity ' + recordId + ': ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void updateAircraft(String oppId, String aircraftId, Decimal aircraftQty) {
        try {
            Opportunity opp = [
                  SELECT Id,
                        L2I_Aircraft_Type__c,
                        L2I_AircraftQuantity__c
                  FROM Opportunity
                  WHERE Id = :oppId
            ];
            opp.L2I_Aircraft_Type__c = aircraftId;
            opp.L2I_AircraftQuantity__c = aircraftQty;
            update opp;
            System.debug('*** update opp ' + opp);
        } catch (DmlException e) {
            System.debug('error: ' + e);
            throw new AuraHandledException('There was an error updating the Aircraft Qty on Opportunity ' + oppId + ': ' + e.getMessage());
        }
    }
    
    public class oppAircraft {
        @AuraEnabled public String oppId { get; set; }
        @AuraEnabled public String aircraftTypeName { get; set; }
        @AuraEnabled public String aircraftTypeId { get; set; }
        @AuraEnabled public String prodCategory { get; set; }
        @AuraEnabled public Decimal aircraftQty { get; set; }
    }
}