objects/L2I_Aircraft_Type__c.object
<CustomObject>
    <description>Custom Object to hold the different types of Aircrafts</description>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The type of the aircraft (ex. A380, A380-800, A380-841, etc.)</inlineHelpText>
        <label>Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSH__c.object
<CustomObject>
    <description>This object represents a Planned Delivery Schedule Header. It corresponds to a set of planes with the same configuration and type.</description>
    <fields>
        <fullName>Line_Count__c</fullName>
        <label>Line Count</label>
        <summaryFilterItems>
            <field>L2I_DSL__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deleted, Deactivate</value>
        </summaryFilterItems>
        <summaryForeignKey>L2I_DSL__c.Delivery_Schedule_Header__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DSH-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Schedule_Header__c</fullName>
        <label>Delivery Schedule Header</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IFEC_DSL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IFEC DSL</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>L2I_DSL__c.Product_Category__c</field>
                <operation>equals</operation>
                <value>IFEC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSL__c</referenceTo>
        <relationshipLabel>DSLs</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Line_Number__c</fullName>
        <label>Line Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_AircraftQuantity__c</fullName>
        <label>Aircraft Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>L2I_Aircraft_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Aircraft Type</label>
        <referenceTo>L2I_Aircraft_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales, Amendment, Renewal</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.RecordTypeId</field>
                <operation>equals</operation>
                <value>Deal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>ChildOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Schedule</label>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IFEC</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>PTS</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/L2I_ManageRelatedSchedController.cls
/**
 *      @author       Sarah Kennedy
 *      @date         02/18/2020
 *      @description  Controller class to support management of IFEC Schedules related to Service Schedules
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Sarah Kennedy                 01/18/2020         Initial creation
 *
 */
public with sharing class L2I_ManageRelatedSchedController {

    @AuraEnabled
    public static List<IFECWrap> getIFECSchedules(String oppId, String sortFilter, String sortedBy, String sortDirection) {
        System.debug('*** oppId ' + oppId);
        List<IFECWrap> ifecWList = new List<IFECWrap>();
        IFECWrap ifecW;
        Map<String, List<L2I_DSL__c>> dshDSLIFECMap = new Map<String, List<L2I_DSL__c>>();
        // get Service Schdule Account
        Opportunity oppAcct = [
              SELECT
                    Id,
                    Name,
                    AccountId
              FROM Opportunity
              WHERE Id = :oppId
        ];
        System.debug('*** oppAcct ' + oppAcct);
        // find all IFEC Schedules under the same Account
        for (Opportunity oppty : [
              SELECT
                    Id,
                    Name,
                    Account.Name,
                    RecordType.DeveloperName,
                    L2I_Delivery_Schedule__c,
                    L2I_Delivery_Schedule__r.Name,
                    L2I_Delivery_Schedule__r.Line_Count__c,
                    L2I_Aircraft_Type__r.Name,
                    L2I_AircraftQuantity__c,
                    L2I_Parent_Opportunity__r.Name
              FROM Opportunity
              WHERE AccountId = :oppAcct.AccountId
              AND L2I_Product_Category__c = 'IFEC'
              AND L2I_Delivery_Schedule__c <> null
              ORDER BY Name
        ]) {
            ifecW = new IFECWrap();
            ifecW.keyId = oppty.L2I_Delivery_Schedule__c;
            ifecW.oppDesc = oppty.Name;
//            ifecW.oppDescLink = '/' + oppty.Id;
            ifecW.oppDescLink = oppty.Id;
            ifecW.oppAircraftQty = oppty.L2I_AircraftQuantity__c;
            ifecW.ifecName = oppty.L2I_Delivery_Schedule__r.Name;
            ifecW.ifecLineCount = oppty.L2I_Delivery_Schedule__r.Line_Count__c;
            ifecW.oppAircraftType = oppty.L2I_Aircraft_Type__r.Name;
            ifecW.accountName = oppty.Account.Name;
            ifecW.parentOppName = oppty.L2I_Parent_Opportunity__r.Name;
//            ifecW.parentOppNameLink = '/' + oppty.L2I_Parent_Opportunity__c;
            ifecW.parentOppNameLink = oppty.L2I_Parent_Opportunity__c;
            System.debug('*** ifecW ' + ifecW);
            ifecWList.add(ifecW);
        }
        return ifecWList;
    }

    @AuraEnabled
    public static Integer addScheduleLines(String oppId, String dshIFECId) {
        Set<Id> ifecIds = new Set<Id>();
        List<L2I_DSL__c> dslAddList = new List<L2I_DSL__c>();
        L2I_DSL__c dslAdd;
        Integer highLineNumber = 0;
        Id dshId;
        // get the DSH from the Opportunity
        Opportunity oppty = [
              SELECT
                    Id,
                    Name,
                    L2I_Delivery_Schedule__c
              FROM Opportunity
              WHERE Id = :oppId
        ];
        dshId = oppty.L2I_Delivery_Schedule__c;
        System.debug('*** dshId ' + dshId);
        System.debug('*** dshIFECId ' + dshIFECId);
        // get the DSLs for the Service Schedule
        for (L2I_DSL__c dsl : [
              SELECT
                    Id,
                    Name,
                    Line_Number__c,
                    IFEC_DSL__c
              FROM L2I_DSL__c
              WHERE Delivery_Schedule_Header__c = :dshId
        ]) {
            System.debug('*** dsl ' + dsl);
            if (dsl.IFEC_DSL__c != null) {
                ifecIds.add(dsl.IFEC_DSL__c);
            }
            if (dsl.Line_Number__c.isNumeric()) {
                if (Integer.valueOf(dsl.Line_Number__c) > highLineNumber) {
                    highLineNumber = Integer.valueOf(dsl.Line_Number__c);
                }
            }
        }

        System.debug('*** ifecIds existing in dsh ' + ifecIds);
        // find the IFEC DSLs that are not already on the Service Delivery Schedule
        for (L2I_DSL__c dslIFEC : [
              SELECT
                    Id,
                    Name,
                    Delivery_Schedule_Header__c
              FROM L2I_DSL__c
              WHERE Delivery_Schedule_Header__c = :dshIFECId
              AND Id NOT IN :ifecIds
        ]) {
            System.debug('*** dslIFEC ' + dslIFEC);
            String currentLineNumber = String.valueOf(highLineNumber);
            dslAdd = new L2I_DSL__c();
            dslAdd.Delivery_Schedule_Header__c = dshId;
            dslAdd.IFEC_DSL__c = dslIFEC.Id;
            dslAdd.Status__c = '';
            dslAdd.Original_Opportunity__c = oppId;
            dslAdd.Line_Number__c = highLineNumber + 1 < 10 ? '0' + String.valueOf(highLineNumber + 1) : String.valueOf(highLineNumber + 1);
            dslAdd.PT_Line_Number__c = PT_Program_Utils.characterSequencer(currentLineNumber);
            highLineNumber++;
            dslAddList.add(dslAdd);
        }
        insert dslAddList;
        Set<String> excludeStatuses =
              L2I_JSON_Settings.getSpecificSettingCollection('Delivery_Schedule_Settings',
                    'Exclude_Statuses');
        return [
              SELECT COUNT()
              FROM L2I_DSL__c
              WHERE Delivery_Schedule_Header__c = :dshId
              AND Status__c NOT IN :excludeStatuses
              AND ((Original_Opportunity__r.StageName IN ('Pending Close', 'Closed Won', 'Closed')
              AND Original_Opportunity__r.SBQQ__PrimaryQuote__c <> null
              AND Original_Opportunity__r.SBQQ__PrimaryQuote__r.SBQQ__Ordered__c = true)
              OR (Original_Opportunity__r.StageName NOT IN ('Pending Close', 'Closed Won', 'Cancelled', 'No Bid', 'Closed Lost', 'Closed')))
        ];
    }

    public class IFECWrap {
        @AuraEnabled public String keyId { get; set; }
        @AuraEnabled public String oppDesc { get; set; }
        @AuraEnabled public Decimal oppAircraftQty { get; set; }
        @AuraEnabled public String ifecName { get; set; }
        @AuraEnabled public String oppDescLink { get; set; }
        @AuraEnabled public Decimal ifecLineCount { get; set; }
        @AuraEnabled public String oppAircraftType { get; set; }
        @AuraEnabled public String accountName { get; set; }
        @AuraEnabled public String parentOppName { get; set; }
        @AuraEnabled public String parentOppNameLink { get; set; }
        @AuraEnabled public String linkOpp { get; set; }
        @AuraEnabled public String linkParent { get; set; }

        public IFECWrap() {
            this.linkOpp = 'link';
            this.linkParent = 'link';
        }
    }
}