objects/L2I_Aircraft__c.object
<CustomObject>
    <description>Custom object to hold Aircraft level information</description>
    <fields>
        <fullName>L2I_Registration_Number__c</fullName>
        <description>Aircraft identification number assigned by a civil aviation authority (ex. FAA) - Often called &quot;tail number&quot; - Not an MSN, Block, Fleet or Line Number</description>
        <label>Registration Number (Tail Number)</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Aircraft</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/L2I_DSL__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link by custom field to the associated aircraft object</inlineHelpText>
        <label>Aircraft</label>
        <referenceTo>L2I_Aircraft__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PT Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Delivery Schedule Lines</relationshipLabel>
        <relationshipName>Delivery_Schedule_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Schedule Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Schedule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Effectivity__c</fullName>
        <label>Effectivity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>PT_Program_Aircraft_IDs__c</fullName>
        <label>Program Aircraft IDs</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_EditTailNumber.cls
public class PT_EditTailNumber {
    @InvocableMethod
    public static List<String> getAvailableAirCrafts(List<Requests> requests) {
        List<String> results = new List<String>();
        //system.assertEquals(requests, null);
        String aircraftsName = '';
        
        List<String> lEff = new List<String>();
        Set<String> sEff = new Set<String>();
        
        if (requests[0].dslId != null) {
            //Get dsl record
            L2I_DSL__c dslRec = [SELECT Id, PT_Program__c, PT_Program__r.PT_Program_Aircraft_IDs__c,
                                 Original_Opportunity__c // Added by Jan Geronga for W-003864
                                FROM L2I_DSL__c
                                WHERE Id = :requests[0].dslId LIMIT 1];
            
            //Added by Jan Geronga for W-003864: Start
            if (dslRec.PT_Program__c != null && dslRec.Original_Opportunity__c != null) {
                Opportunity opp = [SELECT Id, Effectivity__c From Opportunity WHERE ID =: dslRec.Original_Opportunity__c];
                if(opp.Effectivity__c != null){
                    lEff.addAll(opp.Effectivity__c.split(';'));
                    sEff.addAll(lEff);
                }

                for (L2I_Aircraft__c aircraft : [SELECT Id, L2I_Registration_Number__c, Name FROM L2I_Aircraft__c WHERE L2I_Registration_Number__c IN: sEff]) {
                    aircraftsName = aircraftsName + aircraft.Name + ';';
                }
                
                aircraftsName = aircraftsName.removeEnd(';');
                if(aircraftsName == null || aircraftsName == ''){
                    results.add('No Aircraft Available');
                } else {
                    results.add(aircraftsName);
                }
            }
            //Added by Jan Geronga for W-003864: End
            
            /*if (dslRec.PT_Program__c != null && dslRec.PT_Program__r.PT_Program_Aircraft_IDs__c != null) {
                List<String> splitProgramAircrafts = dslRec.PT_Program__r.PT_Program_Aircraft_IDs__c.removeEnd(';').split('\\;');
                Set<String> allAircraftsForProgram = new Set<String>(splitProgramAircrafts);
                for (L2I_DSL__c dsl : [SELECT Id, Name, Aircraft__c, Aircraft__r.Name
                                        FROM L2I_DSL__c
                                        WHERE PT_Program__c = :dslRec.PT_Program__c AND Aircraft__c != null]) {
                    if (allAircraftsForProgram.contains(dsl.Aircraft__c)) {
                        allAircraftsForProgram.remove(dsl.Aircraft__c);
                    }
                }
                for (L2I_Aircraft__c aircraft : [SELECT Id, Name FROM L2I_Aircraft__c WHERE Id IN :allAircraftsForProgram]) {
                    aircraftsName = aircraftsName + aircraft.Name + ';';
                }
                aircraftsName = aircraftsName.removeEnd(';');
                if(aircraftsName == null || aircraftsName == ''){
                    results.add('No Aircraft Available');
                } else {
                    results.add(aircraftsName);
                }
            }*/
                        
            else {
                results.add('No Aircraft Available');
            }
        }
        return results;
    }
    public class Requests {
    @InvocableVariable
    public Id dslId;
    }
}