objects/L2I_General_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Usage_Batch_Size__c</fullName>
        <label>Adjustment Usage Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>L2I General Settings</label>
    <pluralLabel>L2I General Settings</pluralLabel>
</CustomObject>

classes/L2I_AircraftServiceAdjUsageSched.cls
global class L2I_AircraftServiceAdjUsageSched implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        
        Integer batchSize = Integer.valueOf([SELECT Adjustment_Usage_Batch_Size__c 
                                             FROM L2I_General_Settings__mdt 
                                             LIMIT 1].Adjustment_Usage_Batch_Size__c);
        System.debug('batchSize: ' + batchSize);
        
        L2I_AircraftServiceAdjUsageBatch b = new L2I_AircraftServiceAdjUsageBatch();
        
        database.executebatch(b, batchSize);
        
    }

}