objects/L2I_General_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Order_Activation_Batch_Size__c</fullName>
        <label>Order Activation Batch Size</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>L2I General Settings</label>
    <pluralLabel>L2I General Settings</pluralLabel>
</CustomObject>

objects/L2I_Order_Activation_Execution_Log__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Execution_Date__c</fullName>
        <label>Execution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step1_Entry_Time__c</fullName>
        <label>Step1 Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step1_Exit_Time__c</fullName>
        <label>Step1 Exit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Step1_Log_Message__c</fullName>
        <label>Step1 Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step1_Name__c</fullName>
        <label>Step1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step1_Status__c</fullName>
        <label>Step1 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step2_Name__c</fullName>
        <label>Step2 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step3_Name__c</fullName>
        <label>Step3 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step4_Name__c</fullName>
        <label>Step4 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step5_Name__c</fullName>
        <label>Step5 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step6_Name__c</fullName>
        <label>Step6 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step7_Name__c</fullName>
        <label>Step7 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step8_Name__c</fullName>
        <label>Step8 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Contract Management Log</label>
    <nameField>
        <displayFormat>OAL-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Contract Management Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2I_AE_AutoExtendSched.cls
/**
 *      @author       Sarah Kennedy
 *      @date         06/25/2020
 *      @description  L2I_AE_AutoExtendSched - Starting Schedule for the AutoExtend automated process
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Sarah Kennedy                 06/25/2020         Initial scaffold
 *
 */
global class L2I_AE_AutoExtendSched implements Schedulable {
    private L2I_LoggingStringBuffer logBuffer = new L2I_LoggingStringBuffer();
    private L2I_Order_Activation_Execution_Log__c oaeLog;
    
    public void execute(SchedulableContext sc) {
        System.debug('*** Starting L2I_AE_AutoExtendSched');
        try {
// create the log
            oaeLog = L2I_OAExecutionLog_Helper.createLogEntry('AutoExtend');
            oaeLog.Step1_Name__c = 'AutoExtend Create Opportunity and Quote';
            oaeLog.Step2_Name__c = 'AutoExtend Prepare Quote';
            oaeLog.Step3_Name__c = 'AutoExtend Create Order';
            oaeLog.Step4_Name__c = 'AutoExtend Activate Order';
            oaeLog.Step5_Name__c = 'AutoExtend Create Contract';
            oaeLog.Step6_Name__c = 'AutoExtend Activate Contract';
            oaeLog.Step7_Name__c = 'Terminate Prior Contract';
            oaeLog.Step8_Name__c = 'AutoComplete Cases';
            oaeLog.Step1_Status__c = 'Started';
            oaeLog.Step1_Entry_Time__c = Datetime.now();
            oaeLog.Batch_Date__c = Date.today();
            oaeLog.Execution_Date__c = Date.today();
            L2I_OAExecutionLog_Helper.updateLogEntry(oaeLog);
            
            Integer batchSize = Integer.valueOf([SELECT Order_Activation_Batch_Size__c FROM L2I_General_Settings__mdt LIMIT 1].Order_Activation_Batch_Size__c);
            logBuffer.append('AutoExtend Batch Size: ' + batchSize);
            Database.executeBatch(new L2I_AE_CreateOppQuoteBatch(oaeLog.GUID__c), batchSize);
        } catch (Exception e) {
            oaeLog.Step1_Status__c = 'Encountered Exception';
            logBuffer.append('Exception Error Message :\n' + e.getMessage());
        }
        
        oaeLog.Step1_Exit_Time__c = Datetime.now();
        
        String logTrace = oaeLog.Step1_Log_Message__c + '\n' + logBuffer.toStr();
        if (logTrace.length() > L2I_StaticConstants.LONGTEXT_AREA_LIMIT) {
            logTrace = logTrace.substring(0, L2I_StaticConstants.LONGTEXT_AREA_LIMIT);
        }
        oaeLog.Step1_Log_Message__c = logTrace;
        L2I_OAExecutionLog_Helper.updateLogEntry(oaeLog);
        //
        // call the next step
        //
//        Datetime now = System.now();
//        Integer minsOffset = 1; // Schedule it a minute after the final batch has been completed.
//        String cronTab = L2I_UtilityHelper.getCRONexpression(now, 0, minsOffset, 0);
//
//        if (!Test.isRunningTest()) {
//            L2I_AE_PrepareQuoteSched step2 = new L2I_AE_PrepareQuoteSched(oaeLog.GUID__c);
//            String jobId = System.schedule('AutoExtend Step2 ' + oaeLog.GUID__c, cronTab, step2);
//            System.debug('AutoExtend Step 2 ' + oaeLog.GUID__c + ' has been scheduled as :' + jobId);
//        }
    }
}