objects/myIfeOrderHeaders__x.object
<CustomObject>
    <description>myIfeOrderHeaders</description>
    <externalDataSource>Order_Status</externalDataSource>
    <externalName>myIfeOrderHeaders</externalName>
    <fields>
        <fullName>CUSTOMER_ID__c</fullName>
        <description>CUSTOMER_ID</description>
        <externalDeveloperName>CUSTOMER_ID</externalDeveloperName>
        <label>CUSTOMER_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HEADER_ID__c</fullName>
        <description>HEADER_ID</description>
        <externalDeveloperName>HEADER_ID</externalDeveloperName>
        <label>HEADER_ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SALES_ADMIN__c</fullName>
        <description>SALES_ADMIN</description>
        <externalDeveloperName>SALES_ADMIN</externalDeveloperName>
        <label>SALES_ADMIN</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>myIfeOrderHeaders</label>
    <pluralLabel>myIfeOrderHeaders</pluralLabel>
</CustomObject>

classes/ife_OrderHeaderListCtrlMockRecords.cls
public class ife_OrderHeaderListCtrlMockRecords {
 /*@TestVisible protected List<SObject> mockedRecords =
        new List<SObject>();

    public void addTestRecord(SObject record) {
        mockedRecords.add(record);
    }

    public void addTestRecords(List<SObject> records) {
        mockedRecords.addAll(records);
    }*/
    
    public static myIfeOrderHeaders__x getRecords()
    {
        myIfeOrderHeaders__x order1 = new myIfeOrderHeaders__x(
            ExternalId = '123',
            CUSTOMER_ID__c = '123',
            HEADER_ID__c  = '234',
            SALES_ADMIN__c  = 'admin'     
        );
      
     //   List<myIfeOrderHeaders__x> orderList = new List<myIfeOrderHeaders__x>{order1};
         
        return order1;
    }
}