objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Num__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Number</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Current_Parts_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is updated whenever a CPL/PPL quote document is created. The value is that same quote Id used to the document generation.</description>
        <label>Current Parts List</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities (Current Parts List)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Is_CPL__c</fullName>
        <formula>AND( RecordType.DeveloperName = &#39;Sales&#39;,  TEXT(L2I_Product_Category__c) = &#39;IFEC&#39;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is CPL?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Is_PPL__c</fullName>
        <formula>IF ( RecordType.DeveloperName = &#39;PPL&#39;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is PPL?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Approver_Comments__c</fullName>
        <label>PL Approval Approver Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PL Approval Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Date__c</fullName>
        <label>PL Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Submitter_Comments__c</fullName>
        <label>PL Approval Submitter Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval</description>
        <label>PL Approval Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Batch_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PL Batch In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_PL_Document_Generation_Status__c</fullName>
        <label>PL Document Generation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Part_List_Document_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Part List Document Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name_Rev__c</fullName>
        <formula>PT_Part_List_Name__c &amp; &#39;_&#39; &amp;  PT_Revised_Parts_List_Version_Trans__c
+
IF( PT_Is_PPL__c ,  &quot; (&quot; + TEXT(PT_PPL_Type__c) + &quot;)&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part List Name Rev</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name__c</fullName>
        <label>Part List Name</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PT_Program_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval flow</description>
        <label>Program Mgr</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Revised_Parts_List_Version_Trans__c</fullName>
        <label>Revised Parts List Version Trans</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>PPL</fullName>
        <active>true</active>
        <businessProcess>Program Part List</businessProcess>
        <label>PPL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program_Number__c</fullName>
        <externalId>true</externalId>
        <label>Program Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_QuoteDocGeneration.cls
/**
 *  @author       Sarah Kennedy
 *  @date         12/08/2020
 *  @description  PT_QuoteDocGeneration class
 *
 *  Modification Log:
 *  ------------------------------------------------------------------------------------
 *  Developer                       Date                Description
 *  ------------------------------------------------------------------------------------
 *  Sarah Kennedy                  12/08/2020         Initial scaffold
 *
 */

public without sharing class PT_QuoteDocGeneration {
    
    @AuraEnabled
    public static void genDoc(Id oppId) {
        List<FlowInput> fiList = new List<FlowInput>();
        FlowInput fi = new FlowInput();
        fi.oppIdToProcess = oppId;
        fiList.add(fi);
        genQuoteDoc(fiList);
    }
    
    @InvocableMethod(Label = 'Generate Quote Proposal')
    public static void genQuoteDoc(List<FlowInput> inputs) {
        String oppId;
        System.debug('*** Starting PT_QuoteDocGeneration.genQuoteDoc ' + inputs);
    
        if (inputs == null) {
            System.debug('*** Flow inputs is null ');
            return;
        }
        for (FlowInput inId : inputs) {
            oppId = inId.oppIdToProcess;
        }
    
        if (oppId == null) {
            System.debug('*** oppId is null ');
            return;
        }
    
        System.debug('*** oppId ' + oppId);
 
        List<Opportunity> oppList = new List<Opportunity>();
        oppList = [
              SELECT Id, PT_Current_Parts_List__c, PT_Part_List_Name_Rev__c, L2I_Program_Num__r.Program_Number__c,
                    StageName, PT_Is_PPL__c, PT_Is_CPL__c, L2I_Delivery_Schedule__c,
                    Name, PT_Program_Mgr__r.Email, PT_Program_Mgr__r.Name,
                    PT_PL_Approval_Approver__r.Name, PT_PL_Approval_Approver_Comments__c,
                    PT_PL_Approval_Submitter__r.Name, PT_PL_Approval_Submitter_Comments__c,
                    PT_Part_List_Name__c, PT_Revised_Parts_List_Version_Trans__c,
                    PT_PL_Approval_Date__c, SBQQ__PrimaryQuote__c, PT_Part_List_Document_Generated__c
              FROM Opportunity
              WHERE Id = :oppId
        ];
        
        if (oppList.isEmpty() || oppList.size() == 0){
            System.debug('*** PL Opportunity is null ');
            return;
        }
        
        Opportunity opp = oppList[0];
        
        if (opp.SBQQ__PrimaryQuote__c == null) {
            System.debug('*** opp.SBQQ__PrimaryQuote__c is null ');
            return;
        }
        
         String quoteId = opp.SBQQ__PrimaryQuote__c;
        System.debug('*** quoteId ' + quoteId);
        
        opp.PT_Current_Parts_List__c = quoteId;
        update opp;
        
        // generate CPL/PPL document
        // create the CPL Integration document
        // to be used for creating CPL document to send to PAC Agile (W-001777)
        System.debug('*** before gendoc');
        System.debug('*** PT_Part_List_Name_Rev__c ' + opp.PT_Part_List_Name_Rev__c);
        if (opp.StageName == 'Delivery' &&
              quoteId != null &&
              !String.isBlank(opp.PT_Part_List_Name_Rev__c)) {
            String fileName = '';
            PageReference pdf;
            pdf = Page.PT_PartsListPDF;
            fileName = opp.PT_Part_List_Name_Rev__c + '.pdf';
            pdf.getParameters().put('id', opp.Id);

            // attach to Opportunity
            Blob body;
            if(Test.isRunningTest()) {
                body = blob.valueOf('Unit.Test');
            } else {
                body = pdf.getContentAsPDF();
            }
            
            Attachment attachmentPDF = new Attachment();
            attachmentPDF.ParentId = opp.Id;
            attachmentPDF.Name = fileName;
            attachmentPDF.Body = body; //This creates the PDF content
            insert attachmentPDF;
            System.debug('*** after gendoc atttachment created');
    
            // generate the XLS ===========================================
            try{
            System.debug('*** generating xls');
            String fileNameX = '';
            PageReference xls;
//            xls = Page.PT_PartsListXLS;
                xls = Page.PT_PartsListMSXLS;
            System.debug('*** xls ' + xls);
            fileNameX = opp.PT_Part_List_Name_Rev__c + ' XLS.xls';
            xls.getParameters().put('id', opp.Id);
    
            // attach to Opportunity
            if(Test.isRunningTest()) {
                body = blob.valueOf('Unit.Test');
            } else {
                body = xls.getContent();
            }
            System.debug('*** body ' + body);
            Attachment attachmentXLS = new Attachment();
            attachmentXLS.ParentId = opp.Id;
            attachmentXLS.Name = fileNameX;
            attachmentXLS.Body = body; //This creates the XLS content
            insert attachmentXLS;
            System.debug('*** attachmentXLS ' + attachmentXLS);
            } catch (Exception e){
                System.debug('*** Error generating Final XLS Part List document: ' + e.getMessage());
            }
            // ================================================================
    
            // call future method of generate the PDF and attach it to the PL Opportunity
//            PT_GenerateCPLDocCall.callGenerateCPLDoc(opp.Id, opp.PT_Part_List_Name_Rev__c, UserInfo.getSessionId());

            System.debug('*** PT_QuoteDocGeneration - generated QuoteProposal for quoteId: ' + quoteId +
                  ' StageName: ' + opp.StageName +
                  ' CPL Name: ' + opp.PT_Part_List_Name_Rev__c);
            
            // save the quoteId for updating the TagCsv field on the ContentVersion when the
            // quote doc -> Attachment -> ContentVersion is created (via a setting in CPQ)
            System.debug('*** updating opp.PT_Current_Parts_List__c ');
            opp.PT_Part_List_Document_Generated__c = true;
            opp.PT_PL_Document_Generation_Status__c = 'Completed'; // Added by Khrisna for W-003113
            update opp;
            System.debug('*** updating opp.PT_Current_Parts_List__c opp ' + opp);
            // serialize the PL Data and add as files to the Opportunity
            System.debug('*** calling PT_OpportunityService.serializeOppShipset ');
//            PT_OpportunityService.serializeOppShipset(opp, quoteId);
        } else {
            System.debug('*** PT_QuoteDocGeneration - Was not generateQuoteProposal for quoteId: ' + quoteId +
                  ' StageName: ' + opp.StageName +
                  ' CPL Name: ' + opp.PT_Part_List_Name_Rev__c);
        }
        System.debug('*** Exiting PT_QuoteDocGeneration.genQuoteDoc ' + quoteId);
    }
    
    public class FlowInput {
        @InvocableVariable
        public String oppIdToProcess;
    }
    
//    @AuraEnabled
//    public static Boolean getInProcessStatus(Id oppId) {
//        return [Select Id, Name, PT_PL_Batch_In_Process__c From Opportunity Where Id =: oppId].PT_PL_Batch_In_Process__c;
//    }
}