objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Program_Num__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Number</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_CR_Parts_List_Revision_Number__c</fullName>
        <description>W-003749 - Part list revision number only for CR PPL Type</description>
        <inlineHelpText>Parts List Revision Number starts with 1 and increments by 1, every time Part List is revised.
FOR CR PPL TYPE</inlineHelpText>
        <label>CR Parts List Revision Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PT_Is_PPL__c</fullName>
        <formula>IF ( RecordType.DeveloperName = &#39;PPL&#39;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is PPL?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Approver_Comments__c</fullName>
        <label>PL Approval Approver Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PL Approval Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Date__c</fullName>
        <label>PL Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Submitter_Comments__c</fullName>
        <label>PL Approval Submitter Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_PL_Approval_Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval</description>
        <label>PL Approval Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PL_Batch_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PL Batch In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_PL_Document_Generation_Status__c</fullName>
        <label>PL Document Generation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_PPL_Type__c</fullName>
        <label>PPL Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PPL_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_Part_List_Document_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Part List Document Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name_Rev__c</fullName>
        <formula>PT_Part_List_Name__c &amp; &#39;_&#39; &amp;  PT_Revised_Parts_List_Version_Trans__c
+
IF( PT_Is_PPL__c ,  &quot; (&quot; + TEXT(PT_PPL_Type__c) + &quot;)&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part List Name Rev</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name__c</fullName>
        <label>Part List Name</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PT_Parts_List_Revision_Number__c</fullName>
        <description>Parts List Revision Number starts with 1 and increments by 1 every time Part List is revised.</description>
        <inlineHelpText>Parts List Revision Number starts with 1 and increments by 1, every time Part List is revised.</inlineHelpText>
        <label>Parts List Revision Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PT_Pending_Parts_List__c</fullName>
        <label>Pending Parts List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Principal_Prgrm_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program_Mgr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned during Part List Approval flow</description>
        <label>Program Mgr</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Revised_Parts_List_Version_Trans__c</fullName>
        <label>Revised Parts List Version Trans</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>PPL</fullName>
        <active>true</active>
        <businessProcess>Program Part List</businessProcess>
        <label>PPL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>Principal_Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Needed for MROD Approval process</description>
        <label>Principal Program Manager User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/PPL_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>EQ</fullName>
    </customValue>
    <customValue>
        <fullName>CR</fullName>
    </customValue>
    <customValue>
        <fullName>ZZ</fullName>
    </customValue>
    <customValue>
        <fullName>FC</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
    </customValue>
    <customValue>
        <fullName>OT</fullName>
    </customValue>
    <customValue>
        <fullName>SW</fullName>
    </customValue>
    <customValue>
        <fullName>DSS</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
        <isActive>false</isActive>
        <label>Service</label>
    </customValue>
    <masterLabel>PPL Types</masterLabel>
</GlobalValueSet>

classes/PT_PartsListApproval.cls
/**
 *      @author       
 *      @date         
 *      @description  PT_PartsListApproval 
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *		--								--					Initial
 *		QOng							Sept-1-2021			W-003749 - Updated to include the Changes for CR PPL Type
 */
public without sharing class PT_PartsListApproval {
    
   /**
    * @Method Name        : processPartsListApproval
    * @Description        : This method updates the Opportunity and Generates File upon approval of Parts List modification
    * @Author             : 
    * @Modification Log   : 
    * Ver       	Date       	  	Author              Modification
    * --			--			  	--				    Initial Version
    * 				Sept-1-2021		MS Simplus QOng		W-003749 Formatting for CR PPL Type
    **/
    @InvocableMethod(Label = 'Parts List Approval')
    public static void processPartsListApproval(List<PLApprovalParams> params) {
        String oppId = params[0].oppId;
        String submitterComments = params[0].comments;
        // Submit the Approval Request
        // Opportunity cannot have queues (will be GA in Summer '21).
        // The requirement is to allow Approval by any PM but only send an Approval email to the Program's PM Mgr
        // This could be accomplished by specifying the Related User for the PM Mgr, and the PM queue to allow other PMs
        // to approve, also, but with no email sent to the queue members (controlled by the queue not sending emails)
        // But cannot do that in configuration with the Opportunity (due to no Opportunity queue allowed), but
        // we can do it via Apex
        List<Approval.ProcessSubmitRequest> approvalRequestList = new List<Approval.ProcessSubmitRequest>();
        QueueSobject qo = [SELECT Queue.Id, Queue.Name FROM QueueSobject WHERE Queue.DeveloperName = 'Program_PM_PPM_Queue' LIMIT 1];
    
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(submitterComments);
        req1.setObjectId(oppId);
        req1.setProcessDefinitionNameOrId('Part_List_Approval2');
        // setNextApproverIds only allows a single entry
        req1.setNextApproverIds(new List<Id>{
              qo.Queue.Id
        });
        approvalRequestList.add(req1);
        // Submit the approval request for the Opportunity
        System.debug('*** req1 ' + req1);
        Approval.ProcessResult result = Approval.process(req1);
        System.debug('*** result ' + result);
    
        Opportunity opp = [
              SELECT Id, Name, PT_Program_Mgr__r.Email, PT_Program_Mgr__r.Name,
                    PT_PL_Approval_Approver__r.Name, PT_PL_Approval_Approver_Comments__c,
                    PT_PL_Approval_Submitter__r.Name, PT_PL_Approval_Submitter_Comments__c,
                    PT_Part_List_Name__c, PT_Revised_Parts_List_Version_Trans__c, PT_Is_PPL__c, PT_Pending_Parts_List__c,
                    PT_PL_Approval_Date__c, PT_Part_List_Name_Rev__c, PT_Parts_List_Revision_Number__c, PT_PPL_Type__c,
                    PT_Part_List_Document_Generated__c, PT_PL_Batch_In_Process__c, PT_Principal_Prgrm_Mgr__c, L2I_Program_Num__r.Principal_Program_Manager__c,
            		PT_CR_Parts_List_Revision_Number__c, L2I_Program_Num__r.Name
              FROM Opportunity
              WHERE Id = :oppId
        ];
        Integer nextRevNumber = Integer.valueOf(opp.PT_Parts_List_Revision_Number__c == null ? 1 : (opp.PT_Parts_List_Revision_Number__c + 1));
        
        //W-003749
        if('CR' == opp.PT_PPL_Type__c){
            nextRevNumber = Integer.valueOf(opp.PT_CR_Parts_List_Revision_Number__c == null ? 1 : (opp.PT_CR_Parts_List_Revision_Number__c + 1));
        }
        
        String revTrans = PT_Program_Utils.revisionCharacter(Integer.valueOf(nextRevNumber));
        String revName = opp.PT_Part_List_Name__c + '_' + revTrans;
        if (opp.PT_Is_PPL__c) {
            revName = revName + ' (' + opp.PT_PPL_Type__c + ')';
            //W-003749
            if(opp.PT_PPL_Type__c == 'CR'){
                revName = 'CR-'+opp.L2I_Program_Num__r.Name+'-'+opp.PT_Parts_List_Revision_Number__c+'_'+revTrans;
            }
        }
        opp.PT_Pending_Parts_List__c = revName;
        opp.PT_Part_List_Document_Generated__c = false;
        opp.PT_PL_Document_Generation_Status__c = 'In Progress'; // Added by Khrisna for W-003113
        opp.PT_PL_Batch_In_Process__c = true;
        opp.PT_Principal_Prgrm_Mgr__c = opp.L2I_Program_Num__r.Principal_Program_Manager__c;
        update opp;
        // generate the PDF
        PageReference pdf;
        pdf = Page.PT_PartsListPDFPending;
        String fileName = revName + ' Pending.pdf';
        pdf.getParameters().put('id', opp.Id);
        pdf.getParameters().put('status', 'Pending');
        pdf.getParameters().put('nextRev', revTrans);
    
        // attach to Opportunity
        Blob bodyPDF;
        if (Test.isRunningTest()) {
            bodyPDF = blob.valueOf('Unit.Test');
        } else {
            bodyPDF = pdf.getContent();
        }
        Attachment attachmentPDF = new Attachment();
        attachmentPDF.ParentId = opp.Id;
        attachmentPDF.Name = fileName;
        attachmentPDF.Body = bodyPDF; //This creates the PDF content
        insert attachmentPDF;
    
    
        // generate the XLS ===========================================
        try {
            System.debug('*** generating xls');
            PageReference xls;
//            xls = Page.PT_PartsListXLSPending;
            xls = Page.PT_PartsListMSXLSPending;
            System.debug('*** xls ' + xls);
            String fileNameX = revName + ' PendingXLS.xls';
            xls.getParameters().put('id', opp.Id);
            xls.getParameters().put('status', 'Pending');
            xls.getParameters().put('nextRev', revTrans);
    
            Blob bodyXLS;
            // attach to Opportunity
            if (Test.isRunningTest()) {
                bodyXLS = blob.valueOf('Unit.Test');
            } else {
                bodyXLS = xls.getContent();
            }
            System.debug('*** bodyXLS ' + bodyXLS);
            Attachment attachmentXLS = new Attachment();
            attachmentXLS.ParentId = opp.Id;
            attachmentXLS.Name = fileNameX;
            attachmentXLS.Body = bodyXLS; //This creates the XLS content
            insert attachmentXLS;
            System.debug('*** attachmentXLS ' + attachmentXLS);
        } catch (Exception e) {
            System.debug('*** Error generating Pending XLS Part List document: ' + e.getMessage());
        }
        // ================================================================
    
    
        // send email to the PM user on the Opportunity
        System.debug('*** Sending email to : ' + opp.PT_Program_Mgr__c);
        EmailTemplate emailTemplate = [
              SELECT Id, Subject, Description, HtmlValue, DeveloperName,Body
              FROM EmailTemplate
              WHERE DeveloperName = 'Part_List_Submit_for_Approval'
        ];
        String templateId = emailTemplate.Id;
        String userId = opp.PT_Program_Mgr__c;
        String emailAddr = opp.PT_Program_Mgr__r.Email;
        String whatId = opp.Id;
    
        Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(templateId, userId, whatId);
        // attachment
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setContentType('application/pdf');
        efa.setFileName(opp.PT_Pending_Parts_List__c + ' Pending.pdf');
//        efa.setInline(false);
        efa.body = bodyPDF;
    
        String emailSubject = email.getSubject();
        String emailHTMLBody = email.getHtmlBody();

//        email.setTargetObjectId(userId);
        List<String> sendTo = new List<String>();
        sendTo.add(emailAddr);
        email.setToAddresses(sendTo);
    
        email.setSubject(emailSubject);
        email.setHtmlBody(emailHTMLBody);
        email.saveAsActivity = false;
    
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{
              efa
        });
    
        if (!Test.isRunningTest()) {
            Messaging.SendEmailResult[] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                  email
            });
        
            for (Messaging.SendEmailResult rr : r) {
                if (rr.isSuccess()) {
                    System.debug('Email result ' + rr.IsSuccess());
                } else {
                    System.debug('Error Email result ' + rr.getErrors());
                }
            }
        }
        
        // create a task for the PM
//        System.debug('*** Creating task for : ' + userId);
//        Task tsk = new Task();
//        tsk.Subject = 'Approval Requested for Parts List - ' + opp.PT_Part_List_Name_Rev__c;
//        tsk.WhatId = whatId;
//        tsk.OwnerId = userId;
//        tsk.Status = 'In Progress';
//        tsk.ActivityDate = Date.today();
//        insert tsk;
    }
    
    public class PLApprovalParams {
        @InvocableVariable public String oppId;
        @InvocableVariable public String comments;
    }
}