objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2I_Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The delivery schedule header record to be associated with a Sales Opportunity</description>
        <label>Delivery Schedule</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>L2I_DSH__c.Deal_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.L2I_Parent_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>L2I_DSH__c</referenceTo>
        <relationshipLabel>Sales Opportunities</relationshipLabel>
        <relationshipName>Sales_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Program_Num__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Number</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Current_Parts_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is updated whenever a CPL/PPL quote document is created. The value is that same quote Id used to the document generation.</description>
        <label>Current Parts List</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities (Current Parts List)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Is_CPL__c</fullName>
        <formula>AND( RecordType.DeveloperName = &#39;Sales&#39;,  TEXT(L2I_Product_Category__c) = &#39;IFEC&#39;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is CPL?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Is_PPL__c</fullName>
        <formula>IF ( RecordType.DeveloperName = &#39;PPL&#39;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is PPL?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Part_List_Name_Rev__c</fullName>
        <formula>PT_Part_List_Name__c &amp; &#39;_&#39; &amp;  PT_Revised_Parts_List_Version_Trans__c
+
IF( PT_Is_PPL__c ,  &quot; (&quot; + TEXT(PT_PPL_Type__c) + &quot;)&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part List Name Rev</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>PPL</fullName>
        <active>true</active>
        <businessProcess>Program Part List</businessProcess>
        <label>PPL</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program_Number__c</fullName>
        <externalId>true</externalId>
        <label>Program Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_QuoteService.cls
/**
 *  @author       Sarah Kennedy
 *  @date         12/08/2020
 *  @description  PT_QuoteService class
 *
 *  Modification Log:
 *  ------------------------------------------------------------------------------------
 *  Developer                       Date                Description
 *  ------------------------------------------------------------------------------------
 *  Sarah Kennedy                  12/08/2020         Initial scaffold
 *
 */

public with sharing class PT_QuoteService {
//    public static void genQuoteDoc(Id quoteId) {
//        System.debug('*** Starting PT_QuoteService.genQuoteDoc ' + quoteId);
//
//        SBQQ__Quote__c q = [
//              SELECT Id, SBQQ__Opportunity2__c
//              FROM SBQQ__Quote__c
//              WHERE Id = :quoteId
//        ];
//
//        if (q.SBQQ__Opportunity2__c == null) {
//            System.debug('*** q.SBQQ__Opportunity2__c is null ');
//            return;
//        }
//
//        Opportunity opp = [
//              SELECT Id, PT_Current_Parts_List__c, PT_Part_List_Name_Rev__c,
//                      L2I_Program_Num__r.Program_Number__c,
//                    StageName, PT_Is_PPL__c, PT_Is_CPL__c, L2I_Delivery_Schedule__c
//              FROM Opportunity
//              WHERE Id = :q.SBQQ__Opportunity2__c
//        ];
//
//        System.debug('*** opp ' + opp);
//
//        // generate CPL/PPL document
//        // create the CPL Integration document
//        // generate quote proposal
//        // to be used for creating CPL document to send to PAC Agile (W-001777)
//        System.debug('*** before gendoc');
//        String documentTemplateId = String.valueOf (
//              L2I_JSON_Settings.getSpecificSetting('CPL_Settings', 'CPLDocTemplateId'));
//
//        if (Test.isRunningTest()) {
//            SBQQ__QuoteTemplate__c qtemplate = new SBQQ__QuoteTemplate__c(Name = 'Test Template');
//            insert qtemplate;
//            documentTemplateId = qtemplate.Id;
//        }
//
//        System.debug('*** PT_Part_List_Name_Rev__c ' + opp.PT_Part_List_Name_Rev__c);
//        System.debug('*** documentTemplateId ' + documentTemplateId);
//        if (opp.StageName == 'Delivery' &&
//              quoteId != null &&
//              !String.isBlank(opp.PT_Part_List_Name_Rev__c) &&
//              !String.isBlank(documentTemplateId)) {
//            L2I_QuoteService.generateQuoteProposal(quoteId, opp.PT_Part_List_Name_Rev__c, documentTemplateId);
//            System.debug('*** L2I_QuoteApprovalController - generated QuoteProposal for quoteId: ' + quoteId +
//                  ' StageName: ' + opp.StageName +
//                  ' CPL Name: ' + opp.PT_Part_List_Name_Rev__c +
//                  ' CPL Document Template Id: ' + documentTemplateId);
//
//            // save the quoteId for updating the TagCsv field on the ContentVersion when the
//            // quote doc -> Attachment -> ContentVersion is created (via a setting in CPQ)
//            System.debug('*** updating opp.PT_Current_Parts_List__c ');
//            opp.PT_Current_Parts_List__c = quoteId;
//            update opp;
//            System.debug('*** updating opp.PT_Current_Parts_List__c opp ' + opp);
//            // serialize the PL Data and add as files to the Opportunity
//            System.debug('*** calling PT_OpportunityService.serializeOppShipset ');
//            PT_OpportunityService.serializeOppShipset(opp, quoteId);
//        } else {
//            System.debug('*** L2I_QuoteApprovalController - Was not generateQuoteProposal for quoteId: ' + quoteId +
//                  ' StageName: ' + opp.StageName +
//                  ' CPL Name: ' + opp.PT_Part_List_Name_Rev__c +
//                  ' CPL Document Template Id: ' + documentTemplateId);
//        }
//    }
}