objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PT_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>PT_PriceList__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_PriceList__c.object
<CustomObject>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <label>Price List Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Sequence__c</fullName>
        <label>Price List Sequence</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Program Price List</relationshipLabel>
        <relationshipName>Program_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Price List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>PT_Primary_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Price List</label>
        <referenceTo>PT_PriceList__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <inlineHelpText>Active state of the Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_CreateProgramPriceListHandler.cls
/**
 *      @author       Nitin Gupta
 *      @date         01/07/2021
 *      @description  Create Program Part List Controller Handler
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Nitin Gupta                01/07/2021            Initial creation
 */


public class PT_CreateProgramPriceListHandler {
    public static void createInitialProgramPriceList(Id programId) {
        PT_Program__c prog = [SELECT Id, Name, Sales_Opportunity__c, Sales_Opportunity__r.SBQQ__PrimaryQuote__c FROM PT_Program__c WHERE Id = :programId];
        PT_PriceList__c priceList = new PT_PriceList__c(PT_Program__c = prog.Id,
                                                        PT_Description__c = 'TBD',
                                                        PT_IsActive__c = TRUE,
                                                        PT_Price_List_Sequence__c = '01',
                                                        PT_Price_List_Name__c = 'CPL-PL-' + prog.Name + '-01');
        insert priceList;

        prog.PT_Primary_Price_List__c = priceList.Id;
        update prog;

        if (prog.Sales_Opportunity__c != null && prog.Sales_Opportunity__r.SBQQ__PrimaryQuote__c != null) {
            PT_ProgramPriceList_Utils.createUpdatePriceListEntries(prog.Sales_Opportunity__r.SBQQ__PrimaryQuote__c, priceList.Id);
        }
        if (prog.Sales_Opportunity__c != null) {
            Opportunity oppty = new Opportunity (Id = prog.Sales_Opportunity__c, PT_Price_List__c = priceList.Id);
            update oppty;
        }
    }
}