objects/PL_IL2PS__c.object
<CustomObject>
    <fields>
        <fullName>Inst_loc__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>SBQQ__SolutionGroup__c</referenceTo>
        <relationshipLabel>Install Loc 2 Product Summary</relationshipLabel>
        <relationshipName>Install_Loc_2_Product_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2I_Migration_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PL_PS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Summary</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PL_MD__c.MD_Type__c</field>
                <operation>equals</operation>
                <value>Product Summary</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PL_MD__c</referenceTo>
        <relationshipLabel>Install Loc 2 Product Summary</relationshipLabel>
        <relationshipName>Install_Loc_2_Product_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Install Loc 2 Product Summary</relationshipLabel>
        <relationshipName>Install_Loc_2_Product_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Install Loc 2 Product Summary</label>
    <nameField>
        <displayFormat>IL2PL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Install Loc 2 Product Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PL_MD__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Display Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Migration_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MD_Type__c</fullName>
        <label>Master Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost Allocation</fullName>
                </value>
                <value>
                    <fullName>Product Group</fullName>
                </value>
                <value>
                    <fullName>Product Summary</fullName>
                </value>
                <value>
                    <fullName>CreditType2PS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Translated_Value__c</fullName>
        <label>Translated Value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>P&amp;L Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Master Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PL_Product_Group__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>Start_Date__c &lt;= TODAY() &amp;&amp; (ISNULL(End_Date__c) || End_Date__c &gt;=Today())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>L2I_Migration_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PL_MD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Data</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PL_MD__c.MD_Type__c</field>
                <operation>equals</operation>
                <value>Product Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PL_MD__c</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <formula>PL_MD__r.Product_Group__c</formula>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PL_PS__c.object
<CustomObject>
    <fields>
        <fullName>CAL_COGS__c</fullName>
        <description>Cost * Third Party over head + Net * COGs%</description>
        <formula>(ps_NS_to_Cust__c *  Product_Group__r.COGS__c) + (Cost__c * Product_Summary__r.Third_Party_Overhead__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>COGS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <label>Credit</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>IF( Text(Quote__r.SBQQ__Opportunity2__r.L2I_Product_Category__c) != &quot;PTS&quot;, Gross_Sales__c - Net_Sales__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Sales__c</fullName>
        <description>Hold total Standard Price from all Quote Lines.</description>
        <label>Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Line_Maintenance_Cost__c</fullName>
        <description>Used for PTS Quote&#39;s Line Maintenance Cost</description>
        <label>Line Maintenance Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Sales__c</fullName>
        <label>Net Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Group</label>
        <referenceTo>PL_Product_Group__c</referenceTo>
        <relationshipName>Product_Summary_by_Ins_Loc</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Summary</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PL_MD__c.MD_Type__c</field>
                <operation>equals</operation>
                <value>Product Summary</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PL_MD__c</referenceTo>
        <relationshipLabel>Quote Product Summary</relationshipLabel>
        <relationshipName>Product_Summary_by_Ins_Loc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipName>Product_Summary_by_Ins_Loc</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Red_in_GS__c</fullName>
        <formula>Discount__c +  Credit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reduction in Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>Product_Summary__r.Sort_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Warranty_Cost__c</fullName>
        <label>Warranty Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ps_GM__c</fullName>
        <formula>ps_NS_to_Cust__c -  Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ps_NS_to_Cust__c</fullName>
        <formula>Gross_Sales__c - Red_in_GS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Sales to Customer</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Product Summary</label>
    <nameField>
        <label>Product Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Product Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PL_Utils.cls
/**
 * Created by sanjay.singhal on 10/23/20.
 *      @author       Sanjay Singhal
 *      @date         10/23/2020
 *      @description  Service class for P&L calculations and Data management
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Sanjay Singhal                10/23/2020         Initial creation
 *      MS KElumba                    03/28/2022         W-004372 Set null value to 0 on P&L View
 */

global class PL_Utils {

    public static List <String> args =  new String[]{'0','number','###,###,##0'};


    //Main Method to Create P&L data when quote is finalized
    @InvocableMethod(label='Calculate P&L Summary Data')
    public static void createPLData(List <ID> QuoteId) {
        System.debug('*** Starting PL_Utils.createPLData for QuoteID :' + QuoteId + '***');

        //createPLData(quoteId[0]);
        PL_UtilsFunctions plFunctions = new PL_UtilsFunctions(QuoteId[0]);
        // if there are quote line which can be proceseed.
        if (plFunctions.myQL.size() > 0){

            if (plFunctions.psMDMap.size() > 0 && plFunctions.pgMap.size() > 0) {
                // delete Quote Product Summaries
                plFunctions.delQuotePSData(quoteId[0]);

                // Process and create Product Summaries based on Quote line.
                plFunctions.createQuotePSData();
                
                // Process for update on the junction object:
                plFunctions.updatePLSalesOpp();

                //finished processing
                System.debug('PL_Utils : Finished processing createPLData()');

            } else {
                System.debug('PL_Utils : unable to find Product Summary or Prroduct Group data');
            }
        }
    }

    public static List <PL_MD__c> getProductSummaryMasterDataList(){
        // Initialize LIst
        List<PL_MD__c> plMDList = [SELECT id, Name, Product_Group__c, Sort_Order__c, L2I_Migration_External_Id__c, Color__c
        FROM PL_MD__C Where MD_Type__c = 'Product Summary' order by Sort_Order__c];

        return plMDList;
    }

    Public Static Map <String, PL_MD__c> getProductSummaryMasterDataMap(){
        Map <String, PL_MD__c> psMDMap = new Map <String, PL_MD__c> ();
        for (PL_MD__c psMD : getProductSummaryMasterDataList()) {
            psMDMap.put(psMD.L2I_Migration_External_Id__c, psMD);
        }
        return psMDMap;
    }

    public static Map <String, PL_Product_Group__c> getProductGroupMDMap(){
        Map <String, PL_Product_Group__c> pgMDMap = new  Map <String, PL_Product_Group__c> ();
        for (PL_Product_Group__c activePG : [SELECT id, Name, Product_Group__c FROM PL_Product_Group__c Where Is_Active__c = TRUE]) {
            pgMDMap.put(activePG.Product_Group__c.trim(), activePG);
        }
        return pgMDMap;
    }

    public static Map <String, SBQQ__SolutionGroup__c> getInstallLocationMap(){
        Map <String, SBQQ__SolutionGroup__c> iLMap = new  Map <String, SBQQ__SolutionGroup__c> ();
        // Updated by Lipton for W-004443
        // Added a Translated_Value__c in the query fields
        for (SBQQ__SolutionGroup__c il : [SELECT id, Name, PL_PS__c, PL_PS__r.Name, PL_PS__r.L2I_Migration_External_Id__c, PL_PS__r.Translated_Value__c  FROM SBQQ__SolutionGroup__c Where Name != null]) {
            ilMap.put(il.Name.trim(), il);
        }
        return iLMap;
    }

    /* commented out as this is not being used.
    public static Map <String, String> GetProduct2InstallLocationMap(Set <Id> myQLProdIds, Set <String> myQLInstLocs){
        Map <String, String> pil2psMap = new Map <String, String>();

        // get Product+:+installloc 2 PS map
        if (myQLInstLocs.size() > 0 && myQLProdIds.size() > 0) {
            // get productinstallloc to product summary if quote lines have install locatitons.
            for (PL_IL2PS__c ilps : [SELECT PL_PS__c, PL_PS__r.name,  PL_PS__r.L2I_Migration_External_Id__c, Product__c, Inst_loc__r.name
                                     FROM PL_IL2PS__c Where Product__c in :myQLProdIds and Inst_loc__r.name in :myQLInstLocs]){

                pil2psMap.put(ilps.Product__c+':'+ilps.Inst_loc__r.name.trim(), ilps.PL_PS__r.L2I_Migration_External_Id__c);
            }
        }
        return pil2psMap;
    }
    */

    public static List <PL_PS__c> getQuoteProductSummaryList(Set <Id> QuoteIds) {
        List<PL_PS__c> lstPS = [
                SELECT Id, Name, Product_Summary__r.name, Cost__c, Line_Maintenance_Cost__c,  Credit__c, Discount__c,
                        Red_in_GS__c, ps_NS_to_Cust__c, ps_GM__c, Gross_Sales__c, Net_Sales__c, Product_Group__c,
                        Product_Summary__c, Quote__c, Quote__r.L2I_Aircraft_Quantity__c, Quote__r.L2I_Total_Seat_Count__c,
                        Sort_Order__c, Product_Summary__r.L2I_Migration_External_Id__c, Warranty_Cost__c,
                        Product_Group__r.PL_MD__r.L2I_Migration_External_Id__c, CAL_COGS__c
                FROM PL_PS__c WHERE Quote__c IN :QuoteIds];
        system.debug('Test## QuoteIds===='+QuoteIds);
        system.debug('Test## ===='+lstPS);
        return lstPS;
    }

    public static String getDisplayStrValue(Decimal decValue){
        String strValue = '';
        // W-004372 Display 0
        if (decValue == 0 || decValue == null) {
            return '0';
        }
        //if (decValue !=0) { // W-004372
            strValue = String.format(decValue.setScale(0).format(), args);
        //}  // W-004372
        return strValue;
    }

    public Static Decimal getDecimalValuefromList(List <Decimal> lstDec, Integer ind){
        if (lstDec[ind] != null && lstDec[ind] !=0) {
            return lstDec[ind];
        } else {
            return 0;
        }
    }
}