objects/Product2.object
<CustomObject>
    <fields>
        <fullName>L2I_Inventory_Item_Id__c</fullName>
        <description>EBS Item Id</description>
        <externalId>true</externalId>
        <label>Inventory Item Id</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2I_Primary_Unit_Code__c</fullName>
        <label>Primary Unit Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Integration__mdt.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client_Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PT Integration</label>
    <pluralLabel>PT Integrations</pluralLabel>
</CustomObject>

objects/PT_PriceList__c.object
<CustomObject>
    <fields>
        <fullName>L2I_Header_ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>L2I_Header_ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>L2I_IntegrationStatus__c</fullName>
        <label>L2I_IntegrationStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <label>Price List Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>PT_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integration Pending</fullName>
                </value>
                <value>
                    <fullName>Integration Completed</fullName>
                </value>
                <value>
                    <fullName>Retry Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Price List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_PriceList_Entry__c.object
<CustomObject>
    <fields>
        <fullName>L2I_IntegrationStatus__c</fullName>
        <label>L2I_IntegrationStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L2I_Line_ExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>price list entry id from oracle</inlineHelpText>
        <label>L2I_Line_ExternalId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <formula>PT_Program_Price_List__r.PT_Price_List_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price List Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_ProductCode__c</fullName>
        <formula>PT_Product__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Price List</label>
        <referenceTo>PT_PriceList__c</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Added</fullName>
                </value>
                <value>
                    <fullName>Reconcile</fullName>
                </value>
                <value>
                    <fullName>Integrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Program Price List Entry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Price List Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_ProgramPriceListIntegrationWithEBS.cls
public class PT_ProgramPriceListIntegrationWithEBS {

    @InvocableMethod( label='Integrate Program Price List with EBS' )
    public static void invokeProgramPriceListToEBS (List <String> inputs) {
        processProgPriceListToEBS(inputs.get(0));
    }

    @future(callout=true)
    public static void processProgPriceListToEBS (Id progPLId) {
        PT_PriceList__c priceListWithPLEs = [SELECT Id, CreatedDate, CurrencyIsoCode, L2I_Header_ExternalId__c, PT_Description__c, PT_Price_List_Name__c, PT_Status__c,
                                                (SELECT Id, L2I_Line_ExternalId__c, PT_UnitPrice__c, PT_ProductCode__c, PT_Product__r.L2I_Inventory_Item_Id__c, PT_Product__r.L2I_Primary_Unit_Code__c, PT_StartDate__c
                                                FROM Program_Price_List_Entries__r WHERE PT_Status__c = 'Approved' OR (PT_Status__c = 'Integrated' AND L2I_IntegrationStatus__c != 'Success'))
                                            FROM PT_PriceList__c
                                            WHERE Id = :progPLId];
        PT_ProgramPriceListWrapper postBody = getPriceListJSON(priceListWithPLEs);
        HttpResponse response = sendPriceListToEBS(postBody);
        if (response != null && response.getStatusCode() == 200) {
            System.debug(response.getBody());
            // update Program Price List and related PLEs
            List<PT_PriceList_Entry__c> updatePLEList = new List<PT_PriceList_Entry__c>();
            for (PT_PriceList_Entry__c ple : priceListWithPLEs.Program_Price_List_Entries__r) {
                PT_PriceList_Entry__c updatePLE = new PT_PriceList_Entry__c(Id = ple.Id, PT_Status__c = 'Integrated');
                updatePLEList.add(updatePLE);
            }
            if (updatePLEList.size() > 0) {
                update updatePLEList;
            }

            priceListWithPLEs.PT_Status__c = 'Integration Completed';
            update priceListWithPLEs;
        }
    }
    public static PT_ProgramPriceListWrapper getPriceListJSON (PT_PriceList__c priceListWithPLEs) {
        PT_ProgramPriceListWrapper plJSON = new PT_ProgramPriceListWrapper();
        plJSON.sourceSystem = 'Salesforce';
        PT_ProgramPriceListWrapper.Header header = new PT_ProgramPriceListWrapper.Header();
        header.priceListName = priceListWithPLEs.PT_Price_List_Name__c;
        header.priceListDescription = priceListWithPLEs.PT_Description__c;
        header.headerExternalId = priceListWithPLEs.L2I_Header_ExternalId__c != null ? priceListWithPLEs.L2I_Header_ExternalId__c : '';
        header.currencyCode = priceListWithPLEs.CurrencyIsoCode;
        header.originalHeaderID = priceListWithPLEs.Id;
        header.activationStartDate = String.ValueOf(priceListWithPLEs.CreatedDate);
        header.operationType = 'CREATE';
        plJSON.Header = header;
        List<PT_ProgramPriceListWrapper.Lines> lines = new List<PT_ProgramPriceListWrapper.Lines>();
        for (PT_PriceList_Entry__c ple : priceListWithPLEs.Program_Price_List_Entries__r) {
            PT_ProgramPriceListWrapper.Lines line = new PT_ProgramPriceListWrapper.Lines();
            line.itemValuePerUnit = ple.PT_UnitPrice__c != null ? String.ValueOf(ple.PT_UnitPrice__c) : '';
            line.inventoryItemID = ple.PT_Product__r.L2I_Inventory_Item_Id__c != null ? ple.PT_Product__r.L2I_Inventory_Item_Id__c : '';
            line.primaryUnitOfMeasure = ple.PT_Product__r.L2I_Primary_Unit_Code__c != null ? ple.PT_Product__r.L2I_Primary_Unit_Code__c : '';
            line.originalLineId = ple.Id;
            line.operationType = 'CREATE';
            line.activationStartDate = ple.PT_StartDate__c != null ? String.ValueOf(ple.PT_StartDate__c) : '';
            line.lineExternalId = ple.L2I_Line_ExternalId__c != null ? ple.L2I_Line_ExternalId__c : '';
            lines.add(line);
        }
        plJSON.lines = lines;
        System.Debug(JSON.serialize(plJSON));
        return plJSON;
    }
    public static HttpResponse sendPriceListToEBS (PT_ProgramPriceListWrapper postBody) {
        HttpResponse response;
        PT_Integration__mdt integrationMdtObj = [SELECT Id, Client_Secret__c, Client_Id__c, URL__c, MasterLabel
		                                          FROM PT_Integration__mdt
		                                          WHERE MasterLabel = 'ProgramPriceList_EBS'
		                                          LIMIT 1];
        try {
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setHeader('client_id', integrationMdtObj.Client_Id__c);
            request.setHeader('client_secret', integrationMdtObj.Client_Secret__c);
            request.setHeader('Content-Type', 'application/json');
            request.setEndpoint(integrationMdtObj.URL__c);
            request.setMethod('POST');
            String reqBody = JSON.serialize(postBody);
            request.setBody(reqBody);
            response = http.send(request);
        } catch (Exception e) {
            System.debug('e---------' + e);
        }
        return response;
    }
}