objects/PT_Install_Location__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_MROD_Revision__c.object
<CustomObject>
    <fields>
        <fullName>Current_MROD__c</fullName>
        <label>Current MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>D1_Date__c</fullName>
        <label>D1 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Default_Shipping_Org__c</fullName>
        <label>Default Shipping Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expedite__c</fullName>
        <label>Expedite</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extended_Price__c</fullName>
        <label>Extended Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Location</label>
        <referenceTo>PT_Install_Location__c</referenceTo>
        <relationshipLabel>MROD Revisions</relationshipLabel>
        <relationshipName>MROD_Revisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Time_Days__c</fullName>
        <label>Lead Time Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <label>Lead Time</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MROD_FORECAST_DATE__c</fullName>
        <label>MROD FORECAST DATE</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orderable_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orderable Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PPL_Type__c</fullName>
        <label>PPL Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Administrator__c</fullName>
        <label>Program Administrator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <label>Program Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>MROD Revisions</relationshipLabel>
        <relationshipName>MROD_Revisions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Qty__c</fullName>
        <label>Purchase Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_MROD__c</fullName>
        <label>Requested MROD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipset_PPL__c</fullName>
        <formula>Asset__r.PT_Install_Location_Parent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shipset PPL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <label>Sub Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MROD Revision</label>
    <nameField>
        <label>MROD Revision</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MROD Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>MROD_Latest_Approval_Questions__c</fullName>
        <label>MROD Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Operator)</relationshipLabel>
        <relationshipName>Programs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Administrator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Administrator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_PendingMRODChangesController.cls
public class PT_PendingMRODChangesController {
    
    public ID ptProgramID { get; set; }
    public List<PT_MROD_Revision__c> mrodRevList {get; set;}
    public String mrodQuestions {get; set;}
    public String mrodSubmittedDate {get; set;}
	public String xlsHeader
    {
        get {
            String strHeader = '';
            strHeader += '<?xml version="1.0"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }
    
    public PT_PendingMRODChangesController(ApexPages.StandardController controller) {
        ptProgramID = ApexPages.currentPage().getParameters().get('Id');
        
        mrodRevList = [SELECT Id, Region__c, Sub_Group__c, Operator__c, Program_Manager__c, Program_Administrator__c, Program__r.Name,
                                                 Shipset_PPL__c, PPL_Type__c, Install_Location__r.Name, Part_Number__c, Description__c, Purchase_Qty__c, Orderable_Item__c, 
                                                 Current_MROD__c, Requested_MROD__c, Expedite__c, D1_Date__c, Name, Program__r.MROD_Latest_Approval_Questions__c,
                       							 Lead_Time__c, Lead_Time_Days__c, Default_Shipping_Org__c, MROD_FORECAST_DATE__c, Createddate, Extended_Price__c
                                                 FROM PT_MROD_Revision__c WHERE Program__c =: ptProgramID];// AND Status__c = 'Pending'];
        
        if(!mrodRevList.isEmpty()){
            mrodQuestions = mrodRevList[0].Program__r.MROD_Latest_Approval_Questions__c;
            DateTime dt = mrodRevList[0].Createddate;
            mrodSubmittedDate = dt.format('MMMMM dd, yyyy hh:mm:ss a');
        } else { mrodQuestions = ''; mrodSubmittedDate = '';}
        
        
    }    
    
}