objects/PT_MROD_Approval_Question__mdt.object
<CustomObject>
    <fields>
        <fullName>Question_Nbr__c</fullName>
        <label>Question Nbr</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MROD Approval Question</label>
    <pluralLabel>MROD Approval Questions</pluralLabel>
</CustomObject>

classes/PT_ProgramService.cls
public with sharing class PT_ProgramService {
    @InvocableMethod(Label = 'MROD Approval Questions')
    public static List<String> processMRODApprovalQuestions() {
        List<String> questions = new List<String>();
    
        List<PT_MROD_Approval_Question__mdt> questionList =
        [SELECT Question_Nbr__c, Question__c
        FROM PT_MROD_Approval_Question__mdt
        ORDER BY Question_Nbr__c];
        
        String q = '';
    
        for (PT_MROD_Approval_Question__mdt question : questionList) {
            q += question.Question_Nbr__c + '. ' +
                  question.Question__c + '\n';
        }
        questions.add(q);
        System.debug('*** questions ' + questions);
        
        return questions;
    }
}