objects/PT_PMO_Groups__c.object
<CustomObject>
    <fields>
        <fullName>Group_Type__c</fullName>
        <label>Group Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Sub Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PMO Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMO Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>PMO_Regional_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Needed in the MROD Approval process</description>
        <label>PMO Regional Director User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PMO_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>PMO Group Programs</relationshipLabel>
        <relationshipName>PMOGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_PMO_SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PMO Sub Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PT_PMO_Groups__c.Group_Type__c</field>
                <operation>equals</operation>
                <value>Sub Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PT_PMO_Groups__c</referenceTo>
        <relationshipLabel>Programs (PMO Sub Group)</relationshipLabel>
        <relationshipName>PMOSubGroupPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Needed for MROD Approval process</description>
        <label>Principal Program Manager User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Number__c</fullName>
        <externalId>true</externalId>
        <label>Program Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_PMO_GroupsTriggerFunctionsTest.cls
@IsTest
private class PT_PMO_GroupsTriggerFunctionsTest {
    @testSetup
    private static void dataSetup() {
        L2I_DataFactory df = new L2I_DataFactory();
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'PAC Sales'].Id;
        Id profileSAId = [SELECT Id FROM Profile WHERE Name = 'PAC System Administrator'].Id;
        User u1 = df.createTestUser(null, profileId, 'User1', 'Test');
        insert u1;
        User u2 = df.createTestUser(null, profileId, 'User2', 'Test');
        insert u2;
        User u3 = df.createTestUser(null, profileId, 'User3', 'Test');
        insert u3;
        User sa = df.createTestUser(null, profileSAId, 'SA', 'Test');
        insert sa;
    }
    
    // Test RD
    @IsTest
    private static void addMemberToRDQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program RD Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg = new PT_PMO_Groups__c();
            pg.Group_Type__c = 'Group';
            Test.startTest();
            insert pg;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
    }
    @IsTest
    private static void deleteMemberToRDQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program RD Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg = new PT_PMO_Groups__c();
            pg.Group_Type__c = 'Group';
            insert pg;
            Test.startTest();
            delete pg;
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
    }
    @IsTest
    private static void deleteMemberExistingToRDQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id FROM User WHERE FirstName = 'User2' LIMIT 1];
        User u3 = [SELECT Id FROM User WHERE FirstName = 'User3' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program RD Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg1 = new PT_PMO_Groups__c();
            pg1.Group_Type__c = 'Group';
            insert pg1;
            PT_PMO_Groups__c pg2 = new PT_PMO_Groups__c();
            pg2.Group_Type__c = 'Group';
            insert pg2;
            PT_PMO_Groups__c pg3 = new PT_PMO_Groups__c();
            pg3.Group_Type__c = 'Group';
            insert pg3;
            pg3.OwnerId = u1.Id;
            update pg3;
            Test.startTest();
            delete pg1;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
        System.assertEquals(2, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND (UserOrGroupId = :sa.Id OR UserOrGroupId = :u1.Id)]);
    }
    @IsTest
    private static void changeMemberToRDQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program RD Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg = new PT_PMO_Groups__c();
            pg.Group_Type__c = 'Group';
            insert pg;
            pg.OwnerId = u1.Id;
            Test.startTest();
            update pg;
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
    }
    
    // Test PPM
    @IsTest
    private static void addMemberToPPMQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PPM Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg = new PT_PMO_Groups__c();
            pg.Group_Type__c = 'Sub Group';
            Test.startTest();
            insert pg;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
    }
    @IsTest
    private static void deleteMemberToPPMQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PPM Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg = new PT_PMO_Groups__c();
            pg.Group_Type__c = 'Sub Group';
            insert pg;
            Test.startTest();
            delete pg;
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
    }
    @IsTest
    private static void deleteMemberExistingToPPMQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id FROM User WHERE FirstName = 'User2' LIMIT 1];
        User u3 = [SELECT Id FROM User WHERE FirstName = 'User3' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PPM Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg1 = new PT_PMO_Groups__c();
            pg1.Group_Type__c = 'Sub Group';
            insert pg1;
            PT_PMO_Groups__c pg2 = new PT_PMO_Groups__c();
            pg2.Group_Type__c = 'Sub Group';
            insert pg2;
            PT_PMO_Groups__c pg3 = new PT_PMO_Groups__c();
            pg3.Group_Type__c = 'Sub Group';
            insert pg3;
            pg3.OwnerId = u1.Id;
            update pg3;
            Test.startTest();
            delete pg1;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
        System.assertEquals(2, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND (UserOrGroupId = :sa.Id OR UserOrGroupId = :u1.Id)]);
    }
    @IsTest
    private static void changeMemberToPPMQueueTest() {
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        Group grpObj = [SELECT Id FROM Group WHERE Name = 'Program PPM Group' LIMIT 1];
        System.debug('*** ' + [SELECT count() FROM GroupMember WHERE GroupId = :grpObj.Id]);
        System.runAs(sa) {
            PT_PMO_Groups__c pg = new PT_PMO_Groups__c();
            pg.Group_Type__c = 'Sub Group';
            insert pg;
            pg.OwnerId = u1.Id;
            Test.startTest();
            update pg;
            Test.stopTest();
        }
        System.assertEquals(0, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :sa.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM GroupMember WHERE GroupId = :grpObj.Id AND UserOrGroupId = :u1.Id]);
    }
    
    @IsTest
    private static void changeOwnerToRDTest() {
        System.debug('*** changeOwnerToRDTest');
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id FROM User WHERE FirstName = 'User2' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        System.debug('*** sa ' + sa);
        System.debug('*** u1 ' + u1);
    
        System.runAs(sa) {
            PT_PMO_Groups__c pg1 = new PT_PMO_Groups__c();
            pg1.Group_Type__c = 'Group';
            insert pg1;
    
            PT_PMO_Groups__c pg2 = new PT_PMO_Groups__c();
            pg2.Group_Type__c = 'Sub Group';
            insert pg2;

            PT_Program__c prog1 = new PT_Program__c();
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            prog1.Program_Manager__c = u1.Id;
            prog1.PT_PMO_Group__c = pg1.Id;
            prog1.PT_PMO_SubGroup__c = pg2.Id;
            insert prog1;
            System.assertEquals(1, [SELECT COUNT() FROM PT_Program__c WHERE PMO_Regional_Director__c = :sa.Id]);
    
            pg1.OwnerId = u1.Id;
    
            Test.startTest();
            update pg1;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM PT_Program__c WHERE PMO_Regional_Director__c = :u1.Id]);
    }
    
    @IsTest
    private static void changeOwnerToPPMTest() {
        System.debug('*** changeOwnerToRDTest');
        User u1 = [SELECT Id FROM User WHERE FirstName = 'User1' LIMIT 1];
        User u2 = [SELECT Id FROM User WHERE FirstName = 'User2' LIMIT 1];
        User sa = [SELECT Id FROM User WHERE FirstName = 'SA' LIMIT 1];
        System.debug('*** sa ' + sa);
        System.debug('*** u1 ' + u1);
        
        System.runAs(sa) {
            PT_PMO_Groups__c pg1 = new PT_PMO_Groups__c();
            pg1.Group_Type__c = 'Group';
            insert pg1;
            
            PT_PMO_Groups__c pg2 = new PT_PMO_Groups__c();
            pg2.Group_Type__c = 'Sub Group';
            insert pg2;
            
            PT_Program__c prog1 = new PT_Program__c();
            prog1.Name = 'Prog1';
            prog1.Program_Number__c = 'Prog1';
            prog1.Program_Manager__c = u1.Id;
            prog1.PT_PMO_Group__c = pg1.Id;
            prog1.PT_PMO_SubGroup__c = pg2.Id;
            insert prog1;
            System.assertEquals(1, [SELECT COUNT() FROM PT_Program__c WHERE Principal_Program_Manager__c = :sa.Id]);
            
            pg2.OwnerId = u2.Id;
            
            Test.startTest();
            update pg2;
            Test.stopTest();
        }
        System.assertEquals(1, [SELECT COUNT() FROM PT_Program__c WHERE Principal_Program_Manager__c = :u2.Id]);
    }
}