objects/PT_PriceList__c.object
<CustomObject>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PT_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <label>Price List Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Sequence__c</fullName>
        <label>Price List Sequence</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>PT_Program__c</referenceTo>
        <relationshipLabel>Program Price List</relationshipLabel>
        <relationshipName>Program_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>PT_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integration Pending</fullName>
                </value>
                <value>
                    <fullName>Integration Completed</fullName>
                </value>
                <value>
                    <fullName>Retry Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Price List</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Price List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_PriceList_Entry__c.object
<CustomObject>
    <fields>
        <fullName>PT_CanEscalate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CanEscalate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PT_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Price_List_Name__c</fullName>
        <formula>PT_Program_Price_List__r.PT_Price_List_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price List Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_Program_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Price List</label>
        <referenceTo>PT_PriceList__c</referenceTo>
        <relationshipLabel>Program Price List Entries</relationshipLabel>
        <relationshipName>Program_Price_List_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PT_StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Added</fullName>
                </value>
                <value>
                    <fullName>Reconcile</fullName>
                </value>
                <value>
                    <fullName>Integrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PT_UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Price List Entry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Price List Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PT_Program__c.object
<CustomObject>
    <fields>
        <fullName>PT_isActive__c</fullName>
        <inlineHelpText>Active state of the Program</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PT_ProgramPriceListEscalationHandler.cls
/**
 *      @author       Nitin Gupta
 *      @date         01/07/2021
 *      @description  PT_ProgramPriceListEscalationHandler
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Nitin Gupta                01/08/2021            Initial creation
 */


public class PT_ProgramPriceListEscalationHandler {
    public static void escalateProgramPriceList(Id progPriceListId, Decimal escalationPercentage, String description) {
        PT_PriceList__c progPL = [SELECT Id, Name, PT_Description__c, PT_IsActive__c, PT_Price_List_Name__c, PT_Price_List_Sequence__c, PT_Program__c, PT_Program__r.Name
                                FROM PT_PriceList__c
                                WHERE Id = :progPriceListId];
        String maxPriceListSeq = [SELECT Id, PT_Price_List_Sequence__c FROM PT_PriceList__c  WHERE PT_Program__c = :progPL.PT_Program__c ORDER BY PT_Price_List_Sequence__c DESC LIMIT 1].PT_Price_List_Sequence__c;
        String nextPriceListSeq = String.valueOf(Decimal.valueOf(maxPriceListSeq) + 1);
        if (nextPriceListSeq.length() == 1) {
            nextPriceListSeq = '0' + nextPriceListSeq;
        }
        List<PT_PriceList_Entry__c> progPLEList = [SELECT Id, Name, PT_CanEscalate__c, PT_Description__c, PT_EndDate__c, PT_isActive__c, PT_Product__c,
                                                    PT_Program_Price_List__c, PT_StartDate__c, PT_Status__c, PT_UnitPrice__c
                                                    FROM PT_PriceList_Entry__c
                                                    WHERE PT_Program_Price_List__c = :progPriceListId];

        PT_PriceList__c priceList = new PT_PriceList__c(PT_Program__c = progPL.PT_Program__c,
                                                        PT_Description__c = ' \n Escalation of Price list ' + progPL.Name + ' using factor of ' + escalationPercentage + '\n' + description,
                                                        PT_IsActive__c = TRUE,
                                                        PT_Price_List_Sequence__c = nextPriceListSeq,
                                                        PT_Price_List_Name__c = 'CPL-PL-' + progPL.PT_Program__r.Name + '-' + nextPriceListSeq);
        insert priceList;

        List<PT_PriceList_Entry__c> insertPLE = new List<PT_PriceList_Entry__c>();
        for (PT_PriceList_Entry__c ple : progPLEList) {
            insertPLE.add(new PT_PriceList_Entry__c(
                    PT_Program_Price_List__c = priceList.Id,
                    PT_CanEscalate__c = ple.PT_CanEscalate__c,
                    PT_isActive__c = ple.PT_isActive__c,
                    PT_StartDate__c = Date.today(),
                    PT_Status__c = 'New',
                    PT_Product__c = ple.PT_Product__c,
                    PT_UnitPrice__c = ple.PT_CanEscalate__c ? ple.PT_UnitPrice__c * (1 + escalationPercentage) : ple.PT_UnitPrice__c,
                    Name = ple.Name
                ));
        }
        if (insertPLE.size() > 0) {
            insert insertPLE;
        }
    }

}